### ISSUE TITLE
IO Error: CRLF expected at end of chunk

### ISSUE THREAD

**Issue by LowiePete** [validator/validator#1002]
This has become a regular response - if I take a copy of the page source and put it through my local HTML checker, there are no reactions. Can someone explain what this error means, and is it something we're meant to fix?  Thanks.

Code of validated page...

  | <!DOCTYPE html>
-- | --
  | <html lang="en-GB">
  | <head>
  | <meta charset="UTF-8">
  | <meta name="author" content="Peter Stevens" />
  | <meta name="classification" content="Dewey Index: 623.8 - Ships, Shipbuilding, Cruise ships, Ocean Travel" />
  | <meta name="ContentAltering" content="none" />
  | <meta name="copyright" content="Peter Stevens - All rights reserved" />
  | <meta name="country" content="GB" />
  | <meta name="privacy" content="http://www.caronia2.info/w3c/privacy.html" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=3.0, minimum-scale=1.0" />
  | <meta name="Description" content="RMS Caronia Timeline: further research feedback form" />
  | <meta name="Keywords" content="Cunard, Cunard Line, RMS Caronia, Green Goddess, Caronia II, ship, liner, cruise, cruising, ship research, feedback form, contact webmaster, lap of luxury, luxurious cruise ships, crossing oceans, itinerary, cruise ship history, maritime history, itineraries, brochures,		daily program, UK, timeline" />
  | <link rel="index" href="home.php" title="Home page" />
  | <link rel="first" href="em2pete2.php" title="Main Feedback page" />
  | <link rel="next" href="yr1949.php" title="Next page" />
  | <link rel="prev" href="em2pete2.php" title="Previous page" />
  | <link rel="author" href="about.php" title="About the Caronia Timeline &amp; its Author" />
  | <link rel="contents" href="sitemap.php" title="Table of Contents" />
  | <link rel="license" href="legalstuff.php" title="Copyright and Terms of Use" />
  | <link rel="help" href="firstvis.php" title="Caronia Timeline Help" />
  | <link rel="home" href="home.php" title="Home Page" />
  | <link rel="glossary" href="glossary.php" title="Glossary of Nautical Terms" />
  | <link rel="last" href="siteindx.php" title="Caronia Timeline Directory" />
  | <link rel="search" href="firstvis.php#sch" title="Searching the Caronia Timeline" />
  | <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  | <link rel="stylesheet" type="text/css" media="screen" href="css/nav.css" />
  | <link rel="stylesheet" type="text/css" media="screen, print" href="css/caronia.css" />
  | <link rel="P3Pv1" type="application/xml" title="P3P Privacy Policy" href="http://www.caronia2.info/w3c/p3p.xml" />
  | <link rel="shortcut icon" href="favicon.ico" title="Shortcut Icon" />
  | <link rel="sitemap" type="application/xml" title="Google Sitemap" href="sitemap_index.xml" />
  | <script src="js/extlinks.js"></script>
  | <title>RMS Caronia Timeline: Further research feedback form</title>
  | <style>
  | fieldset { text-align: left; margin-bottom: 5px; }
  | label { cursor: pointer; float: none; }
  | .ertxt { background: transparent; font: bolder 1em/1.5em Arial,Helvetica,sans-serif; color: #FF0D0D; }
  | .big { font-size:110%; line-height: 1.6em; padding: 5px 0 0 4px; }
  | </style>
  | </head>
  | <body>
  | <div class="tablcen">
  | <div id="hedr">
  | <h1>RMS <span class="oq">Caronia</span> Timeline</h1>
  | <h2>Email Feedback Page</h2>		<a class="xm" href="forms/myxmail.php"><img src="img/tpnt.gif" width="1" height="1" alt="&nbsp;"
  | /></a>
  | <div class="skp ccn">
  | <ul class="mnu3">
  | <li><a href="#tdir" title="Skip to Main Content">Skip</a></li>
  | <li><a href="#navb" title="Jump to Main Navigation Bar">Navigation</a></li>
  | <li><a href="getswitch.php?set=/em2pete2.php" title="Link: Display / Text sizing options through CSS">Text</a></li>
  | <li><a href="firstvis.php#sch" title="Link: Assisted site search on Timeline Help Page">Search</a></li></ul>
  | <div class="clr"></div>
  | </div>
  | <h3 class="brk">Cunard's &lsquo;Green Goddess&rsquo;</h3>
  | <h4 class="brk">Contacting the Webmaster directly</h4>
  | </div>
  | <div class="ffct" id="top">
  | <p class="plnav">
  | <em>You are here:</em> <a href="home.php" title="Return to Site Opening Page">Home Page</a>
  | &rarr; Visitor Feedback Page</p>
  | <a class="txt" href="getswitch.php?set=/em2pete2.php" title="Link: Display / Text size options">
  | <span class="skp">Text</span></a>
  | <p class="plnav">
  | <em>Quick Links:</em> <a href="#pp">My Privacy Policy</a> \|
  | <a href="javascript:history.go(-1)" title="Go back a page">Go Back a Page</a></p>
  | <a class="navlt" href="#navb" title="Jump to Navigation Bar">Navigation Bar</a>&nbsp;
  | </div>
  | <div class="decotp1"></div>
  | <div class="bcf bdb">
  | <a id="tdir" class="sbmt" href="siteindx.php#pindex" title="Link: Extended Quick Index">Extended Index</a>
  | <div class="prt">
  |  
  | <h5 class="ft" id="frm">Your Feedback ...</h5>
  | <p>
  | One of the aims of this site is to gather as much information as possible while there are still people
  | around who are able to give us first-hand accounts. So, any additional feedback that you can provide will
  | be very gratefully accepted - Many thanks. The form below may also be used to request a link-exchange
  | with other maritime related sites.</p>
  | <h5 id="pp">C.O.P.P.A. Compliance</h5>
  | <p>
  | If you are _under_ 14 years of age, please read the <a href="legalstuff.php"
  | title="Review Copyright and other Legal Statements">Legal Stuff page</a> for details of C.O.P.P.A. compliance.
  | By sending information on the form below, you certify that either you are 14 years of age or older, or that
  | you have the required permissions.</p>
  | <h5>Privacy Policy</h5>
  | <p>
  | I uphold the right of anyone to not have their email address or other private information published here.
  | I may, at my discretion, relay visitor emails up to this site (with email address excluded), unless you
  | specifically tell me not to. I will normally advise you of my intention to publish an email as a matter of courtesy.</p>
  | <p>
  | Otherwise, other than for directly contacting you personally, your email address and any other private
  | information you may provide, such as telephone numbers, are kept confidential and <em>not used</em> by me
  | for any other purpose.</p>
  | <a href="#fm2">Bring Feedback Form up to page top</a></div>
  | </div>
  | <div class="cfc btb">
  | <h5 id="fm2">Caronia Timeline Feedback</h5>
  |  
  | <p class="plnav">
  | There is little or no risk of &ldquo;spamming" by sending this form.<br />
  | <em>Please Note:</em> Titles marked with a <em>&para;</em> suffix will require a validated entry!<br />
  | Use the [Tab Key] to move from box to box</p>
  | <form method="post" id="fbk1" action="/em2pete2.php">
  | <fieldset><legend>My Personal Details</legend>
  | <label class="plnav big" for="uname">Name<br>
  | <input type="text" name="uname" id="uname" size="30" maxlength="30" required autocomplete="username"
  | title="Enter your name here" value="" placeholder=" My Name is ..." ></label>
  | <label class="plnav big" for="from">From <em>&para;</em> <span class="sml">Enter your home town, this
  | helps me assess your response needs</span><br />
  | <input type="text" name="from" id="from" size="20" maxlength="35" required autocomplete="address-level1"
  | title="Required - Enter your location here" value="" placeholder=" I come from..." ></label>
  | <label class="plnav big" for="email">Email address <em>&para;</em></label>
  | <input type="email" name="email" id="email" size="30" maxlength="40" required autocomplete="email"
  | title="Required - Enter your email address here" value="" placeholder=" My eMail Address is ..." >
  | <p class="plnav big">In your own interests, before you proceed ...<br />
  | Please, <em>double-check</em> your email address entry above.<br />
  | A wrongly entered email address prevents <em>you</em> from getting a reply!</p>
  | </fieldset>
  | <fieldset><legend>My Feedback</legend>
  | <label class="plnav big" for="topic">Topic <em>&para;</em><br />
  | <input type="text" name="topic" id="topic" size="30" maxlength="40" required value=""
  | title="Required - Enter topic title here" placeholder=" My topic title is ..." ></label>
  | <label class="plnav big" for="comments">Comments</label>
  | <textarea name="comments" id="comments" rows="10" cols="65" placeholder=" My feedback&hellip;"
  | title="Type your feedback information here"></textarea></fieldset>
  | <fieldset>
  | <legend>For Maritime Site-Link Requests Only!</legend>
  | <label class="plnav big" for="webname">Web Site Name</label>
  | <input type="text" name="webname" id="webname" size="40" maxlength="70"
  | title="Enter your web site name here - no URL's allowed!" placeholder=" My Web Site Name ..."
  | />
  | <label class="plnav big" for="weburl">Web Site URL</label>
  | <input type="text" name="weburl" id="weburl" size="50" maxlength="70" placeholder=" My Web Site address ..."
  | title="Enter web site address here - only URL!" pattern="https?://.+"
  | />
  | <div class="ltimg w49">
  | <label class="sml dow cntr" for="category">Please Specify Your Site's Category</label>
  | <select class="cntr" title="Select only for Link-Exchange" name="category" id="category" size="5">
  | <option selected>No site-link requested</option>
  | <option>General maritime site</option>
  | <option>Historical reference / Research</option>
  | <option>Link / Portal / Gateway site</option>
  | <option>Nautical collectors' sites</option>
  | <option>Personal home page</option>
  | <option>Site about a specific port</option>
  | <option>Site about a specific ship</option>
  | <option>Site about a specific shipping company</option>
  | <option>Site for contacting old shipmates</option>
  | <option>Society or eMail discussion group</option></select></div>
  | <div class="rtimg w49">
  | <p class="plnav"><span class="em">Please Note:</span><br />
  | When requesting a link-exchange with the Caronia Timeline, you must specify your site's
  | Category. This webmaster reserves the right to decline an exchange request at his discretion.</p></div></fieldset>
  | <div class="clr"></div>
  | <div class="ltimg w49">
  | <fieldset><legend>&lsquo;Not a Robot&rsquo; Confirmation</legend>
  | <p class="plnav">Please select the correct answer below&hellip;</p>
  | <p class="dow">When I multiply 5 by 2 - written as a word, the answer is:</p>
  | <label class="cntr" for="one">
  | <input type="radio" name="ruhuman" id="one" value="one"> One</label>
  | <label class="cntr" for="ten">
  | <input type="radio" name="ruhuman" id="ten" value="ten"> Ten</label>
  | <label class="cntr" for="two">
  | <input type="radio" name="ruhuman" id="two" value="two"> Two</label>
  | </fieldset></div>
  | <div class="rtimg w49">
  | <fieldset><legend>Arrival Source</legend>
  | <label class="sml dow cntr" for="source">How did you first land on the Timeline?</label>
  | <select class="cntr" title="Please select one of these options" name="source" id="source" size="5">
  | <option selected>Select from list below ...</option>
  | <option>I'm now a Regular Visitor</option>
  | <option>Link from another Web site / Web Blog</option>
  | <option>Search engine</option>
  | <option>Printed Source e.g. Magazine</option>
  | <option>Reputation / Word of mouth</option>
  | <option>Spotted while looking for something else</option></select></fieldset></div>
  | <div class="clr"></div>
  | <fieldset style="width: 65%;" class="cntr"><legend>Despatch my feedback&hellip;</legend>
  | <p class="pcnav big">
  | Have you <span class="em oq">double-checked</span> your eMail address entry<br />
  | and <span class="em oq">correctly answered</span> the &ldquo;Not a Robot&rdquo; question?</p>
  | <p class="cntr"><br />
  | <input type="hidden" name="btnSubmit" value="1"
  | />
  | <button class="sbmt" type="submit" value="&nbsp;Send My Feedback "
  | title="Click just ONCE to send your message"> Send My Feedback &raquo;&raquo;</button></p>
  | <p class="sml cntr"><br />
  | [An acknowledgement will appear shortly]<br />
  | [Note: This may take several seconds]</p></fieldset>
  | <noscript>
  | <p>Javascript elements are used on this form only for functional purposes.</p></noscript>
  | </form>
  | <div class="clr"></div>
  | </div>
  | <div class="bcf btb">
  | <div class="prt">
  | <h6>Awaiting a Response?</h6>
  | <p>
  | Almost certainly my response will contain web addresses which your email client may interpret as being risky!
  | The email title will begin with the words &ldquo;[Caronia2 Feedback]&rdquo;. Do please ensure that you
  | check your SPAM folder just in case my reply has been caught there. Thanks.</p>
  | </div>
  | </div>
  | <div class="ffcb">
  | <a class="navup" href="#top" title="Jump to Page Top">Top</a>
  | <p class="prnav"><em>Back to ...</em> <a href="javascript:history.go(-1)"
  | title="Link: Back to Previous Page">Previous Page</a> \|
  | <a href="shiplinks.php" title="Link: Back to Ship Links page">Links page</a></p>
  | </div>
  | <h6 class="nvb">Navigation Bar</h6>
  | <div id="navb" role="navigation" aria-label="Main">
  | <p class="skp">&middot;<a href="#skip" title="Skip Navigation Bar">Skip Navigation</a>&middot;</p>
  | <div id="sitenav">
  | <ul>
  | <li><a href="home.php" title="Return to Site Opening Page">Home</a></li>
  | <li><a href="yr1949.php" title="Link: 1949 Year Index">1949</a></li>
  | <li><a href="yr1950.php" title="Link: 1950 Year Index">1950</a></li>
  | <li><a href="yr1951.php" title="Link: 1951 Year Index">1951</a></li>
  | <li><a href="yr1952.php" title="Link: 1952 Year Index">1952</a></li>
  | <li><a href="yr1953.php" title="Link: 1953 Year Index">1953</a></li>
  | <li><a href="yr1954.php" title="Link: 1954 Year Index">1954</a></li>
  | <li><a href="yr1955.php" title="Link: 1955 Year Index">1955</a></li>
  | <li><a href="yr1956.php" title="Link: 1956 Year Index">1956</a></li>
  | <li><a href="yr1957.php" title="Link: 1957 Year Index">1957</a></li>
  | <li><a href="yr1958.php" title="Link: 1958 Year Index">1958</a></li>
  | </ul>
  | <ul>
  | <li><a href="crewindx.php" title="Link: Crew Quarters Index">Crew</a></li>
  | <li><a href="yr1959.php" title="Link: 1959 Year Index">1959</a></li>
  | <li><a href="yr1960.php" title="Link: 1960 Year Index">1960</a></li>
  | <li><a href="yr1961.php" title="Link: 1961 Year Index">1961</a></li>
  | <li><a href="yr1962.php" title="Link: 1962 Year Index">1962</a></li>
  | <li><a href="yr1963.php" title="Link: 1963 Year Index">1963</a></li>
  | <li><a href="yr1964.php" title="Link: 1964 Year Index">1964</a></li>
  | <li><a href="yr1965.php" title="Link: 1965 Year Index">1965</a></li>
  | <li><a href="yr1966.php" title="Link: 1966 Year Index">1966</a></li>
  | <li><a href="yr1967.php" title="Link: 1967 Year Index">1967</a></li>
  | <li><a href="ephem00.php" title="Link: Ephemeral Items Folio">Folio</a></li>
  | </ul>
  | <ul>
  | <li><a href="caribiandx.php" title="Link: Caribia - A Sad Ending">Caribia</a></li>
  | <li><a href="eventindx.php" title="Link: Caronia Key Events Index">Events</a></li>
  | <li><a href="features.php" title="Link: Special Features Summary">Features</a></li>
  | <li><a class="thispg" href="#top" title="Jump to Page Top">Feedback</a></li>
  | <li><a href="glossary.php" title="Link: Glossary of Nautical Terms">Glossary</a></li>
  | <li><a href="shiplinks.php" title="Link: External Maritime Sites List">Links</a></li>
  | <li><a href="sitemap.php" title="Link: full text Table of Contents">Site Map</a></li>
  | <li><a href="vtour00.php" title="Link: Virtual Tours Index">Virtual Tours</a></li>
  | </ul></div>
  | <div class="clr"></div>
  | <footer id="ftr">
  | <div id="btm" class="ltftr">
  | <p class="pcnav">
  | <a href="sitemap.php" id="skip" title="Link: full-text Table of Contents">
  | <img class="pad5" src="image/cariconp.gif" width="153" height="101" alt="Link: full-text Table of Contents"
  | /></a></p>
  | </div>
  | <div class="ltftr"><span>&nbsp;</span>
  | <p class="cntr">
  | <a class="help sbmt" href="legalstuff.php?#pp" title="Link: View my Privacy Policy">My Privacy Policy</a></p>
  | <p class="cntr">
  | <a class="help sbmt" href="access.php" title="Link: View my Accessibility &amp; Standards Policy">Accessibility Policy</a></p>
  | <p class="cntr">
  | <a class="sbmt" href="https://validator.w3.org/check?uri=https://www.caronia2.info/em2pete2.php" rel="external"
  | title="Validate the HTML5 in a new window">Validate HTML5<span class="xtr xbr">&nbsp;</span></a></p>
  | </div>
  | <div class="ltftr"><span>&nbsp;</span>
  | <p class="cntr">
  | <a class="sbmt" href="siteindx.php#pindex" title="Link: Extended Quick Index">Extended Index</a></p>
  | <p class="cntr">
  | <a class="sbmt" href="em2pete2.php" title="Link: Feedback Your Information">Your Feedback</a></p>
  | <p class="cntr"><a class="sbmt" href="#btm" title="Visitors Online in past 10mins."><em>5</em> Visitors aboard</a></p></div>
  | <div class="clr"></div>
  | <div class="ltftr">&nbsp;</div>
  | <p class="vld">
  | <span class="dow">
  | <a class="tip" href="legalstuff.php"
  | title="Link: Copyright, Terms of Use, COPPA, Privacy">Copyright &copy; 2004-2020 <span>Copyright &copy; P.E. Stevens 2004-2020<br />
  | All Rights Reserved<br />
  | Warning! Caronia II Timeline Web site protected by<br />
  | International Copyright Law - do NOT copy!</span></a></span>&nbsp;&middot;
  | <span class="dow" title="Date when page was last updated">Page updated: Tue, 21 Jul 2020</span></p>
  | </footer>
  | <div class="deco"></div></div>
  | </div>
  | <div id="sdnavdn">
  | <a class="navdn" id="ndn" href="#navb" title="Jump to Navigation Bar">Nav</a>
  | </div>
  | <script src="js/showremote.js"></script>
  | <div id="sdnavup">
  | <a class="navup" id="nup" href="#top" title="Jump to Page Top">Top</a>
  |  
  | </div>
  | <div id="topright">
  | <p class="pcnav2">
  | <a class="nup" href="#top" title="Jump to Page Top">Top</a>
  | <a class="nlt" href="javascript:history.go(-1)" title="Go Back a page">Back</a>
  | <a class="nlt" href="home.php" title="Go Back to Home page">Home</a>
  | <a class="ndn" href="#navb" title="Jump to Navigation Bar">NavBar</a></p>
  | </div>
  | </body>
  | </html>

**Comment by sideshowbarker** [comment]
I’ve fixed this and pushed the fix to https://validator.w3.org/nu/. Please re-check and let me know if you’re still running into the problem.

> if I take a copy of the page source and put it through my local HTML checker, there are no reactions

The reason the checker didn’t report the error in that case is that it’s an HTTP-related error — so it only occurs when you’re serving the document from a particular web server.

And the root cause of the problem is that web server from which you’re serving the document is technically in violation of the HTTP spec. That’s because the HTTP spec requires the closing chunk of `Transfer-Encoding: chunked` messages to be followed by `CRLF` (that is, a carriage returned followed by a linefeed) — but the web server from which you’re serving the document doesn’t add that `CRLF` to the closing chunk.

However, that particular violation of the HTTP spec isn’t something that causes any real problems in practice — so browsers and most other client tools that send and receive HTTP requests and responses just ignore that problem. But the HTTP client which the HTML checker uses follows the HTTP spec more strictly; hence the error report.

So the “fix” I made was to basically just internally suppress the error so that it doesn’t end up getting reported to you as an end user. That seems appropriate in the case — given that you unless you’re a web-server admin, you likely don’t have any way to prevent the error (other than switching to a new web server/hosting provider).
