### ISSUE TITLE
“ambiguous” ampersands in attribute values causing misalignment of source-code highlighting

### ISSUE THREAD

**Issue by Cerberooo** [validator/validator#1003]
If you validate the following string:
```html
<map><area href="?t&a"><area href="?t&a"><area href="?t&a"><area href="?t&a"><area href="?t&a"></map>
```
you can see that the code excerpt and the column numbers are incorrect. However if you delete the `&`'s in the markup these two things are correct.

**Comment by sideshowbarker** [comment]
Thanks very much for reporting this. I know the cause of this is a bug somewhere in validator/htmlparser@c6778f8 but it’s not clear to me yet where. It’s likely going to be a couple more weeks before I can get back to investigating it further. So in the mean time, please don’t think I’m ignoring this — it’s just not something I can quickly fix.

**Comment by sideshowbarker** [comment]
I’ve now made a fix for this and pushed the fix to https://validator.w3.org/nu/. If it doesn’t solve the problem — or seems to be causing any new problems — please let me know.

Thanks again very much for having taken time to report this.

**Comment by Cerberooo** [comment]
Look's good! Thanks! :smile:
