### ISSUE TITLE
Attribute aria-label

### ISSUE THREAD

**Issue by naftandev** [validator/validator#1014]
It is used to reference elements that do not contain text or a label that is visible to the user. In this case I am using it in an <i> element that will contain an icon per CSS.
In my opinion it is correctly implemented, I await your feedback.

**Comment by shlomif** [comment]
I am running into that too now:

«hi all! i'm trying to add an accessible asciiart &lt;pre&gt; section to https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.shlomifish.org%2FFiles%2Ffiles%2Ftext%2Fscreenp-ascii-art-test.xhtml (for future use here: https://www.shlomifish.org/humour/by-others/hitchhiker-guide-to-star-trek-tng-htmlised.html ). I followed this: https://stackoverflow.com/questions/33929647/alt-attribute-for-ascii-art-in-html but get a warning :(
»

Can/should this be fixed please? Thanks!

**Comment by sideshowbarker** [comment]
Per https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/, `aria-label` is not allowed for `i` elements nor for `pre` elements. In both cases, the stated reason is: *“Maps to role=generic naming not allowed”*.
