### ISSUE TITLE
The HTML checker has misidentified the language of my website

### ISSUE THREAD

**Issue by Smokolisz** [validator/validator#1019]
My website https://remedium.fulara.com is obviously in polish language.

The warning i got from validator:
This document appears to be written in Catalan but the html start tag has lang="pl". Consider using lang="ca" (or variant) instead.

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this, and sorry for the delay in replying.

Looking at the content of https://remedium.fulara.com/ I see that its text content currently seems to be mostly just placeholder text — specifically, so-called “Lorem ipsum” text.

I think that’s what’s throwing off the language guesser. The presence of that “Lorem ipsum” text prevents the content from being obviously in polish. If you replace that “Lorem ipsum” text with Polish-language content instead, I think you’ll find that the checker no longer guesses that document is in Catalan but instead is in Polish.

**Comment by doktorbro** [comment]
what is «the language guesser»? the html spec [says](https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes):

> To determine the language of a node, user agents must look at the nearest ancestor element (including the element itself if the node is an element) that has a lang attribute in the XML namespace set or is an HTML element and has a lang in no namespace attribute set. That attribute specifies the language of the node (regardless of its value).

i repeat: regardless of its value. this bug is disturbing.
