### ISSUE TITLE
Does not recognize the `all`CSS property

### ISSUE THREAD

**Issue by thierryk** [validator/validator#1021]
The validator returns the following:

> Error: **CSS**: `all`: **Property** `all` **doesn't exist**.
> ...
> `-skip{all:unset;}

Even though `all` is:

> a shorthand property for resetting all CSS properties except for direction and unicode-bidi. 

Source: https://caniuse.com/#search=all / https://www.w3.org/TR/css-cascade-3/#all-shorthand

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this.

If you don’t mind, could you please re-report it at https://github.com/w3c/css-validator/issues?

For CSS checking, the HTML checker (validator) uses the same backend as the W3C CSS validator. So for the HTML checker to support `all`, we’d need to for the support to be added upstream, in the CSS validator sources.

**Comment by thierryk** [comment]
> If you don’t mind, could you please re-report it at https://github.com/w3c/css-validator/issues?

[Done!](https://github.com/w3c/css-validator/issues/283)

**Comment by sideshowbarker** [comment]
I’ve added a workaround for this in the HTML checker but it still needs to be fixed property in the CSS backend, https://github.com/w3c/css-validator/issues/283
