### ISSUE TITLE
Maven Plugin

### ISSUE THREAD

**Issue by McNetic** [validator/validator#1024]
I've got a rudimentary maven plugin implementation to enable validation of files in the maven build process. I'd rather have it integrated into this project than publishing and maintaining it all by myself. Is there any interest in having this, and if yes, what would be the requirements (aside from the obvious license grant)?

**Comment by sideshowbarker** [comment]
Thanks for raising this issue. The https://github.com/validator/gulp-html (gulp plugin) and https://github.com/validator/grunt-html (Grunt plugin) are some precedents for this kind of case.

So how about if I create a https://github.com/validator/maven-plugin repo, and then you could add the code there?

**Comment by McNetic** [comment]
That could work. I obviously used maven as build tool. For the maven it is important that it is published to maven central. As you already have the validator itself there, would it be possible to also publish the plugin? I do not know about your build process and workflow...

**Comment by sideshowbarker** [comment]
Yeah we could also publish the plugin in the Maven `nu.validator` space

**Comment by McNetic** [comment]
Ok, would you create the repository?

**Comment by sideshowbarker** [comment]
> Ok, would you create the repository?

Yup — done just now. You should find an invite from the system waiting for you

**Comment by McNetic** [comment]
Thank you. I just uploaded the initial plugin implementation. I think we should continue discussing the further process over there.
