### ISSUE TITLE
Remove allowpaymentrequest attribute

### ISSUE THREAD

**Issue by mtrootyy** [validator/validator#1029]
Ref: https://github.com/whatwg/html/commit/140dd67172e5c6c3a0043ac0e40a013662c0e600

**Comment by zcorpan** [comment]
https://github.com/validator/validator/pull/1034

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/validator/validator/pull/1034/commits/fe885c4cfb258693bccd852a159fdc8ad16d066e
