### ISSUE TITLE
Warning issued when headers are nested in an article

### ISSUE THREAD

**Issue by curry684** [validator/validator#103]
During validation of http://mennolanting.nl/post/646 I encountered a lot of warnings on this bit of markup:

    <article data-bg="url(/assets/Leiderschap.jpg)"><a href="/post/1006">
            <aside></aside>
            <h3>Op zoek naar de nieuwe leider</h3>
            <h4>In dit netwerktijdperk zijn we op zoek naar organisatieleiders die voortdurend het functioneren van </h4>
    </a></article>

The warning states:

> Warning: Article lacks heading. Consider using h2-h6 elements to add identifying headings to all articles.

As it contains an `h3` and `h4`, for title and subtitle respectively, I was surprised at this, but I suppose it is complaining because both are wrapped in an anchor. And as `a` is now considered transparent in the HTML5 specs I don't think it should issue this warning here.

**Comment by unor** [comment]
I don’t think it’s related to the `a` element, but to the `aside`.

The `aside` element opens another section, and because there is no preceding heading element (`h1`-`h6`), the `article` section has no heading associated, i.e., "Article lacks heading".

**Comment by sideshowbarker** [comment]
> The aside element opens another section, and because there is no preceding heading element (h1-h6), the article section has no heading associated (it gets an implied heading), i.e., "Article lacks heading".

That assessment of what’s happening here sounds like it could be right but I still need to check the code (and the requirements in the spec) to make sure this isn’t actually a bug in the code.

**Comment by curry684** [comment]
It sounds more plausble than my initial explanation I think, but I'm not quite sure it would be correct in that case either. The given example is about a `header` section, which has standalone meaning, while an `aside` is supposedly just 'less relevant content' within its container. I don't think it should therefore participate in the outline itself... Willing to be corrected there though, think it's one of those places where a lot of discussion is possible, and even that part of the spec says it's non-normative.

**Comment by unor** [comment]
@curry684 The [`header` element](http://www.w3.org/TR/2014/REC-html5-20141028/sections.html#the-header-element) is not a sectioning content element:

> The `header` element is not sectioning content; it doesn't introduce a new section.

So `header` elements can be ignored when creating the outline. 

The [`aside`](http://www.w3.org/TR/2014/REC-html5-20141028/sections.html#the-aside-element) element, on the other hand, is one of [the four sectioning content elements](http://www.w3.org/TR/2014/REC-html5-20141028/dom.html#sectioning-content-0), so it always takes part in the outline.

So the outline-relevant markup for the example in the HTML5 spec would be:

    <body>
        <h1>Ray's blog</h1>
        <article>
            <nav></nav> 
            <h2>We're adopting a child!</h2>
        </article> 
    </body>

To me (see [related issue for the **html5outliner**](https://github.com/hoyois/html5outliner/issues/7)), the "intuitive" outline would be:

1. "Ray's blog"
 1. "We're adopting a child!"
   1. Untitled navigation section

But according to the example, it is:

1. "Ray's blog"
 1. Untitled article
   1. Untitled navigation section
 1. "We're adopting a child!"

The second last example says:

> Headings never rise above other sections.

However, this statement as well as the examples are non-normative; I did not dive into the (normative) [algorithm](http://www.w3.org/TR/2014/REC-html5-20141028/sections.html#outlines) to verify it.

**Comment by curry684** [comment]
Fascinating, and as said I'm open to fixing my markup in this case. If this is the underlying reason however, and it holds to the standards, I think the warning is still curious as it's about a symptom, not the cause - it could probably warn better on "`aside` without title creates untitled subsection within container" or something first.

**Comment by sideshowbarker** [comment]
> During validation of http://mennolanting.nl/post/646 I encountered a lot of warnings on this bit of markup:

So looking at the DOM of that page now, I see that the `aside` there just has an image in it, with a button for collapsing the article. On the face of it, that seems like a fairly idiosyncratic use of `aside`. I’m not sure why there’s any point in marking that part up as an aside at all. IMHO it doesn’t seem to add anything semantically. It could just as well or better be marked up just with a `div`.

And as far as other possible cases where an article might start off with an aside (either titled or untitled) before the title of the article, I personally can’t think of any that make a lot of sense. That just seems odd. I can sorta imagine a case for a `nav` before the title, but I’ve never actually seen one.

So, given all that, I think the warning the checker is emitting here is still more helpful in more cases than it is harmful. But regardless, it’s just a warning, so you can safely ignore it or use the “Message filtering” feature in the checker to suppress it.

With that said, I’m gonna go ahead and close out this issue for now. But feel free to re-open any time (e.g., if/when you have new information about other use cases/examples).
