### ISSUE TITLE
Docker EXPOSE command on builder image not final image

### ISSUE THREAD

**Issue by sellersj** [validator/validator#1031]
The EXPOSE command isn't on the final image, so automated tools that see what ports are exposed can't find it.

I think that it just needs to be moved down a couple of lines to just above the CMD line
https://github.com/validator/validator/blob/master/Dockerfile

`$ docker inspect --format='{{.Config.ExposedPorts}}' validator/validator`
gives
`map[]`

**Comment by sellersj** [comment]
I suspect that the ENV commands are also not making it into the final container, but if I terminaled into the running container it didn't have the `env` command so I could not check it.

**Comment by sideshowbarker** [comment]
Should this be closed now that the #1032 fix is merged?

**Comment by sellersj** [comment]
It can be, but I think all the env vars need to be moved down as well. If you would prefer, I can open a PR for that.

**Comment by sideshowbarker** [comment]
> I think all the env vars need to be moved down as well. If you would prefer, I can open a PR for that.

Yes, please raise a PR for that — I can review and merge it quickly
