### ISSUE TITLE
Ant's build.xml refers to the file that doesn't exist: dist/VERSION

### ISSUE THREAD

**Issue by yurivict** [validator/validator#1036]
Here https://github.com/validator/validator/blob/master/build/build.xml#L26

**Comment by sideshowbarker** [comment]
`dist/VERSION` isn’t a static file that’s stored in the repo; instead it’s file that’s generated by the build. So the fact that it’s not stored in the repo itself isn’t a problem.

**Comment by yurivict** [comment]
Ok, thanks.
