### ISSUE TITLE
Support conic-gradient() from CSS Image Values and Replaced Content Module Level 4

### ISSUE THREAD

**Issue by christianhujer** [validator/validator#1041]
The CSS Image Values and Replaced Content Module Level 4 specifies a `conic-gradient()` function https://www.w3.org/TR/css-images-4/#conic-gradients. While the specification itself is still a working draft, browser support is will very soon be wide-spread enough: https://caniuse.com/?search=conic-gradient. Edge, Chrome, Safari, and Opera support it already. The next version of Firefox (Firefox 83) will also support it.

Currently, `conic-gradient()` is reported by Nu Validator as "not a background-image value".

**Comment by sideshowbarker** [comment]
Thanks for reporting this — fixed in the sources and pushed to https://validator.w3.org/nu/
