### ISSUE TITLE
Unable to show outline 

### ISSUE THREAD

**Issue by sonegs** [validator/validator#1045]
I validated a web with https://validator.w3.org/. All are ok, but i received a warning message, said that:

Unable to show outline. (Most likely due to a malformed HTTP response from the server hosting the document that was checked.)

By this way, I can't watch the Heading-level outline - that is necessary for me. Where can i looking for solved it?

**Comment by cvrebert** [comment]
Is the webpage you were validating public? If so, posting the URL here would help greatly.

**Comment by sonegs** [comment]
> ¿La página web que estaba validando es pública? Si es así, publicar la URL aquí sería de gran ayuda.

Yes, this is the URL https://www.manipulador-de-alimentos.es/curso-carnet/alicante/

**Comment by sideshowbarker** [comment]
The outline should now be shown as expected, as a result of 6a41cff.
