### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by dontcallmedom** [validator/validator#1046]
Could you push a new release to https://github.com/w3c/css-validator/pull/286?

Thanks!

**Comment by XhmikosR** [comment]
@sideshowbarker: I suppose the request is to cut a new stable release?

if so, please have a look at disabling the duplicate IDs issue we talked on IRC :)

**Comment by sideshowbarker** [comment]
OK, I just published v21.2.5 https://www.npmjs.com/package/vnu-jar/v/21.2.5 of the npm package

> I suppose the request is to cut a new stable release?

I did the npm release without doing a new stable release. I can do a stable release soonish

> if so, please have a look at disabling the duplicate IDs issue we talked on IRC :)

I think the cause of that might actually just be a syntax error. See my IRC comments
