### ISSUE TITLE
Validator homepage links to 404 error

### ISSUE THREAD

**Issue by Juergeen** [validator/validator#1051]
The validator homepage https://validator.w3.org/ links to https://www.w3.org/QA/2005/01/Validator-IE_WinXP_SP2 which returns HTTP 404.

**Comment by sideshowbarker** [comment]
Please re-open this at https://github.com/w3c/markup-validator/issues

**Comment by Juergeen** [comment]
Looks like the issue has been resolved in the meantime:  
I cannot find the link in question on the current version of the validator homepage anymore.
