### ISSUE TITLE
false error around figure

### ISSUE THREAD

**Issue by gj52** [validator/validator#1052]
`<p><figure><img  src=/post/freigabe.gif width=516 ></figure></p>`

will give error `</p>` without starting `<p>`

https://junker.endofinternet.org/post/2020/07/29/wireguard-im-lan/

**Comment by nschonni** [comment]
If you look in the Developer console, you can see that the browser will close the `<p>` tag when seeing the `<figure>`
![image](https://user-images.githubusercontent.com/1297909/101260142-c1bcd000-36fb-11eb-83f5-74cd7ea41865.png)

**Comment by gj52** [comment]
YES, the HTML is OK, but the validator show errors!

**Comment by nschonni** [comment]
No, the HTML isn't OK, you can't nest a figure in a `<p>`. The error is telling you the closing `</p>` is closing an unopened `<p>` because the browser just automatically started a new `<p>` after the `<figure>`

**Comment by gj52** [comment]
Thanks, HTML is generated from markdown (gohugo.io) and will generate it.  Will open an issue there.

**Comment by nschonni** [comment]
Probably not the case, but I remember that Hugo changed the Markdown processor a little while ago https://gohugo.io/news/0.60.0-relnotes/. Might be worth checking your version to see if you're on the newer parser

**Comment by gj52** [comment]
I'm on version 0.79.0
Thanks for help
It's only my playground, not a commercial project etc...  
Please close the issue
