### ISSUE TITLE
aria-label on ul element

### ISSUE THREAD

**Issue by anselmbradford** [validator/validator#1054]
![Screen Shot 2020-12-02 at 10 03 15 AM](https://user-images.githubusercontent.com/704760/101392110-56a60180-3893-11eb-8d5d-707638d3a568.png)

`aria-label` is added to a `ul` element. Replacing `aria-label` with `title` makes the validator pass, but creates a tooltip. According to https://www.w3.org/TR/wai-aria/#aria-label

> Most host languages provide an attribute that could be used to name the element (e.g., the title attribute in HTML), yet this could present a browser tooltip. In the cases where a visible label or visible tooltip is undesirable, authors MAY set the accessible name of the element using aria-label.

So it seems like the `aria-label` should pass when the tooltip is not desired.

You can see this code in practice in the main menu of https://www.consumerfinance.gov

**Comment by anselmbradford** [comment]
Also, the point of the label on the `ul` is so VoiceOver names the list.

**Comment by sideshowbarker** [comment]
See related issues #904 and #964, and see also https://www.w3.org/TR/using-aria/#practical-support-aria-label-aria-labelledby-and-aria-describedby:

> Don't use <code>aria-label</code>  or <code>aria-labelledby</code>  on any other non-interactive content such as <code>p</code>, <code>legend</code>, <code>li</code>, or <code>ul</code>, because it is ignored.

**Comment by stevefaulkner** [comment]
@sideshowbarker I have recently mapped out the suggested [usage of aria-label](https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/) based on testing and implementation support, I will update the advice in using aria to reflect this.

**Comment by sideshowbarker** [comment]
> @sideshowbarker I have recently mapped out the suggested [usage of aria-label](https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/) based on testing and implementation support, I will update the advice in using aria to reflect this.

Oh cool — I can actually go ahead and update the checker code based the table in that https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/ doc (and maybe after I raise the PR for it, you can review the patch).

So for the checker purposes at least, you don’t need to go back and update the https://w3c.github.io/using-aria/ doc. I guess it’d be great to have it updated too — but maybe in the short term you can just put a link in the https://w3c.github.io/using-aria/#practical-support-aria-label-aria-labelledby-and-aria-describedby section to https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/

**Comment by sideshowbarker** [comment]
@anselmbradford Thanks for raising this. Since https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/ says `aria-label` for `ul` is well-supported in browsers, I’ll update the checker code this week to drop the warning for it.

**Comment by simevidas** [comment]
> Also, the point of the label on the ul is so VoiceOver names the list.

@anselmbradford In what situations would you want such a visually hidden label? Is it a good idea?

**Comment by anselmbradford** [comment]
@simevidas In the menu I work on we have lists of links in columns and using VoiceOver on a mac, the list will not be labelled with its section if the `aria-label` is put on the `ul` parent's container, but will when it is on the `ul`. We also do not want a tooltip popping up, so using `title` is not an option.

On container:
![Screen Shot 2020-12-02 at 11 43 31 AM](https://user-images.githubusercontent.com/704760/101537692-ee761f00-3969-11eb-99ab-0d548c96e715.png)

On `ul`:
![Screen Shot 2020-12-02 at 11 44 24 AM](https://user-images.githubusercontent.com/704760/101537710-f59d2d00-3969-11eb-9ba1-65aab157d6e8.png)
