### ISSUE TITLE
Don't complain about CSS "scrollbar-color"

### ISSUE THREAD

**Issue by 1jj** [validator/validator#1055]
See https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Febay.de.cool%2FAEG-Preisliste%2F2020.html
The validator complains about CSS `scrollbar-color`.
Otherwise `::-webkit-scrollbar-*` and Microsoft's `scrollbar-*-color` as well as `-ms-scrollbar-*-color` are ok.

It doesn't make sense to warn about `scrollbar-colors` and not the others.

Firefox shipped `scrollbar-color` two years ago, it has a spec 
https://drafts.csswg.org/css-scrollbars/ 
and Chromium started implementing:
https://groups.google.com/a/chromium.org/g/blink-dev/c/zwG2m_KG0RY/m/VKoMXn06BQAJ

The goal is deprecation of WebKit's existing implementation and so it seems bad to tell authors not to use the new thing.

**Comment by sideshowbarker** [comment]
Thanks for having raised this — it’s been fixed by recent changes in the CSS-checking backend.
