### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release: not future any more

### ISSUE THREAD

**Issue by martindholmes** [validator/validator#1058]
I'm seeing this warning when running vnu.jar at the command line, and although it's been there for a while and I've got used to ignoring it over the years, today I came across the first instance of a JDK which doesn't have Nashorn, and therefore fails to run anything that makes use of it. OpenJDK 15 removes Nashorn (https://openjdk.java.net/jeps/372) leaving no JavaScript engine in the JDK. The Oxygen XML Editor now ships with OpenJDK 15, which means no JS support there, and as OSes running OpenJDK gradually move to 15 and above, VNU may fail too. I can't figure out where the Nashorn error is coming from in the validator source code, though.

**Comment by sideshowbarker** [comment]
Which version of vnu.jar does this happen with?

**Comment by martindholmes** [comment]
Sorry, you're right -- it's 16.6.29. I thought I had the latest. Apologies.

**Comment by sideshowbarker** [comment]
> Sorry, you're right -- it's 16.6.29. I thought I had the latest. Apologies.

No worries
