### ISSUE TITLE
HTML `name` attribute, if specified, must not be the empty string

### ISSUE THREAD

**Issue by dhodder** [validator/validator#106]
According to [**4.10.19.1 Naming form controls: the `name` attribute**](https://html.spec.whatwg.org/multipage/forms.html#naming-form-controls:-the-name-attribute), if a name attribute is specified on a form control its value must not be the empty string. However the following appears to validate:

``` html
<!DOCTYPE html>
<title>Test</title>
<input name="">
```

Should it instead generate a 'bad value' error message, similar to e.g. if an empty string `id` attribute is specified? Thanks.

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this.
Fix pushed to https://validator.w3.org/nu/

**Comment by dhodder** [comment]
Excellent, thank you @sideshowbarker !
