### ISSUE TITLE
http://validator.w3.org/check?uri=referer Not working properly

### ISSUE THREAD

**Issue by wmmead** [validator/validator#1061]
Putting this link at the bottom of a page and clicking it results in checking the validity of the default file in the domain rather than the specific file to be checked.

_<a href="http://validator.w3.org/check?uri=referer">valid HTML</a>_

For example: When the link is clicked on the page at **https://examplesite.com/testing.html** the file that is tested is **https://examplesite.com/index.html**

**Comment by sideshowbarker** [comment]
Please re-post this at https://github.com/w3c/markup-validator/issues
