### ISSUE TITLE
`font-variation-settings` not recognized

### ISSUE THREAD

**Issue by virgofx** [validator/validator#1066]
```
CSS: font-variation-settings: Property font-variation-settings doesn't exist.
```

![image](https://user-images.githubusercontent.com/739719/103488746-41ee5800-4dc4-11eb-93af-adcabe570f17.png)

---
### Reference

![image](https://user-images.githubusercontent.com/739719/103488736-2e42f180-4dc4-11eb-9123-1aa7f8a4de8d.png)

![image](https://user-images.githubusercontent.com/739719/103488739-37cc5980-4dc4-11eb-8c4b-459804d8aca5.png)

**Comment by sideshowbarker** [comment]
Thanks for reporting this — fixed in the sources and pushed to https://validator.w3.org/nu/
