### ISSUE TITLE
Updated error explanation list

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#1076]
The error explanation list at https://validator.w3.org/docs/errors.html is an excellent resource, but it's not up to date with the error messages the current validator produces.

Is there a more up-to-date list? If not, is there a way to help build it?

**Comment by sideshowbarker** [comment]
> Is there a more up-to-date list?

No, there is not.

> If not, is there a way to help build it?

One part of the way would be to go through the code and look for places where the code emits error messages; those places have calls to `error(…)` or `err(…)` methods. But along with those, there are messages that get emitted by the jing backend, which basically translate/rewrite into our own messages, using the message fragments defined starting at https://github.com/validator/validator/blob/master/src/nu/validator/messages/MessageEmitterAdapter.java#L305.

I realize that’s not a very satisfying answer, but that’s the state of things.

**Comment by jaimeiniesta** [comment]
OK, thanks!
