### ISSUE TITLE
IMG ASYNC

### ISSUE THREAD

**Issue by nicolesharp100** [validator/validator#1078]
W3C Validator produces the error of "attribute ASYNC not allowed on element IMG at this point" when attempting to use the ASYNC attribute for IMG elements, in conflict with Section 4.8.4.3.4 of the HTML Standard:

https://html.spec.whatwg.org/multipage/images.html#decoding-images

https://validator.w3.org/nu/?doc=https://nikkitestbox.dreamhosters.com/temporary/html.htm

If using ASYNC for images is still experimental, then that should be noted in the HTML living standard.

**Comment by sideshowbarker** [comment]
Try `decoding="async"`.

The relevant attribute name is `decoding`, and `async` is one of the possible values for that `decoding` attribute. That‘s what https://html.spec.whatwg.org/multipage/images.html#decoding-images shows.

**Comment by nicolesharp100** [comment]
That fixed it, thanks!!!  I missed that part and was using ASYNC="ASYNC" instead of DECODING="ASYNC".

**Comment by nicolesharp100** [comment]
It might still be good though for the W3C Validator to provide the suggestion to correct the attribute from ASYNC to DECODING="ASYNC" when it detects this error.

**Comment by sideshowbarker** [comment]
> It might still be good though for the W3C Validator to provide the suggestion to correct the attribute from ASYNC to DECODING="ASYNC" when it detects this error.

thanks, yeah we have a general issue about making the validator a bit smarter about those kinds of cases
