### ISSUE TITLE
Validator does not recognize appearance: button or appearance: textfield

### ISSUE THREAD

**Issue by tmb-github** [validator/validator#1086]
```
<style>
/*
It's unaware of appearance: textfield; and appearance: button;
See: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
*/
.appearance-textfield {
    appearance: textfield;
}
.appearance-button {
    appearance: button;
}
</style>
```
Error message: CSS: appearance: textfield is not a appearance value.
Error message: CSS: appearance: button is not a appearance value.

See: [MDN on appearance property and its attributes](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance)

**Comment by sideshowbarker** [comment]
Thanks for reporting this — fixed in the sources and pushed to https://validator.w3.org/nu/
