### ISSUE TITLE
Attribute arai-label not allowed on span

### ISSUE THREAD

**Issue by ap-prog** [validator/validator#1090]
Checking some HTML5 gives me this error
  Attribute arai-label not allowed on element span at this point

Yet the spec
  https://w3c.github.io/html-aria/#el-span
says it can have any aria-* attribute.

What am I missing?

**Comment by sideshowbarker** [comment]
Please post a test document or URL for web document that causes the checker to report the error

**Comment by scottaohara** [comment]
ARIA 1.2 will prohibit the naming of generic elements.  `<span>` is a generic element and unless it is given a role which has not prohibited naming this is an error.

see: https://www.w3.org/TR/wai-aria-1.2/#generic
related concepts: div & span
prohibited states and properties: aria-label & aria-labelledby

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1090#issuecomment-787232914
