### ISSUE TITLE
br only allows roles none/presentation

### ISSUE THREAD

**Issue by scottaohara** [validator/validator#1097]
URL being validated or code to reproduce error:
[test case](https://w3c.github.io/html-aria/tests/br-test.html)

[`br` only allows `none` and `presentation` roles in ARIA in HTML](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/br-test.html)

expect all other role values to be flagged as errors

**Comment by sideshowbarker** [comment]
> URL being validated or code to reproduce error:
> [test case](https://w3c.github.io/html-aria/tests/br-test.html)

That URL is a 404…

**Comment by scottaohara** [comment]
oops.  yeh looks like the correct test case url was applied to the second link.  apologies / thanks for getting this updated
