### ISSUE TITLE
erroneous HTML validates just fine

### ISSUE THREAD

**Issue by wlnirvana** [validator/validator#1100]
URL being validated or code to reproduce error:

```html
<!doctype html>
<html lang="zh-cn">
	<head>
		<meta charset="UTF-8">
		<title>Hello</title>
	</head>
	<body>
		<p> hello
```

Closing tags for html, body and p are missing, but the code snippet passes the validation.

Validator version: 20.6.30

**Comment by nschonni** [comment]
Those tags self close https://github.com/validator/validator/issues/919#issuecomment-593650232

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1100#issuecomment-788638393
