### ISSUE TITLE
Incorrect "No `p` element in scope but a `p` end tag seen" error

### ISSUE THREAD

**Issue by zstadler** [validator/validator#1101]
URL being validated or code to reproduce error: https://israelhiking.osm.org.il

```
No p element in scope but a p end tag seen.
```

The annotated source in [the result](https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fisraelhiking.osm.org.il) shows a `<p dir="rtl">` or `<p>` element for each of the `</p>` elements flagged as an error:

![image](https://user-images.githubusercontent.com/1304610/109769395-d0375c80-7c02-11eb-96f8-d1289b29b6b7.png)

**Comment by sideshowbarker** [comment]
Fix: Add `</p>` end tags before the `<ol>` start tags.

Explanation: An `ol` element can’t be put inside a `p` element. So an `<ol>` start tag following an unclosed `p` element implies a `</p>` end tag before the `<ol>` tag. So the HTML parser closes that `p` element when it sees the `<ol>` start tag. And so at the point where the parser see the `</p>` end tag after the `</ol>` end tag, there is no open `p` element for it to close. Hence the error message.
