### ISSUE TITLE
Incorrect saying role=presentation on nav is invalid

### ISSUE THREAD

**Issue by selfthinker** [validator/validator#1104]
The validator says that having `role="presentation"` on a `<nav>` is invalid.
But it is [listed in the spec](https://w3c.github.io/html-aria/#el-nav).

Example code which triggers the error:
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head><title>Test</title></head>
<body>

<nav role="presentation">
  <a href="#">Some</a> <a href="#">links</a>
</nav>

</body>
</html>
```

Error message:
```
Error: Bad value presentation for attribute role on element nav.
```

**Comment by nschonni** [comment]
FYI @scottaohara since you're going through these through the tests.

It seems odd to use a `nav` with presentation, because then I'm not sure why you'd pick it for the semantics, but only my 2 cents

**Comment by scottaohara** [comment]
Thanks for the ping @nschonni.

At some point the allowed roles for `nav` were accidentally deleted in the spec and then these ended up getting added for parity with other elements that expose landmark regions, like `<header>`.

That said, I now think it was a mistake to add `group`, `none` and `presentation` to the allowed roles, as I agree with your point, why use a `nav` if only to remove its semantics.  It'd be just as easy to change the `<nav>` to a `<div>`.

That said, the validator does need an update to not flag the use of `menu`, `menubar` and `tablist` on a `<nav>`.  Those were specifically added to allow for developers to progressively enhance a `<nav>` into these sorts of widgets.

**Comment by selfthinker** [comment]
> why use a `nav` if only to remove its semantics. It'd be just as easy to change the `<nav>` to a `<div>`

That is a tautological argument as the whole point of `role=presentation` is to remove semantics.
The same can be said about any of the other elements which allow it.
Why use `<h1|header|ol|... role="presentation">` if you can use a div?

You could make an argument to disallow `role=presentation` altogether, but that should be discussed elsewhere.

In this particular case I find allowing it on `nav` useful because it is bad practice to have too many landmarks on a page and best practice to focus on the most important ones.
There are often too many smaller navigation sections on websites which create too much noise for screen reader users.
Those could all be `div`s but it feels wrong as `nav` is the correct semantic element.

**Comment by scottaohara** [comment]
>Those could all be divs but it feels wrong as nav is the correct semantic element.

but if you're removing the semantics with `role=presentation` then it's clearly not the correct element.

**Comment by selfthinker** [comment]
> but if you're removing the semantics with `role=presentation` then it's clearly not the correct element.

Following that logic would mean using `role=presentation` is never used on the correct element.
Again, I would question why `nav` is different to `header` or `h1` or `ol` or `figure` or `form` or any of the other 65 HTML element which allow the use of `role=presentation`?

I saw that you changed the spec in https://github.com/w3c/html-aria/commit/daca00dc304f5c3944ed0a0ae4d3b6f9d60039bc which means that the validator is now correct, so this can be closed.
I will open an issue on https://github.com/w3c/html-aria regarding that change and this discussion.

**Comment by selfthinker** [comment]
I just found something else which seems to support @scottaohara's stance:
The [HTML 5.1 spec](https://www.w3.org/TR/html51/sections.html#the-nav-element) allowed `role=presentation` on `nav` but it was removed in the [HTML 5.2 spec](https://www.w3.org/TR/html52/sections.html#the-nav-element).

**Comment by scottaohara** [comment]
yes.  again, these roles were added to nav in error.  i'm sorry for the confusion this caused, but they weren't intended to be there, which this issue brought to light
