### ISSUE TITLE
The web page is not fully loaded into the validator 

### ISSUE THREAD

**Issue by alex-webmaster** [validator/validator#1113]
I am trying to validate https://chitatel.by home page, but it is not fully loaded into the validator. 

https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fchitatel.by%2F

![Screenshot_1](https://user-images.githubusercontent.com/22845834/110670763-cef7c800-81de-11eb-8e03-98d10ce20c2f.png)
![Screenshot_4](https://user-images.githubusercontent.com/22845834/110670772-d0c18b80-81de-11eb-8fe2-ce725993edab.png)

**Comment by sideshowbarker** [comment]
Yeah the cause of that is not a bug in the checker but instead appears to be some problem with the https://chitatel.by/ server itself.

Try making a request to that server using something like wget or curl:

```
curl https://chitatel.by/ -o /dev/null
…
curl: (18) transfer closed with outstanding read data remaining

…
wget -q -O- https://chitatel.by/
```
Notice how the output gets truncated.

**Comment by alex-webmaster** [comment]
Thank you!
