### ISSUE TITLE
label containing 2 inputs 1 of which is type=hidden

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#112]
when a label includes 2 inputs 1 of which is type=hidden it throws an error
Error: The label element may contain at most one input, button, select, textarea, or keygen descendant.
but the spec indicates that input type=hidden is not a labelable element so should not be cosnidered in the rule:
label content model:
"Phrasing content, but with no descendant labelable elements unless it is the element's labeled control, and no descendant label elements."
http://www.w3.org/TR/html5/forms.html#the-label-element

**Comment by cvrebert** [comment]
More specifically, https://html.spec.whatwg.org/multipage/forms.html#category-label says:
> **labelable elements**. These are elements that can be associated with a label element.
> => [...] `input` (*if the `type` attribute is not in the `hidden` state*), [...]

**Comment by sideshowbarker** [comment]
Pushed to http://validator.w3.org/nu/
