### ISSUE TITLE
For more informations

### ISSUE THREAD

**Issue by MahamadouLH** [validator/validator#1121]
Greetings,
I have to use accessibility on my website but aria-label values are not allowed by the validator because they send me warnings about aria-label.
if you can give the appropriate way to use aria-label, you will be helpful thank you.

respectfully

**Comment by cvrebert** [comment]
What specific warnings are you encountering?

**Comment by MahamadouLH** [comment]
The warning is about the value of aria-label  Here is the warning i gotPossible misuse of aria-label. (If you disagree with this warning, file an issue report or send e-mail to ***@***.***)From line 13, column 4; to line 13, column 64ader">↩ <div id="firstBanner" aria-label="First" class="firstBanner">  Provenance : Courrier pour Windows 10 De : Chris RebertEnvoyé le :vendredi 19 mars 2021 06:32À : validator/validatorCc : Mahamadou LH; AuthorObjet :Re: [validator/validator] For more informations (#1121) What specific warnings are you encountering?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by scottaohara** [comment]
You should not be using aria-label on a generic element like a div, unless you also provide it a role. That’s why you got the error. 

https://www.tpgi.com/short-note-on-aria-label-aria-labelledby-and-aria-describedby/

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1121#issuecomment-802724559

**Comment by MahamadouLH** [comment]
Thank you too much...
