### ISSUE TITLE
Element style not allowed as child of element div in this context

### ISSUE THREAD

**Issue by RawMajkel** [validator/validator#1133]
URL being validated or code to reproduce error: https://usg-warszawa.pl/

```
Element style not allowed as child of element div in this context
```

Based on "4.2.6. The style element" in https://www.w3.org/TR/html52/document-metadata.html#the-style-element it's not a bug anymore.

**Comment by scottaohara** [comment]
The HTML 5.2 specification was superseded Jan 28, 2021
see: https://html.spec.whatwg.org/multipage/semantics.html#the-style-element

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1133#issuecomment-814944825
