### ISSUE TITLE
<a> is not allowed as child of a <label> element

### ISSUE THREAD

**Issue by petervangrieken** [validator/validator#1139]
According to https://www.w3.org/TR/html52/sec-forms.html#the-label-element the only allowed content for a `<label>` element is

> Phrasing content, but with no descendant labelable elements unless it is the element’s labeled control, and no descendant label elements.

However, the validator does not flag an `<a>` inside a `<label>` element as an error.

Here’s an example page that I used to test this: https://cdpn.io/petervangrieken/debug/VwPErMv/LQAExgmVPppr

**Comment by scottaohara** [comment]
The 5.2 Specification does not actually make a normative requirement that says an `<a>` cannot be placed within a `<label>`. The example and note it provides is good advice, but does not actually make state it's invalid markup.

Also note, the W3C HTML 5.2 specification was superseded 28 January 2021.  [The HTML Living Standard](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) also makes no normative requirement that `<a>` cannot be a child of a `<label>`.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1139#issuecomment-823398199
