### ISSUE TITLE
Autocomplete with checkbox shouldn't be an error

### ISSUE THREAD

**Issue by rknasc12** [validator/validator#1141]
URL being validated or code to reproduce error:
<!DOCTYPE HTML>
<html lang="en">

<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="Bug in validator with checkboxes and autocorrect" />
<title>A checkbox with autocomplete shouldn't be an error</title>
</head>

<body>
<input type="checkbox" id="alphabox" name="alphabox" autocomplete="off">
</body>
</html>

```
Error: Attribute autocomplete is only allowed when the input type is color, date, datetime-local, email, hidden, month, number, password, range, search, tel, text, time, url, or week.

From line 16, column 1; to line 16, column 72

>↩<body>↩↩<input type="checkbox" id="alphabox" name="alphabox" autocomplete="off">↩↩</bo
```

autocomplete has a meaning with checkbox. It tells the browser to leave the value of the box as it is in the HTML file and not to set it to the value from before the reload. To see the difference, run the code above, check the box and reload. Then do the same with autocomplete="on" (the default)

**Comment by cvrebert** [comment]
https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type=checkbox)

> ## 4.10.5.1.15 Checkbox state (type=checkbox)
> [...]
> ***Bookkeeping details***
> [...]
> * The following content attributes must not be specified and do not apply to the element: [...], `autocomplete`, [...]

While the attribute is sadly needed in practice due to https://bugzilla.mozilla.org/show_bug.cgi?id=654072 , the validator is just following the spec here.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1141#issuecomment-826371930
