### ISSUE TITLE
Property text-underline-offset doesn't exist.

### ISSUE THREAD

**Issue by okeul** [validator/validator#1143]
URL being validated or code to reproduce error: 
```
a:link{text-underline-offset:.1rem}
```

Error:
```
CSS: text-underline-offset: Property text-underline-offset doesn't exist.
```
![Capture d’écran 2021-04-30 à 21 37 56](https://user-images.githubusercontent.com/6248074/116746210-6b2e9600-a9fc-11eb-99c0-c7e4226ddfce.png)
![Capture d’écran 2021-04-30 à 21 38 03](https://user-images.githubusercontent.com/6248074/116746213-6bc72c80-a9fc-11eb-98d5-41e79da65e1e.png)

The W3C validator indicates that the text-underline-offset property does not exist, but it does: https://caniuse.com/?search=text-underline-offset

**Comment by sideshowbarker** [comment]
Thanks for reporting this — fixed in the sources and pushed to https://validator.w3.org/nu/
