### ISSUE TITLE
Warning: Possible misuse of aria-label

### ISSUE THREAD

**Issue by elieserdiaz** [validator/validator#1151]
If I used the `arial-label` here 👇 it is due to the fact that this `li` element acts as a link to perform an action 

![Captura el 2021-05-18 a las 08 19 02](https://user-images.githubusercontent.com/34104884/118649879-6c820000-b7fd-11eb-91ab-56821120f4e1.png)

`<ul>
					<li class="item-content list-panel-all close-panel item-link" aria-label="Todos mis pacientes">
						<div class="item-media"><i class="icon simbicon-contact-s1" aria-hidden="true"></i></div>
						<div class="item-inner">
							<div class="item-title">Show all</div>
						</div>
					</li>
					<li class="item-content list-panel-favorites close-panel item-link" aria-label="Mis pacientes favoritos">
						<div class="item-media"><i class="icon simbicon-star-s1" aria-hidden="true"></i></div>
						<div class="item-inner">
							<div class="item-title">Show favorites</div>
						</div>
					</li>
				</ul>`
My question is if it may be possible to keep the `aria-label` or I should remove it or maybe add a real `a href` link?

**Comment by sideshowbarker** [comment]
Per https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/ aria-label should not be used for `li` elements. The stated reason is, *“aria-label use not well supported”*
