### ISSUE TITLE
Error: CSS: margin-block-start: Property margin-block-start doesn't exist.

### ISSUE THREAD

**Issue by r12a** [validator/validator#1173]
URL being validated or code to reproduce error:
https://w3c.github.io/i18n-glossary/

```
Error: CSS: margin-block-start: Property margin-block-start doesn't exist.
```

margin-block-start and numerous other -block-start and -block-end property pairs do exist and work in browsers. Furthermore, their use is strongly recommended for internationalization.

Please fix.

For a few more examples of related things that should work, see https://www.w3.org/International/questions/qa-html-dir#alignment

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve fixed it now, and pushed the fix to https://validator.w3.org/nu/
