### ISSUE TITLE
Error: Stray start tag script yet there is no JS and.....

### ISSUE THREAD

**Issue by Fisch488** [validator/validator#1174]
URL being validated or code to reproduce error:https://ruralpropertycroatia.com
The error arises at a line which does not exist (after final </html>).  There is no javascript anywhere on the page.   Nothing is in <head> that shouldn't be. <body> follows immediately after </head>, nothoing follows </body> except </html> 

paste error messages into code block
```

**Comment by Fisch488** [comment]
Now the <tags> have disappeared????    Nothing is in <head> that shouldn't be.  <body> follows </head> immediately, nothing follows </body> except </html>    

<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="description" content="Real Estate for sale in Croatia inland. Countryside, rural, urban or residential settings, see what is available here.">
<title>ruralpropertycroatia.com</title>
<link rel="stylesheet" type="text/css" href="./css/newrpc1.css">
<link rel="shortcut icon" href="ico5.ico" />

<style>
@media only screen and (max-width: 768px),
(min-width: 768px) and (max-width: 1024px)  
{table, thead, tbody, th, td, tr {display: block;}}
</style>

<STYLE>A {text-decoration: none;} </STYLE>

</head>

**Comment by Fisch488** [comment]
I closed it?   I've given up - I only speak English.

**Comment by sideshowbarker** [comment]
In fact in the source of https://ruralpropertycroatia.com/ after the `</html>` end tag, there’s a `script` element:

```html
</body></html><script type = "text/javascript"> (function(d, w) { var x = d.getElementsByTagName('SCRIPT')[0]; var f = function() { var _id = 'lexity-pixel'; var _s = d.createElement('script'); _s.id = _id; _s.type = 'text/javascript'; _s.async = true; _s.src = "//np.lexity.com/embed/YW/1dabd51e04b0094b88128cafdac65f02?id=e65a1bf61c4a"; if (!document.getElementById(_id)) { x.parentNode.insertBefore(_s, x); } }; w.attachEvent ? w.attachEvent('onload', f) : w.addEventListener('load', f, false); }(document, window)); </script>
```
To confirm that, you can use `curl` or something, like this:

```
$ curl -s https://ruralpropertycroatia.com/ | tail
<a href="./properties/2492/2492.html">
<img src="./properties/2492/2492_01.jpg" alt="Ref 2492" style="max-width:100%; border:1px solid black"></a>
<br>
<p><b>€55,000</b>&nbsp; &nbsp;  &nbsp; <small>Ref: 2492. &nbsp; &nbsp;  &nbsp; 22/6/2021</small>
<br>Large property on a big plot in the countryside near Karlovac.
</td>
</tr>
</table>

</body></html><script type = "text/javascript"> (function(d, w) { var x = d.getElementsByTagName('SCRIPT')[0]; var f = function() { var _id = 'lexity-pixel'; var _s = d.createElement('script'); _s.id = _id; _s.type = 'text/javascript'; _s.async = true; _s.src = "//np.lexity.com/embed/YW/1dabd51e04b0094b88128cafdac65f02?id=e65a1bf61c4a"; if (!document.getElementById(_id)) { x.parentNode.insertBefore(_s, x); } }; w.attachEvent ? w.attachEvent('onload', f) : w.addEventListener('load', f, false); }(document, window)); </script>
```
