### ISSUE TITLE
New feature request: "Congratulations! No Error Found." on green background.

### ISSUE THREAD

**Issue by iorgu** [validator/validator#120]
Dear W3C Team!

I'm missing the "Congratulations! No Error Found." on green background.
Please make it like the CSS3 validator.

Thank you in advance!

**Comment by sideshowbarker** [comment]
Hi @iorgu 
Thanks for your report. See my responses at https://github.com/validator/validator/issues/109#issuecomment-114315421 and https://github.com/validator/validator/issues/110#issuecomment-114731726
