### ISSUE TITLE
W3C misses my <html> tag

### ISSUE THREAD

**Issue by noemie-ma** [validator/validator#1206]
Hello. 
So your generator has surlined my <html> tag and said "defining an html tag". But I have one.

**Comment by nschonni** [comment]
Can you provide a URL or snippet that reproduces the issue

**Comment by noemie-ma** [comment]
https://zupimages.net/viewer.php?id=21/32/p0mt.jpg

**Comment by nschonni** [comment]
It's suggesting you set the `lang` attribute on the `<html>` element, not that the tag is missing
