### ISSUE TITLE
U+007C (|) is now a forbidden host code point per URL Standard

### ISSUE THREAD

**Issue by dd8** [validator/validator#1207]
A URL Standard commit earlier this year added U+007C (|) to the list of forbidden host code points:
https://github.com/whatwg/url/commit/40252530f93fe37f092be90583f82e9f337da1ab

and an earlier commit added <, >, and ^ to the forbidden host code points:
https://github.com/whatwg/url/commit/302ba419cb3248568243aaf7b5aca9003694d5c3

This causes 2 issues:

1) VNU doesn't flag errors for U+007C (|), U+003C (<), U+003E (>), and U+005E (^) in URL hosts
2) tools that do flag these can't pass the conformance checker WPT tests because `file://abc|/foo/bar` appears in the URL -isvalid tests

There's a live reference implementation here:
https://jsdom.github.io/whatwg-url/

We can submit a PR to fix 2) but there are two options:

a) just remove `file://abc|/foo/bar` from the isvalid tests
b) move `file://abc|/foo/bar` from the isvalid tests to the novalid tests

Any preference for either of these?

**Comment by sideshowbarker** [comment]
> We can submit a PR to fix 2) but there are two options:
> 
> a) just remove `file://abc|/foo/bar` from the isvalid tests
> b) move `file://abc|/foo/bar` from the isvalid tests to the novalid tests

"b" is better, I think — it’s better to have a test for it

> VNU doesn't flag errors for U+007C (|), U+003C (<), U+003E (>), and U+005E (^) in URL hosts

I’ll try to get a fix for that made soon. The change would need to be made somewhere in the https://github.com/validator/galimatias code. (You might be able to locate and patch it on your own — I think that code is fairly readable.)
