### ISSUE TITLE
CSS: Unknown pseudo-element or pseudo-class “::file-selector-button”.

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#1209]
Hello, when validating the following HTML I get a `CSS: Unknown pseudo-element or pseudo-class “::file-selector-button”.` error.

```html
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
<style>
input[type=file]::file-selector-button {
  border: 2px solid #6c5ce7;
  padding: .2em .4em;
  border-radius: .2em;
  background-color: #a29bfe;
  transition: 1s;
}
</style>
</head>
<body>
<form>
  <label for="fileUpload">Upload file</label>
  <input type="file" id="fileUpload">
</form>
</body>
</html>
```

I believe this is a bug in the validator, as this example was taken from:

https://developer.mozilla.org/en-US/docs/Web/CSS/::file-selector-button

And it fits the guide at:

https://www.w3.org/TR/css-pseudo-4/#file-selector-button-pseudo

Am I missing something?

Thanks!

**Comment by sideshowbarker** [comment]
I think the CSS backend just doesn’t have any support for `::file-selector-button` yet.

So for now I’ve just added a workaround to the checker which causes it to filter out that error.
