### ISSUE TITLE
Old Jetty (9.4.18.v20190429)

### ISSUE THREAD

**Issue by MikaelLindmark** [validator/validator#1219]
The Jetty (version  9.4.18.v20190429) is old and it needs to be updated due to security flaws.

**Comment by sideshowbarker** [comment]
Thanks for raising this. I’ve pushed a change that updates all the Jetty dependencies to 10.0.6.

**Comment by sideshowbarker** [comment]
Update: I ended up jumping back instead to the latest Jetty 9 version, 9.4.43.v20210629 — because upgrading to Jetty 10 broke the build we use for creating the modular jar and binary runtime images.
