### ISSUE TITLE
CSS: scrollbar-width: Property scrollbar-width doesn't exist.

### ISSUE THREAD

**Issue by bnbabu55** [validator/validator#1220]
URL being validated or code to reproduce error:

https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fpomareslawgroup.smr-sandbox.com%2F#l5c40860

```
paste error messages into code block
```
`CSS: scrollbar-width: Property scrollbar-width doesn't exist.`

I am seeing this  error message, but the feature is supported in HTML5 accroding to MDN, https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width, please look into this and see if a fix is required.

**Comment by sideshowbarker** [comment]
I believe this is fixed now. If not, we can re-open this.

**Comment by bnbabu55** [comment]
Worked, thanks for a quick resolution.
