### ISSUE TITLE
var(--tw-empty,/*!*/ /*!*/) is not recognized as valid value.

### ISSUE THREAD

**Issue by bnbabu55** [validator/validator#1222]
URL being validated or code to reproduce error:
https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fpomareslawgroup.smr-sandbox.com%2F#cl5c2858
```
paste error messages into code block
```
`Error: CSS: --tw-blur: Parse Error.`

Using Tailwindcss as my css framework, they have these auto generated variables for empty values, errors start at the first occurrence of `var(--tw-empty,/*!*/ /*!*/)` usage. Please check the link for further details. 

I have done research on this, in Tailwindcss forum and they say this is a valid syntax, https://github.com/tailwindlabs/tailwindcss/issues/2889, can you please check?

Thanks,
Babu.

**Comment by ylafon** [comment]
See w3c/css-validator#320

**Comment by bnbabu55** [comment]
Tested and it, this is not getting flagged now. Thanks a lot for fixing it so quickly.
