### ISSUE TITLE
Wrong unicode domain name decoding

### ISSUE THREAD

**Issue by ZettaScript** [validator/validator#1225]
In the "Validate by URI" address field, the hostname is decoded the same way as the rest of the URI. This causes unicode hostnames to be badly decoded.

For example, the domain name `ğ.ml` should give `xn--tea.ml`, however it gives `%C4%9F.ml`.

**Comment by sideshowbarker** [comment]
Thanks for reporting this. Could you please re-raise this issue in the issue tracker at https://github.com/w3c/markup-validator/issues/new ?

**Comment by ZettaScript** [comment]
Done: https://github.com/w3c/markup-validator/issues/63

**Comment by sideshowbarker** [comment]
Thanks!
