### ISSUE TITLE
Says "clip" is not a valid property for overflow-y

### ISSUE THREAD

**Issue by mangelozzi** [validator/validator#1229]
Code to reproduce error:
```
<style>
@media (min-width: 1000px) {
    html {
        overflow-y: clip;
    }
}
</style>
```

MDN (although not authoritive but is a good source) says clip is a valid property: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y

![image](https://user-images.githubusercontent.com/19764314/132898201-eac1ca41-aaae-4234-8c65-1c60781f2074.png)

**Comment by sideshowbarker** [comment]
Thanks for reporting this.

I updated the CSS-checking backend today, and I can’t reproduce this currently. So I imagine it got fixed by the recent updated.
