### ISSUE TITLE
ERRORs Not Reported

### ISSUE THREAD

**Issue by davideugeneking** [validator/validator#123]
ERRORs Not Reported

https://validator.w3.org/check 
Validate by File Upload
No ERRORs Reported

Validation Output: 2 Warnings 
Below is a list of the warning message(s) produced when checking your document. 
 This interface to HTML5 document checking is deprecated. 
Use the Nu Html Checker at https://validator.w3.org/nu/ directly instead.
↑ Top
Congratulations
The uploaded document "index.html" was successfully checked as HTML5. This means that the resource in question identified itself as "HTML5" and that we successfully performed a formal validation of it. The parser implementations we used for this check are based on validator.nu (HTML5). 

Used validator.nu (HTML5).

Should Have Reported ERROR
Line 74 < / body > closing element…no opening element <body>

Inserted < p > element without closing < / p > and saved…
Validate by File Upload
AGAIN…
No ERRORs Reported

**Comment by sideshowbarker** [comment]
> Should Have Reported ERROR
> Line 74 < / body > closing element…no opening element

That's not an error. The opening `<body>` tag is optional.
See the **Tag omission in text/html** section here:

https://html.spec.whatwg.org/multipage/semantics.html#the-body-element

> Inserted < p > element without closing < / p > and saved…

That's not an error. The closing `<p>` tag is optional.

https://html.spec.whatwg.org/multipage/semantics.html#the-p-element
