### ISSUE TITLE
w3school validator failed

### ISSUE THREAD

**Issue by HarshVakil** [validator/validator#1236]
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>ME</title>
</head>
<body>
 harsh 
</body>
</html>
```

Can you tell me whats the problem

**Comment by cvrebert** [comment]
I get no errors when checking that code on https://validator.w3.org/nu/ , just 1 warning suggesting a `lang` attribute (with links to explanations).
What error are you encountering?

**Comment by sideshowbarker** [comment]
Closing for lack of response
