### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [validator/validator#1237]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by sideshowbarker** [comment]
Thanks — I’ve created https://github.com/validator/validator/blob/main/SECURITY.md; this gist of which is:

> To report a security vulnerability by e-mail, send a message to mike@w3.org. PGP-encrypted messages are welcome. To send a PGP-encrypted message, you can use the key at https://github.com/sideshowbarker.gpg.

**Comment by nschonni** [comment]
Not sure if it makes sense to add https://securitytxt.org/ to the subdomain root
