### ISSUE TITLE
    IO Error: Read timed out

### ISSUE THREAD

**Issue by HiteshVaghela** [validator/validator#124]
I am trying check this site for validation but ending up with this error. Cant catch up where i am going wrong . Thanks if anyone got idea or solution for this

ERROR :     IO Error: Read timed out

Site : http://www.divesitenet.com/

**Comment by sideshowbarker** [comment]
The reason for the error is that site takes an extremely long time to respond to connection requests (along with taking an extremely long time to load), and it was causing the checker to hit a timeout. So I increased the timeout in the checker, and you should be able to check it now.
