### ISSUE TITLE
Google Site Name recommended markup reports as invalid

### ISSUE THREAD

**Issue by dreamwhisper** [validator/validator#125]
Google is recommending the following markup for Site Name at https://developers.google.com/structured-data/site-name

```html
 <head itemscope itemtype="http://schema.org/WebSite">
    <title itemprop='name'>Your WebSite Name</title>
    <link rel="canonical" href="https://example.com/" itemprop="url">
```
However, the validator reports this markup as invalid `Error: Attribute itemprop not allowed on element link at this point.` due to `<link rel="canonical" href="https://example.com/" itemprop="url">`.

Is this technically invalid or is the validator just reporting it as such?

**Comment by sideshowbarker** [comment]
Hi, thanks for reporting this.
> Is this technically invalid or is the validator just reporting it as such?

The HTML spec is clear about it; see the third paragraph of the content after the green section here:
https://html.spec.whatwg.org/multipage/semantics.html#the-link-element
> A link element must have either a rel attribute or an itemprop attribute, but not both.

So the markup example at https://developers.google.com/structured-data/site-name is non-conforming and should be changed, I think, by just removing the `rel="canonical"` attribute.

And so as far as what markup you use in your documents I think you can ignore what the example says and just use `<link href="https://example.com/" itemprop="url">` (without the `rel="canonical"`) and everything will work as expected as far as having it appear correctly in Google search results.

FYI @danbri. I would raise a bug for this but don’t see a **Report a bug** or whatever link on that page nor anywhere on that site…
