### ISSUE TITLE
& sign in urls.

### ISSUE THREAD

**Issue by michaelcheers** [validator/validator#126]
In urls it says & sign should be &amp; when in urls  is requried.

**Comment by sideshowbarker** [comment]
yeah there's an open bug for this already, issue #31. I'm still working on getting it fixed but I don't really have an ETA

**Comment by sideshowbarker** [comment]
Fixed in v16.1.1 and after https://github.com/validator/validator/releases/latest and pushed to https://validator.w3.org/nu/
