### ISSUE TITLE
Question: Parsing and internal attribute on a <script> element

### ISSUE THREAD

**Issue by mmiron-HC** [validator/validator#1266]
We are running W3C validator on Appian website (cannot share URL) and it is returning the following:

Error: Attribute internal not allowed on element script at this point.

`<script async src=""/suite/tempo/ui/sail-client/embeddedBootstrap.nocache.js?appian_environment=sites"" id=""appianEmbedded"" internal=""true"" data-bannerposition=""hidden""></script>"`

Vendor is arguing that this is not a failure since as per their understanding of the Parsing success criterion as long as it doesn't interfere and can be accurately interpreted/parsed by screen reader that this would not be a violation of the SC. They say it would only be a violation if it negatively impacted the end users.

We disagree and argued that while it does say something to this affect in the SC, [techniques H88](https://www.w3.org/WAI/WCAG21/Techniques/html/H88) mentions that we should "Check that the page uses only elements, attributes and attribute values that are defined in the relevant specification." and the [HTML specification](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-script-element.html) doesn't outline the "internal" attribute as an allowed attribute on the <script> element. 

We want to confirm that this is also your understanding.

**Comment by sideshowbarker** [comment]
> and the [HTML specification](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-script-element.html) doesn't outline the "internal" attribute as an allowed attribute on the <script> element.

That’s correct and that’s the reason the validator reports an error.
