### ISSUE TITLE
"Possible misuse of aria-label" disagree

### ISSUE THREAD

**Issue by F-nour** [validator/validator#1268]
It's an option to the tag `<div>` for the web accessibility!

**Comment by scottaohara** [comment]
an `aria-label` on a generic element (`div`) is not a good idea.  https://www.w3.org/TR/wai-aria-1.2/#generic

if you are going to add an `aria-label` to a `div`, that element needs to also have a role that allows for naming.  e.g., `region`, `group`, `button`, etc.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1268#issuecomment-965576653
