### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by Goodluck5956** [validator/validator#1271]
Having corrected the error I got from the filter message using the W3 Validator, I noticed the same error keep occurring. From the error message, I was asked to add my `<!DOCTYPE html>`, The `<head></head>` and in between the head, i should have my `<title></title>`. I have done all of that but once I run the check again, I got the same error message. Kindly help look into it, please.

**Comment by sideshowbarker** [comment]
Please post a document or URL for a document that demonstrates the problem

**Comment by Goodluck5956** [comment]
Here is my URL to the problem: https://codepen.io/lucky-james/pen/JjyerjV

**Comment by nschonni** [comment]
There is no error running the text from the pen on https://validator.w3.org/nu/ which is this project. There are errors on the codepen HTML analyzer, but we can't help you debug your code
