### ISSUE TITLE
Page Anchoring Appears To Be Broken

### ISSUE THREAD

**Issue by michaelspellacy** [validator/validator#1275]
Hi there! I would love to be able to anchor to certain portions of a report, after a scan has been completed, but this does not seem to work properly. My guess is that because portions of the page appear to be dynamic and load after the initial page load, that this may be what is interfering with anchoring to correct location on page. You can see the issue here: 

Header Outline: https://validator.w3.org/nu/?showoutline=yes&doc=https://www.w3.org/#headingoutline

Image Report: https://validator.w3.org/nu/?showimagereport=yes&doc=https://www.w3.org/#imagereport 

Maybe setting a slight delay when a hash is present in URL or including a checkbox to disable error reporting might help? 

Thank you! Such an invaluable tool!

**Comment by sideshowbarker** [comment]
Thanks much for reporting this. I believe I have it fixed in the sources, and I’ve pushed the fix to https://validator.w3.org/nu/ — but if you try and find it’s still not working as expected, please let me know.

**Comment by michaelspellacy** [comment]
Wow! Thank you so much for doing this so quickly! Works great now!
