### ISSUE TITLE
aria-roledescription is not working with implicit/explicit role

### ISSUE THREAD

**Issue by ElamuruganGR** [validator/validator#1283]
a)
```
<section aria-roledescription="carousel" aria-labelledby="carousel-header" >
        <h1 id="carousel-header" >Popular Web series and Episodes</h1>
        <button>Trigger</button>
</section>
```
b)
```
<div role="region" aria-roledescription="carousel" aria-labelledby="carousel-header" >
        <h1 id="carousel-header" >Popular Web series and Episodes</h1>
        <button>Trigger</button>
</div>
```

For the above codes, axe-core-4.3.5 gives the following error eventhough using implicit/explicit aria-role:
a & b) **aria-roledescription must be on elements with a semantic role.**
**Issue Description: Ensure aria-roledescription is only used on elements with an implicit or explicit role**

Screen reader (ChromeVox and voiceover) is reading the above as
**a) Section Trigger button**
**b) Popular Web Series and its Episodes Trigger**

Please refer my work below to detect the issue:
https://wizardly-davinci-611bef.netlify.app/

Its not reading the text inside aria-roledescription.

FYI: Even the carousel design pattern examples provided in w3c is also not reading the aria-roledescription

**Comment by scottaohara** [comment]
@ElamuruganGR is there a problem with the validator you are trying to raise?  As your issue seems to be talking about issues you're having with axe's flags, and potential browser / AT bugs.

**Comment by ElamuruganGR** [comment]
@scottaohara I thought it as w3c and raised this issue. But thanks for checking out. I'll close this.
