### ISSUE TITLE
Pset9 Finance TraceBack, FileNotFoundError, AttributeError

### ISSUE THREAD

**Issue by RianMarques26** [validator/validator#1290]
I have been stuck for the past 2 hours trying to identify what is the issue in my code. When I put my API_Key and run flask, I get these errors that I haven't seen before and don't know how to fix.

I tried to ignore them and start the problem set by doing the register part and when I test it I get more issues (AttributeError: 'str' object has no attribute 'get') as you can see. Please help!

![0](https://user-images.githubusercontent.com/92201113/147436653-38841d1a-b8d9-4c91-a8f1-fc1a59ae612f.png)
![1](https://user-images.githubusercontent.com/92201113/147436655-667724dc-9146-47c3-89a3-4f3fc33b7a54.png)
![2](https://user-images.githubusercontent.com/92201113/147436656-eca8d5b3-a24c-4343-ab1d-b303f5e9fafc.png)

**Comment by nschonni** [comment]
This looks like a StackOverflow question, that has nothing to do with this library/site
