### ISSUE TITLE
Warn authors of deprecated aria-* attributes

### ISSUE THREAD

**Issue by scottaohara** [validator/validator#1295]
`aria-grabbed` and `aria-dropeffect` were deprecated in ARIA 1.1, and their support is rather poor.  The HTML validator should flag instances of these attributes and warn authors that they are deprecated, and ideally that support for them is poor and will likely not improve.

**Comment by stevefaulkner** [comment]
@sideshowbarker  need some help with where to define this?

**Comment by sideshowbarker** [comment]
> am thinking the attributes should be listed in validator\schema.drivers\legacy.rnc and messages in validator\schema\html5\assertions.sch under `<pattern name="Warnings for HTML5 attributes that are obsolete but conforming">`

That sounds right, yeah — and you’d also want to delete any existing places in files in `schema/html5` where `aria-grabbed` and `aria-dropeffect` currently show up.

**Comment by sideshowbarker** [comment]
> > am thinking the attributes should be listed in validator\schema.drivers\legacy.rnc and messages in validator\schema\html5\assertions.sch under `<pattern name="Warnings for HTML5 attributes that are obsolete but conforming">`
> 
> That sounds right, yeah

Sorry, I misspoke — `validator\schema\html5\assertions.sch` is no longer used; the changes instead need to be made to the `src/nu/validator/checker/schematronequiv/Assertions.java` code.

The additions to `validator\schema.drivers\legacy.rnc` still need to be made.

> and you’d also want to delete any existing places in files in `schema/html5` where `aria-grabbed` and `aria-dropeffect` currently show up

I pushed an update to the PR branch here which makes those deletions.
