### ISSUE TITLE
W3C validator flagging Gatsby Image generated picture and img tags as errors - may be related to ReactJS hydration logic.

### ISSUE THREAD

**Issue by bnbabu55** [validator/validator#1298]
URL being validated or code to reproduce error:
https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fpomareslawgroup.com%2F
```
paste error messages into code block
```
`Element source is missing required attribute srcset.
The sizes attribute may be specified only if the srcset attribute is also present.
Attribute layout not allowed on element img at this point.
Element img is missing required attribute src.
The sizes attribute may be specified only if the srcset attribute is also present.
Attribute layout not allowed on element img at this point.
`

I created a [ticket](https://github.com/gatsbyjs/gatsby/issues/34431) in Gatsby repo to get a response, they are saying, validator tool is just considering the HTML but not checking <script> tag that has the logic to hydrate the correct HTML code. And stating that it is working as intended and not a problem, they closed the ticket.

I don't know how to take this forward, hence creating this new ticket. Please take a look and see if you can resolve this issue.

The website works fine, I don't notice any problems here. But client ran the W3C validator and insisted that these errors should be resolved.

**Comment by nschonni** [comment]
yeah, it looks like they're trying to do stuff around react performance, but the bottom line is that it isn't valid HTML

**Comment by nschonni** [comment]
It seems like it's been reported a few times over the years https://github.com/gatsbyjs/gatsby/issues/31635

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1298#issuecomment-1009643414

**Comment by LekoArts** [comment]
This is considered "modern best practice" so in fact the validator needs adjustment, see https://github.com/validator/validator/issues/811
