### ISSUE TITLE
Release on Maven Central

### ISSUE THREAD

**Issue by gdelhumeau** [validator/validator#13]
Hello.

Could you release your application into Maven Central (http://search.maven.org/)? It would make easy for developers to integrate the VNU classes into their applications.

Thanks,
Guillaume

**Comment by sideshowbarker** [comment]
FYI this weekend I made code changes that reduce the number of runtime dependencies.

So at this point I think **all the dependencies are now available from maven central except a icu4j-charset-*.jar** (`com/ibm/icu/charset` & `com/ibm/icu/impl/data` packages). And the reason it's not there is just, no ICU project devs have had time yet to do the work needed to make it available; see http://bugs.icu-project.org/trac/ticket/8241 & http://sourceforge.net/p/icu/mailman/message/30089933/

**Comment by skibz** [comment]
kudos @sideshowbarker !!

**Comment by rwhogg** [comment]
Great to hear it! Ideally I'll be able to update the POM in my fork sometime on the weekend.

**Comment by sideshowbarker** [comment]
> Great to hear it! Ideally I'll be able to update the POM in my fork sometime on the weekend.

Super—if you end up having time to work on it this weekend and run into any questions or need help, please feel free to ping me.

**Comment by jitpack** [comment]
If there are dependencies that are on GitHub but not on any public repositories you could get them with https://jitpack.io

**Comment by sideshowbarker** [comment]
So FYI this weekend I finally got around to adding a build target to publish releases to the Central Repository that will meet the requirements given at http://central.sonatype.org/pages/requirements.html

So I've filed a project-creation request (see https://issues.sonatype.org/browse/OSSRH-14147) and as soon as the project gets created, I'll publish a release.

**Comment by rwhogg** [comment]
Great to hear it!

I've been using your new autogenerated POM file (no sense in updating mine anymore) and experiencing some problems - namely that log4j 1.2.15 has certain dependencies that are seemingly unavailable in Maven Central, which causes ```bash mvn install ``` to fail. I haven't looked into the compatibility issues yet, but using 1.2.17 appears to fix the download problem, so maybe someone (me?) should investigate whether or not you can upgrade. Assuming the releases follow semver, there shouldn't be any problems, but I'm not 100% sure.

I found another minor issue as well, but I'll be issuing a PR for that shortly.

**Comment by sideshowbarker** [comment]
> I've been using your new autogenerated POM file

Cool—thanks for testing it

> I've been using your new autogenerated POM file (no sense in updating mine anymore) and experiencing some problems - namely that log4j 1.2.15 has certain dependencies that are seemingly unavailable in Maven Central, which causes mvn install to fail. I haven't looked into the compatibility issues yet, but using 1.2.17 appears to fix the download problem

Using log4j 1.2.17 should be fine. I think the only reason we're using 1.2.15 is, that was the latest available at the time we last updated that dependency (more than 6 years ago…)

> I haven't looked into the compatibility issues yet, but using 1.2.17 appears to fix the download problem, so maybe someone (me?) should investigate whether or not you can upgrade.

I'll go ahead and change the dependency in our build script and test with it. If it seems to be working as expected, I'll switch it in the source for the generated POM as well, and then push it all.

Thanks again much for attention and help

**Comment by sideshowbarker** [comment]
Travis CI liked the log4j update to 1.2.17 just fine https://travis-ci.org/validator/validator/builds/52702187
and locally I also built fine and started and ran the service fine with no unexpected warnings or errors. I ran the regression test suite with no unexpected results and I (manually) tested the WAR file too. So, everything's passing.

**Comment by rwhogg** [comment]
Sonatype is ready to accept the project! :)

**Comment by sideshowbarker** [comment]
We have liftoff:

https://repo1.maven.org/maven2/nu/validator/validator/15.3.10/

**Comment by cvrebert** [comment]
:fireworks: :sunglasses: :tada:

**Comment by gdelhumeau** [comment]
Great news! Thanks!

**Comment by sideshowbarker** [comment]
FYI, since the checker uses a forked version jing, I also released package of that version. And since the HTML parser that we use hasn't been released on maven in more than 2 years, I also released an updated version of that.

All can be found here:

https://repo1.maven.org/maven2/nu/validator/

The validator package of course has its dependency info set to depend on those two packages.

Please test and raise new issues if you find any problems.

**Comment by rwhogg** [comment]
Great news!
