### ISSUE TITLE
Importmap validation error

### ISSUE THREAD

**Issue by alecslupu** [validator/validator#1309]
Using the default `javascript_importmap_tags` method helper defined in  https://github.com/rails/importmap-rails, will generate the following output sequence 
```
<script type="importmap" data-turbo-track="reload">{
  "imports": {
    "leaflet": "https://ga.jspm.io/npm:leaflet@1.3.1/dist/leaflet-src.js",
  }
}
</script>
```
As per  https://wicg.github.io/import-maps/#integration-environment-settings-object, the above snippet is valid. 

Validating the HTML output of a page using: https://validator.w3.org/nu/#textarea will yield a validation error like : 

![image](https://user-images.githubusercontent.com/105683/151056379-bc24e222-9448-4234-95d1-aaf60ef68077.png)

In order to avoid that, it is recommended to set the script type to `application/importmap+json` .

<details>
  <summary>Faliling validation</summary>

```
<!DOCTYPE html>
<html  lang="en">
    <title>Koelpin-Macejkovic</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<script type="importmap" data-turbo-track="reload">
{
  "imports": {
    "./resources/log.js?pipe=sub&name=A": "./resources/log.js?pipe=sub&name=B"
  }
}
</script>
<script>
const log = [];
promise_test(() => {
  return import("./resources/log.js?pipe=sub&name=A")
    .then(() => import("./resources/log.js?pipe=sub&name=B"))
    .then(() => assert_array_equals(log, ["log:B"]))
  },
  "Module map's key is the URL after import map resolution");
</script>
```
</details>

<details>
  <summary>Passing validation</summary>

```
<!DOCTYPE html>
<html  lang="en">
    <title>Koelpin-Macejkovic</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<script type="application/importmap+json" data-turbo-track="reload">
{
  "imports": {
    "./resources/log.js?pipe=sub&name=A": "./resources/log.js?pipe=sub&name=B"
  }
}
</script>
<script>
const log = [];
promise_test(() => {
  return import("./resources/log.js?pipe=sub&name=A")
    .then(() => import("./resources/log.js?pipe=sub&name=B"))
    .then(() => assert_array_equals(log, ["log:B"]))
  },
  "Module map's key is the URL after import map resolution");
</script>
```
</details>
Refs: https://github.com/rails/importmap-rails/issues/102

**Comment by guybedford** [comment]
If it helps, the import map specification defines `"type": "importmap"` for scripts in https://wicg.github.io/import-maps/.
