### ISSUE TITLE
Why this error message: "An img element which has an alt attribute whose value is the empty string must not have a role attribute."? 

### ISSUE THREAD

**Issue by kantoche** [validator/validator#1321]
Hi,

Code snippet that triggered the error:
```
cale(1);"><img alt="" role="presentation" src="https://b.tile.openstreetmap.org/10/504/355.png" class="leaflet…loaded" style="width: 256px; height: 256px; transform: translate3d(491px, 277px, 0px); opacity: 1;"><img a
```
Error message that occured:
"An img element which has an alt attribute whose value is the empty string must not have a role attribute."

Issue:
The error message seems inappropriate in this context; indeed, since it is an img element with an empty alt attribute, the presentation role corresponds to its implicit WAI-ARIA semantics (see https://www.w3.org/TR/html-aria/#el-img-empty-alt) and the message should rather be a warning message like: 'The presentation role is unnecessary for element img[alt=""]'.

**Comment by sideshowbarker** [comment]
See the explanation at https://github.com/validator/validator/issues/1425#issuecomment-1293018573
