### ISSUE TITLE
menu element is a type of 'list', not deprecated

### ISSUE THREAD

**Issue by scottaohara** [validator/validator#1343]
URL being validated or code to reproduce error:

Was checking [the `role=directory` test case](https://w3c.github.io/html-aria/tests/deprecated-directory.html) to see if that rule had landed in the latest released build.  Noticed though that the checker flagged use of the`menu` element with the following:
>The `<menu>` element is deprecated in HTML 5

While the w3c html spec did deprecate the `menu` element, [it is not in the HTML standard](https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element).  It's essentially just another `ul` element that [maps to `role=list`](https://w3c.github.io/html-aam/#el-menu)

**Comment by sideshowbarker** [comment]
> Was checking [the `role=directory` test case](https://w3c.github.io/html-aria/tests/deprecated-directory.html) to see if that rule had landed in the latest released build. Noticed though that the checker flagged use of the`menu` element with the following:
> 
> > The `<menu>` element is deprecated in HTML 5

I don’t see how the checker would ever report that message. I don’t think it’s possible for the checker code to ever emit any message with that *“is deprecated in HTML 5”* string in it. And I don’t get that message when I try myself:

https://validator.w3.org/nu/?doc=https://w3c.github.io/html-aria/tests/deprecated-directory.html

**Comment by scottaohara** [comment]
Ah so sorry. Had too many issue tracked open. This doesn’t belong here!
