### ISSUE TITLE
Warning Misuse of aria-label

### ISSUE THREAD

**Issue by StellarRaccoon** [validator/validator#1355]
Misues of aria-label warning appears <i class="bi bi-github" aria-label="github"></i> bootstrap icons recommend the use of aria-label for accesibility

**Comment by scottaohara** [comment]
Guessing the icons are divs or spans without an img role?

**Comment by sideshowbarker** [comment]
Closing due to necessary details being missing.

@StellarRaccoon if you’d like this re-opened, please provide the details listed in https://github.com/validator/validator/issues/new?assignees=&labels=bug&template=incorrect-validation.md&title=
