### ISSUE TITLE
Redesign the UI for the Web frontend

### ISSUE THREAD

**Issue by sideshowbarker** [validator/validator#137]
It would be great to have someone with actual design/UX skills redesign the UI for the Web frontend.

**Comment by benbrignell** [comment]
Happy to help

**Comment by sideshowbarker** [comment]
@benbrignell Thanks and sorry for not replying before not but I don’t have much else to add at this point beyond what’s in the title of the issue. Maybe that best way would be to talk about some ideas on https://gitter.im/validator/validator when we’re both not otherwise preoccupied (I’m in Tokyo, GMT +9).

**Comment by sideshowbarker** [comment]
I’ve done a number of redesign tweaks to the Web UI over the last few months and I think the changes have improved the UX/usability of it enough that I don’t plan to make any further changes unless/until anyone has specific further refinements or redesign to propose.
