### ISSUE TITLE
W3C Validator -> Warning "aria-label"

### ISSUE THREAD

**Issue by brioche2022** [validator/validator#1370]
Hi everyone,,

When I check my website with W3C Validator I have lot of warnings on value "aria-label". 

Here are some examples:

Warning: Possible misuse of aria-label. (If you disagree with this warning, [file an issue report](https://github.com/validator/validator/issues/new) or send e-mail to www-validator@w3.org.)

From line 1089, column 17; to line 1089, column 70 : <span class="regular-price" aria-label="Prix de base">119,99

From line 1040, column 15; to line 1040, column 52 : <span class="price" aria-label="Prix">↩     

Could someone tell me how to fix these warnings? Should I replace the value "aria-label" with something else, maybe just "label"?

Will this affect the positioning of my website in search engines?

Thanks in advance.

**Comment by stevefaulkner** [comment]
@brioche2022 you fix it by not using aria-label on elements that don't support it. Have a read of https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/

**Comment by brioche2022** [comment]
@stevefaulkner thank you for your answer. I went to the link page but I'm not sure I understood what to do.
On the link page it says that for numbers, accessible name from label is preferred.
I replaced the value "aria-label" by "label" but the warnings turned into errors in W3C validator. So I put back the value "aria-label".
Could you tell me what value I should replace "aria-label" with to fix the warnings please?
Thanks for your help.

**Comment by stevefaulkner** [comment]
@brioche2022  can you provide the URL for where you are getting the warnings, or example code?

**Comment by stevefaulkner** [comment]
@brioche2022 

> On the link page it says that for numbers, accessible name from label is preferred.

it means the `label` element https://html.spec.whatwg.org/multipage/forms.html#the-label-element

**Comment by brioche2022** [comment]
@stevefaulkner The problem concerns an online store, the warnings are on the home page and the product pages.

Home page: https://modelisme-rc.net

A product page: https://modelisme-rc.net/kit-a-monter-electrique/726-wpl-b-16-vehicule-militaire-6x6-rc-electrique-116-en-kit-a-monter.html

Thanks!

**Comment by brioche2022** [comment]
Code of the TPL file:

<span class="regular-price" aria-label="{l s='Regular price' d='Shop.Theme.Catalog'}">{$product.regular_price}</span>

and

<span class="price" aria-label="{l s='Price' d='Shop.Theme.Catalog'}">

**Comment by brioche2022** [comment]
``Code of the TPL file:

`<span class="regular-price" aria-label="{l s='Regular price' d='Shop.Theme.Catalog'}">{$product.regular_price}</span>`

and

`<span class="price" aria-label="{l s='Price' d='Shop.Theme.Catalog'}">`

**Comment by brioche2022** [comment]
Someone to help me please?

**Comment by nschonni** [comment]
https://www.w3.org/TR/using-aria/#firstrule look at if you can use native elements before you start look at using ARIA

**Comment by kantoche** [comment]
The draft version of HTML in Aria now specifies the prohibited uses of the aria-label and aria-labelledby attributes according to the HTML elements (see https://w3c.github.io/html-aria/#docconformance) and the mapping table entitled "Rules of ARIA attribute usage by HTML element" where the elements concerned are indicated by the mention "Naming prohibited" which means precisely "Elements which are identified as Naming prohibited are elements authors MUST NOT specify an aria-label or aria-labelledby attribute, unless the element allows for its implicit role to be overwritten by an explicit WAI-ARIA role which allows naming from authors."

In addition, the documentation proposed by the APG (ARIA Authoring Practice Guide) now proposes explicit guidance for naming an element according to the role used (6 possible statuses) and a correspondence table is also available (see https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/#naming_role_guidance)

We won't be able to say we didn't know anymore...
