### ISSUE TITLE
CSS `min`, `max` are unnecessarily case-sensitive

### ISSUE THREAD

**Issue by hyvyys** [validator/validator#1372]
`Min`, `Max` (or `MIN`, `MAX`, `miN`, `mAx`...) should be just as valid as `min` `max` (the former may be used to bypass the `min` and `max` functions built into SCSS).

Code to reproduce error:

```css
margin-left: Max(-5rem,-7vw);
```

```
Error: CSS: margin-left: Too many values or values are not recognized.

At line 4, column 7058

:Max(-5rem,-7vw);margin-right:
```

**Comment by sideshowbarker** [comment]
@ylafon I guess this is an upstream issue?

**Comment by ylafon** [comment]
Indeed, I opened an issue (see above)

**Comment by M7sn1982** [comment]
Delete

**Comment by ylafon** [comment]
and fixed now, I'll let you close when merged here.

**Comment by sideshowbarker** [comment]
Rebased from upstream and pushed to https://validator.w3.org/nu/
