### ISSUE TITLE
Missing iframe sandbox allow-popups token

### ISSUE THREAD

**Issue by FedgeNo** [validator/validator#138]
Error: Bad value allow-popups for attribute sandbox on element iframe.

Spec: The sandbox attribute, when specified, enables a set of extra restrictions on any content hosted by the iframe. Its value must be an unordered set of unique space-separated tokens that are ASCII case-insensitive. The allowed values are allow-forms, allow-popups, allow-same-origin, allow-scripts, and allow-top-navigation.

**Comment by FedgeNo** [comment]
I didn't test it but if you're going for compatibility with XHTML style attributes, it should also accept "sandbox" as the value of the sandbox attribute. Some of us do still write documents that will pass XML parsing.

**Comment by sideshowbarker** [comment]
Thanks for reporting this. The `allow-pointer-lock` value is also valid per the current spec—
https://html.spec.whatwg.org/multipage/embedded-content.html#attr-iframe-sandbox
Adding support for that and for `allow-popups` is just waiting on me making time to rewrite the way we're checking this now (the rules for the value are currently expressed in the RELAX NG schema we use, but rightly I need too write a custom datatype checker instead).

**Comment by sideshowbarker** [comment]
> I didn't test it but if you're going for compatibility with XHTML style attributes, it should also accept "sandbox" as the value of the sandbox attribute.

`<iframe sandbox="">`

**Comment by FedgeNo** [comment]
That may work in browsers but anyone who developed their coding habits during the XHTML phase uses things like selected="selected" as SGML parses expando attributes in this manner and we were basically doing the job of the SGML parser in cases where SGML differed from XML. That's why I mentioned it because sandbox with no value actually means sandbox="sandbox".

**Comment by FedgeNo** [comment]
My bad. I just googled it and HTML5 is no longer based on SGML. Sorry for the notifications.

**Comment by sideshowbarker** [comment]
> My bad. I just googled it and HTML5 is no longer based on SGML. Sorry for the notifications.

No worries. You're actually right in that there are a number of so-called "boolean" attributes in the spec where the syntax is essentially what you describe; e.g., `<input type=checkbox checked=checked>`; see https://html.spec.whatwg.org/multipage/infrastructure.html#boolean-attribute. (But the `sandbox` attribute just isn't one of those "boolean" attributes.)
