### ISSUE TITLE
Howto: run standalone server using `vnu` on the command line?

### ISSUE THREAD

**Issue by siegel** [validator/validator#1381]
**Is your feature request related to a problem? Please describe.**

I'm unable to figure out how to run the prebuilt binary (`vnu`) as a standalone server. I'm on macOS 12.4 (but have attempted using previous versions as well), and installed `vnu` using `brew install vnu`.

If I try (for example) `vnu nu.validator.servlet.Main 8888`, the command ends immediately without any visible effect, and attempts to browse to `0.0.0.0:8888` fail.

**Describe the solution you'd like**
A simple command-line invocation to start an installed `vnu` in server mode, e.g. `vnu --server --port 8888 --addr 127.0.0.1` seems like it would be simplest.

**Additional context**
I'm trying to figure out the feasibility of using `vnu` for user-initiated syntax checking of HTML documents (and folders) in a GUI text editor. I cannot ask my customers to install Java, nor can I expect it to be installed.

I *can* recommend that they `brew install vnu`, and detect at runtime that it's installed, and use it if it's present. But in order to get to the desired goal state, I need a fairly succinct way to start the local server using a shell command.

If I've missed something obvious, I would appreciate either a pointer or a clarification in the existing documentation.

Thanks for reading. :-)

**Comment by nschonni** [comment]
https://github.com/validator/validator#standalone-web-server looks like you're trying to call it from `vnu` rather than the separate standalone java client

**Comment by siegel** [comment]
> looks like you're trying to call it from vnu rather than the separate standalone java client

Yes, that's what I'm getting at -- I _want_ to call it from `vnu`, because I cannot expect or rely on Java being called in order to invoke it directly. (If that makes sense.)

**Comment by nschonni** [comment]
Look in the ZIP file, it ships with the standalone java executable that the examples are using

**Comment by sideshowbarker** [comment]
Closing, at this seems to be an issue for the `vnu` brew tool rather than the upstream jar.
