### ISSUE TITLE
Accessibility gaps in the validator pages

### ISSUE THREAD

**Issue by kantoche** [validator/validator#1391]
I am training a blind developer and I introduced him to the validator to check the code his team produces, but we encountered several rendering problems with his screen reader (JAWS 2022) because of the sometimes inaccessible code in the HTML interface.
Two examples:
- The "Check" button on the https://validator.w3.org/#validate_by_input page is a link without proper semantics;
- When the results are displayed, the legend element of the filtering offers two links "Hide all errors" and "Show all errors" which are not identified as such by JAWS and therefore not operable.

Could you make the interface more easily accessible? I can help you with this if needed.

**Comment by nschonni** [comment]
I believe that link is to the legacy checker, rather than the "Nu" that is this repo https://validator.w3.org/nu/

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1391#issuecomment-1162559357. Please consider re-opening this at https://github.com/w3c/markup-validator/issues
