### ISSUE TITLE
Spaces in file name when inserted is considered wrong

### ISSUE THREAD

**Issue by NUKER13764** [validator/validator#1393]
Spaces in the file name when inserted are considered wrong. Site: [HTML tests by Nuker13764 on Replit](https://html-tests.nuker13764.repl.co/). I inserted a video and used the validator to check for errors. The video file name had spaces so I added the spaces, and it said that was a bug.

**Comment by nschonni** [comment]
You need to encode spaces to `%20` to be valid. Further info https://stackoverflow.com/a/5442701/455535
