### ISSUE TITLE
Content model of hgroup element was changed

### ISSUE THREAD

**Issue by mtrootyy** [validator/validator#1397]
Ref: https://github.com/whatwg/html/commit/6682bdeee6fb08f5972bea92064fe250f1b4ec9c
Ref: https://whatpr.org/html/7829/328a813...dd81361/sections.html#the-hgroup-element

**Comment by stevefaulkner** [comment]
While the content model message for this code, suggests it is permitted:
```
<hgroup>
<h1>All At Sea Over Ventriloquism</h1> 
<p>Captain Dick's Logbook</p> 
<p>By Richard P. Wightman alias Captain Dick</p> 
</hgroup>
```

> Content model for element [hgroup](https://html.spec.whatwg.org/multipage/#the-hgroup-element):
>     Zero or more [p](https://html.spec.whatwg.org/multipage/#the-p-element) elements, followed by one [h1](https://html.spec.whatwg.org/multipage/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h2](https://html.spec.whatwg.org/multipage/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h3](https://html.spec.whatwg.org/multipage/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h4](https://html.spec.whatwg.org/multipage/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h5](https://html.spec.whatwg.org/multipage/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), or [h6](https://html.spec.whatwg.org/multipage/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements) element, followed by zero or more [p](https://html.spec.whatwg.org/multipage/#the-p-element) elements, optionally intermixed with [script-supporting elements](https://html.spec.whatwg.org/multipage/#script-supporting-elements-2).

the error suggests otherwise

> Error: Element [p](https://html.spec.whatwg.org/multipage/#the-p-element) not allowed as child of element [hgroup](https://html.spec.whatwg.org/multipage/#the-hgroup-element) in this context. (Suppressing further errors from this subtree.)

**Comment by alanfluff** [comment]
Was about to use in production, but my boss will look at me like this
o_O
if I use something in apparent contravention of the validator. So here's hoping this is adopted by the validator soon.

**Comment by ravau** [comment]
Validator doesnt even allow other headers in hgroup:

`<hgroup class="komunikat_top cs18"><h1 class="cs19">Title</h1><p></p><h2 class="cs19">title2</h2></hgroup>`

What is purpose of hgroup if you can't group headers?
