### ISSUE TITLE
W3C Validator -> Error  "The value of the for attribute of the label element must be the ID of a non-hidden form control"

### ISSUE THREAD

**Issue by brioche2022** [validator/validator#1398]
Hi everyone,,

When I check my website with W3C Validator I have this error -> "The value of the for attribute of the label element must be the ID of a non-hidden form control".

Here are errors:

**Error: The value of the for attribute of the label element must be the ID of a non-hidden form control.
From line 1738, column 17; to line 1738, column 62**
          `<label class="form-label" for="comment_title">Title<`

**Error: The value of the for attribute of the label element must be the ID of a non-hidden form control.
From line 1742, column 17; to line 1742, column 62**
          `<label class="form-label" for="customer_name">Your name<` 

**Error: The value of the for attribute of the label element must be the ID of a non-hidden form control.
From line 1749, column 15; to line 1749, column 62**
          `<label class="form-label" for="comment_content">Review<`

Here are the code in the tpl file:

`<div class="col-md-8 col-sm-8">`
 `<label class="form-label" for="comment_title">{l s='Title' d='Modules.Productcomments.Shop'}<sup class="required">*</sup></label>`
 `<input name="comment_title" type="text" value=""/>`
`</div>`

`<div class="col-md-4 col-sm-4">`
 `<label class="form-label" for="customer_name">{l s='Your name' d='Modules.Productcomments.Shop'}<sup class="required">*</sup></label>`
 `<input name="customer_name" type="text" value=""/>`
`</div>`

`<div class="row">`
`<div class="col-md-12 col-sm-12">`
 `<label class="form-label" for="comment_content">{l s='Review' d='Modules.Productcomments.Shop'}<sup class="required">*</sup></label>`
`</div>`
`</div>`
`<div class="row">`
`<div class="col-md-12 col-sm-12">`
`<textarea name="comment_content"></textarea>`
`</div>`
`</div>`

Could someone tell me what I have to change to fix these warnings please?

Thanks in advance.

**Comment by scottaohara** [comment]
none of your form fields have IDs.  they have `name` attributes, but they need IDs, as mentioned in the error message.  If you provide each of the form controls with an ID that has the same value of the `name` you've given each, you'll be fine.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1398#issuecomment-1179549250
