### ISSUE TITLE
validator.w3.org  --- Error: Misplaced non-space characters insided a table

### ISSUE THREAD

**Issue by rc-carter** [validator/validator#141]
Why is the following code failing the validation test?
The error message is...  "Misplaced non-space characters insided a table"

<!DOCTYPE html>
<html >
<head>
<meta charset="utf-8" />
<title>test</title>
</head>
<body>
<table>﻿<tr><td><div>hello world</div></td></tr></table> 
</body>
</html>

**Comment by cvrebert** [comment]
Use fenced code blocks ( https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks ) when posting HTML code in a GitHub comment/issue.

**Comment by cvrebert** [comment]
You seem to have a ZERO WIDTH NO-BREAK SPACE (U+FEFF) character between the `<table>` and the `<tr>`. Perhaps HTML uses some unintuitive definition of "space characters" in this context.

**Comment by sideshowbarker** [comment]
> You seem to have a ZERO WIDTH NO-BREAK SPACE (U+FEFF) character between the <table> and the <tr>.
 
Yeah, that no-break-space character is the problem. Per-spec it's not allowed there.

@rc-carter please go ahead and close this out if it answers your question.

**Comment by sideshowbarker** [comment]
> Perhaps HTML uses some unintuitive definition of "space characters" in this context.

So yeah the HTML spec in fact has a precise definition of "space characters":

https://html.spec.whatwg.org/multipage/infrastructure.html#space-character
> The space characters, for the purposes of this specification, are U+0020 SPACE, U+0009 CHARACTER TABULATION (tab), U+000A LINE FEED (LF), U+000C FORM FEED (FF), and U+000D CARRIAGE RETURN (CR).

Personally I guess I find that fairly intuitive but however unintuitive it might seem, the fact is that ZERO WIDTH NO-BREAK SPACE (U+FEFF) is not an HTML space character, and so it's also not **inter-element whitespace**  https://html.spec.whatwg.org/multipage/dom.html#inter-element-whitespace and since the only allowed child content of the `table` element is inter-element whitespace and other particular elements, the U+FEFF there  is an error.

**Comment by rc-carter** [comment]
Thanks for the clarification.  I eventually found the "no-break-space character" a short while after I posted the issue. Something like this is hard to find visually. The question I'm now trying to answer is how the "no-break-space character" got inserted into the code. I'm seeing this issue in several web pages that I created using VS2012. I'm not sure how this is happening. I guess it my be due to some corruption from a cut/paste.

**Comment by sideshowbarker** [comment]
> Something like this is hard to find visually.

> The question I'm now trying to answer is how the "no-break-space character" got inserted into the code.

Yeah, dealing with no-break spaces in editing applications is a PITA, for just the reason you describe—most editing apps don't by default show you any different kind of visual indicator for no-break spaces; even if the editing app has a "show spaces" option and you turn it on, I think it usually just shows the same indicator for non-break spaces as for normal spaces.

But maybe there's some way to get VS2012 to show them to you differently.
