### ISSUE TITLE
Misidentifiying language

### ISSUE THREAD

**Issue by warrenlc** [validator/validator#1410]
You keep warning that I am writing in Norwegian, when I am clearly writing Swedish on the project I am trying to evaluate. Please stop.

**Comment by nschonni** [comment]
Can you proved the information in the issue template that you skipped https://github.com/validator/validator/issues/new?assignees=&labels=bug&template=bad-language-detection.md&title=

**Comment by sideshowbarker** [comment]
Closing for lack of response.

@warrenlc If you can provide a document or URL to test with, I can look into fixing it
