### ISSUE TITLE
The validator doesn't detect non-closed tag

### ISSUE THREAD

**Issue by michaelhref** [validator/validator#1411]
Hello,

It seems the validator doesn't detect when html tag is not finished.
For example, if you have a "p" which is not closed, the validator doesn't show any error.

Thanks for you work on this project.

**Comment by stevefaulkner** [comment]
@michaelhref 
https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element

> A [p](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element) element's [end tag](https://html.spec.whatwg.org/multipage/syntax.html#syntax-end-tag) can be omitted if the [p](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element) element is immediately followed by an [address](https://html.spec.whatwg.org/multipage/sections.html#the-address-element), [article](https://html.spec.whatwg.org/multipage/sections.html#the-article-element), [aside](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element), [blockquote](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element), [details](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element), [div](https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element), [dl](https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element), [fieldset](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element), [figcaption](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figcaption-element), [figure](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element), [footer](https://html.spec.whatwg.org/multipage/sections.html#the-footer-element), [form](https://html.spec.whatwg.org/multipage/forms.html#the-form-element), [h1](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h2](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h3](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h4](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h5](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [h6](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements), [header](https://html.spec.whatwg.org/multipage/sections.html#the-header-element), [hgroup](https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element), [hr](https://html.spec.whatwg.org/multipage/grouping-content.html#the-hr-element), [main](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element), [menu](https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element), [nav](https://html.spec.whatwg.org/multipage/sections.html#the-nav-element), [ol](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ol-element), [p](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element), [pre](https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element), [section](https://html.spec.whatwg.org/multipage/sections.html#the-section-element), [table](https://html.spec.whatwg.org/multipage/tables.html#the-table-element), or [ul](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element) element, or if there is no more content in the parent element and the parent element is an [HTML element](https://html.spec.whatwg.org/multipage/infrastructure.html#html-elements) th[a](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element)t is not an a, [audio](https://html.spec.whatwg.org/multipage/media.html#the-audio-element), [del](https://html.spec.whatwg.org/multipage/edits.html#the-del-element), [ins](https://html.spec.whatwg.org/multipage/edits.html#the-ins-element), [map](https://html.spec.whatwg.org/multipage/image-maps.html#the-map-element), [noscript](https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element), or [video](https://html.spec.whatwg.org/multipage/media.html#the-video-element) element, or an [autonomous custom element](https://html.spec.whatwg.org/multipage/custom-elements.html#autonomous-custom-element).
