### ISSUE TITLE
html report

### ISSUE THREAD

**Issue by MAXCOOL-7** [validator/validator#1417]
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Welcome my my world</title>
</head>
<body>
The world is now evolving! cool, this is awesome!
</body>
</html>

what is the problem with the code that it cannot be validated

**Comment by stevefaulkner** [comment]
@MAXCOOL-7 please provide the full code of the document, it is impossible to answer your question with what you have provided.

**Comment by MAXCOOL-7** [comment]
that is all the code for the document, for now, I just tested running the code on the website

**Comment by stevefaulkner** [comment]
@MAXCOOL-7 what's the issue? it passes validation with a warning about lack of lang attribute.

**Comment by MAXCOOL-7** [comment]
okay thanks, so how can I correct the lang attribute

**Comment by MAXCOOL-7** [comment]
okay thanks

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1417#issuecomment-1240580185

**Comment by stevefaulkner** [comment]
> pls help me with the section problem

The answer to your problem is provided in the warning, please read it

**Comment by MAXCOOL-7** [comment]
okay thanks
