### ISSUE TITLE
Directory protection - HTTP status from the remote server was: 401

### ISSUE THREAD

**Issue by Talk19Zehn** [validator/validator#142]
Hello, for a long time, there is a directory protection in my case. Therein a phpBB 3.1.x version- (Ascraeus) is managed, processed and validated. It was a long time with its predecessor 
validator.w3.org without an 401-error. 

Since then the new W3C validator are 
validator.w3.org/nu/, validation is not possible. The new W3C validator is to request input of the data for directory protection given an 401-error.

Quote:
Error: HTTP resource not retrievable. The HTTP status from the remote server was: 401.

I do not know whether the error in the new phpBB version Ascraeus or into the new Validator is validator.w3.org/nu/.

Thank you for an audit on directory protection when you use it.

Note: Unfortunately, the color red is in use and the site is very difficult to read. Would it be possible to make a readable typeface?

Best regards!

**Comment by sideshowbarker** [comment]
Hi. Thanks for raising this question here. It’s a question that’s already come up and that I responded to over at https://github.com/validator/validator/issues/122, so please take a look there.
