### ISSUE TITLE
The pre-release online validator is problematic

### ISSUE THREAD

**Issue by gbnewby** [validator/validator#1431]
I am writing to report/confirm that changes to validation practice, which are already reported in other issues (regarding serialization and self-closing tags) have created problems for downstream consumers.

I oversee Project Gutenberg (www.gutenberg.org), and getting different results from the pre-release is creating uncertainty among our submitters.

It would be great to instead have the current production version of the validator online, rather than a pre-release. Thanks for your consideration.

**Comment by sideshowbarker** [comment]
Thanks for the heads-up about this.

I’ve made a fix and the behavior should now be consistent between the current jar release at https://github.com/validator/validator/releases/download/latest/vnu.jar and the production W3C service at https://validator.w3.org/nu/

Please let me know if that fixes the problem for y’all.

**Comment by gbnewby** [comment]
Thanks very much - the new release definitely improves that unexpected
variations we were seeing in validation reports.

Thanks for all you do. The online validator is a key and valued resource
for creating new Project Gutenberg eBooks.
