### ISSUE TITLE
Html is validated with a <p> tag that has no ending </p> tag.

### ISSUE THREAD

**Issue by kcprabase** [validator/validator#1435]
URL being validated: [https://kcprabase.github.io/lab1/aboutme.html](https://kcprabase.github.io/lab1/aboutme.html)

Moreover, if I actually put the ending </p> tag, it thinks it's an error.
![image](https://user-images.githubusercontent.com/33727948/193947383-f55ebfbc-024c-4622-91ca-deed4b76a1c7.png)

Code to reproduce error:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>About me - Prabesh WAP</title>
        <link href="../styles/styleme.css" rel="stylesheet" >
    </head>

    <body>
      
        <p>
            <pre>Happy: <img class="happyImg" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGdZ6j62RybmqZAqIsPABgZ7Sn06m-yowdLg" alt="happy">     Sad: <img class="sadImg" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR53vC2qUW3Nrznk9NvkHKpuPPukYyO33GzCg" alt="sad"></pre>
       <!-- </p> -->
        
        
    </body>
</html>
```

**Comment by nschonni** [comment]
<img width="530" alt="image" src="https://user-images.githubusercontent.com/1297909/194225173-81ed3c3b-e875-4130-83fe-cf28a4c3db5d.png">
The `<pre>` tag automatically closes the paragraph, so the later closing tag is correctly being flagged
