### ISSUE TITLE
Redirection loops on the github.io page

### ISSUE THREAD

**Issue by rujiel** [validator/validator#1442]
Hello, I'm encountering a frontend redirect loop on the github page

https://validator.github.io/validator/

Console log repeats this each time:
COOP/COEP Service Worker registered https://validator.github.io/validator/resources/ [coi-serviceworker.js:75:43](https://validator.github.io/validator/resources/coi-serviceworker.js)
Reloading page to make use of COOP/COEP Service Worker. [coi-serviceworker.js:84:47](https://validator.github.io/validator/resources/coi-serviceworker.js)

Tested on firefox and chrome

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I’ve pushed a fix, so please try again now. You may need to force reload the page (clear the browser cache).

**Comment by rujiel** [comment]
It's working without needing to clear cache. Thanks!
