### ISSUE TITLE
Warning on aria-label

### ISSUE THREAD

**Issue by aladeuil** [validator/validator#1460]
Hi,
When I check this `<pre tabindex="0" aria-label="zone de code à copier" class="disable-swipe" id="code-162uAjOQTzyc0JD">`, the validator says `Possible misuse of aria-label`.
VoiceOver on Safari read the label correctly.
[Example on this page](https://www.kortic.com/lazy-loading-images-and-content-with-intersection-and-mutation-observer.html)
Is it really a good warning ?
Thanks.

**Comment by pkra** [comment]
>  Is it really a good warning ?

Yes, because the code example is invalid - https://w3c.github.io/html-aria/#pre states that naming is prohibited for `pre`.

>  VoiceOver on Safari read the label correctly.

VO is probably just trying to correct for authoring errors like this one.

**Comment by scottaohara** [comment]
see this issue https://github.com/validator/validator/issues/1334

you have applied an aria-label to a generic element which authors are not supposed to name.  If that element needs an accessible name, then it ALSO needs a role that allows for the element to be named.

**Comment by sideshowbarker** [comment]
Closing in favor of https://github.com/validator/validator/issues/1334
