### ISSUE TITLE
Publish new release on Maven-Central

### ISSUE THREAD

**Issue by fabian-froehlich** [validator/validator#1464]
With the current Version on Maven-Central `20.7.2` it is possible to include a html-validator into our application. 
But since its release is from 2020 it contains outdated dependencies with critical CVE's.
Is there a reason, that there was no further release of the library?
We would be glad if there was an ongoing release cycle.

**Comment by rdeltour** [comment]
seems to be a duplicate of #1354

**Comment by fabian-froehlich** [comment]
Yes, I also saw your post. But it did not have any recent activities.

**Comment by sideshowbarker** [comment]
Closing in favor of https://github.com/validator/validator/issues/1354
