### ISSUE TITLE
Input elements in <head> cause validator to error out. 

### ISSUE THREAD

**Issue by michaelspellacy** [validator/validator#1473]
Hi! I noted today that the validator appears to error out when hidden <input> elements are present in the head of the document being validated, thereby suppressing further errors on the page. While this is certainly a poor location for hidden input elements, and I will work with my team to remove them, I'm not sure if the behavior here is new (or ideal): 

## Test Cases

**Input In head:**  https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https://radancy.dev/playground/product/w3c-validation/input.html

**No input in head:**  https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https://radancy.dev/playground/product/w3c-validation/no-input.html  

### Errors Being Produced: 

Error: Element head is missing a required instance of child element title.

From line 12, column 5; to line 12, column 103

est">↩    <input id="site-google-analytics" name="site-google-analytics" type="hidden" value="UA-XXXXXX-XX">↩    <

Content model for element head:

If the document is an iframe srcdoc document or if title information is available from a higher-level protocol: Zero or more elements of metadata content, of which no more than one is a title element and no more than one is a base element.
Otherwise: One or more elements of metadata content, of which exactly one is a title element and no more than one is a base element.
Error: Element title not allowed as child of element body in this context. (Suppressing further errors from this subtree.)

From line 29, column 5; to line 29, column 11

969">↩    <title>Hosted

Contexts in which element title may be used:
In a head element containing no other title elements.
Content model for element body:
Flow content.
Error: Stray end tag head.

From line 30, column 1; to line 30, column 7

y</title>↩</head>↩↩<bod

Error: Start tag body seen but an element of the same type was already open.

From line 32, column 1; to line 32, column 42

↩</head>↩↩<body id="rad-product-hosted-apply-index">↩↩  <d

Fatal Error: Cannot recover after last error. Any further errors will be ignored.

From line 32, column 1; to line 32, column 42

↩</head>↩↩<body id="rad-product-hosted-apply-index">↩↩  <d

Thanks!

**Comment by nschonni** [comment]
Context were this element can be used https://html.spec.whatwg.org/multipage/input.html#the-input-element
The `<head>` is not a place where phrasing content can be used.
Maybe they're miss-reading the *input* in https://html.spec.whatwg.org/multipage/semantics.html#the-head-element as `<input>`

**Comment by nschonni** [comment]
Also note, that one the input element is hit, there is an implicit opening BODY tag, as you can see if you open the source in browser tools 
![image](https://user-images.githubusercontent.com/1297909/199284466-18b3b15d-5484-4f61-aaf4-3e081d66bad0.png)

**Comment by michaelspellacy** [comment]
@nschonni Yes, I understand that input is not allowed here, just wondering why page would not simply report it as an error only and continue on it's merry way. That is not what is happening here. Further page issues, if any exist, are suppressed, and that is the part I'm more concerned about here, as it will prevent me and my team from capturing other validation issues.

**Comment by michaelspellacy** [comment]
@nschonni Okay, I see your grab above. Why is this happening?

**Comment by nschonni** [comment]
As mentioned above, the first INPUT creates an implied opening BODY because it's encountering phrasing content.

**Comment by michaelspellacy** [comment]
@nschonni Okay, thank you, but it looks like the DOM is being rewritten here. I still do not understand why it would do that. Implied or not. I thought the validator only looked at the raw HTML output.

**Comment by michaelspellacy** [comment]
@nschonni One last thing, the behavior the validator is exhibiting is normal, right?  I just want to confirm so it is easier to go back to my team and have them come up with an alternative to using input in the head. I had this same issue with input in head  a few years ago and I could have sworn the validator was more graceful in it's reporting, but maybe not. Thanks again!

**Comment by nschonni** [comment]
As far as I understand it, the validator has to parse the raw HTML into an AST, and will behave the same way as you see in the parsed tree in the developer window above. I don't believe it will run any JavaScript that is re-writing code, so I don't think it will always be a 1:1 for the final browser parsed tree. I don't think INPUT in the head has ever been valid, so likely the wonky parsing was still happening in the browser, but maybe the older validator wasn't telling you

**Comment by michaelspellacy** [comment]
@nschonni That makes sense. Thank you again. I think I have everything I need here, so I will close this. Take care!
