### ISSUE TITLE
[DOCUMENTATION] List of all and every errors

### ISSUE THREAD

**Issue by KevinG-Acc** [validator/validator#1482]
Hello ! 

I'm currently working on an open source extension to analyse accessibility and performance on websites.

As i am using W3C validator, i tried to find some documentation listing all the possible errors/warning/info that exists and can be detected when running an analysis. bu can't find one.

I already checked on the website :  https://validator.w3.org/docs/errors.html but the errors i get when analysing as 'Consider adding a “lang” attribute to the “html” start tag to declare the language of this document.' aren't listed.

May someone help me ? :)

**Comment by NiedziolkaMichal** [comment]
There is no such list.

To create a comprehensive list of possible errors, you would need to follow up on all calls to `org.xml.sax.ErrorHandler` methods. Maybe in the future, we will move them to properties files, which would allow localization, but it's hard to say when will that happen.

**Comment by KevinG-Acc** [comment]
Ok. Thanks a lot for your answer. I'll check for that ;).

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1482#issuecomment-1304874382
