### ISSUE TITLE
Orphaned FAQ reference in validation error message

### ISSUE THREAD

**Issue by Rosuav** [validator/validator#1493]
Validating an HTML4 document https://gsarchive.net/backups/_html_perf_grps_websites_gb.html produces error messages reporting "there is no attribute X" for many attributes which are better handled by CSS. (Interestingly, validating the exact same content via text input produces more useful error messages, including citing that they are better handled with CSS.) The error message links to https://validator.w3.org/docs/help.html#faq-flash regarding proper ways to use Flash, but this FAQ entry does not exist.

**Comment by nschonni** [comment]
I think this needs to be filed on the legacy validator repo https://github.com/w3c/markup-validator, as this one is for the https://validator.w3.org/nu version

**Comment by Rosuav** [comment]
Gotcha, thanks. I wasn't 100% sure which repo to raise the issue on. Will reraise over there.
