### ISSUE TITLE
where is the XML validator?

### ISSUE THREAD

**Issue by 89z** [validator/validator#1496]
I would like to validate this XML:

~~~xml
<channel>
<link>http://tinyurl.com/ESSNewReleasesArcGIS</link>
</channel>
~~~

but I don't see any option for that here:

https://validator.w3.org/nu

**Comment by NiedziolkaMichal** [comment]
This validator is used to validate HTML, CSS & SVG, not XML.

You could use [W3C Feed Validation](https://validator.w3.org/feed/#validate_by_input) to check RSS feed.

**Comment by 89z** [comment]
are you sure? I get this:

~~~
line 1, column 0: Undefined root element: channel [help]
~~~

I think the XML is valid, but not valid as RSS

**Comment by NiedziolkaMichal** [comment]
That depends what you wish to check exactly. You can check just syntax of your XML, so if every `<` has matching `>`, if all elements are closed etc. You can validate that in [simple xml validator](https://www.w3schools.com/xml/xml_validator.asp). Now if you wish to also check if element called `link` can be in element called `channel`, if they have all required attributes and if their content seems ok, you need to link your XML with schema. This is example of valid RSS xml:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

<channel>
  <title>W3Schools Home Page</title>
  <link>https://www.w3schools.com</link>
  <description>Free web building tutorials</description>
  <item>
    <title>RSS Tutorial</title>
    <link>https://www.w3schools.com/xml/xml_rss.asp</link>
    <description>New RSS tutorial on W3Schools</description>
  </item>
  <item>
    <title>XML Tutorial</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
</channel>

</rss>
```

**Comment by 89z** [comment]
I dont wish to use w3schools, which is why I tried to use the https://validator.w3.org/nu site, because to me its "official" while the w3schools is "third party". So I would like an "official" XML parser if one is available. I am kind of surprise that this is not offered (if that is the case), as HTML is offered, and I always considered HTML a "superset" of XML, so I would assume if HTML can be validated, then it should be trivial to also provide an XML parser on the same w3.org website

**Comment by NiedziolkaMichal** [comment]
[Here is a full list of W3C validators.](https://w3c.github.io/developers/tools/) You could propose adding XML syntax validator from [contact page](https://www.w3.org/Consortium/contact).
