### ISSUE TITLE
CSS subgrid support

### ISSUE THREAD

**Issue by Vallek** [validator/validator#1501]
Please allow subgrid value for grid-template-columns and grid-template-rows in css nu validator since it is valid and already supported by at least some browsers (Firefox and Safari). 

![Снимок экрана 2022-11-21 111006](https://user-images.githubusercontent.com/22982571/202997956-6f06a79a-3c16-454f-aabe-a0c898fbf2c3.png)

**Comment by NiedziolkaMichal** [comment]
Could you please create this issue in [css-validator](https://github.com/w3c/css-validator/issues)? We rely on that repository for all CSS validation.

Thank you

**Comment by Vallek** [comment]
Sure! Didn't know that.

**Comment by NiedziolkaMichal** [comment]
Thank you for filing issue on css-validator. When those guys add subgrid, our validator will get updated and error will no longer be shown. I will close duplicated issue here.
