### ISSUE TITLE
Validator does not recognize valid DOCTYPE, LANG attribute and Title tag.

### ISSUE THREAD

**Issue by dacevedove** [validator/validator#1506]
I'm getting one warning for not including a lang tag and it's actually there, same case for the title tag inside the head tag and de <!DOCTYPE html>

**Comment by nschonni** [comment]
Please provide a URL or code sample that produces this result

**Comment by dacevedove** [comment]
The issue was resolved and I dont know how. I just tried using the text area to paste the html and it worked, then the uri option also read the code without errors.
