### ISSUE TITLE
Integrity attribute

### ISSUE THREAD

**Issue by jonathanKingston** [validator/validator#151]
`integrity` is a new attribute defined in [SRI](www.w3.org/TR/SRI/) for both script and link tags.

To replicate see:
https://validator.w3.org/nu/?doc=http%3A%2F%2Femberobserver.com%2F

Validation message:
```
Error: Attribute integrity not allowed on element link at this point.
```

/cc @kategengler heads up this references your project (Most Ember apps will have this enabled by default in case this is turned off here)

**Comment by sideshowbarker** [comment]
Thanks for raising this. While `integrity` not yet supported in WebKit or IE/Edge, it is supported now in Blink and Gecko, so that’s sufficient for allowing it. I’ll try to get it added soon.

**Comment by PierreLvx** [comment]
Any update on this ? :)

**Comment by cvrebert** [comment]
This is blocking us from using/demoing SRI in some of Bootstrap's documentation.

**Comment by sideshowbarker** [comment]
> This is blocking us from using/demoing SRI in some of Bootstrap's documentation.

I hear you and sorry it’s taken so long but I plan to get this added today or tomorrow, and to get some of the other open bugs fixed, and then get a release out next week.

If there are any other open bugs that are a high priority for you, please (re)post comments to those bugs to let me know. (As far as parser bugs, I think https://github.com/validator/htmlparser/commits/validator-nu has the ones you had reported or are tracking but if not definitely let me know.)

**Comment by cvrebert** [comment]
:heart: :bow: Thank you!

**Comment by sideshowbarker** [comment]
@cvrebert Cheers 🖖 Pushed to https://validator.w3.org/nu/ and updated nightly at https://sideshowbarker.net/nightlies/jar/ (will be doing a new maven release next week after getting other changes in)
