### ISSUE TITLE
A <dialog> element in an <a> element throws an error

### ISSUE THREAD

**Issue by gnpivo** [validator/validator#1514]
Hello!

URL being validated or code to reproduce error:

```html
<!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<title>Dialog Boxes in Hypertext Anchors</title>

<a href=#>
    <dialog open>Hello, world!</dialog>
</a>
```

Error produced by the validator:

```
Error: The element dialog must not appear as a descendant of the a element.

From line 7, column 5; to line 7, column 17

ef=#>↩    <dialog open>Hello,
```

In the HTML markup, we nest a [`dialog` element](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element) inside of an [`a` element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element). According to the HTML specification, the `a` element has a transparent content model that does not allow [interactive content](https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2), other `a` elements, or elements with the `tabindex` attribute. It should be possible to nest a `dialog` element in an `a` element because the `dialog` element is not categorized as interactive content. (The `dialog` element is not allowed to have a `tabindex` attribute either.) However, doing this makes the validator produce an error. The error does not occur when the `dialog` element is replaced with other non-interactive block-level elements, such as `p`.

---

The validator is clearly not happy with `dialog` elements in `a` elements, but I believe that the markup is perfectly valid and should not produce an error or a warning. For example, a web developer might want to programmatically spawn a dialog box (or a group of dialog boxes) which can then be clicked to navigate to a different page. I would appreciate any thoughts regarding how the validator should respond to dialog boxes wrapped in hypertext anchors.

**Comment by scottaohara** [comment]
what is your use case for even needing to do this? 

and would your dialog not contain a close button or other interactive elements, which would then also be invalid as descendants of the hyperlink, regardless of whether dialog should be allowed or not?

**Comment by gnpivo** [comment]
I see what you mean; thank you very much for your response. I will submit an issue for the HTML specification about whether or not a dialog element should be listed under interactive content.
