### ISSUE TITLE
Brackets Nu Markup Checker

### ISSUE THREAD

**Issue by vanesslap** [validator/validator#1517]
Hello, I have a problem with brackets. I have an error message that appears: "Nu Markup Checker arrêté avec l’erreur suivante : null    " and I can not understand where the error comes from. Has anyone encountered this problem before?
Thank you for your help

<img width="732" alt="Capture d’écran 2023-01-06 à 10 01 28" src="https://user-images.githubusercontent.com/122085546/210967594-c9bc90aa-ac75-4992-8abf-ddb3ee323db8.png">

**Comment by nschonni** [comment]
You've installed an extension from https://registry.brackets.io/. There are several from there with the word "validation" in there description. None of them are maintain by this project, so you'll have to find the right one and report it to that project.
