### ISSUE TITLE
Not getting snippet code

### ISSUE THREAD

**Issue by ijas** [validator/validator#152]
I have validated my sit (http://www.ads-comm.com/) through W3C validator. all errors and warnings are fixed. but I haven't get snippet code of W3C label. Is there any way to get this. please help me. thanks in advance.

**Comment by sideshowbarker** [comment]
No, unlike the legacy W3C markup validator, the current W3C HTML checker by design does not provide any badges. For an explanation of some of the reasons, see https://about.validator.nu/#no-badge
