### ISSUE TITLE
Picture overlay?

### ISSUE THREAD

**Issue by itsEtzy** [validator/validator#1520]
Hey there, I wanted to ask what kind of tag i need for this. This is just an example. I am fairly new to programming and I cant seem to find something like this anywhere online. Its like a picture with overlayed pictures and its responsive. Thank you for your help
![image](https://user-images.githubusercontent.com/122216448/211202073-0b836de3-bf19-4ff5-ab93-73bbcde82c39.png)
website link: 
https://warmlydecor.com/

**Comment by nschonni** [comment]
That's a question for StackOverflow, not a project's issue tracker
