### ISSUE TITLE
Do not allow <link rel=prefetch> with as=""

### ISSUE THREAD

**Issue by domenic** [validator/validator#1527]
https://github.com/validator/validator/commit/2a4600e1fb02184f8e16c037db950d33ba111b5a incorrectly added support for `as=""` with `rel="prefetch"`. At the time, `rel="prefetch"` was not specified at all. I guess it was assumed that once we did eventually specify it, it might use `as=""` in some way.

However, this ended up not being the case. https://github.com/whatwg/html/pull/8111 fully specifies `<link rel="prefetch">`, and `as=""` does nothing. The HTML Standard continues to say that `as=""` must not be used with such links.

Note that the only browser that uses `as=""` for `rel="prefetch"` is Chromium, which only supports one value, `as="document"`. Removal of that nonstandard behavior is tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=1352371.

**Comment by sideshowbarker** [comment]
Thanks for catching this. I’ve now fixed in the sources, and pushed a fix to https://validator.w3.org/nu/.

(And at this point, I have no recollection at all about why I committed https://github.com/validator/validator/commit/2a4600e1fb02184f8e16c037db950d33ba111b5a...)
