### ISSUE TITLE
Validation error if there is a script after script[type="importmap"].

### ISSUE THREAD

**Issue by NakajimaTakuya** [validator/validator#1546]
I seem to get the following error if there is a script tag after the importmap definition.
I think this is valid.

code to reproduce error:

```html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>test</title>
    <script type="importmap">{
  "imports": {
    "application": "/assets/application-12345678.js"
  }
}</script>
<script src="hogehoge.js" type="module"></script>
  </head>
  <body>
hogehoge
  </body>
</html>
```

> Error: A script element with a type attribute whose value is importmap must contain a JSON object.
> [From line 11, column 41; to line 11, column 49](https://validator.w3.org/nu/#l11c49)
> ="module"></script>↩  </h

<img width="999" alt="nucheck validation screenshot. The above situation can be confirmed." src="https://user-images.githubusercontent.com/14817756/220335450-b9416003-6387-444d-b0d5-87356935d9d5.png">

**Comment by sideshowbarker** [comment]
@NakajimaTakuya Thanks for catching this — it definitely seems to be a bug

@NiedziolkaMichal Seems like the bug must have been in since 4054c56f5147aa9206e28d79dec400ed80210d94. It’d be great if you have time to investigate it — but if not, lemme me know and I will.

**Comment by NakajimaTakuya** [comment]
@NiedziolkaMichal @sideshowbarker Thank you, I appreciate your very quick response.
