### ISSUE TITLE
"Stream length exceeds limit" error running the validator locally

### ISSUE THREAD

**Issue by pwaller** [validator/validator#155]
I just ran the validator locally, posting my content to it via the multi-part API, but hit this error (with output mode `gnu`):

```
"Stream length exceeds limit.": non-document-error io: 
```

Is the maximum stream length adjustable?

**Comment by pwaller** [comment]
[I just found the relevant code](https://github.com/validator/validator/blob/4c087df377e58b16c45beb32b4aebae6d2d0fa35/src/nu/validator/servlet/Main.java#L54-L55):

```java
    private static final long SIZE_LIMIT = Integer.parseInt(System.getProperty(
            "nu.validator.servlet.max-file-size", "2097152"));
```

So I take it I can do `java -Dnu.validator.servlet.max-file-size=<some size>` to configure it to something larger.

Please reopen if this is incorrect or you feel that documentation needs to go somewhere.

I would have found it helpful if the error message had told me how to configure the maximum stream length.

**Comment by sideshowbarker** [comment]
> o I take it I can do java -Dnu.validator.servlet.max-file-size=<some size> to configure it to something larger.

Yes, that should work.

> Please reopen if this is incorrect or you feel that documentation needs to go somewhere.

OK, I am reopening it. Rightly, this should be exposed as a proper option; you shouldn’t need to resort to setting the java system property for it. So I’ll add some code to expose it, and will update the docs to include information about it.

**Comment by pwaller** [comment]
Ping. I'm following up with old issues. It seems I didn't hit this problem again (since I started using -D), and at least searching for that error message will bring you to this issue. Please open a new issue if you want to continue tracking this.
