### ISSUE TITLE
ARIA role `insertion` and `deletion`

### ISSUE THREAD

**Issue by dontcallmedom** [validator/validator#1558]
I've been trying to use [`role=insertion` ](https://www.w3.org/TR/wai-aria-1.2/#insertion)to markup a complex document containing diffs, but the validator complains with

```
 Bad value “insertion” for attribute “role” on element “section”
```
(likewise for the role [`deletion`](https://www.w3.org/TR/wai-aria-1.2/#deletion))

**Comment by scottaohara** [comment]
not presently allowed on the section element.  Up for consideration if this needs to change.  but with that said...

what's your use case?  as if you want to imply a section is deleted, it'd be best to do it as
```
<del> or <div role=deletion>
  <section>....</section>
</del> or </div>
```


or if it's not a section you want deleted, and you're just arbitrarily using that element, then why not just use a div, or again, the native element that does the same thing?

**Comment by dontcallmedom** [comment]
when you say not allowed, do you mean by the validator or by the spec? My [reading of the spec](https://w3c.github.io/html-aria/#index-aria-insertion) was that it was allowed on any flow content.

My interest in using the `role` attribute rather than a wrapping  `<ins>` is that this is to annotate a complex document via a script, and any structural change (such as wrapper elements) are pretty tricky to manage.

**Comment by scottaohara** [comment]
no, sorry.  that part of the spec is informatively stating what each role would be classified as, and descendants that would be expected for that element.  the table above https://w3c.github.io/html-aria/#el-section is what you should be looking at for what ARIA attributes are allowed on a particular element

**Comment by scottaohara** [comment]
for instance, if you were trying to identify a section with an accname, thus a region landmark, as a role=deletion - the region landmark would be removed in place of this deletion role.  this would cause soemthing that was previously easily discoverable as something that could become hard to re-locate.

**Comment by dontcallmedom** [comment]
thanks a bunch for the pointer and the explanation!

It's very clear this isn't a validator bug, so I'll close this issue.

And from the explanation, it looks like role-less wrapper elements would be hard to avoid here, and that expanding the set of elements that can use `insertion` and `deletion` roles would not likely to achieve the desired result.
