### ISSUE TITLE
`imagesrcset` is not recognized in `link rel=preload`

### ISSUE THREAD

**Issue by XhmikosR** [validator/validator#1565]
I'm using the latest vnu-jar from npm 22.9.29, but when I try to specify `imagesrcset` I'm getting errors:

```
error: Attribute "imagesrcset" not allowed on element "link" at this point.
```

```html
<link
  rel="preload"
  href="/assets/brand/bootstrap-logo-shadow.png"
  imagesrcset="/assets/brand/bootstrap-logo-shadow.png, /assets/brand/bootstrap-logo-shadow@2x.png 2x"
  as="image"
>
```

I searched the old issues and it seems this is already fixed. Maybe we need a new npm release @sideshowbarker?

Thanks!

**Comment by XhmikosR** [comment]
@sideshowbarker friendly ping :)

**Comment by sideshowbarker** [comment]
https://www.npmjs.com/package/vnu-jar/v/23.4.10 published — sorry for the delay

**Comment by XhmikosR** [comment]
Thanks! Confirmed the issue is now gone :)

I also had to change the void elements ignore to `Trailing slash on void elements has no effect and interacts badly with unquoted attribute values`.

**Comment by XhmikosR** [comment]
Actually, @sideshowbarker it seems something new is broken in the new version: https://github.com/twbs/blog/actions/runs/4655422475/jobs/8238049304

It seems vnu-jar exits with error code 1 even when there are no errors. Do you want me to make a new issue?

**Comment by sideshowbarker** [comment]
> It seems vnu-jar exits with error code 1 even when there are no errors. Do you want me to make a new issue?

Yes please
