### ISSUE TITLE
hin not recognised as valid language, even though it's ISO

### ISSUE THREAD

**Issue by MisterZeus** [validator/validator#1567]
Test Case: https://validator.w3.org/nu/?checkerrorpages=yes&useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&acceptlanguage=&doc=https%3A%2F%2Fsemver.org

The validator reports that:
"Bad value hin for attribute lang on element [a](https://html.spec.whatwg.org/multipage/#the-a-element): The language subtag hin is not a valid ISO language part of a language tag."

I believe Hindi is an ISO language these days, so you may need to update your language lookup tables with the latest ISO language data:
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by nschonni** [comment]
Looks like it does accept the 639-1 `hi` https://github.com/validator/validator/blob/228ea687bfa4a50f65648285cab411b83cc42a6f/resources/language-profiles-list.txt#L33 but not the 639-2 `hin`

**Comment by sideshowbarker** [comment]
We use https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry as the authoritative source for language subtags — and that has `hi` but not `hin`.
