### ISSUE TITLE
Allow role="navigation" on a ul

### ISSUE THREAD

**Issue by craigfrancis** [validator/validator#157]
Error: Bad value navigation for attribute role on element ul

The role navigation does not say it can't be used on a ul:

http://www.w3.org/TR/wai-aria/roles#navigation

Simple example below, but trying to use a pagination example from Mike West:

https://mikewest.org/2010/02/an-accessible-pagination-pattern

	<!DOCTYPE html>
	<html>
	<head>
		<meta charset="UTF-8" />
		<title>Text</title>
	</head>
	<body>

		<ul role="navigation">
			<li><a href="/">Link</a></li>
		</ul>

		<div role="navigation"> 
			<p><a href="/">Link</a></p>
		</div>

		<nav> 
			<ul>
				<li><a href="/">Link</a></li>
			</ul>
		</nav>

	</body>
	</html>

**Comment by stevefaulkner** [comment]
>The role navigation does not say it can't be used on a ul:

The WAI-ARIA does not define the rules for use of ARIA attributes in HTML,

The rules are defined in ARIA in HTML

http://www.w3.org/TR/html-aria/

On Thursday, 10 September 2015, Craig Francis <notifications@github.com>
wrote:

> Error: Bad value navigation for attribute role on element ul
>
> The role navigation does not say it can't be used on a ul:
>
> http://www.w3.org/TR/wai-aria/roles#navigation
>
> Simple example below, but trying to use a pagination example from Mike
> West:
>
> https://mikewest.org/2010/02/an-accessible-pagination-pattern
>
> <!DOCTYPE html>
> <html>
> <head>
>     <meta charset="UTF-8" />
>     <title>Text</title>
> </head>
> <body>
>
>     <ul role="navigation">
>         <li><a href="/">Link</a></li>
>     </ul>
>
>     <div role="navigation"> 
>         <p><a href="/">Link</a></p>
>     </div>
>
>     <nav> 
>         <ul>
>             <li><a href="/">Link</a></li>
>         </ul>
>     </nav>
>
> </body>
> </html>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/validator/validator/issues/157>.
>


-- 
--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by craigfrancis** [comment]
ok, fair point...

> Web developers may use the ARIA role and aria-* attributes on HTML elements, in accordance with the requirements described in [wai-aria-1.1], **except where these conflict with the strong native semantics** or are equal to the default implicit ARIA semantics of a given HTML element. These constraints, are intended to prevent developers from making assistive technology products report nonsensical user interface information (UI) that does not represent the actual UI of the document.

http://www.w3.org/TR/html-aria/#rules-wd

**Comment by cvrebert** [comment]
If you check the big table of elements and their valid roles, the entry for `ul` says:
> Role: directory, group, listbox, menu, menubar, tablist, toolbar, tree, presentation

So `navigation` is indeed not currently a valid role for `ul`.

**Comment by craigfrancis** [comment]
Another good point.

Although I do wonder (and suspect has already been debated) why the `<ul>` does not support "navigation", but does support "menubar" - the answer may be as simple as the default role of a `<li>` being a "listitem" (which must be a child of a "list" or "directory"), but it could be changed to "menuitem".

I'm just keeping in mind the old advice (from 2002, e.g. [alistapart](http://alistapart.com/article/taminglists)) where the `<ul>` was the recommended way to mark up navigation, and that maybe we should just move to wrapping the `<ul>` with a `<nav>`.

**Comment by cvrebert** [comment]
You could always file a bug against the spec; they've expanded the set of roles allowed on certain elements in response to feedback before (e.g. http://w3bug.com/27120).

**Comment by craigfrancis** [comment]
Thanks Chris,

I don't think it does need to be changed, but I have raised a bug report anyway (if anyone else wants to continue the discussion):

https://www.w3.org/Bugs/Public/show_bug.cgi?id=29126

**Comment by stevefaulkner** [comment]
@craigfrancis I moved the bug over to the correct spec (ARIA in HTML) http://www.w3.org/TR/html-aria/

**Comment by craigfrancis** [comment]
Thanks Steve, and I think I agree, it shouldn't be done, but thought it was worth questioning.

**Comment by stevefaulkner** [comment]
@craigfrancis 
>but thought it was worth questioning.

It's always worth questioning and thanks for doing so! FYI I have been in touch with @mikewest and he indicated he is going to update his code so as not to cause further confusion.
