### ISSUE TITLE
Structural outlines can be disrupted by sectioning elements

### ISSUE THREAD

**Issue by gnpivo** [validator/validator#1570]
Hi. I've noticed that for some documents with sectioning elements like `nav` and `aside`, the validator produces unusual structural outlines. Here is an example document to illustrate this behavior:

```html
<!DOCTYPE html>
<html lang="en-US">
 <head>
  <title>Test</title>
 </head>
 <body>
  <h1>Earth</h1>
  <h2>South America</h2>
  <h3>Ecuador</h3>
  <aside>
   <h4>The Galapagos Islands</h4>
   <p>The Galapagos Islands are a part of Ecuador.
   They're known for inspiring Charles Darwin's work on natural selection.</p>
  </aside>
  <h3>Chile</h3>
 </body>
</html>
```

Here are the outlines produced by the validator:

<img width="279" alt="outlines" src="https://user-images.githubusercontent.com/113646197/227416166-921cd352-07f3-4991-9317-a008c8608a59.png">

The heading-level outline reflects the intended document structure, with "The Galapagos Islands" and "Chile" having depths of 4 and 3 respectively. However, in the structural outline, both headings appear to have a depth of 2, the same depth as the "South America" heading. Is this supposed to happen?

**Comment by sideshowbarker** [comment]
Thanks for raising this. I just now pushed a change that removes outline that the checker had been emitting under the label **Structural outline**. That outline was based on the legacy HTML5 outline algorithm that had formerly been part of the HTML spec but was subsequently removed some time ago. And so, given that “structural outline” no longer has any basis in any current spec, it’s now been completely removed.

And the outline generated based on the normal heading structure has now been relabeled simply **Outline**.
