### ISSUE TITLE
help

### ISSUE THREAD

**Issue by SBACARI** [validator/validator#1575]
```html
<a href="https://pix.fr↩<p›La plateforme Pix vous permet d'évaluer vos c↩<ol>↩‹li›Information et données‹/li> ‹li›Communication et collaboration‹/li> ‹li›Information et données</li>‹li›Information et données‹/li›↩‹li›Information et données</li›"</a>‹/li>↩
```

**Comment by SBACARI** [comment]
<a href="https://pix.fr
<p›La plateforme Pix vous permet d'évaluer vos c
<ol>
‹li›Information et données‹/li> ‹li›Communication et collaboration‹/li> ‹li›Information et données</li>‹li›Information et données‹/li›
‹li›Information et données</li›"</a>‹/li>
</ol>

**Comment by nschonni** [comment]
Appears to be broken HTML, closing

**Comment by SBACARI** [comment]
thank you i will look

**Comment by SBACARI** [comment]
<!DOCTYPE html>
<html lang=fr>
<head>
<a href="https://pix.fr
</head>
<p›La plateforme Pix vous permet d'évaluer vos compétences numériques.</p>
<ol>
‹li›Information et données‹/li>
<li>Communication et collaboration‹/li>
<li>Information et données</li><li>Information et données‹/li›
‹li›Information et données</li></a>
</ol>
</html>
