### ISSUE TITLE
MathML annotation-xml element encoding not validating

### ISSUE THREAD

**Issue by acabal** [validator/validator#1577]
URL being validated or code to reproduce error:

```xhtml
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:m="http://www.w3.org/1998/Math/MathML" xml:lang="en">
	<head>
		<title>Test</title>
	</head>
	<body>
		<m:math alttext="K">
			<m:semantics>
				<m:mrow>
					<m:mi>K</m:mi>
				</m:mrow>
				<m:annotation-xml encoding="Content-MathML">
					<m:ci>K</m:ci>
				</m:annotation-xml>
			</m:semantics>
		</m:math>
	</body>
</html>
```

Results in this error:

```
"file:test.xhtml":12.5-12.48: error: Bad value “Content-MathML” for attribute “encoding” on element “annotation-xml”.
```

However, [according to the MathML spec](https://www.w3.org/TR/MathML3/chapter5.html#mixing.elements.annotation.xml), `MathML-Content` is a [predefined value](https://www.w3.org/TR/MathML3/chapter6.html#encoding-names) for the `annotation-xml@encoding` attribute. Therefore, this test case should pass validation.

**Comment by sideshowbarker** [comment]
> However, [according to the MathML spec](https://www.w3.org/TR/MathML3/chapter5.html#mixing.elements.annotation.xml), `MathML-Content` is a [predefined value](https://www.w3.org/TR/MathML3/chapter6.html#encoding-names) for the `annotation-xml@encoding` attribute.

Right — but the markup snippet shown in the issue description has `Content-MathML` rather than `MathML-Content`

**Comment by acabal** [comment]
D'oh! Sorry about that.
