### ISSUE TITLE
New npm version exits with error code 1 even when there are no errors

### ISSUE THREAD

**Issue by XhmikosR** [validator/validator#1579]
>Actually, @sideshowbarker it seems something new is broken in the new version: https://github.com/twbs/blog/actions/runs/4655422475/jobs/8238049304

>It seems vnu-jar exits with error code 1 even when there are no errors.

_Originally posted by @XhmikosR in https://github.com/validator/validator/issues/1565#issuecomment-1501490104_

**Comment by sideshowbarker** [comment]
All automated tests with the upstream jar are passing — it never exits 1 unexpectedly.

The log shows that `test-vnu` is what’s exiting with error code 1.

What’s `test-vnu`?

**Comment by XhmikosR** [comment]
You can see the command used just above that line :)

>Running vnu-jar validation...
>command used: java -jar "/home/runner/work/blog/blog/node_modules/vnu-jar/build/dist/vnu.jar" --asciiquotes --skip-non-html --Werror --filterpattern "Duplicate ID.*|The first occurrence of ID.*|Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.*" _site/

I confirmed the issue on my Windows VM too. Indeed, vnu-jar exits with error code 1 instead of 0 like it did with the previous npm version.

**Comment by sideshowbarker** [comment]
Fixed in https://github.com/validator/validator/commit/470d919b6c5a8f880e6976a1367b1412ca379c3d and pushed — but I think I can’t release another npm.js package until tomorrow (due to the npm.js registry’s policy of not allowing previously-published packages to be overwritten).

(If I recall correctly, the GitHub package registry, in contrast, does allow overwriting previously-published packages — so I could push an update to the 23.4.10 package at https://github.com/validator/validator/pkgs/npm/vnu-jar with the fix, but I assume that you need it in the npm.js registry instead…)

**Comment by XhmikosR** [comment]
Thanks!

Can't you name the new version it to `.1` or `-1`?

BTW please try to cut npm releases more frequently so that we can catch such issues sooner than later :)

**Comment by sideshowbarker** [comment]
> Can't you name the new version it to `.1` or `-1`?

I can, yeah — do you have a preference which?

> BTW please try to cut npm releases more frequently so that we can catch such issues sooner than later :)

I could tell you that I will — but honestly, without some automated reminder or something being set up to notify me at some regular interval when it’s time for a new release, then in practice I would just end up forgetting to do it.

Along with that, I don’t know myself how to decide when or how often a new npm release is desired? After every single commit? Or after, say, every month — but only if during that month some change has been made to the checker code (as opposed to just the docs or some other ancillary thing)? Or what?

**Comment by XhmikosR** [comment]
I'd just go with .1 then since we don't use the fourth part yet.

As for the rest, generally I don't think this can be automated unless you
follow some kind of semantic release commit messages and add a deploy to
npm workflow.

Generally, I'd release a new version when there's something important to
include. As for the frequency that's totally up to you and I guess the
previous point.

**Comment by sideshowbarker** [comment]
OK https://www.npmjs.com/package/vnu-jar/v/23.4.1-0.1 now published

**Comment by XhmikosR** [comment]
thanks! But I think something looks weird.

It should be `23.4.10.1` :/

**Comment by sideshowbarker** [comment]
> thanks! But I think something looks weird.
> 
> It should be `23.4.10.1` :/
> 
> Or `23.4.10-1` if you prefer that way. The current one is wrong because it's a smaller number so semver doesn't pick it up

hmm yeah I don’t know how that happened. Locally I definitely have the version set to `23.4.10.1` — in the the updated local `package.json` file too — and all that my publish script is doing is running `npm publish`:

https://github.com/validator/validator/blob/470d919b6c5a8f880e6976a1367b1412ca379c3d/build/build.py#L1323-L1331

 So as far as I can see, it’s geting mangled by the npm.js API.

I have no idea how to further troubleshoot or fix it…

**Comment by XhmikosR** [comment]
I don't know what's wrong either, it's the first time I see this.

Maybe it's your script to blame that script, though, because I don't see a new git tag either.

Either way, publishing manually with `npm version 23.4.10.1 && git push --tags` should work after you bump the version in package.json.

**Comment by sideshowbarker** [comment]
> I don't see a new git tag either.

Where? The repo itself has https://github.com/validator/validator/releases/tag/23.4.10.1 at least

> publishing manually with `npm version 23.4.10.1 && git push --tags` should work

When I try that I npm gives me this:

> npm ERR! Git working directory not clean.

And I know it’s not clean — that’s because the changes are temporary — to the package.json and the README.md and the build/build.py script, and I don’t want nor need to commit those.

**Comment by XhmikosR** [comment]
Try with `npm version 23.4.10.1 --no-git-tag-version && npm publish`

> Where? The repo itself has https://github.com/validator/validator/releases/tag/23.4.10.1 at least

I must have missed refreshing the page or something, now I see it, indeed.

**Comment by sideshowbarker** [comment]
https://www.npmjs.com/package/vnu-jar/v/23.4.11 published
