### ISSUE TITLE
search tag throws an error when used in the main tag

### ISSUE THREAD

**Issue by IrwinJames-FS** [validator/validator#1583]
URL being validated or code to reproduce error: I apologize this is a local file however can be reproduced with the following

```html
<main>
     <search><form><input></form></search>
</main>

```
Error: Element [search](https://html.spec.whatwg.org/multipage/#the-search-element) not allowed as child of element [main](https://html.spec.whatwg.org/multipage/#the-main-element) in this context. (Suppressing further errors from this subtree.)
```


https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element

Example #3 indicates search can be used in this manner.

**Comment by nschonni** [comment]
Not supported till https://github.com/validator/validator/issues/1569 is resolved. I don't think any browsers actually support it yet, since the spec only landed recently
