### ISSUE TITLE
Isn't 'us-ascii' valid UTF-8?

### ISSUE THREAD

**Issue by tcdaly** [validator/validator#1601]
Surely the following two errors are erroneous.  'us-ascii' is a subset of UTF-8, so 'us-ascii' is valid UTF-8?

`: error: Legacy encoding “us-ascii” used. Documents must use UTF-8.`
`:5.5-5.26: error: Internal encoding declaration “utf-8” disagrees with the actual encoding of the document (“us-ascii”). `

**Comment by 1jj** [comment]
Well, being a subset or not is irrelevant.
UTF-8 is the only valid encoding for HTML documents (for various reasons, including securiy considerations). 
Anything else is invalid.
https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-charset
https://html.spec.whatwg.org/multipage/semantics.html#character-encoding-declaration

**Comment by nschonni** [comment]
https://github.com/validator/validator/issues/611#issuecomment-366640965
