### ISSUE TITLE
incorrect warning on img element

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#161]
>Warning: Element img does not need a role attribute.

https://validator.w3.org/nu/?doc=http%3A%2F%2Frawgit.com%2Fa11ydoer%2Faria%2F2e887c7ad1c597f422d93059c6705fdc4fd19aca%2Fpractices%2Fexamples%2Flink%2Flink.html

This should only be a warning when the img element has a role=img

**Comment by sideshowbarker** [comment]
oops

**Comment by sideshowbarker** [comment]
I think I fixed this a couple weeks ago with https://github.com/validator/validator/commit/f2ffaafd586db055b666fdb2f392219461403886

So please re-check and if I’m wrong and it’s re-occurring, please re-open this.
