### ISSUE TITLE
Error!!

### ISSUE THREAD

**Issue by peeberry2023** [validator/validator#1641]
My code looks fine but i'm being told there is an error in my code. i don't see what the issue is

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Learning coding is cool!</title>
</head>
<body>
 Coding is cool! I am learning so much!
</body>
</html>
```

**Comment by stevefaulkner** [comment]
@peeberry2023 what is the error?

**Comment by stevefaulkner** [comment]
for your code example there is a warning

> Consider adding a lang attribute to the html start tag to declare the language of this document.

> For further guidance, consult [Declaring the overall language of a page](https://www.w3.org/International/techniques/authoring-html.en?open=language&open=textprocessing#textprocessing) and [Choosing language tags](https://www.w3.org/International/techniques/authoring-html.en?open=language&open=langvalues#langvalues)
