### ISSUE TITLE
"Attribute `w3-include-html` not allowed on element div at this point."

### ISSUE THREAD

**Issue by mig281** [validator/validator#1658]
URL being validated or code to reproduce error: http://pictureyourwords.ca/

I've followed [the example on the W3Schools website](https://www.w3schools.com/howto/howto_html_include.asp) exactly. 🤔

>Including HTML is done by using a w3-include-html attribute:
>```
><div w3-include-html="content.html"></div>
>```

These are the errors I get:

```
Error: Attribute w3-include-html not allowed on element [div](https://html.spec.whatwg.org/multipage/#the-div-element) at this point.

From line 77, column 5; to line 77, column 46

ader>↩    <div w3-include-html="includes/menu.html"></div>
```

```
Error: Attribute w3-include-html not allowed on element [div](https://html.spec.whatwg.org/multipage/#the-div-element) at this point.

From line 208, column 5; to line 208, column 49

oter>↩    <div w3-include-html="/includes/footer.html"></div>
```

**Comment by nschonni** [comment]
W3Schools is a terrible reference, but has awesome SEO. Using data attributes is a valid way of doing something like this https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
MDN is a better source for learning HTML

**Comment by mig281** [comment]
@nschonni Thanks for the tip, Nick!
