### ISSUE TITLE
Bad value for attribute src on element img: Illegal character in path segment: not a URL code point

### ISSUE THREAD

**Issue by KyleJosef** [validator/validator#166]
Hello, 
I do not understand this problem,
Bad value [images V2/Healthy Eating logo V5.jpg] for attribute src on element img: Illegal character in path segment: not a URL code point.

Any URL. For example: /hello, #canvas, or http://example.org/. Characters should be represented in NFC and spaces should be escaped as %20.

Can someone please explain to me what this is and find out what is wrong with this: images V2/Healthy Eating logo V5.jpg

**Comment by cvrebert** [comment]
As the message says: **spaces should be escaped as %20**
But instead you have raw spaces in your URL.

**Comment by KyleJosef** [comment]
Sorry I still don't understand, I'm a 15 year old so can you please clarify this in a simple way, thanks for replying.

**Comment by cvrebert** [comment]
Replace spaces in the URL with `%20`
So
`images V2/Healthy Eating logo V5.jpg`
should instead be:
`images%20V2/Healthy%20Eating%20logo%20V5.jpg`

**Comment by cvrebert** [comment]
More background info:
* https://en.wikipedia.org/wiki/Percent-encoding
* https://en.wikipedia.org/wiki/Escape_character

**Comment by KyleJosef** [comment]
Thanks a lot!!!

**Comment by sideshowbarker** [comment]
Closing this since it seems that it’s has been resolved satisfactorily.
