### ISSUE TITLE
non-deterministic parsing order makes replicating #1217 difficult

### ISSUE THREAD

**Issue by stephen-huan** [validator/validator#1667]
I've been running into #1217 as well and I think I've came up with a minimum working example.

The setup is simple. It comes from unintended interaction between `--also-check-*`, i.e. run the command
```shell
vnu --also-check-css --also-check-svg --skip-non-html .
```
in a directory with both a css and svg file. For concreteness, consider `test.css` to be
```css
h2 { text-align: center; }
```
and `test.svg` to be
```svg
<svg xmlns="http://www.w3.org/2000/svg"></svg>
```
Then the command
```shell
vnu --also-check-css --also-check-svg --skip-non-html test.css test.svg
```
won't have errors but the command with the css and svg files swapped
```shell
vnu --also-check-css --also-check-svg --skip-non-html test.svg test.css
```
errors with the same message as #1217.
```text
"file:/./test.css":0.16-0.29: error: Element “html” not allowed in this context. (Suppressing further errors from this subtree.)
```
This bug is hard to replicate because one usually runs `vnu` on a directory, in which case the `--verbose` flag reports the processing order. However, the order seems to vary non-deterministically based on the reported filesystem order.
```text
vnu --also-check-css --also-check-svg --skip-non-html --verbose .
```
I think the processing order should be made deterministic by e.g. sorting to make the behavior more predicable.

Of course, the more explicit
```shell
vnu --skip-non-html .
vnu --skip-non-css .
vnu --skip-non-svg .
```
just works. I think it's slightly slower on very many files due to needing to ignore repeatedly, but this is minor.
Perhaps this recipe should be added to the README and specifying both `--also-check-css --also-check-svg` should error.

(also, I'm on an older version, `22.9.29`. I can try upgrading if it'll make a difference.)

**Comment by sideshowbarker** [comment]
Thanks for raising this. I agree this should be fixed but I can’t commit to making time in the near future to fix it myself.

But https://github.com/validator/validator/blob/main/src/nu/validator/client/SimpleCommandLineValidator.java has the source and I could at least commit to making time to review a patch to that for this — if anybody were to put one together.

**Comment by MichaIng** [comment]
Thanks for reporting again the issue and your helpful analysis. Indeed it also re-appeared our end and my workaround as well was to split the calls instead of using `--also-check-css --also-check-svg`.

**Comment by stephen-huan** [comment]
Fixed by https://github.com/validator/validator/pull/1726. Thanks @rcowsill!
