### ISSUE TITLE
Language misidentification

### ISSUE THREAD

**Issue by Henrycaraballo** [validator/validator#1675]
The checker did not recognize that the language "html" was identified.
```hml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Courser is so Cool!</title>
</head>
<body>
Coursera is so COOL! I am learning SO much!
</body>
</html>
```

**Comment by nschonni** [comment]
The message is telling you you're missing the `<html lang="en">`. Please don't use issue trackers for learning a language, StackOverlow is a better place for basic questions.
