### ISSUE TITLE
New Maven Central release?

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#168]
Would it be possible to get an updated jar uploaded to Maven Central?
I want to update LMVTFY so it can benefit from all the bugfixes that have been made since v15.6.29 of the validator.

**Comment by sideshowbarker** [comment]
Yeah will do a new release but I likely will not able to get to til this weekend at the earliest. Please feel free to re-ping me about it then to remind me.

**Comment by sideshowbarker** [comment]
http://search.maven.org/#artifactdetails|nu.validator|validator|16.1.1|jar
http://repo1.maven.org/maven2/nu/validator/validator/16.1.1/
