### ISSUE TITLE
Misunderstood language

### ISSUE THREAD

**Issue by Codeweb1010** [validator/validator#1717]
The validator says that because I am usin loren ipsum I maust change my language from spanish "es" to another one. I don't want to change my language because my website will be in spanish, so it`s a missunderstandig

**Comment by nschonni** [comment]
It's a warning, but it's correctly flagging the language mismatch. You can ignore the warning, but I don't think there is any bug here

**Comment by Codeweb1010** [comment]
Thanks, it is not a bug
