### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by vihdzp** [validator/validator#1731]
I followed the build instructions given [here](https://validator.github.io/validator/#build-instructions). Running the `all` or `build` commands seems to work fine, until I get this error:
```
Traceback (most recent call last):
  File "validator\checker.py", line 42, in <module>
    build.main(args)
  File "validator\build\build.py", line 1910, in main
    release.buildAll()
  File "validator\build\build.py", line 1464, in buildAll
    prepareLocalEntityJar()
  File "validator\build\build.py", line 1591, in prepareLocalEntityJar
    shutil.copyfile(os.path.join(buildRoot, "docs", "Microsyntax-descriptions.md"),  # nopep8
  File "C:\Users\vihdz\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '.\\docs\\Microsyntax-descriptions.md'
```
My `docs` folder is empty, even though I've ran `update` and `dldeps` prior. There doesn't seem to be any executable output.

**Comment by sideshowbarker** [comment]
Thanks for reporting this — and also thanks for removing the spam from the wiki.

I just now also (force) pushed a revert to the wiki, resetting the repo history to the state (and hash) it had before the spam.

Can you please try `./checker.py update` again and see if that fixes the `docs` folder problem.

If that doesn’t fix it, can you try directly running `git submodule update --remote --merge --init`  and see if that fixes it?

All that `./checker.py update` does it to call `git submodule update --remote --merge --init`.

The only other thing I can suggest trying is, to omit either or both of the `--remote` and `--merge` options, and just do
`git submodule update --init`. Or even, also omit the `--init` option.

If none of that fixes anything, then I’m not sure what else to suggest. To me it seems unlikely that it’s a Windows-specific problem — but then, I don’t have a Windows environment to test in.

**Comment by vihdzp** [comment]
The suggested commands didn't seem to work, but deleting the entire repo and running the installation again did. Thanks!
