### ISSUE TITLE
Expand documentation to include the Result Structure

### ISSUE THREAD

**Issue by EvilKarter** [validator/validator#1733]
**Is your feature request related to a problem? Please describe.**
I save the results of the analysis in my database. 
I assumed that the "extract" part is always part of the response. However, this seems to be optional. 

**Describe the solution you'd like**
I would find it practical if the readme contained a short paragraph on how the result is structured and which fields are optional. 
Alternatively, a link to the class that reflects an entry in the response from which I can read which fields are optional would be sufficient.

**Comment by EvilKarter** [comment]
@sideshowbarker hi, can you tell me where I can find the result structure?

**Comment by sideshowbarker** [comment]
It sounds like you probably want to see https://github.com/validator/validator/wiki/Output-»-JSON#root-object

**Comment by EvilKarter** [comment]
@sideshowbarker thank you!
