### ISSUE TITLE
build.py ignores exit status of subprocesses

### ISSUE THREAD

**Issue by kevinoid** [validator/validator#1737]
There are several locations in `build/build.py` where the return value of `runCmd()` is ignored.  This makes it difficult for callers to determine whether the requested operation succeeded (e.g. `build.py update` or `build.py docker-build`) and cause operations to silently proceed despite errors (e.g. `build.py all` runs the validator even if `update` failed).

I'd like to propose changing `runCmd()` to call [`subprocess.check_call`](https://docs.python.org/3/library/subprocess.html#subprocess.check_call) so that `runCmd()` will raise an exception for non-zero exit codes and exit with a non-zero status if the exception is not caught.  Would a pull request with this change be acceptable?  Are there any uses of `runCmd()` where non-zero exit status should be ignored?  (It does not appear so to me.)

Thanks for considering,
Kevin

**Comment by sideshowbarker** [comment]
> I'd like to propose changing `runCmd()` to call [`subprocess.check_call`](https://docs.python.org/3/library/subprocess.html#subprocess.check_call) so that `runCmd()` will raise an exception for non-zero exit codes and exit with a non-zero status if the exception is not caught. Would a pull request with this change be acceptable?

Yes, sounds good to me

> Are there any uses of `runCmd()` where non-zero exit status should be ignored? (It does not appear so to me.)

Same here. I can’t think of any
