### ISSUE TITLE
{success | failure} depends on {presence | absence} of the optional attribute "encoding" in the XML declaration

### ISSUE THREAD

**Issue by Luxitub** [validator/validator#1738]
Validation is done:
        - through [W3C Markup Validation Service # Validate by File Upload](https://validator.w3.org/#validate_by_upload)
        - Character Encoding: (detect automatically)
        - Document Type: (detect automatically)

However, the real document type is: XML syntax for HTML5 (XHTML5).

The validation is inconsistent between:
* an XML declaration having an "`encoding`" attribute: `<?xml version="1.0" encoding="UTF-8"?>`
> Info: Using the preset for XHTML + SVG 1.1 + MathML 3.0 + RDFa 1.1 based on the root namespace.
>
> Document checking completed. No errors or warnings to show.
* an XML declaration without an "`encoding`" attribute: `<?xml version="1.0"?>`
> Fatal Error: end of input while looking for delimiter (started on line 3) (expected ")
>
> At line 3, column 22
>
> xmlns="http://ww

[W3C XML 1.0 (ed.5) Recommendation](https://www.w3.org/TR/xml/#sec-prolog-dtd)  indicates that the encoding declaration is optional (see "`XMLDecl`"). Therefore, removing the attribute "`encoding`" should not change the behavior.

The problem here is not about "(X)HTML5 is (or should be) supported or not". The problem is that in one case the file is successfully checked, but the other throws an error. Either both should be successful, or both should fail, with the exact same message.

Note: Each file starts with a UTF-8 byte-order mark (BOM).

[xhtml-xml-declaration-with-out-encoding.zip](https://github.com/user-attachments/files/16442128/xhtml-xml-declaration-with-out-encoding.zip)

**Comment by nschonni** [comment]
> - through [W3C Markup Validation Service # Validate by File Upload](https://validator.w3.org/#validate_by_upload)

That is the legacy validator, not this repo https://validator.w3.org/nu/

**Comment by nschonni** [comment]
That site is over https://github.com/w3c/markup-validator
