### ISSUE TITLE
I don't understand this hint

### ISSUE THREAD

**Issue by chrisander-2910** [validator/validator#1764]
Can you help me?

![grafik](https://github.com/user-attachments/assets/534a0760-18ec-492c-a5a6-f95d81e7a092)

**Comment by scottaohara** [comment]
looks like a case of color vs colour

**Comment by chrisander-2910** [comment]
Ahhhh .... wow, thank you, I didn't notice that "u"!
________________________________
Von: scottaohara ***@***.***>
Gesendet: Freitag, 15. November 2024 16:21
An: validator/validator ***@***.***>
Cc: Christine Sander ***@***.***>; Author ***@***.***>
Betreff: Re: [validator/validator] I don't understand this hint (Issue #1764)


looks like a case of color vs colour
