### ISSUE TITLE
Unquoted data URIs are valid

### ISSUE THREAD

**Issue by tcrxt** [validator/validator#178]
This issue is explained at http://stackoverflow.com/q/15481088/2657549

    #something {
        background: url(data:image/png;base64,ABCDEF);
    }

with a correct base64 encoding of an image instead of ABCDEF is valid according to http://www.w3.org/TR/CSS21/syndata.html#uri but throws an error when going through the validator:
   
     Value Error : background url(data:image/png;base64,ABCDEF) is an incorrect URL url(data:image/png;base64,ABCDEF) 

Is that a bug?

**Comment by cvrebert** [comment]
I believe you want the CSS validator project (https://github.com/w3c/css-validator). This is the HTML validator project.

**Comment by tcrxt** [comment]
Sorry about the confusion.
