### ISSUE TITLE
HTML5 in php file - daft question ...

### ISSUE THREAD

**Issue by HarveyJAAP** [validator/validator#179]
Is it because I do not have a php server on my machine that I get this error?

IOERROR Non-XML Content-Type: application/x-php. 

(see attached screenshot)

I am in the process of converting my site to HTML5 and plan to replace every affected file at once when I am done.  I am validating each file offline on my domestic machine.
I get this error only with my .php files, unless I change the file name to .html when I get other errors on <? php lines.

Is there any way to check these files before uploading/going live? Apart from dummy running them online or installing a php server on my home machine ...

Thanks.
Harvey

![nuvalidator](https://cloud.githubusercontent.com/assets/15778635/11061695/1e5d96e4-87a9-11e5-8c5d-a40c677c059f.jpg)

**Comment by cvrebert** [comment]
See #93.

**Comment by sideshowbarker** [comment]
As noted in #93, this tool is an HTML checker, not a PHP checker. It’s intended to check the HTML content that’s actually sent over the wire—the same content that browsers parse and process.

> installing a php server on my home machine

That’s actually not a very difficult thing to do at all. You don’t actually have to run a whole PHP server just to check the files—you can automate it using the `php` command-line client.

Anyway, I’m going to close this out but feel free to re-open it if you disagree with the resolution, and/or feel free to add further questions or comments here.
