### ISSUE TITLE
Possible issue with NU HTML Checker

### ISSUE THREAD

**Issue by mdy77** [validator/validator#182]
Is this a possible issue with the NU HTML Checker?

When validating different files that use the role="radio" on the `<li>` element, and the role="radiogroup" on the `<ul>` element, the validator flags each role attribute as an error for those elements.

According to the HTML 5.1 W3C Working Draft 08 October 2015 it appears that the `<ul>` and the `<li>` elements allow those role attributes that are flagged as errors.

http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-ul-element
http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-li-element
  
![error-ul-role-radiogroup](https://cloud.githubusercontent.com/assets/12800631/11325493/03277078-9115-11e5-812f-af927fcb78f0.png)
![error-li-role-radio](https://cloud.githubusercontent.com/assets/12800631/11325494/0c1f327e-9115-11e5-8410-b5b79e7e12b1.png)
![allowed-role-li](https://cloud.githubusercontent.com/assets/12800631/11325497/1d7c81ca-9115-11e5-8e14-67769d08b278.png)
![allowed-ul-role-radiogroup](https://cloud.githubusercontent.com/assets/12800631/11325498/1d7e5d92-9115-11e5-93b2-0445ebab5ea2.png)

**Comment by sideshowbarker** [comment]
Thanks for reporting this. We’ve not done such a good job of making it clear, but the current requirements for ARIA in HTML are actually in https://www.w3.org/TR/html-aria/

And If you look at https://www.w3.org/TR/html-aria/#ul https://www.w3.org/TR/html-aria/#li you’ll see that `role=radiogroup` are not allowed with `ul` and `role=radio` is not allowed with `li`, so the checker is actually correctly conforming with the https://www.w3.org/TR/html-aria/ on this.

So I’m going to go ahead and close this but of course feel free to add further comments if you think this needs more clarification (and/or re-open it if you disagree with the resolution).

**Comment by mdy77** [comment]
Thanks Michael!
Would it be possible to have the headings for the older drafts and URLs changed so they are clearly marked as archived?   If I recall correctly, when I clicked on the latest published version from the October 8 2015 Draft that it did not connect me with the latest/current draft.  
Kind regards,Michelle
