### ISSUE TITLE
Error: Element "meta" is missing required attribute "content".

### ISSUE THREAD

**Issue by M2spbRu** [validator/validator#192]
I'm going to use Structured Data in my web page.

But the code line:

meta itemprop="mainEntityOfPage" itemscope itemType="https://schema.org/WebPage" itemid="http://www.m2-spb.ru/com01"

gets the error message (as in the issue title).

But I got it from the Google developer example from this page:

https://developers.google.com/structured-data/rich-snippets/articles

div itemscope itemtype="http://schema.org/NewsArticle"

meta itemscope itemprop="mainEntityOfPage"  itemType="https://schema.org/WebPage" itemid="https://google.com/article"

....

Then I'm asking is it really error?

**Comment by unor** [comment]
Yes, Google’s example is invalid. If a `meta` element has the `itemprop` attribute, the `content` attribute is required.

(See [my answer on Webmasters SE](http://webmasters.stackexchange.com/a/87982/17633) for an alternative.)

**Comment by sideshowbarker** [comment]
Thanks @unor

Closing per https://github.com/validator/validator/issues/192#issuecomment-166406880

**Comment by M2spbRu** [comment]
Thanks @unor
