### ISSUE TITLE
Could not find or load main class nu.validator.servlet.Main

### ISSUE THREAD

**Issue by Naveen701372** [validator/validator#194]
^
.\src\nu\validator\messages\MessageEmitterAdapter.java:79: error: package com.th
aiopensource.xml.util does not exist
import com.thaiopensource.xml.util.Name;
                                  ^
.\src\nu\validator\validation\SimpleDocumentValidator.java:86: error: cannot fin
d symbol
    private Schema mainSchema;
            ^
  symbol:   class Schema
  location: class SimpleDocumentValidator
.\src\nu\validator\validation\SimpleDocumentValidator.java:90: error: cannot fin
d symbol
    private Schema assertionSchema;
            ^
  symbol:   class Schema
  location: class SimpleDocumentValidator
.\src\nu\validator\validation\SimpleDocumentValidator.java:92: error: cannot fin
d symbol
    private Validator validator;
            ^
  symbol:   class Validator
  location: class SimpleDocumentValidator
.\src\nu\validator\validation\SimpleDocumentValidator.java:106: error: cannot fi
nd symbol
    private Schema schemaByUrl(String schemaUrl, ErrorHandler errorHandler)
            ^
  symbol:   class Schema
  location: class SimpleDocumentValidator
.\src\nu\validator\servlet\imagereview\ImageCollector.java:39: error: package co
m.thaiopensource.validate does not exist
import com.thaiopensource.validate.Validator;
                                  ^
.\src\nu\validator\servlet\imagereview\ImageCollector.java:41: error: cannot fin
d symbol
public class ImageCollector implements Validator, ContentHandler, Iterable<Image
> {
                                       ^
  symbol: class Validator
.\src\nu\validator\spec\Spec.java:29: error: package com.thaiopensource.xml.util
 does not exist
import com.thaiopensource.xml.util.Name;
                                  ^
.\src\nu\validator\messages\MessageEmitterAdapter.java:901: error: cannot find s
ymbol
            AbstractValidationException e) throws SAXException {
            ^
  symbol:   class AbstractValidationException
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1067: error: cannot find
symbol
            Map<String, DatatypeException> datatypeErrors) throws SAXException {

                        ^
  symbol:   class DatatypeException
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1100: error: cannot find
symbol
    private void element(MessageTextHandler messageTextHandler, Name element,
                                                                ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1143: error: cannot find
symbol
            Name attributeName, Name elementName, boolean atSentenceStart)
            ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1143: error: cannot find
symbol
            Name attributeName, Name elementName, boolean atSentenceStart)
                                ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1309: error: cannot find
symbol
    private void elaborateDatatypes(Map<String, DatatypeException> map)
                                                ^
  symbol:   class DatatypeException
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1342: error: cannot find
symbol
    private void elaborateContentModel(Name elt) throws SAXException {
                                       ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1358: error: cannot find
symbol
    private void elaborateContentModelandContext(Name parent, Name child)
                                                 ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1358: error: cannot find
symbol
    private void elaborateContentModelandContext(Name parent, Name child)
                                                              ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1386: error: cannot find
symbol
    private void elaborateElementSpecificAttributes(Name elt)
                                                    ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1391: error: cannot find
symbol
    private void elaborateElementSpecificAttributes(Name elt, Name attribute)
                                                    ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1391: error: cannot find
symbol
    private void elaborateElementSpecificAttributes(Name elt, Name attribute)
                                                              ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1418: error: cannot find
symbol
            XhtmlSaxEmitter xhtmlSaxEmitter, Name elt) throws SAXException {
                                             ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1426: error: cannot find
symbol
    private void emitContextDt(XhtmlSaxEmitter xhtmlSaxEmitter, Name elt)
                                                                ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1435: error: cannot find
symbol
    private void emitContentModelDt(XhtmlSaxEmitter xhtmlSaxEmitter, Name elt)
                                                                     ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1445: error: cannot find
symbol
            Name elt) throws SAXException {
            ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1461: error: cannot find
symbol
            Name elt, Name badAttribute) throws SAXException {
            ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\messages\MessageEmitterAdapter.java:1461: error: cannot find
symbol
            Name elt, Name badAttribute) throws SAXException {
                      ^
  symbol:   class Name
  location: class MessageEmitterAdapter
.\src\nu\validator\spec\Spec.java:32: error: cannot find symbol
    private final Map<Name, String> urisByElement;
                      ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:34: error: cannot find symbol
    private final Map<Name, DocumentFragment> contextsByElement;
                      ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:36: error: cannot find symbol
    private final Map<Name, DocumentFragment> contentModelsByElement;
                      ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:38: error: cannot find symbol
    private final Map<Name, DocumentFragment> attributesByElement;
                      ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:46: error: cannot find symbol
    public Spec(final Map<Name, String> urisByElement, final Map<Name, DocumentF
ragment> contextsByElement, final Map<Name, DocumentFragment> contentModelsByEle
ment, final Map<Name, DocumentFragment> attributesByElement) {
                          ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:46: error: cannot find symbol
    public Spec(final Map<Name, String> urisByElement, final Map<Name, DocumentF
ragment> contextsByElement, final Map<Name, DocumentFragment> contentModelsByEle
ment, final Map<Name, DocumentFragment> attributesByElement) {
                                                                 ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:46: error: cannot find symbol
    public Spec(final Map<Name, String> urisByElement, final Map<Name, DocumentF
ragment> contextsByElement, final Map<Name, DocumentFragment> contentModelsByEle
ment, final Map<Name, DocumentFragment> attributesByElement) {

                                      ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:46: error: cannot find symbol
    public Spec(final Map<Name, String> urisByElement, final Map<Name, DocumentF
ragment> contextsByElement, final Map<Name, DocumentFragment> contentModelsByEle
ment, final Map<Name, DocumentFragment> attributesByElement) {

                ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:53: error: cannot find symbol
    public String elementLink(Name element) {
                              ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:57: error: cannot find symbol
    public DocumentFragment contextDescription(Name element) {
                                               ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:61: error: cannot find symbol
    public DocumentFragment contentModelDescription(Name element) {
                                                    ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\spec\Spec.java:65: error: cannot find symbol
    public DocumentFragment elementSpecificAttributesDescription(Name element) {

                                                                 ^
  symbol:   class Name
  location: class Spec
.\src\nu\validator\client\TestRunner.java:47: error: package org.relaxng.datatyp
e does not exist
import org.relaxng.datatype.DatatypeException;
                           ^
.\src\nu\validator\client\TestRunner.java:48: error: package com.thaiopensource.
relaxng.exceptions does not exist
import com.thaiopensource.relaxng.exceptions.BadAttributeValueException;
                                            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
Removing temp-javac-list
"jar" cf ".\dist\validator.jar" @temp-jar-list
Removing temp-jar-list
Removing .\classes
Removing .\dist
"java" -classpath .\dependencies\commons-codec-1.10.jar;.\dependencies\commons-f
ileupload-1.3.1.jar;.\dependencies\commons-io-2.4.jar;.\dependencies\commons-log
ging-1.2.jar;.\dependencies\commons-logging-1.2-adapters.jar;.\dependencies\comm
ons-logging-1.2-api.jar;.\dependencies\httpcore-4.4.jar;.\dependencies\httpclien
t-4.4.jar;.\dependencies\icu4j-54.1.1.jar;.\dependencies\javax.servlet-api-3.1.0
.jar;.\dependencies\jchardet-1.0.jar;.\dependencies\jetty-http-9.2.9.v20150224.j
ar;.\dependencies\jetty-io-9.2.9.v20150224.jar;.\dependencies\jetty-security-9.2
.9.v20150224.jar;.\dependencies\jetty-server-9.2.9.v20150224.jar;.\dependencies\
jetty-servlet-9.2.9.v20150224.jar;.\dependencies\jetty-servlets-9.2.9.v20150224.
jar;.\dependencies\jetty-util-9.2.9.v20150224.jar;.\dependencies\jetty-util-ajax
-9.2.9.v20150224.jar;.\dependencies\log4j-1.2.17.jar;.\dependencies\rhino-1.7R5.
jar;.\jing-trang\lib\saxon9.jar;.\jing-trang\lib\xercesImpl.jar;.\jing-trang\lib
\xml-apis.jar;.\jing-trang\lib\isorelax.jar;.\jars\galimatias.jar;.\jars\htmlpar
ser.jar;.\jars\validator.jar;jing-trang\build\jing.jar;.\jars\galimatias.jar;.\j
ars\htmlparser.jar;.\jars\validator.jar;jing-trang\build\jing.jar nu.validator.c
lient.TestRunner --ignore=html-its tests/messages.json
Error: Could not find or load main class nu.validator.client.TestRunner
java -XX:-DontCompileHugeMethods -Xms131072k -Xmx131072k -Djava.security.propert
ies=.\resources\security.properties -classpath .\dependencies\commons-codec-1.10
.jar;.\dependencies\commons-fileupload-1.3.1.jar;.\dependencies\commons-io-2.4.j
ar;.\dependencies\commons-logging-1.2.jar;.\dependencies\commons-logging-1.2-ada
pters.jar;.\dependencies\commons-logging-1.2-api.jar;.\dependencies\httpcore-4.4
.jar;.\dependencies\httpclient-4.4.jar;.\dependencies\icu4j-54.1.1.jar;.\depende
ncies\javax.servlet-api-3.1.0.jar;.\dependencies\jchardet-1.0.jar;.\dependencies
\jetty-http-9.2.9.v20150224.jar;.\dependencies\jetty-io-9.2.9.v20150224.jar;.\de
pendencies\jetty-security-9.2.9.v20150224.jar;.\dependencies\jetty-server-9.2.9.
v20150224.jar;.\dependencies\jetty-servlet-9.2.9.v20150224.jar;.\dependencies\je
tty-servlets-9.2.9.v20150224.jar;.\dependencies\jetty-util-9.2.9.v20150224.jar;.
\dependencies\jetty-util-ajax-9.2.9.v20150224.jar;.\dependencies\log4j-1.2.17.ja
r;.\dependencies\rhino-1.7R5.jar;.\jing-trang\lib\saxon9.jar;.\jing-trang\lib\xe
rcesImpl.jar;.\jing-trang\lib\xml-apis.jar;.\jing-trang\lib\isorelax.jar;.\jars\
galimatias.jar;.\jars\htmlparser.jar;.\jars\validator.jar;jing-trang\build\jing.
jar -Dnu.validator.datatype.warn=true -Dnu.validator.messages.limit=1000 -Dnu.va
lidator.servlet.about-page=https://about.validator.nu/ -Dnu.validator.servlet.co
nnection-timeout=5000 -Dnu.validator.servlet.follow-w3c-spec=0 -Dnu.validator.se
rvlet.host.generic= -Dnu.validator.servlet.host.html5= -Dnu.validator.servlet.ho
st.parsetree= -Dnu.validator.servlet.icon=icon.png -Dnu.validator.servlet.log4j-
properties=resources/log4j.properties -Dnu.validator.servlet.max-file-size=83886
08 -Dnu.validator.servlet.path.generic=/ -Dnu.validator.servlet.path.html5=/html
5/ -Dnu.validator.servlet.path.parsetree=/parsetree/ -Dnu.validator.servlet.serv
ice-name=Validator.nu -Dnu.validator.servlet.read-local-log4j-properties=1 -Dnu.
validator.servlet.results-title=Validation results -Dnu.validator.servlet.script
=script.js -Dnu.validator.servlet.socket-timeout=5000 -Dnu.validator.servlet.sta
tistics=0 -Dnu.validator.servlet.style-sheet=style.css -Dnu.validator.servlet.us
er-agent=Validator.nu/LV -Dnu.validator.servlet.version=18 December 2015 -Dnu.va
lidator.spec.html5-load=https://www.whatwg.org/specs/web-apps/current-work/ -Dnu
.validator.spec.html5-link=https://www.whatwg.org/specs/web-apps/current-work/ -
Dorg.mortbay.http.HttpRequest.maxFormContentSize=8388608 nu.validator.servlet.Ma
in 8888
Error: Could not find or load main class nu.validator.servlet.Main
Command failed.

I'm using windows 64-bit OS and java version 1.7.0_79
Please help.

**Comment by sideshowbarker** [comment]
Please post the full output, starting from the point when you actually run the build script.

The output you’ve posted here is incomplete. It indicates an earlier failure. The messages shown in this output are consequences of that earlier failure, not indications of what the actual cause it.

**Comment by Naveen701372** [comment]
@sideshowbarker Hey thanks for replying.
i updated the java version, i got past the above error.
but faced the following error, can you have a look at it please ?

$ python ./build/build.py all

Buildfile: c:\Users\NU00351442\validator\jing-trang\.\build.xml

check-modules:

modules:

check-modbuild:

modbuild:

jar:

init:

mod.util.compile-main:

mod.dtd-parse.compile-main:

mod.dtdinst.compile-main:

mod.dtdinst.jar:
      [jar] Building jar: c:\Users\NU00351442\validator\jing-trang\build\dtdinst.jar

mod.regex-gen.compile-main:

mod.regex.check-gen:

mod.regex.gen:

mod.regex.compile-main:

mod.datatype.compile-main:

mod.xsd-datatype.compile-main:

mod.validate.compile-main:

mod.rng-parse.gen:

mod.rng-parse.compile-main:

mod.rng-validate.compile-main:

mod.nvdl.compile-main:

mod.schematron.compile-res:

mod.schematron.compile-main:

mod.xerces.compile-main:

mod.picl.compile-main:

mod.jing.compile-main:

mod.jing.jar:
      [jar] Building jar: c:\Users\NU00351442\validator\jing-trang\build\jing.jar

mod.infer.compile-main:

mod.rng-schema.compile-main:

mod.convert-from-xml.compile-main:

mod.convert-to-xsd.compile-main:

mod.convert-from-dtd.compile-main:

mod.convert-to-dtd.compile-main:

mod.trang.compile-main:

mod.trang.jar:
      [jar] Building jar: c:\Users\NU00351442\validator\jing-trang\build\trang.jar

jar:

BUILD SUCCESSFUL
Total time: 34 seconds
"git" submodule update --init
https://help.whatwg.org/extensions/a-rel/
https://help.whatwg.org/extensions/link-rel/
https://wiki.whatwg.org/wiki/MicrosyntaxDescriptions
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
https://wiki.whatwg.org/wiki/Validator.nu_alt_advice
.\ant
Copying .\schema\.drivers\html5-all.rnc to .\schema\html5-all.rnc
Copying .\schema\.drivers\html5-its.rnc to .\schema\html5-its.rnc
Copying .\schema\.drivers\html5-no-microdata.rnc to .\schema\html5-no-microdata.rnc
Copying .\schema\.drivers\html5-rdfalite-w3c.rnc to .\schema\html5-rdfalite-w3c.rnc
Copying .\schema\.drivers\html5-rdfalite.rnc to .\schema\html5-rdfalite.rnc
Copying .\schema\.drivers\html5-svg-mathml.rnc to .\schema\html5-svg-mathml.rnc
Copying .\schema\.drivers\html5.rnc to .\schema\html5.rnc
Copying .\schema\.drivers\svg-xhtml5-rdf-mathml.rnc to .\schema\svg-xhtml5-rdf-mathml.rnc
Copying .\schema\.drivers\xhtml1-ruby-rdf-svg-mathml.rnc to .\schema\xhtml1-ruby-rdf-svg-mathml.rnc
Copying .\schema\.drivers\xhtml5-all.rnc to .\schema\xhtml5-all.rnc
Copying .\schema\.drivers\xhtml5-no-microdata.rnc to .\schema\xhtml5-no-microdata.rnc
Copying .\schema\.drivers\xhtml5-rdfalite-w3c.rnc to .\schema\xhtml5-rdfalite-w3c.rnc
Copying .\schema\.drivers\xhtml5-rdfalite.rnc to .\schema\xhtml5-rdfalite.rnc
Copying .\schema\.drivers\xhtml5-svg-mathml.rnc to .\schema\xhtml5-svg-mathml.rnc
Copying .\schema\.drivers\xhtml5.rnc to .\schema\xhtml5.rnc
Copying .\schema\.drivers\xhtml10 to .\schema\xhtml10
Copying .\schema\.drivers\rdf.rnc to .\schema\rdf/rdf.rnc
Removing .\schema\html5-all.rnc
Removing .\schema\html5-its.rnc
Removing .\schema\html5-no-microdata.rnc
Removing .\schema\html5-rdfalite-w3c.rnc
Removing .\schema\html5-rdfalite.rnc
Removing .\schema\html5-svg-mathml.rnc
Removing .\schema\html5.rnc
Removing .\schema\svg-xhtml5-rdf-mathml.rnc
Removing .\schema\xhtml1-ruby-rdf-svg-mathml.rnc
Removing .\schema\xhtml5-all.rnc
Removing .\schema\xhtml5-no-microdata.rnc
Removing .\schema\xhtml5-rdfalite-w3c.rnc
Removing .\schema\xhtml5-rdfalite.rnc
Removing .\schema\xhtml5-svg-mathml.rnc
Removing .\schema\xhtml5.rnc
Removing .\schema\html5\html5core.rnc
Removing .\schema\html5\html5full-no-microdata.rnc
Removing .\schema\html5\html5full-rdfa.rnc
Removing .\schema\html5\html5full-rdfalite.rnc
Removing .\schema\html5\html5full.rnc
Removing .\schema\html5\its20-html5-types.rnc
Removing .\schema\html5\its20-html5.rnc
Removing .\schema\html5\legacy.rnc
Removing .\schema\html5\xhtml5core-plus-web-forms2.rnc
Removing .\schema\html5\xhtml5core.rnc
Removing .\schema\html5\xhtml5full-html-no-microdata.rnc
Removing .\schema\html5\xhtml5full-html-rdfalite.rnc
Removing .\schema\html5\xhtml5full-html.rnc
Removing .\schema\html5\xhtml5full-xhtml-no-microdata.rnc
Removing .\schema\html5\xhtml5full-xhtml-rdfa.rnc
Removing .\schema\html5\xhtml5full-xhtml-rdfalite.rnc
Removing .\schema\html5\xhtml5full-xhtml.rnc
Removing .\schema\xhtml10
Removing .\schema\rdf
Removing .\galimatias\classes
"javac" -g -nowarn -classpath ".\dependencies\commons-codec-1.10.jar;.\dependencies\commons-fileupload-1.3.1.jar;.\dependencies\commons-io-2.4.jar;.\dependencies\commons-logging-1.2.jar;.\dependencies\commons-logging-1.2-adapters.jar;.\dependencies\commons-logging-1.2-api.jar;.\dependencies\httpcore-4.4.jar;.\dependencies\httpclient-4.4.jar;.\dependencies\icu4j-54.1.1.jar;.\dependencies\javax.servlet-api-3.1.0.jar;.\dependencies\jchardet-1.0.jar;.\dependencies\jetty-http-9.2.9.v20150224.jar;.\dependencies\jetty-io-9.2.9.v20150224.jar;.\dependencies\jetty-security-9.2.9.v20150224.jar;.\dependencies\jetty-server-9.2.9.v20150224.jar;.\dependencies\jetty-servlet-9.2.9.v20150224.jar;.\dependencies\jetty-servlets-9.2.9.v20150224.jar;.\dependencies\jetty-util-9.2.9.v20150224.jar;.\dependencies\jetty-util-ajax-9.2.9.v20150224.jar;.\dependencies\log4j-1.2.17.jar;.\dependencies\rhino-1.7R5.jar;.\dependencies\fest-assert-1.4.jar;.\dependencies\hamcrest-api-1.0.jar;.\dependencies\junit-4.12.jar;.\dependencies\slf4j-api-1.7.13.jar;.\dependencies\xom-1.2.5.jar;.\jing-trang\lib\saxon9.jar;.\jing-trang\lib\xercesImpl.jar;.\jing-trang\lib\xml-apis.jar;.\jing-trang\lib\isorelax.jar" -sourcepath ".\galimatias\src" -d ".\galimatias\classes" -encoding UTF-8 -target 1.6 -source 1.6 @temp-javac-list
Traceback (most recent call last):
  File "./build/build.py", line 1465, in <module>
    buildAll()
  File "./build/build.py", line 1195, in buildAll
    buildGalimatias()
  File "./build/build.py", line 631, in buildGalimatias
    buildModule( os.path.join(buildRoot, "galimatias"), "galimatias",

  File "./build/build.py", line 320, in buildModule
    runJavac(sourceDir, classDir, classPath)
  File "./build/build.py", line 279, in runJavac
    if runCmd('"%s" %s %s' % (javacCmd, " ".join(args), '@temp-javac-l
  File "./build/build.py", line 206, in runCmd
    subprocess.call(cmd)
  File "C:\Python26\lib\subprocess.py", line 444, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python26\lib\subprocess.py", line 595, in __init__
    errread, errwrite)
  File "C:\Python26\lib\subprocess.py", line 804, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by sideshowbarker** [comment]
The most-recent error message you posted indicates a problem with your Python environment, as far as I can tell. You maybe should try re-installing Python, and probably you should have Python 2.7 installed (not Python 2.6, which is extremely old at this point).

**Comment by sideshowbarker** [comment]
By the way, unless you have a non-typical need, you probably don’t need to build the code from the sources but instead you can just download the latest already-build `vnu.jar` file either from the [github release area for this project](https://github.com/validator/validator/releases/latest) or from [the alternate release area](https://sideshowbarker.net/releases/jar/).

**Comment by cvrebert** [comment]
My guess would be that the `os.name == 'nt'` cases in https://github.com/validator/validator/blob/e889095ebaabfc491eac18eaac504593b1e3fdfc/build/build.py#L205-L221 might be broken. Really there shouldn't be any need to special-case Windows like that; the `subprocess` module is cross-platform.

**Comment by sideshowbarker** [comment]
> My guess would be that the `os.name == 'nt'` cases in https://github.com/validator/validator/blob/e889095ebaabfc491eac18eaac504593b1e3fdfc/build/build.py#L205-L221 might be broken. Really there shouldn't be any need to special-case Windows like that; the `subprocess` module is cross-platform.

I unfortunately don’t have any Windows environment to test on myself. So I’m happy to have a patch from anybody who does and who has time to make the changes and test them.

**Comment by cvrebert** [comment]
Now that #205 has been merged, building on Windows stands a better chance of working.
