### ISSUE TITLE
Validation fails if script source contains '&' element

### ISSUE THREAD

**Issue by firstsano** [validator/validator#196]
I have Yii framework with extension which minifies scripts when requesting specified url. So when that url contains `&` symbol (i.e. when I send params to extention) I get errors:

1. No space between attributes.
2. Saw " when expecting an attribute name. Probable cause: = missing immediately before.
3. Warning: Attribute " is not serializable as XML 1.0.
4. Attribute " not allowed on element script at this point.

Example of script tag:
`<script async type="text/javascript" src="/webmain/min/serve?g=71b42b5e952f4dbb5c8569c09d37ae85&lm=1447666642" > </script>`

**Comment by sideshowbarker** [comment]
I think this is a regression I introduced with a recent change. But before I made that recent change, a message would have been emitted for this case, saying that you need to replace the `&` raw ampersand with `&amp;`. However I think this case is still one that the current spec says is not an error, so I need to look back at the code and see if I can manage to get it to allow this without munging it.

**Comment by sideshowbarker** [comment]
Thanks very much for taking to report this. You helped catch a pretty bad bug/regression and get it fixed. But anyway I do believe I have it fixed now; please confirm at https://validator.w3.org/nu/ and if it’s still not working as expected now, please let me know.

**Comment by firstsano** [comment]
Yes, everything works now. Thank you very much!
