### ISSUE TITLE
Add support for amphtml link rel type

### ISSUE THREAD

**Issue by bazzadp** [validator/validator#197]
Accelerated Mobile Pages (AMP) is a new HTML format proposed by Google, Twitter...et all and a number of publishers: https://www.ampproject.org.

The AMP format itself is still in a state of flux, and has it's own validator so probably not (yet?) worth adding all the AMP specific tags to this HTML validator.

However standard HTML pages are supposed to add a link tag to their pages to indicated if an AMP version of the page exists, such as this:

    <link rel="amphtml" href="http://www.example.com/page/amp/">

Currently when I try to run the validator on these pages they break with the following error:

    error: Bad value “amphtml” for attribute “rel” on element “link”: The string “amphtml” is not a registered keyword.

The amphtml value has been proposed as an addition to the HTML5 spec (http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions) and while it's not approved yet, other similar proposed extensions work in the validator.

It seems, from a very quick hunt around the code, that a simple addition of amphtml to this file solves the validation error:

    src/nu/validator/localentities/files/link-rel-extensions

I am not familiar enough with the code to say that is all that is needed, but when I change my own src to that and build again that seems to work and only real errors are flagged. Also seems a safe enough change.

Additionally I cannot find that file in this GIT repository, though the file that references that (/src/nu/validator/datatype/LinkRel.java) is in this repository. Sorry if I'm missing something obvious here but fairly new to GIT so still learning the ropes!

Can we add this type?

Thanks,
Barry

**Comment by sideshowbarker** [comment]
How are you running the validator? rel=amphtml is supported now at https://validator.w3.org/nu/ at least

**Comment by bazzadp** [comment]
Ah interesting. Hadn't noticed that as running locally and the fact this file is a dependency rather than a core part of the repo confused me.

Deleting the local repo completely and reinstalling fixed it. Though would love to know how to update dependencies like this without having to do this if anyone can tell me that?

**Comment by sideshowbarker** [comment]
If you’re running a local copy of the validator, it downloads a copy of the list of rel values and creates a cache of it each time you restart. So if there have been changes to the http://microformats.org/wiki/existing-rel-values page, the way to update a local validator is to just restart it.

**Comment by bazzadp** [comment]
Was running it from command line using jar build. The following command seems to update the dependencies so will run that periodically:

    python ./build/build.py dldeps

Thanks for your help.

Thanks,
Barry
