### ISSUE TITLE
input type="checkbox" unchecked

### ISSUE THREAD

**Issue by rss81** [validator/validator#199]
This appears to work but the validator says error

         <input type="checkbox" name="cookie" value="true"  unchecked />Remember Me

**Comment by cvrebert** [comment]
There is no attribute named `unchecked`. A checkbox input is unchecked by default, unless the `checked` attribute is present.

**Comment by sideshowbarker** [comment]
Yeah as https://github.com/validator/validator/issues/199#issuecomment-168353745 notes the checker is behaving as expected here in flagging the unknown/invalid `unchecked` attribute as an error.

**Comment by rss81** [comment]
thanks, should have known better
