### ISSUE TITLE
CSP referrer error

### ISSUE THREAD

**Issue by laukstein** [validator/validator#202]
validator.w3.org/nu/ for header `content-security-policy:referrer no-referrer` shows

    Error: Content-Security-Policy HTTP header: Bad content security policy: The referrer directive is not in the CSP specification yet.

No errors while checking trough html5.validator.nu.
Is validator.w3.org/nu/ outdated?

Spec https://w3c.github.io/webappsec-referrer-policy/, http://www.w3.org/TR/referrer-policy/, https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#referrer

**Comment by sideshowbarker** [comment]
That message comes from a 3rd-party lib we use for CSP syntax checking. So please consider reporting the problem upstream at https://github.com/shapesecurity/salvation/issues

> No errors while checking trough html5.validator.nu.
> Is validator.w3.org/nu/ outdated?

`html5.validator.nu` is typically months out of date these days. `validator.w3.org/nu/` is always kept up to date with the latest changes to the sources. In this case, CSP syntax checking was added just a few days ago.

**Comment by sideshowbarker** [comment]
I’ve fixed this and pushed the change to https://validator.w3.org/nu/
