### ISSUE TITLE
Build JDK Version Matters For Dependencies

### ISSUE THREAD

**Issue by reid-spencer** [validator/validator#206]
I tried to use the [maven version of validator](http://mvnrepository.com/artifact/nu.validator/validator/16.1.1) but it fails with this exception:

```
java.lang.ExceptionInInitializerError: Fatal execution error, caused by null (SourceSizeList.java:44)
nu.validator.datatype.SourceSizeList.<clinit>(SourceSizeList.java:44)
nu.validator.datatype.Html5DatatypeLibrary.createDatatype(Html5DatatypeLibrary.java:174)
nu.validator.datatype.Html5DatatypeLibrary.createDatatypeBuilder(Html5DatatypeLibrary.java:52)
com.thaiopensource.relaxng.impl.SchemaBuilderImpl.makeDataPatternBuilder(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.DataExpr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.PrimaryExpr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.AnnotatedPrimaryExpr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.UnaryExpr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Expr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Define(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Definition(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.TopLevelGrammar(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Input(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.parse(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactParseable.parse(Unknown Source)
com.thaiopensource.relaxng.impl.SchemaBuilderImpl.parse(Unknown Source)
com.thaiopensource.relaxng.impl.SchemaReaderImpl.createSchema(Unknown Source)
com.thaiopensource.validate.AbstractSchemaReader.createSchema(Unknown Source)
nu.validator.validation.SimpleDocumentValidator.schemaByUrl(SimpleDocumentValidator.java:125)
nu.validator.validation.SimpleDocumentValidator.setUpMainSchema(SimpleDocumentValidator.java:175)
CAUSED BY
org.mozilla.javascript.EcmaError: TypeError: Cannot find function create in object function Object() { [native code for Object.Object, arity=1] }. (unnamed script#550) (ScriptRuntime.java:3654)
org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3654)
org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3632)
org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3660)
org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3679)
org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3743)
org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2247)
org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2214)
org.mozilla.javascript.gen.c1._c2(unnamed script:550)
org.mozilla.javascript.gen.c1.call(unnamed script)
org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
org.mozilla.javascript.gen.c1._c1(unnamed script:8)
org.mozilla.javascript.gen.c1.call(unnamed script)
org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
org.mozilla.javascript.gen.c1._c0(unnamed script:0)
org.mozilla.javascript.gen.c1.call(unnamed script)
org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
org.mozilla.javascript.gen.c1.call(unnamed script)
org.mozilla.javascript.gen.c1.exec(unnamed script)
org.mozilla.javascript.Context.evaluateReader(Context.java:1135)
nu.validator.datatype.tools.CssParser.<clinit>(CssParser.java:55)
nu.validator.datatype.SourceSizeList.<clinit>(SourceSizeList.java:44)
nu.validator.datatype.Html5DatatypeLibrary.createDatatype(Html5DatatypeLibrary.java:174)
nu.validator.datatype.Html5DatatypeLibrary.createDatatypeBuilder(Html5DatatypeLibrary.java:52)
com.thaiopensource.relaxng.impl.SchemaBuilderImpl.makeDataPatternBuilder(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.DataExpr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.PrimaryExpr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.AnnotatedPrimaryExpr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.UnaryExpr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Expr(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Define(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Definition(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.TopLevelGrammar(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.Input(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactSyntax.parse(Unknown Source)
com.thaiopensource.relaxng.parse.compact.CompactParseable.parse(Unknown Source)
com.thaiopensource.relaxng.impl.SchemaBuilderImpl.parse(Unknown Source)
com.thaiopensource.relaxng.impl.SchemaReaderImpl.createSchema(Unknown Source)
com.thaiopensource.validate.AbstractSchemaReader.createSchema(Unknown Source)
nu.validator.validation.SimpleDocumentValidator.schemaByUrl(SimpleDocumentValidator.java:125)
nu.validator.validation.SimpleDocumentValidator.setUpMainSchema(SimpleDocumentValidator.java:175)
```
In researching this issue, I found it to be a problem between code compiled with JDK 6 (or earlier) but run on JDK 7 (or later), per [this StackOverflow issue](http://stackoverflow.com/questions/18634585/typeerror-in-rhino-migration-from-java-6-to-java-7). It seems that the Rhino dependency that validator-16.1.1.jar depends on was compiled by an old JDK. After grappling with the issue for a while, I tried the vnu.jar version which has all its dependencies built with the same (modern) JDK and included in the jar without maven dependencies. That worked fine. 

A subsequent gitter conversation with @sideshowbarker identified that the Rhino version that validator-16.1.1.jar depends on was compiled with JDK 1.5. 

If validator is to be released as a maven package with dependencies then there needs to be a way to ensure the dependencies are compiled with a modern JDK.

**Comment by sideshowbarker** [comment]
@cvrebert @rwhogg would be helpful to get your insight on this

**Comment by cvrebert** [comment]
[LMVTFY](https://github.com/cvrebert/lmvtfy) is using the validator Maven package with OpenJDK 8 without any problems, so I have no insight here.

**Comment by sideshowbarker** [comment]
@reid-spencer about the specific issue with the Rhino maven package, please consider also filing an issue at https://github.com/mozilla/rhino/issues

There’s a [newer Rhino 1.7.7 maven release](https://repo1.maven.org/maven2/org/mozilla/rhino/maven-metadata.xml) but examining the [rhino-1.7.7.jar file](https://repo1.maven.org/maven2/org/mozilla/rhino/1.7.7/rhino-1.7.7.jar) indicates it was built with/for Java6:

```
$ file org/mozilla/classfile/ByteCode.class
org/mozilla/classfile/ByteCode.class: compiled Java class data, version 50.0 (Java 1.6)
``` 

Given that [the final public update of Java6 was in 2013, almost 3 years ago](https://en.wikipedia.org/wiki/Java_version_history#cite_ref-6u45_78-1) and it’s received no security updates or any other kinds of updates since, it doesn’t seem to make any sense to be targeting anything for Java6 any longer (and we’re not helping users by continuing to facilitate Java6 user environments).

Moreover, the [last public update of Java7 was 9 months ago](https://en.wikipedia.org/wiki/Java_version_history#cite_ref-java.com_172-1) so I’d also argue it’s time to help users move on from Java7 as well.

But for the time being if the Rhino maintainers could at least update their maven package to target Java7, that would seem to fix the problem you’re having in your environment.

**Comment by reid-spencer** [comment]
@sideshowbarker - good point, and I agree completely. I tried my project with Rhino 1.7.7 and the problem was still present (unsurprisingly). I will file an issue with the Rhino folks.

**Comment by cvrebert** [comment]
Is the exception thrown only when validating certain pages, or most/all pages?

**Comment by reid-spencer** [comment]
It occurs during the construction of the validator:
```
nu.validator.datatype.tools.CssParser.<clinit>(CssParser.java:55)
```
That's the class init for CssParser .. which initializes Rhino. 

So, pretty much before anything is even started with validation.

**Comment by rwhogg** [comment]
> Moreover, the last public update of Java7 was 9 months ago so I’d also argue it’s time to help users move on from Java7 as well.

This might be difficult. Ubuntu 12.04 and 14.04 are both still supported until at least 2017, and both come with both Java 6 and Java 7, but no Java 8. It's possible to get Java 8 working on 14.04, and presumably on 12.04 as well, but it's something of a pain.

How about, in the interest of transitioning, we make a Dockerfile for running VNU that includes OpenJDK 8 (and maybe also Tomcat or Jetty)? That obviously won't solve @reid-spencer's problem, but it would be a nice way to ensure people aren't running VNU on an insecure Java version.

@reid-spencer, I unfortunately don't have any recommendations beyond "ask Mozilla" at this time; sorry.

**Comment by sideshowbarker** [comment]
> How about, in the interest of transitioning, we make a Dockerfile for running VNU that includes OpenJDK 8 (and maybe also Tomcat or Jetty)?

I think that’s an excellent idea and I’d be happy to help with distributing releases of such a Dockerfile but practically speaking I can’t commit to putting any significant amount of time into developing it. I’d need for you or others to do the work, and I could be around just to answer questions and resolve build issues.

> Ubuntu 12.04 and 14.04 are both still supported until at least 2017, and both come with both Java 6 and Java 7, but no Java 8.

I see. But the latest version of Ubuntu is 15 (released in April) and there’s a Java8 package for that, right? I realize that Ubuntu may be committed to supporting 12.04 and 14.04 through 2017 but that doesn’t mean we need to keep supporting it—specifically, it doesn’t mean we should restrict improvements to the HTML checker just to make it continue to be runnable on the old Ubuntu environments.

So, unless/until we distribute a Dockerfile, users who want to run the checker in those old environments can continue running the [15.6.29 release](https://github.com/validator/validator/releases/tag/15.6.29) just fine, and we can update the docs to indicate that’s what they should do. But if they want to run the current checker they way they have been, then they either need to upgrade to Ubuntu 15 or deal with installing Java8 directly.

**Comment by rwhogg** [comment]
>  I realize that Ubuntu may be committed to supporting 12.04 and 14.04 through 2017 but that doesn’t mean we need to keep supporting it—specifically, it doesn’t mean we should restrict improvements to the HTML checker just to make it continue to be runnable on the old Ubuntu environments.

I didn't notice until today that the newest release already requires Java 8 anyways. In that case, yeah, doing everything we can to encourage upgrading to a newer Java version makes sense.

> I think that’s an excellent idea and I’d be happy to help with distributing releases of such a Dockerfile but practically speaking I can’t commit to putting any significant amount of time into developing it. I’d need for you or others to do the work, and I could be around just to answer questions and resolve build issues.

I don't personally have much time to do this at the moment either. It's possible I'll be able to help, but I've been rather busy recently.

**Comment by sideshowbarker** [comment]
> I didn't notice until today that the newest release already requires Java 8 anyways. In that case, yeah, doing everything we can to encourage upgrading to a newer Java version makes sense.

Yeah, though currently the only reason it requires Java8 is because I added a dependency on [Salvation](https://github.com/shapesecurity/salvation) for Content Security Policy syntax checking, and the Salvation code (which is really nice code btw) uses some Java8-only features.

But that said, I’m also considering to just drop the Rhino dependency entirely and switch to using Nashorn (the new JavaScript thing in Java8).

**Comment by sideshowbarker** [comment]
> It occurs during the construction of the validator:
> ```
> nu.validator.datatype.tools.CssParser.<clinit>(CssParser.java:55)
> ```
> That's the class init for CssParser .. which initializes Rhino. 

So a possible workaround is that I can just disable that CssParser code without any loss to the user-facing behavior of the checker. That code is not actually doing anything user-affecting yet but is instead something I put in for doing some initial very limited experimenting with using a conforming CSS parser in parallel with the ad-hoc CSS-parsing we’re using now.

So what I could do is, I would disable that code and push a snapshot to maven central that you could test with. Is that worth trying?

**Comment by reid-spencer** [comment]
> So what I could do is, I would disable that code and push a snapshot to maven central that you could test with. Is that worth trying?

If there was an "HTML Only" mode, that would help. That is, any embedded scripts or stylesheets would be treated much the same as comments (validated only for html termination of the block). In such a case, not instantiating any CSS or Javascript parser might avoid the issue, yes. 

My use case is that I'm building a content management system on top of Play Framework and I use nu.validator to ensure that the HTML5 content I'm generating is valid. I'm not as concerned with the Javascript or CSS as they come into play in different parts of the system and are checked/validated at build time. Only the HTML is dynamic.

**Comment by reid-spencer** [comment]
@sideshowbarker - This has bitten me again (sorry for the delay in response) so, yes, it is worth trying and I would be happy to validate that workaround here.

**Comment by sideshowbarker** [comment]
> @sideshowbarker - This has bitten me again (sorry for the delay in response) so, yes, it is worth trying and I would be happy to validate that workaround here.

OK, will make a change soonish and push a snapshot to maven central to try

**Comment by reid-spencer** [comment]
Thank you. I started down a road of trying to find a workaround but discovered SimpleDocumentValidator to not be amenable to easy extension. Not knowing what I'm doing in your code base doesn't help much either :)

**Comment by sideshowbarker** [comment]
I pushed a snapshot to https://oss.sonatype.org/content/repositories/snapshots/nu/validator/validator/16.3.3-SNAPSHOT/ and will be pushing a new stable release to maven central soon.
