### ISSUE TITLE
Gradle?

### ISSUE THREAD

**Issue by tomasbjerre** [validator/validator#21]
I started working on Gradle-scripts for building the Nu Validator. Check my fork for current progress. It is far from done! Is this something that you want? If not, I'll find something else to work on =) But if you want it I'll continue. 

There are many reasons for using Gradle. For example new comitters will get into the code faster as they will recognize how the code is being built. Any problem with the build process can be googled...

**Comment by sideshowbarker** [comment]
I’d be happy to consider a patch for this if/when there is one. I’m not interested in replacing the python build script we’re already using, but I could imagine it being possible to have a parallel gradle build script for those who wanted it.

Anyway, for now I’m gonna go ahead and close this issue. If/when there’s code for this, of course please raise a PR.
