### ISSUE TITLE
Typo in typemustmatch message

### ISSUE THREAD

**Issue by dd8** [validator/validator#214]
else if ("object" == localName) {
                if (atts.getIndex("", "typemustmatch") >= 0) {
                    if ((atts.getIndex("", "data") < 0)
                            || (atts.getIndex("", "type") < 0)) {
                        {
                            err("Element \u201Cobject\u201D must not have"
                                    + " attribute \u201Ctypemustmatch\u201D unless"
                                    + " both attribute \u201Cdata\u201D"
                                    + " and attribute \u201Csrc\u201D are also specified.");
                        }
                    }
                }
            }

Think message should say "both attribute data and attribute type"  instead of "both attribute data and attribute src"

**Comment by sideshowbarker** [comment]
Thanks for catching this. The fix is now live at https://validator.w3.org/nu/ and will be in the next release of the jar file (soon).

**Comment by dd8** [comment]
Should get round to SVG-in-HTML test suite additions soon. Planning to produce these by script from existing SVG test suite, then add some hand-crafted failures. Want to avoid adding more dependencies. Would Python work best with existing toolchain?

**Comment by sideshowbarker** [comment]
> Should get round to SVG-in-HTML test suite additions soon. Planning to produce these by script from existing SVG test suite, then add some hand-crafted failures. Want to avoid adding more dependencies. Would Python work best with existing toolchain?

Yes, definitely Python
