### ISSUE TITLE
Should type attribute should be optional for <script> in SVG?

### ISSUE THREAD

**Issue by dd8** [validator/validator#217]
SVG 1.1 2nd edition spec says 
"If a ‘type’ is not provided, the value of ‘contentScriptType’ on the ‘svg’ element shall be used, which in turn defaults to "application/ecmascript". 
http://www.w3.org/TR/SVG/script.html#ScriptElement

HTML5 4.8.18 SVG says
"The following features from SVG 1.1 must not be implemented ... The contentScriptType and contentStyleType attributes (use the type attribute on the script and style elements instead)"

There's 2 alternative interpretations of this:

1) type is mandatory in embedded SVG because there's no default (which seems unlikely in real-world implementations)
2) type is optional in embedded SVG, and defaults to "application/ecmascript" like script elements in HTML

Changing this is simple in svg-script.rnc:

- change:       attribute type { ContentType.datatype }
- to:        attribute type { ContentType.datatype }?

**Comment by sideshowbarker** [comment]
Thanks, fixed in the sources and pushed to https://checker.html5.org/ and https://validator.w3.org/nu/
