### ISSUE TITLE
Eclipse .project file missing from repository

### ISSUE THREAD

**Issue by scop** [validator/validator#220]
The Eclipse ```.project``` file appears to be intentionally missing from the repository (it's listed in ```.gitignore```). I wonder why, because on the other hand, other Eclipse specific files such as stuff in ```.settings```, and ```.classpath```, are there, and having the project file there as well would make it easier to import the project in Eclipse?

**Comment by sideshowbarker** [comment]
I can’t think of any good reason why I hadn’t added it, nor any good reason why it shouldn’t be added, so I’ve gone ahead and checked it in.
