### ISSUE TITLE
Documentation: broken link "Basic example using jQuery"

### ISSUE THREAD

**Issue by hhubik** [validator/validator#227]
The link to "Basic example using jQuery" at the bottom of the page https://wiki.whatwg.org/wiki/Validator.nu_Web_Service_Interface is broken as of today. The link target URL https://gist.github.com/gists/3902535 generates 404 error.

**Comment by sideshowbarker** [comment]
> The link to "Basic example using jQuery"… The link target URL https://gist.github.com/gists/3902535 generates 404 error.

Thanks, I’ve fixed that by copying in the JavaScript source:

https://github.com/validator/validator/wiki/Service:-HTTP-interface#cors-example

If that’s not the fix you had in mind, feel free to comment or re-open this.

**Comment by hhubik** [comment]
Looks good. Thanks!
-----Original Message----- From: "Michael[tm] Smith" Sent: Jan 19, 2016 9:22 PM To: validator/validator Cc: hhubik Subject: Re: [validator] Documentation: broken link "Basic example using jQuery" (#227) 

The link to "Basic example using jQuery"… The link target URL https://gist.github.com/gists/3902535 generates 404 error.
Thanks, I’ve fixed that by copying in the JavaScript source:
https://github.com/validator/validator/wiki/Service:-HTTP-interface#cors-example
If that’s not the fix you had in mind, feel free to comment or re-open this.
