### ISSUE TITLE
Make a Dockerfile

### ISSUE THREAD

**Issue by rwhogg** [validator/validator#229]
To make Validator easier to use, it would be nice to provide a Dockerfile. I've spun this issue off from #206 as it's peripheral to that discussion.

I've got a Dockerfile based on Debian+OpenJDK 8+Tomcat at https://github.com/rwhogg/validator/tree/dockerfile if you would like to use it.

**Comment by jaimeiniesta** [comment]
Having an official Dockerfile would be a great help - here's another one:

https://github.com/sitevalidator/nu-cat

**Comment by jarodium** [comment]
Hello,
Is it also possible to provide a tutorial for setting up a openshift cartridge to be setup on a node based application? Just like you did for herokup deployment in the wiki?

**Comment by sideshowbarker** [comment]
> Is it also possible to provide a tutorial for setting up a openshift cartridge to be setup on a node based application? Just like you did for herokup deployment in the wiki?

It’s a wiki, so somebody who knows about openshift could contribute something to the wiki.

**Comment by sideshowbarker** [comment]
A Dockerfile for the checker has been published at https://hub.docker.com/r/validator/validator/ and gets updated each time anything is pushed to the master branch of this repo. So I’m gonna go ahead and close this issue out.
