### ISSUE TITLE
Add option to validate all specified files

### ISSUE THREAD

**Issue by jzaefferer** [validator/validator#23]
The validator currently ignores files that don't match the `html` or `xhtml` extensions. That makes sense when crawling directories. For the grunt-html plugin, which resolves files and only passes a list of specific files as argument, an option to check all files independent of their extension would allow validating other formats.

See also https://github.com/jzaefferer/grunt-html/issues/37#issuecomment-68885308

**Comment by rwhogg** [comment]
I'm working on a Maven plugin - this would be very useful for me too.

**Comment by sideshowbarker** [comment]
I just released a new version of vnu.jar: https://github.com/validator/validator/releases/tag/20150216

This change alters the default handling of non-HTML files. Before by default it skipped any documents without .html, .htm, .xhtml, or .xht extensions; instead now by default all documents that are found are checked, regardless of extension. I added a new `--skip-non-html` option to provide the old default behavior— that is, to causes any files without .html, .htm, .xhtml, or .xht extensions to be skipped.

Please test and let me know if it's not working as expected.
