### ISSUE TITLE
ERROR A charset attribute on a meta element found after the first 512 bytes

### ISSUE THREAD

**Issue by zimorodokan** [validator/validator#232]
HTML5 Standart says «The element containing the character encoding declaration must be serialized completely within the first 1024 bytes of the document.» https://www.w3.org/TR/html5/document-metadata.html#character-encoding-declaration

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. The fix is now live at https://validator.w3.org/nu/
