### ISSUE TITLE
Warning for <details> does not mention using a polyfill

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#233]
"Warning: The details element is not supported properly by browsers yet. It would probably be better to wait for implementations."

vs

"Warning: The color input type is not supported in all browsers. Please be sure to test, and consider using a polyfill."

Suggest recasting warning for details in same stayle as for that of 'color' input

**Comment by sideshowbarker** [comment]
Thanks—pushed to https://validator.w3.org/nu/
