### ISSUE TITLE
Multiple character encoding <meta>s should be an error

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#236]
See https://www.w3.org/Bugs/Public/show_bug.cgi?id=20743
The example given therein still repros with https://validator.w3.org/nu/

**Comment by ROBPY** [comment]
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<p></p>
</body>
</html>

**Comment by sideshowbarker** [comment]
So I think we are looking are two relevant requirements here:

* [There must not be more than one meta element with a charset attribute per document.](https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-charset)

* [A document must not contain both a meta element with an http-equiv attribute in the Encoding declaration state and a meta element with the charset attribute present.](https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-content-type)
