### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Pageboy** [validator/validator#237]
The validator exhibits fatal error if file upload is used from the home page but does not if the the file upload is used on the secondary page (I mean the results page you get that reports the error).
![screenshot 2016-02-04 16 26 30](https://cloud.githubusercontent.com/assets/619455/12821674/41ef76bc-cb5c-11e5-8ed5-7be194b2fca6.png)
and then
![screenshot 2016-02-04 16 26 58](https://cloud.githubusercontent.com/assets/619455/12821673/41cf7bfa-cb5c-11e5-8262-682d6d4459da.png)

**Comment by sideshowbarker** [comment]
The solution is to use the https://validator.w3.org/nu/ page directly from now on. It is in fact the primary entry point. The https://validator.w3.org/ page is in practice now a secondary legacy entry point that is essentially being deprecated. And so at this point any bugs with how that legacy entry point behaves are not a high priority.
