### ISSUE TITLE
site-relative absolute-path links

### ISSUE THREAD

**Issue by ikar-us** [validator/validator#245]
I use to write `<img src="/path/within/site/image.png">` .
Browsers resolve this as expected. Google's bots and check tools resolve it as expected.
The validator's image report says these images are "not resolvable".
Is this a bug in the validator or in common HTML usage?

**Comment by sideshowbarker** [comment]
Please post a URL/document I can check with.

**Comment by ikar-us** [comment]
I noticed with this page:
https://validator.nu/?doc=http%3A%2F%2Fwofea.in%2FJames_Stanton_about&showimagereport=yes

**Comment by ikar-us** [comment]
Now I founbd that my first idea was wrong.
It simply doesn't resolve anything without protocol given.
Test page: http://ikar.us/path/img.html 
https://validator.nu/?doc=http%3A%2F%2Fikar.us%2Fpath%2Fimg.html&showimagereport=yes

**Comment by sideshowbarker** [comment]
Yeah, thanks for catching this. I can reproduce it—it’s definitely a bug. Basically it doesn’t work at all any more, as far as actually showing the images. Will try to figure out when/how I broke it.
