### ISSUE TITLE
Emit errors for use of rel=copyright and any other old rel keywords that are synonyms for current keywords

### ISSUE THREAD

**Issue by sideshowbarker** [validator/validator#254]
See http://stackoverflow.com/questions/35645360/are-attribute-values-like-contents-glossary-for-rel-attribute-deprecated/35645679#35645679

The spec states that where it lists synonyms for any of the predefined `rel` keywords, those synonyms “are to be handled as specified by user agents, but must not be used in documents”.

So we should emit an error for `rel=copyright`.

**Comment by xfq** [comment]
I'm trying to solve this issue. @sideshowbarker Can you point me in the right direction?

I have found some files that may relate to the issue: [Assertions.java](https://github.com/validator/validator/blob/master/src/nu/validator/checker/schematronequiv/Assertions.java) / [AbstractRel.java](https://github.com/validator/validator/blob/master/src/nu/validator/datatype/AbstractRel.java) / [ARel.java](https://github.com/validator/validator/blob/master/src/nu/validator/datatype/ARel.java) / [LinkRel.java](https://github.com/validator/validator/blob/master/src/nu/validator/datatype/LinkRel.java). Currently, `<a rel="copyright">` will not report any error/warning, but `<a rel="ccopyrighttt">` will. Where/How is it checked?

**Comment by sideshowbarker** [comment]
The` ARel.java` and `LinkRel.java` files would be the places to do the extra checking for this, I think. If you need more specific suggestions on how to tackle it, would probably work best to chat somewhere in real time—e.g., #whatwg IRC, or https://gitter.im/sideshowbarker

**Comment by xfq** [comment]
OK, we can chat on Gitter.
