### ISSUE TITLE
Start tag body seen but an element of the same type was already open.

### ISSUE THREAD

**Issue by KyleJosef** [validator/validator#255]
I validated my HTML for my website and it came up with this problem, I tried to solve it but I keep failing. Can someone please explain to the problem and come up with a solution?

This is my HTML code:

<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8" />
		<title>SpaceScience.com</title>
		<link href="divisions.css" rel="stylesheet" type="text/css" />
	</head>
		<div id="container"> 
			<header>
				<img src="images/SSLogo%20v5.png" alt="Image%20of%20SpaceScience.com%20logo" width="150" height="110">
				<nav role="navigation"> 
					<ul> 
						<li><a href="Home.html">Home</a></li>
						<li><a href="About.html">About</a></li>
						<li><a href="Contact.html">Contact</a></li>
					</ul> 
				</nav> 
			</header>

			<audio autoplay="autoplay" loop="loop">
				<source src="Audio/ufo_landing.mp3" type="audio/mpeg"> 
				<source src="Audio/ufo_landing.ogg" type="audio/ogg"> 
			</audio>

		<body>
					
				<div id="sidebar"> 
						<aside role="complementary"> 
						<h1>More about...</h1>
						<nav role="navigation" title="Related sites"> 
							<div class="menu">
								<h2>Space</h2>
								<a href="http://www.nasa.gov/">Nasa</a>
								<a href="http://www.space.com/">Space.com</a>
								<a href="http://www.spacedaily.com/">Space Daily</a>
							</div>
						
						
						<div class="menu">
							<h2>Science</h2>
							<a href="http://www.science%20channel.com/">Science Channel</a>
							<a href="http://www.science%20daily.com/">Science Daily</a>
							<a href="http://www.science%20news.com/">Science News</a>
						</div>
						
						
						<div class="menu">
							<h2>Studying Planetary and Space Science</h2>
							<a href="http://www.otago%20university.com/">Otago University</a>
							<a href="http://www.waikato%20university.com/">Waikato University</a>
							<a href="http://www.victoria%20university.com">Victoria University</a>
						</div>
						
						</nav> 
					</aside> 
					
				</div>	
					
					<div id="content"> 
						<section id="intro"> 
							<p>Welcome to SpaceScience.Com</p>
						</section> 
						
						<section id="main"> 
							<h1>Which space topic captivates you?</h1>
								<ul id="toc" title="Website contents">
									
										<li><a href="SolarSystem.html">The Solar System - Our Place in Space</a></li>
										<img src="images/SolarSystem.jpg" alt="SolarSystem" width="150" height="110">
								
									<div id="content_2">
										<li><a href="Aliens.html">Are We Alone? The Search for Life on Other Planets</a></li>
										<img src="images/Alien.jpg" alt="Alien" width="150" height="110">
									</div>
									<div id="content_3">
										<li><a href="SpaceThreats.html">Apocalypse Now? Threats from Space</a></li>
										<img src="images/armageddon.jpg" alt="Armageddon" width="150" height="110">
									</div>
								</ul>
						</section> 
					</div>
					
					
					<footer>
						<nav role="navigation"> 
						
								<div id="twitter">
								<h4>Get watching...</h4>
									<li title="Follow us on Twitter"></li>
									<a href="http://twitter.com/spacescience.com"><img src="images/twitter.jpg" alt="twitter"></a>
								
								</div>
								<div id="facebook">
								<h4>Get Friendly...</h4>
									<li title="Like us on Facebook"></li>
									<a href="http://facebook.com/spacescience.com"><img src="images/facebook.jpg" alt="Facebook Logo"></a>
								
								</div>
								<div id="vimeo">
								<h4>Get following...</h4>
									<li title="Watch our videos on Vimeo"></li>
									<a href="http://vimeo.com/spacescience.com"><img src="images/vimeo.jpg" alt="Vimeo Icon"></a>
									
								
								</div>
							
						</nav>
						<div class="small">
							<h5><small>&copy; 2012 Angela Snel and Mitchel Wang
							</small></h5>
						</div>
						
					</footer> 
		</div>
	</body>

</html>

**Comment by cvrebert** [comment]
Your opening `<body>` tag, which you currently have directly before
`<div id="sidebar"> <!--start of sidebar container-->`
should instead come directly before your
`<div id="container"> <!--Start of page container-->`.

**Comment by KyleJosef** [comment]
I don't understand, the <body> tag is directly before <div id="sidebar">

**Comment by cvrebert** [comment]
It should be before the **page** container, *not* the *sidebar* container.

**Comment by KyleJosef** [comment]
Oh ok

**Comment by KyleJosef** [comment]
Thanks for the help!!

**Comment by cvrebert** [comment]
In other words, the very next thing after `</head>` should be `<body>`.

**Comment by ldcwoodir** [comment]
I validated my wordpress for my website and it came up with this problem, I tried to solve it but I keep failing. Can someone please explain to the problem and come up with a solution?
This is my HTML code:
<?php
/**
 * The header for our theme.
 *
 * Displays all of the <head> section and everything up till <div id="content">
 *
 * @package Sydney
 */
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-3232525101388979",
    enable_page_level_ads: true
  });
</script>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
<?php if ( ! function_exists( 'has_site_icon' ) || ! has_site_icon() ) : ?>
	<?php if ( get_theme_mod('site_favicon') ) : ?>
		<link rel="shortcut icon" href="<?php echo esc_url(get_theme_mod('site_favicon')); ?>" />
	<?php endif; ?>
<?php endif; ?>
<?php wp_head(); ?>

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W8PN789');</script>

<meta name="msvalidate.01" content="7791D9C1F13C9D493ACB1BAF76FD84DB" />
</head>
<body <?php body_class(); ?>>

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W8PN789"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<?php do_action('sydney_before_site'); //Hooked: sydney_preloader() ?>

<div id="page" class="hfeed site">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'sydney' ); ?></a>
	<?php do_action('sydney_before_header'); //Hooked: sydney_header_clone() ?>
	<header id="masthead" class="site-header" >
		<div class="header-wrap">
            <div class="container">
                <div class="row">
				<div class="col-md-4 col-sm-8 col-xs-12">
		        <?php if ( get_theme_mod('site_logo') ) : ?>
					<a href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php bloginfo('name'); ?>"><img class="site-logo" src="<?php echo esc_url(get_theme_mod('site_logo')); ?>" alt="<?php bloginfo('name'); ?>" /></a>
		        <?php else : ?>
					<h1 class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></h1>
					<h2 class="site-description"><?php bloginfo( 'description' ); ?></h2>	        
		        <?php endif; ?>
				</div>
				<div class="col-md-8 col-sm-4 col-xs-12">
					<div class="btn-menu"></div>
					<nav id="mainnav" class="mainnav" >
						<?php wp_nav_menu( array( 'theme_location' => 'primary', 'fallback_cb' => 'sydney_menu_fallback' ) ); ?>
					</nav>
				</div>
				</div>
			</div>
		</div>
	</header>
	<?php do_action('sydney_after_header'); ?>

	<div class="sydney-hero-area">
		<?php sydney_slider_template(); ?>
		<div class="header-image">
			<?php sydney_header_overlay(); ?>
			<img class="header-inner" src="<?php header_image(); ?>" width="<?php echo esc_attr( get_custom_header()->width ); ?>" alt="<?php bloginfo('name'); ?>"title="<?php bloginfo('name'); ?>" >
		</div>
		<?php sydney_header_video(); ?>

		<?php do_action('sydney_inside_hero'); ?>
	</div>

	<?php do_action('sydney_after_hero'); ?>

	<div id="content" class="page-wrap">
		<div class="container content-wrapper">
			<div class="row">
</div>
</body>

**Comment by ldcwoodir** [comment]
I validated my wordpress for my website and it came up with this problem, I tried to solve it but I keep failing. Can someone please explain to the problem and come up with a solution?

This is my HTML code:
<?php
/**
 * The header for our theme.
 *
 * Displays all of the <head> section and everything up till <div id="content">
 *
 * @package Sydney
 */
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-3232525101388979",
    enable_page_level_ads: true
  });
</script>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
<?php if ( ! function_exists( 'has_site_icon' ) || ! has_site_icon() ) : ?>
	<?php if ( get_theme_mod('site_favicon') ) : ?>
		<link rel="shortcut icon" href="<?php echo esc_url(get_theme_mod('site_favicon')); ?>" />
	<?php endif; ?>
<?php endif; ?>
<?php wp_head(); ?>

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W8PN789');</script>

<meta name="msvalidate.01" content="7791D9C1F13C9D493ACB1BAF76FD84DB" />
</head>
<body <?php body_class(); ?>>

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W8PN789"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<?php do_action('sydney_before_site'); //Hooked: sydney_preloader() ?>

<div id="page" class="hfeed site">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'sydney' ); ?></a>
	<?php do_action('sydney_before_header'); //Hooked: sydney_header_clone() ?>
	<header id="masthead" class="site-header" >
		<div class="header-wrap">
            <div class="container">
                <div class="row">
				<div class="col-md-4 col-sm-8 col-xs-12">
		        <?php if ( get_theme_mod('site_logo') ) : ?>
					<a href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php bloginfo('name'); ?>"><img class="site-logo" src="<?php echo esc_url(get_theme_mod('site_logo')); ?>" alt="<?php bloginfo('name'); ?>" /></a>
		        <?php else : ?>
					<h1 class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></h1>
					<h2 class="site-description"><?php bloginfo( 'description' ); ?></h2>	        
		        <?php endif; ?>
				</div>
				<div class="col-md-8 col-sm-4 col-xs-12">
					<div class="btn-menu"></div>
					<nav id="mainnav" class="mainnav" >
						<?php wp_nav_menu( array( 'theme_location' => 'primary', 'fallback_cb' => 'sydney_menu_fallback' ) ); ?>
					</nav>
				</div>
				</div>
			</div>
		</div>
	</header>
	<?php do_action('sydney_after_header'); ?>

	<div class="sydney-hero-area">
		<?php sydney_slider_template(); ?>
		<div class="header-image">
			<?php sydney_header_overlay(); ?>
			<img class="header-inner" src="<?php header_image(); ?>" width="<?php echo esc_attr( get_custom_header()->width ); ?>" alt="<?php bloginfo('name'); ?>"title="<?php bloginfo('name'); ?>" >
		</div>
		<?php sydney_header_video(); ?>

		<?php do_action('sydney_inside_hero'); ?>
	</div>

	<?php do_action('sydney_after_hero'); ?>

	<div id="content" class="page-wrap">
		<div class="container content-wrapper">
			<div class="row">
</div>
</body>

**Comment by ldcwoodir** [comment]
I validated my HTML for my website and it came up with this problem, I tried to solve it but I keep failing. Can someone please explain to the problem and come up with a solution?

This is my HTML code:
> <?php
> /**
>  * The header for our theme.
>  *
>  * Displays all of the <head> section and everything up till <div id="content">
>  *
>  * @package Sydney
>  */
> ?><!DOCTYPE html>
> <html <?php language_attributes(); ?>>
> <head>
> <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
> <script>
>   (adsbygoogle = window.adsbygoogle || []).push({
>     google_ad_client: "ca-pub-3232525101388979",
>     enable_page_level_ads: true
>   });
> </script>
> <meta charset="<?php bloginfo( 'charset' ); ?>">
> <meta name="viewport" content="width=device-width, initial-scale=1">
> <link rel="profile" href="http://gmpg.org/xfn/11">
> <link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
> <?php if ( ! function_exists( 'has_site_icon' ) || ! has_site_icon() ) : ?>
> 	<?php if ( get_theme_mod('site_favicon') ) : ?>
> 		<link rel="shortcut icon" href="<?php echo esc_url(get_theme_mod('site_favicon')); ?>" />
> 	<?php endif; ?>
> <?php endif; ?>
> <?php wp_head(); ?>
> 
> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
> new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
> j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
> 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
> })(window,document,'script','dataLayer','GTM-W8PN789');</script>
> 
> <meta name="msvalidate.01" content="7791D9C1F13C9D493ACB1BAF76FD84DB" />
> </head>
> <body <?php body_class(); ?>>
> 
> <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W8PN789"
> height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
> 
> <?php do_action('sydney_before_site'); //Hooked: sydney_preloader() ?>
> 
> <div id="page" class="hfeed site">
> 	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'sydney' ); ?></a>
> 	<?php do_action('sydney_before_header'); //Hooked: sydney_header_clone() ?>
> 	<header id="masthead" class="site-header" >
> 		<div class="header-wrap">
>             <div class="container">
>                 <div class="row">
> 				<div class="col-md-4 col-sm-8 col-xs-12">
> 		        <?php if ( get_theme_mod('site_logo') ) : ?>
> 					<a href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php bloginfo('name'); ?>"><img class="site-logo" src="<?php echo esc_url(get_theme_mod('site_logo')); ?>" alt="<?php bloginfo('name'); ?>" /></a>
> 		        <?php else : ?>
> 					<h1 class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></h1>
> 					<h2 class="site-description"><?php bloginfo( 'description' ); ?></h2>	        
> 		        <?php endif; ?>
> 				</div>
> 				<div class="col-md-8 col-sm-4 col-xs-12">
> 					<div class="btn-menu"></div>
> 					<nav id="mainnav" class="mainnav" >
> 						<?php wp_nav_menu( array( 'theme_location' => 'primary', 'fallback_cb' => 'sydney_menu_fallback' ) ); ?>
> 					</nav>
> 				</div>
> 				</div>
> 			</div>
> 		</div>
> 	</header>
> 	<?php do_action('sydney_after_header'); ?>
> 
> 	<div class="sydney-hero-area">
> 		<?php sydney_slider_template(); ?>
> 		<div class="header-image">
> 			<?php sydney_header_overlay(); ?>
> 			<img class="header-inner" src="<?php header_image(); ?>" width="<?php echo esc_attr( get_custom_header()->width ); ?>" alt="<?php bloginfo('name'); ?>"title="<?php bloginfo('name'); ?>" >
> 		</div>
> 		<?php sydney_header_video(); ?>
> 
> 		<?php do_action('sydney_inside_hero'); ?>
> 	</div>
> 
> 	<?php do_action('sydney_after_hero'); ?>
> 
> 	<div id="content" class="page-wrap">
> 		<div class="container content-wrapper">
> 			<div class="row">
> </div>
> </body>

**Comment by ldcwoodir** [comment]
I validated my HTML for my website and it came up with this problem, I tried to solve it but I keep failing. Can someone please explain to the problem and come up with a solution?

This is my HTML code:
```
<?php
/**
 * The header for our theme.
 *
 * Displays all of the <head> section and everything up till <div id="content">
 *
 * @package Sydney
 */
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-3232525101388979",
    enable_page_level_ads: true
  });
</script>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
<?php if ( ! function_exists( 'has_site_icon' ) || ! has_site_icon() ) : ?>
	<?php if ( get_theme_mod('site_favicon') ) : ?>
		<link rel="shortcut icon" href="<?php echo esc_url(get_theme_mod('site_favicon')); ?>" />
	<?php endif; ?>
<?php endif; ?>
<?php wp_head(); ?>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W8PN789');</script>
<!-- End Google Tag Manager -->
<meta name="msvalidate.01" content="7791D9C1F13C9D493ACB1BAF76FD84DB" />
</head>
<body <?php body_class(); ?>>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W8PN789"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<?php do_action('sydney_before_site'); //Hooked: sydney_preloader() ?>

<div id="page" class="hfeed site">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'sydney' ); ?></a>
	<?php do_action('sydney_before_header'); //Hooked: sydney_header_clone() ?>
	<header id="masthead" class="site-header" >
		<div class="header-wrap">
            <div class="container">
                <div class="row">
				<div class="col-md-4 col-sm-8 col-xs-12">
		        <?php if ( get_theme_mod('site_logo') ) : ?>
					<a href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php bloginfo('name'); ?>"><img class="site-logo" src="<?php echo esc_url(get_theme_mod('site_logo')); ?>" alt="<?php bloginfo('name'); ?>" /></a>
		        <?php else : ?>
					<h1 class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></h1>
					<h2 class="site-description"><?php bloginfo( 'description' ); ?></h2>	        
		        <?php endif; ?>
				</div>
				<div class="col-md-8 col-sm-4 col-xs-12">
					<div class="btn-menu"></div>
					<nav id="mainnav" class="mainnav" >
						<?php wp_nav_menu( array( 'theme_location' => 'primary', 'fallback_cb' => 'sydney_menu_fallback' ) ); ?>
					</nav><!-- #site-navigation -->
				</div>
				</div>
			</div>
		</div>
	</header><!-- #masthead -->
	<?php do_action('sydney_after_header'); ?>

	<div class="sydney-hero-area">
		<?php sydney_slider_template(); ?>
		<div class="header-image">
			<?php sydney_header_overlay(); ?>
			<img class="header-inner" src="<?php header_image(); ?>" width="<?php echo esc_attr( get_custom_header()->width ); ?>" alt="<?php bloginfo('name'); ?>"title="<?php bloginfo('name'); ?>" >
		</div>
		<?php sydney_header_video(); ?>

		<?php do_action('sydney_inside_hero'); ?>
	</div>

	<?php do_action('sydney_after_hero'); ?>

	<div id="content" class="page-wrap">
		<div class="container content-wrapper">
			<div class="row">
</div>
</body>
```

**Comment by kishensd** [comment]
I tried validating my code but it shows me this error
![Sceen](https://user-images.githubusercontent.com/52025623/60776921-fffa3c80-a161-11e9-9f06-60433cb08d33.PNG)


<!DOCTYPE html>
<html>

<meta charset="utf-8">

<head>
	<title>Bookworm Library</title>
	<link rel = "icon" href = "icon.png" type = "image/x-icon"> 
</head>

<body>
	<header>
		<link rel="stylesheet" type="text/css" href="1.css">
		<div class="logo">
		<a href="index.html"><img src="logo.png" alt="logo">
		
		<div class="container">
			<nav>
				
				<ul>
					<li><a>Home</a></li>
					<li><a>Books</a>
						<ul>
							<li><a href="Fiction.html">Fiction</a></li>
							<li><a href="Non-Fiction.html">Non-Fiction</a></li>
						</ul>
					</li>
					<li><a>Research Papers</a>
						<ul>
							<li><a href="Monography.html">Monography</a></li>
							<li><a href="ResearchByPublication.html">Research by Publication</a></li>
						</ul>
					</li>
					<li><a>Journals</a>
						<ul>
							<li><a href="Magazines.html">Magazines</a></li>
							<li><a href="Newspapers.html">Newspapers</a></li>
						</ul>
					</li>
					<li><a>Table of Books</a>
						<ul>
							<li><a href="NoOfBooks.html">Tabular Data</a></li>
						</ul>
					</li>
					<li><a>Feedback</a>
						<ul>
							<li><a href="Feedback.html">Form</a></li>
						</ul>
					</li>
				</ul>
			</nav>
		</div>
	</header>
</body>
<div class="box">
	<form>
		<input type="text" name="" placeholder="Type..">
		<input type="submit" name="" value="Search">
	</form>

</div>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="example">
	<h1>ABOUT US</h1>
	<p>Bookworm, the name of our Website isn't just a web-based system likewise an absolute administration arrangement of our library system. It gives subtleties data on different Books, Research Papers, articles and journals.</p>
	<p>Since present day period of science is conquered by internet and PC’s. Current PC framework gives the clients every part of life. Along these lines, we take great pleasure in working in this field to get the data effectively delivered to the users.We are going to make a best library site which will be so valuable to the students and educators of our HELP University.</p>

</div>
</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="logout">
	<form action="NewLogin.html">
		<input type="submit" name="" value="Logout">
	</form>
</div>
</body>

<footer>
	<div class="footer">
		<p>About Us</p>
		<p><address><a href="mailto:bookwormlibrary01">Email us</a></p>
		<p>HAVE A GREAT DAY READING !</p>
		
	</div>
</footer>


</html>

**Comment by speedyhoon** [comment]
@kishensd
- Tag `<meta charset="utf-8">` needs to be moved inside the head tag. Head opening and closing tags are optional, so the validator is telling you that the head tag has been implicitly opened by `<meta>` on line 4 and you're trying to insert another `<head>` tag on line 6.
- Tag `<a href="index.html">` isn't closed before `<div class="container">`. A tags aren't allowed to contain block content (div's).
