### ISSUE TITLE
Bad value http://www.science%20channel.com/ for attribute href on element a: Invalid host: Illegal character in domain: space is not allowed.

### ISSUE THREAD

**Issue by KyleJosef** [validator/validator#256]
I saw this while validating my website, i replaced the spaces with %20 but it still keeps coming up. Can someone please find a solution to my problem?

From line 48, column 8; to line 48, column 49
a>↩							<a href="http://www.science%20daily.com/">Scienc
Syntax of URL:
Any URL. For example: /hello, #canvas, or http://example.org/. Characters should be represented in NFC and spaces should be escaped as %20. Common non-alphanumeric characters other than ! $ & ' ( ) * +  - . / : ; = ? @ _ ~ generally must be percent-encoded. For example, the pipe character (|) must be encoded as %7C.

**Comment by cvrebert** [comment]
May I recommend that you such questions on [StackOverflow](http://stackoverflow.com/questions/tagged/html) instead?

**Comment by KyleJosef** [comment]
Ok I will

**Comment by sideshowbarker** [comment]
It’s fine to ask these questions here too but I think the @cvrebert was making is that you’re likely to get more help asking on StackOverflow, and another advantage is that both your questions and the answers will get more visibility there and so end up being more helpful to other users.

But the short answer on this is that if you’ve already replaced all the spaces then the problem must be another character that must be percent-encoded but isn’t. So the solution is to look through the URL for any characters other than alphanumerics or ` ! $ & ' ( ) * + - . / : ; = ? @ _ ~` and percent-encode them.

**Comment by KyleJosef** [comment]
ok thanks

**Comment by sideshowbarker** [comment]
By the way, I realize now I misread your issue initially. A space is never allowed in the domain-name part of a URL—even if you percent-encode it. `www.science%20channel.com` clearly can’t be a real domain.
