### ISSUE TITLE
Did not check for body tag

### ISSUE THREAD

**Issue by dalerrogers** [validator/validator#259]
I teach HTML/CSS. Was validating a student's page. They left out the body element completely. I was surprised to find the validator came back with no errors or warnings. The body section is a required element. Certainly that has not changed.

**Comment by stevefaulkner** [comment]
>**Tag omission in text/html:**
A body element’s start tag may be omitted if the element is empty, or if the first thing inside the body element is not a space character or a comment, except if the first thing inside the body element is a meta, link, script, style, or template element.
> 
> A body element’s end tag may be omitted if the body element is not immediately followed by a comment.

https://w3c.github.io/html/sections.html#the-body-element

**Comment by dalerrogers** [comment]
Thanks. I learned something. I check with the w3.org before posting again.

Dale R Rogers, M.Ed.
Assistant Professor, Multimedia Design
Visual Communications
Nashville State Community College
ofc: dale.rogers@nscc.edu
personal: dale@dalerogers.me
web: www.dalerogers.me
linkedin: https://www.linkedin.com/in/dalerrogers

**Comment by stevefaulkner** [comment]
@dalerrogers no worries, yes it's best to check the HTML spec, but yes sometimes the requirements can be surprising. This article [HTML5 – Check it Before you Wreck it](http://html5doctor.com/html5-check-it-before-you-wreck-it-with-miketm-smith/) may be of interest.
