### ISSUE TITLE
aria-label is allowed on section

### ISSUE THREAD

**Issue by dstorey** [validator/validator#261]
I get the following validator error:

Error: Attribute arial-label not allowed on element section at this point.
From line 1, column 9411; to line 1, column 9527
nt--home"><section role="region" arial-label="recent activity" …

Attributes for element section:
Global attributes

But this isn't the case. Section allows global aria attributes of which aria-label is one:
http://w3c.github.io/html/single-page.html#global-aria--attributes

There is also a section in the HTML to accessibility mapping spec that includes section and grouping elements:
https://www.w3.org/TR/html-aam-1.0/#section-and-grouping-element-accessible-name-calculation

CC @sideshowbarker @stevefaulkner

**Comment by sideshowbarker** [comment]
> `<section role="region" arial-label="recent activity"`

You got `arial-` instead of `aria-` in there man. Which personally I like the sound of better myself but it’s hard for me to teach the checker to appreciate it

**Comment by dstorey** [comment]
@sideshowbarker so embarrassing. Should get more sleep. :/  I must have read it about 5 times and still not spotted…dyslexia playing up. In my defence I didn't write the code on that page.

**Comment by sideshowbarker** [comment]
No worries. I guess this is a case that suggests the checker really should implement some fuzzy matching like the legacy W3C markup validator does (or did)—so that the message would say:
> Attribute `arial-label` not allowed… Did you mean `aria-label`?

But I seem to recall that feature ended up getting dropped from the legacy validator for some reason (maybe just because it couldn’t guess that well, I dunno).

**Comment by dstorey** [comment]
yeah, close but no cigar checking would be good. When searching on GitHub, it is surprising how many typos you find in various API/css/html names.
