### ISSUE TITLE
Random blindness in validation.

### ISSUE THREAD

**Issue by StudentHtmlfunf** [validator/validator#264]
I've notice several times that certain html5 tags would not be fully seen. Sometimes it is the opening tag and sometimes the closing tag. This gets annoying especially when there is nothing to fix or correct on a html5 document. Tags in question as of now, are; \<div>\</div> this one comes into question when it is given an id. \<article>\</article> I don't fully understand why this one happens. I always ensure that my HTML5 is well written. Not only was there an issue with this validator randomly missing tags. There is also an issue with it parsing the wrong data type. Example. It parses HTML5 often as an XML document or as an HTML4.01 document. \<!DOCTYPE html> isn't a HTML4.01 document declaration.

**Comment by sideshowbarker** [comment]
Please post URLs for some documents that cause the checker behavior you describe.

> Example. It parses HTML5 often as an XML document or as an HTML4.01 document. \<!DOCTYPE html> isn't a HTML4.01 document declaration.

If you’re using the http://validator.w3.org/ frontend, don’t. Instead start from https://checker.html5.org/ or https://validator.w3.org/nu/ The only time either of those will ever parse your document as an XML document is if you serve it with an XML mime type. Neither of them will ever check your document as HTML4.01.

**Comment by sideshowbarker** [comment]
Closing due to lack of response from OP.
