### ISSUE TITLE
Developing a client for the v.Nu web service: blacklist validator.nu (et al)?

### ISSUE THREAD

**Issue by GrahamHannington** [validator/validator#265]
I have developed a working prototype Atom Editor Linter provider that uses the v.Nu HTTP interface (web service).

I am using this provider to validate XHTML documents "on-the-fly" as I edit them in Atom.

I am very happy, and a little giddy, riding on the shoulders of giants. Thank you.

However, before I make this provider publicly available as an Atom package, I thought I should at least raise the following question: **should I blacklist the public Validator.nu URLs?**

That is:

- The generic facet at https://validator.nu/
- The (X)HTML5 facet at https://html5.validator.nu/

(Are there any others?)

That is, should I, in the provider code, disallow those URLs? (Do I need to worry about blacklisting dotted-decimal IP address equivalents? I think the answer is "no", but I thought I'd check with you.)

By default, the Atom Linter triggers its providers every 300 milliseconds (0.3 seconds). According to my interpretation of the Validator.nu [terms of service](https://about.validator.nu/#tos), calling the public instance that often would be unreasonable (uncool).

But it's not quite that simple. Each provider can set its `lintOnFly` property to either `true` or `false`. I can probably expose that property as a user-configurable setting. While I think the most popular use case will be `true` (uncool to use the public v.Nu), `false` might, under some circumstances, be cool. (I think `false` might lint only on open and save, but I need to confirm that.)

Right now, I've got the v.Nu URL hardcoded to my local v.Nu instance at `http://localhost:8888`.

In case it occurs to you: I do not want to just whitelist, say, `localhost`, because I want to allow shared v.Nu instances.

My preference would be to not blacklist any URLs (especially if they're liable to change), and instead refer users to the Validator.nu terms of service.

**Your thoughts?**

If your answer is, "Yes, definitely, blacklist 'em" (even for `lintOnFly: false`?), then could you please list the URLs? (Or is it just those two "facets" I cited previously? If it's more, you could just add another HTTP API response to v.Nu, to return those URLs; but, yeah, that would be a non-trivial _just_ :smile:, so I'm not going to ask for that.)

## Why an Atom Editor Linter provider?

As @sideshowbarker knows, I have been [playing with the schemas from v.Nu](https://github.com/unsoup/validator) in various external tools, including editors. But the implementation-specific nature of the required datatype library irks me; it's proven to be a barrier, or at least a nuisance.

At the same time, I have noticed some colleagues (mostly, much younger colleagues) using the Atom Editor. Atom has an `xmllint` Lint provider, but I could not see any Atom package - Lint provider or otherwise - that refers to v.Nu.

A week or so ago, the idea landed in my head to develop an Atom Editor Lint provider that uses the v.Nu HTTP interface. No need for an external datatype library, because it's bound into v.Nu. You get the full benefit of v.Nu validation (including Schematron), not just the RELAX NG schemas. And, as long as the HTTP interface continues to be supported, it doesn't matter whether the underlying validation technology moves away from a RELAX NG schemas.

I started with a web page outside of Atom, but developed specifically for Chrome (for example, using the new-ish promise-based `fetch` API instead of `XMLHttpRequest`. I wondered whether performance would be an issue. Nope, so far so good; at least, on the relatively small files I've tested so far.

It's early days - I only got it working tonight - so I might yet hit some problems, but it's looking good.

I'm looking forward to trying the `schema` ("bring your own schema") parameter of the HTTP interface in this Linter provider. That will open a universe of validation possibilities for the Atom Editor.

**Comment by GrahamHannington** [comment]
@sideshowbarker,

FYI, a sample screen capture of "on the fly" v.Nu messages in Atom in a [comment I have just added to a related GitHub repo](https://github.com/steelbrain/linter/issues/878#issuecomment-201317144).

Here's another screen capture showing a v.Nu message as a tooltip:

![image](https://cloud.githubusercontent.com/assets/8519708/14046267/33cb37aa-f2db-11e5-9f30-67f5c7d31cec.png)

I plan to ask some colleagues to test the provider in the next few days, and then, if all is well, publish next week.

**Comment by sideshowbarker** [comment]
This looks extremely cool. Thanks for sharing info about it here. I think a lot of people are going to find it very useful.

As far as the question about blacklisting, I think it would be preferable if you or somebody else ran a specific separate instance of the checker somewhere that you could point this too (rather than pointing it to https://validator.nu/ or https://checker.html5.org/).

But it seems to me that what you are proposing is would actually not strictly be a violation of the ToS just as long as it doesn’t end up generating an excessive amount of requests. Of course judging what is excessive is subjective but I would that at least that after you make this available it’s not likely that it would generate a huge amount of traffic right away. So I think you could try it and see and if it does end up generating excessive requests, we could figure out how to deal with the problem.

**Comment by GrahamHannington** [comment]
@sideshowbarker,

FYI, I've published the Atom editor linter provider:

https://atom.io/packages/linter-vnu
