### ISSUE TITLE
Headings within DT element

### ISSUE THREAD

**Issue by massic80** [validator/validator#267]
Hi all,
I just tried validating a page where I inserted H£ tags within the DT element.
Validator says it's not allowed, but this page

https://www.w3.org/TR/html-markup/dt.html

doesn't specify why (on the inverse, it seems to allow my decision).
Which one is the correct hypothesis? :)
Massi

**Comment by cvrebert** [comment]
Per https://html.spec.whatwg.org/multipage/semantics.html#the-dt-element
> [Content model:](https://html.spec.whatwg.org/multipage/dom.html#concept-element-content-model)
> Flow content, but with no [...] heading content descendants.

Where ["heading content" is defined as](https://html.spec.whatwg.org/multipage/dom.html#heading-content-2) any of: h1, h2, h3, h4, h5, h6, hgroup

**Comment by cvrebert** [comment]
Regarding the document you cited:
> [This document has been discontinued and is only made available for historical purposes.](https://www.w3.org/TR/html-markup/Overview.html#abstract)

**Comment by massic80** [comment]
Whoops!
I'm sorry!
http://docs.webplatform.org/wiki/html/elements/dt
Hope that this will teach something to someone (it did to me)! :)
