### ISSUE TITLE
Forms autocomplete attribute doesn't accept autofill field keywords

### ISSUE THREAD

**Issue by laukstein** [validator/validator#268]
![autocomplete](https://cloud.githubusercontent.com/assets/183966/14090745/cfc72090-f544-11e5-8bfa-6b453709ef77.png)

---

Spec http://w3c.github.io/html/single-page.html#autofill-field

**Comment by sideshowbarker** [comment]
Do we know which `autocomplete` values are actually supported in browsers? There are 30+ values defined in the spec, but I am pretty certain that browsers do not support all of those.

**Comment by laukstein** [comment]
@sideshowbarker, why would it be important? All browsers, also **validator** are supposed to fallow spec.

**Comment by sideshowbarker** [comment]
> @sideshowbarker, why would it be important? All browsers, also validator are supposed to fallow spec.

It’s important because the fact that something is in the spec doesn’t make it a real feature of the platform. Requirements that are in the spec that don’t get implemented eventually just end up getting removed from the spec (for example, `<iframe seamless>`. In the interim, if a requirement in the spec is not implemented yet, it is a waste of all of our time to add support to it in tools like the HTML checker if the requirement is just going to end up being dropped from the spec.

**Comment by AutoSponge** [comment]
You already display the polyfill caveat when a feature may not perform the same way in all browsers. How is this different?

The example code from the spec fails: https://html.spec.whatwg.org/#autofill

**Comment by sideshowbarker** [comment]
I’m asking for specific data about actual browser support—which values of the `autocomplete` attribute do browsers actually implement support for

**Comment by sideshowbarker** [comment]
OK testing with http://w3c-test.org/html/semantics/forms/the-form-element/form-autocomplete.html indicates that Chrome, Safari, and Edge all do actually conform to the spec on this, so I’ll go ahead and add support.

**Comment by cvrebert** [comment]
@sideshowbarker Any idea when the next release JAR might be available?

**Comment by sideshowbarker** [comment]
> Any idea when the next release JAR might be available?

Hopefully be able to get a new release out by next weekend. Will still aim for earlier in the week though.

**Comment by sideshowbarker** [comment]
> @sideshowbarker Any idea when the next release JAR might be available?

Just released https://github.com/validator/validator/releases/tag/16.6.18

As usual, sorry for taking so long to get it out.

**Comment by cvrebert** [comment]
No worries. Thank you!
