### ISSUE TITLE
Add minimum Java version requirement to web page

### ISSUE THREAD

**Issue by GrahamHannington** [validator/validator#269]
"[The Nu Html Checker (v.Nu)](http://validator.github.io/validator/)" web page offers clear instructions on running the checker as a standalone service. Thank you!

However, you have to dig into the changelog to see the Java version required:

> 1 January 2016
> - Java8 is now required to run the checker

Could you please consider adding this requirement to the instructions on the web page?

The build instructions on the same page refer to:

> JDK 5 or later

I'm raising this issue because I'm preparing to publish an Atom editor package: the readme for that package refers to this v.Nu web page. I'd prefer the v.Nu web page to mention this requirement rather than mentioning it in the package readme.

**Comment by sideshowbarker** [comment]
Prominent mention added to http://validator.github.io/validator/ (sorry it took be so long to get to it)
