### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#27]
What are the chances of getting a new release JAR any time soon?
I'd very much like to take advantage of `meta@http-equiv=X-UA-Compatible` no longer being an error.

**Comment by sideshowbarker** [comment]
Will try to get a new release out this week, by Saturday at the latest. Otherwise I won't have time next week at all, so the next window would the first week of next month.

**Comment by cvrebert** [comment]
Good luck this week then.

**Comment by sideshowbarker** [comment]
https://github.com/validator/validator/releases/tag/20150207

Sorry it took me so long to get around to it.

**Comment by cvrebert** [comment]
:clap: :tada:
