### ISSUE TITLE
Cannot see charset

### ISSUE THREAD

**Issue by RHaworth** [validator/validator#275]
This page http://rhaworth.net/shakes/shaxref.php validates clean but gives the message:

    "The Content-Type header specified text/html but no charset."

But my content-type item is: 

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

Why does the validator think that no charset is specified?

**Comment by sideshowbarker** [comment]
>    "The Content-Type header specified text/html but no charset."

Right—note that the message is strictly just about the contents of the `Content-Type` HTTP header and not about the contents of the actual document.

> But my content-type item is: 
> 
>    \<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
>
> Why does the validator think that no charset is specified?

It doesn’t. The `"The Content-Type header specified text/html but no charset."` message cited above is only about the  `Content-Type` HTTP header and not about the charset specified in the `meta` element in the document itself.

**Comment by sideshowbarker** [comment]
closing per https://github.com/validator/validator/issues/275#issuecomment-206708595
