### ISSUE TITLE
Any plans on adding support for rel="preload"?

### ISSUE THREAD

**Issue by bazzadp** [validator/validator#276]
A new preload option is being considered to be added to HTML (Spec: https://www.w3.org/TR/preload/) which will be available in Chrome in the net version of Chrome (https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/).

This allows syntax like this:

   `<link rel="preload" href="/assets/fonts/LatoLatin-Thin.woff2" as="font" type="font/woff2" crossorigin>`

which allows publishers to let the browser know that fonts should be downloaded immediately, rather than waiting for the CSS to be parsed, see if the font is needed (which we know it will be), and then downloading it. This gives a good performance benefit.

Currently this fails in the validator due to two issues:

1. The value preload is not recognised as a valid "link rel" value.

   `Error: Bad value preload for attribute rel on element link: The string preload is not a registered keyword.`

   It is under the brainstorming section of the microformats page (http://microformats.org/wiki/existing-rel-values#brainstorming) and don't think those are loaded into the nu validator?

2. The "as" part is not recognised as valid HTML.

   `Error: Attribute as not allowed on element link at this point.`

   There are a number of valid values for the "as" attribute as listed here: https://fetch.spec.whatwg.org/#concept-request-destination

With Chrome about to add support websites may start using this (I plan to) so would be interested in this being added to the validator.

What's the policy on adding support for Working Draft syntax or is it only considered once it becomes part of the spec?

Thanks,
Barry

**Comment by sideshowbarker** [comment]
> The value preload is not recognised as a valid "link rel" value… It is under the brainstorming section of the microformats page (http://microformats.org/wiki/existing-rel-values#brainstorming) and don't think those are loaded into the nu validator?

Right. So the way to make it be recognized is to edit that wiki page to move it up to one of the tables that are recognized. That is, one of the tables from which the following list of `rel` values is generated https://help.whatwg.org/extensions/link-rel/

> The "as" part is not recognised as valid HTML… There are a number of valid values for the "as" attribute as listed here: https://fetch.spec.whatwg.org/#concept-request-destination

I don’t find an `as` attribute mentioned at all in the Fetch spec. I guess the place where it is defined is http://w3c.github.io/preload/#attributes

Do any browsers actually do anything with that `as` attribute yet? If not I think it would be premature for the checker to add support for it yet.

**Comment by zcorpan** [comment]
Now shipped: https://dev.opera.com/blog/opera-37/

**Comment by sideshowbarker** [comment]
@bazzadp Thanks for reporting this. Pushed to https://checker.html5.org/ and https://validator.w3.org/nu/

**Comment by bazzadp** [comment]
Wow that's great news. Thanks! Seems to work a treat.
