### ISSUE TITLE
Change entity resolver to conform to the HTML spec

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#288]
> This specification provides the following additional information that user agents should use when retrieving an external entity: the public identifiers given in the following list all correspond to the URL given by this link. (This URL is a DTD containing the entity declarations for the names listed in the named character references section.) [XML]

> -//W3C//DTD XHTML 1.0 Transitional//EN
-//W3C//DTD XHTML 1.1//EN
-//W3C//DTD XHTML 1.0 Strict//EN
-//W3C//DTD XHTML 1.0 Frameset//EN
-//W3C//DTD XHTML Basic 1.0//EN
-//W3C//DTD XHTML 1.1 plus MathML 2.0//EN
-//W3C//DTD XHTML 1.1 plus MathML 2.0 plus SVG 1.1//EN
-//W3C//DTD MathML 2.0//EN
-//WAPFORUM//DTD XHTML Mobile 1.0//EN

> Furthermore, user agents should attempt to retrieve the above external entity's content when one of the above public identifiers is used, and should not attempt to retrieve any other external entity's content.

https://html.spec.whatwg.org/multipage/xhtml.html#parsing-xhtml-documents

Right now there's a switch to either not load entities at all or load the specified ones. Consider changing it to match the spec so it is less confusing for users?

**Comment by sideshowbarker** [comment]
As far as I know, the XML parser the checker uses is mostly still just a general purpose XML parser that attempts to conform only to the XML and Namespaces in XML specs and not to any additional requirements that the HTML spec may have introduced with regard to XML parsing.

And the backend supports checking non-HTML content using that XML parser, so implementing that “should not attempt to retrieve any other external entity's content” requirement globally in the XML parser would break behavior for other checking of other XML content.

So I think the only way to implement this would be by adding some additional special XHTML mode to the XML parser. Which is do-able but is not likely to get prioritized very high unless someone submits a patch.

**Comment by sideshowbarker** [comment]
@zcorpan see https://github.com/validator/validator/issues/288#issuecomment-216849841. I’m not sure I can make a change to this code in the checker without also having it affect behavior for all XML documents (not just XHTML ones). Which is not really a problem for https://checker.html5.org/ but would be for https://validator.nu/ (since exposes a UI for checking XML docs) and for any users of the checker API (rather than just the Web UI for the service).

**Comment by zcorpan** [comment]
I guess I agree this shouldn't be prioritized high. And yes it would either be a new mode or break some users if you don't want 3 XML modes.
