### ISSUE TITLE
The Content-Type header specified text/html but no charset

### ISSUE THREAD

**Issue by Odud** [validator/validator#291]
I get the warning "The Content-Type header specified text/html but no charset. Used the HTML parser." but my meta tag is
`<meta` http-equiv="Content-Type" content="text/html; charset=utf-8">
which looks ok to me

**Comment by naena** [comment]
I have a similar situation:
http://mypollingcenter.com/ starts like this:
&lt;!DOCTYPE html&gt;
&lt;html lang="en-US"&gt;
&lt;head&gt;
  &lt;meta charset="utf-8"&gt;
I see the same error as above:
The Content-Type header specified text/html but no charset. Used the HTML parser.

Then http://ahangama.com/ starts like this:
&lt;!DOCTYPE html&gt;
&lt;html lang="si-Latn"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;

That one passes!
The Content-Type header specified text/html and the charset utf-8. Used the HTML parser.

**Comment by sideshowbarker** [comment]
> I see the same error as above:
> The Content-Type header specified text/html but no charset. Used the HTML parser.

That’s not an error. It’s stating the fact that the HTTP Content-Type header does not specify a charset.

If it were intended to point out a problem that needed to be fixed, the checker would include the message among the errors and warnings it emits. Instead, the message is emitted in what is essentially the footer of the results section, in small type.
