### ISSUE TITLE
html5, equals sign after reference in attribute should produce error

### ISSUE THREAD

**Issue by alwinb** [validator/validator#293]
I think I’ve found a case that should be reported as an error but isn’t. 

Consider the example:
`<span class="ab&not=cd">`

Then the ampersand does not start a character reference, but still should report an error (and does not), or at least that's what I've gathered from the html5 specification:

> If the character reference is being consumed as part of an attribute, and the last character matched is not a U+003B SEMICOLON character (;), and the next character is either a U+003D EQUALS SIGN character (=) or an alphanumeric ASCII character, then, for historical reasons, all the characters that were matched after the U+0026 AMPERSAND character (&) must be unconsumed, and nothing is returned. However, if this next character is in fact a U+003D EQUALS SIGN character (=), then this is a parse error, because some legacy user agents will misinterpret the markup in those cases.

**Comment by sideshowbarker** [comment]
@zcorpan can you remind me what’s the current thinking on the best thing to do for this case? (I mean not necessarily what the current spec says but instead what it seems like we should make it say.)

**Comment by alwinb** [comment]
I am curious about this. Charref handling has become quite messy. 

FWIW, It might be more clear to specify the tokenisation of charrefs as a two pass process, a lexical pass followed by a resolution pass, see e.g. these [notes](https://github.com/alwinb/html-lexer/blob/develop/notes/charrefs.txt).

**Comment by zcorpan** [comment]
It's no longer a parse error per spec. It changed in https://github.com/whatwg/html/commit/6c629ac9e5736cdb824293999673de6a0f5ea06d

**Comment by sideshowbarker** [comment]
Closing this per https://github.com/validator/validator/issues/293#issuecomment-225861649 (thanks @zcorpan).

@alwinb If you believe the checker doesn’t align with the current spec on this then feel free to reopen. And still feel free to post any other comments here, but note that if you disagree with this being a non-error, you would want to raise that as an issue at https://github.com/whatwg/html/issues (not here).

**Comment by alwinb** [comment]
I didn't notice that the specification changed. I prefer the new version, thanks.
