### ISSUE TITLE
Attribute myname not allowed on element __ at this point

### ISSUE THREAD

**Issue by ben-gold** [validator/validator#295]
My HTML document uses some custom/proprietary attributes on standard HTML elements. These attributes are used to pass data to Javascript.

Currently I use Message Filtering to suppress errors related to each custom attribute. Is there a better way?

Or perhaps suppressions can be embedded in the HTML page somehow. e.g. by a specially formatted comment. That might be a useful enhancement generally.

**Comment by sideshowbarker** [comment]
> My HTML document uses some custom/proprietary attributes on standard HTML elements.
> Or perhaps suppressions can be embedded in the HTML page somehow

You can use [`data-*`-prefixed attribute names](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes). The use case you describe in basically what those are for.

**Comment by ben-gold** [comment]
Thanks for the pointer!
