### ISSUE TITLE
Support link type "noopener" (rel=noopener)

### ISSUE THREAD

**Issue by laukstein** [validator/validator#298]
Spec https://html.spec.whatwg.org/multipage/semantics.html#link-type-noopener says
> The **noopener** keyword may be used with **a** and **area** elements.

Supported on Blink http://caniuse.com/#feat=rel-noopener

Test-case

```
<!doctype html>
<title>a</title>
<a href=/ rel=noopener></a>
```

Failed result

> Error: Bad value noopener for attribute rel on element a: The string noopener is not a registered keyword.

**Comment by syradar** [comment]
Now available in multiple browsers: https://caniuse.com/#feat=rel-noopener
