### ISSUE TITLE
Column count depends on the previous table

### ISSUE THREAD

**Issue by rknetwork** [validator/validator#299]
Warning: A table row was 2 columns wide, which is less than the column count established by the first row (3).

This warning refers to the previous table which has 3 columns. This is incorrect behavior. Different tables may have different numbers of columns.

`    <table class='menu-side'>↩
      <tr><td colspan='3'>&nbsp;</td></tr>↩
      <tr><th>Created</th><td class='created item'>07/05/2014 01:47 pm</td></tr>↩
      <tr><th>Updated</th><td class='updated item'>03/11/2016 01:26 pm</td></tr>↩
      <tr><td colspan='3'>&nbsp;</td></tr>↩
      <tr class='due'>↩
        <th>Due</th>↩
        <td class='item'>↩
          <span>12/01/2015 09:00 pm</span>↩
          <input class='date none' placeholder='mm/dd/yyyy' value='12/01/2015'>↩
          <input class='time none' placeholder='hh:mm' value='09:00 pm'>↩
        </td>↩
        <td class='edit-icon align-center'><a class='fa fa-pencil'></a><button class='fa fa-check none'></button></td>↩
      </tr>↩
    </table>↩
    <table class='menu-side'>↩
      <tr><th colspan='2'>&nbsp;</th></tr>↩
      <tr><td colspan='2'>Assignee(s)</td><td class='edit-icon align-center'><a class='fa fa-pencil'></a></td></tr>↩
      <tr class='assignee'><td colspan='2' class='name item'>Alex Galiyev</td><td>end</td></tr>↩
      <tr class='assignee'><td colspan='2' class='name item'>Alex Galiyev</td><td>end</td></tr>↩
      <tr class='assignee'><td colspan='2' class='name item'>Max Hess</td><td>end</td></tr>↩
      <tr class='assignee'><td colspan='2' class='name item'>Alex Galiyev</td><td>end</td></tr>↩
      <tr class='assignee'><td colspan='2' class='name item'>Alex Galiyev</td><td>end</td></tr>↩
      <tr class='assignee'><td colspan='2' class='name item'>Alex Galiyev</td><td>end</td></tr>↩
      <tr class='assignee'><td colspan='2' class='name item'>Max Hess</td><td>end</td></tr>↩
      <tr class='assignee'><td colspan='2' class='name item'>Alex Galiyev</td><td>end</td></tr>↩
    </table>↩`

**Comment by sideshowbarker** [comment]
You have two tables in that example document. Both of them have problems that cause warnings and ath need to be fixed.

Please try running each table through the checker separately one-by-one and compare the results to what you get when you have them together in the same document.

I think what you will find is that you get exactly the same errors reported for each of them as you do when you have them in the same document. But if you try what I asked and check them separately and find otherwise, then let me know.
