### ISSUE TITLE
question re use of <style scoped>

### ISSUE THREAD

**Issue by leserman** [validator/validator#303]
I was not aware that "scoped" had been removed from the spec so I was using it. Now I encounter the construct is failing validation. 

My question: In this case, what subtree is in question in the message "Suppressing further errors from this subtree?" Is it a) the subtree contained within the <style scoped> construct or b) the subtree that would be affected by the <style scoped> construct, that is, the parent container and all of it's embedded containers?

This is related to Issue #296 per whatwg/html@c2a3b2a closed 2 days ago.

Error statement from validator is stated bellow.

Thanks.

David Leserman

Error: Element style not allowed as child of element div in this context. (Suppressing further errors from this subtree.)
From line 109, column 15; to line 109, column 44
          <style type="text/css" scoped>↩     
Contexts in which element style may be used:
Where metadata content is expected.
In a noscript element that is a child of a head element.
Content model for element div:
Flow content.

**Comment by sideshowbarker** [comment]
> Element style not allowed as child of element div in this context. (Suppressing further errors from this subtree.)

That means the subtree that has the `style` element as its root. It means that the validator is not checking for errors in any of the child content of that `style` element. Which isn’t a big deal, because a `style` element can’t have any child element content anyway, so there’s really nothing it would check otherwise.

**Comment by leserman** [comment]
Thanks for your clear response.
