### ISSUE TITLE
This repository is several release versions behind of the W3C version, please align.

### ISSUE THREAD

**Issue by mfhepp** [validator/validator#306]
The latest release available here is 16.3.3, while the W3C deployment shows 16.6.9.

The version 16.3.3. does not accept @content within a div element and thus discards RDFa in HTML.

Please make the improvements from the W3C fork available here. Thanks!

Martin

**Comment by sideshowbarker** [comment]
> 16.3.3. does not accept @content within a div element and thus discards RDFa in HTML.

None of the jar releases here will ever support @content within a div element. That support is intentionally only enabled in the W3C instance of the checker service.

So If you want a jar with support for that, you need to build it from the sources, following the instructions at https://validator.github.io/validator/#build-instructions with the `--follow-w3c-spec` option specified.

A minimal invocation for building such a jar:

```
python build/build.py \
  --name="Ready to check" \
  --results-title="Showing results" \
  --page-template="site/NuPageEmitter.xml" \
  --form-template="site/NuFormEmitter.xml" \
  --about-file="site/nu-about.html" \
  --script-file="site/nu-script.js" \
  --stylesheet-file="site/nu-style.css" \
  --presets-file="resources/nu-presets.txt" \
  --follow-w3c-spec \
  update dldeps build jar
```

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/306#issuecomment-225363236

I will actually be doing a new checker jar release this week but as mentioned in that previous comment, like all previous releases of the jar it will have support for `div[content]`.

@mfhepp Feel free to reopen this if choose, or to raise a separate more specific issue for it. But barring any new compelling information, I don’t anticipate any change in any upcoming jar releases for this.

**Comment by mfhepp** [comment]
Thanks @sideshowbarker ; I built a version locally with the settings as suggested and that solved my issue. Again, thanks for your help!

**Comment by sideshowbarker** [comment]
@mfhepp cheers—glad you got it working
