### ISSUE TITLE
IE Conditional Comment “<!-->” triggering “nested comment” error

### ISSUE THREAD

**Issue by eel-in-a-hovercraft** [validator/validator#310]
I understand comment checking is only **experimentally** changed as of 16.6.18, and Conditional Comments are not supported as of IE10 but…

Use of a conditional comment construct like:

```HTML
<!--[if gt IE 8]><!-->
some code
<!--<![endif]-->
```

Triggers the error:

> Saw `<!--` within a comment. Probable cause: Nested comment (not allowed).

The recent change to the spec regarding comments is fine, but can the checker make an exception for the specific string `<!-->`?

**Comment by sideshowbarker** [comment]
So yeah see https://github.com/whatwg/html/issues/1453 for the proposed change to the HTML spec to address this. As soon as a PR for that gets merged, I’ll get a fix made for it made to the checker code as soon as possible after that.

**Comment by sideshowbarker** [comment]
Fixed and pushed to https://checker.html5.org

Thanks for taking time to raise this.
