### ISSUE TITLE
Warning about lang is not resolvable

### ISSUE THREAD

**Issue by quaap** [validator/validator#314]
I was checking my URL ( http://quaap.com/D/ ) and it gave me a warning:

`This document appears to be written in English. Consider adding lang="en" (or variant) to the html element start tag.`

My page is in English, but when I add `lang="en"` to the html element, it then gives me:

`This document appears to be written in Telugu but the html element start tag has a lang attribute with the value en. Consider changing the lang value to te (or variant) instead.`

I admit I laughed :)

**Comment by sideshowbarker** [comment]
Thanks for the report. When I tested at https://validator.w3.org/nu/ it thinks your page is written in Vietnamese :) Anyway, I just pushed this feature to validator literally only an hour ago, and it is already clear that I need to revert it until I can get the bugs fixed, so please bear with me a bit til I can do that.

**Comment by quaap** [comment]
Thanks for looking at the issue!  When I searched for previous issues I saw the lang warning was a new feature, but I guess I didn't realize it was _that_ new.

**Comment by sideshowbarker** [comment]
OK, please check again now. I pushed https://github.com/validator/validator/commit/992b650425ac227255a0a16a62e801baec6dee7e to https://validator.w3.org/nu/ and I believe it should eliminate the problem you ran into.

**Comment by quaap** [comment]
Yup, it works now.  When I add `lang="en"` in the "Validate by Direct Input" box I get `Document checking completed. No errors or warnings to show.`.

Thanks for the quick work!

**Comment by sideshowbarker** [comment]
Cheers & thanks for taking time to report it quickly
