### ISSUE TITLE
TextMessageEmitter can only be constructed with an OutputStream

### ISSUE THREAD

**Issue by veita** [validator/validator#318]
`nu.validator.messages.TextMessageEmitter ` requires a `java.io.OutputStream` for constructing. Internally the constructor then creates a `Writer` for UTF-8 output.

This is not very convenient if the caller only has a `Writer`.

**Comment by sideshowbarker** [comment]
So you want an additional constructor added that just takes a `Writer`?

(By the way I’ve never been aware that anybody was actually using `TextMessageEmitter` for anything. If you have a real use case for it, I am curious to hear.)

**Comment by sideshowbarker** [comment]
Is the following what you had in mind?

```diff
diff --git a/src/nu/validator/messages/TextMessageEmitter.java b/src/nu/validator/messages/TextMessageEmitter.java
index ac4d7b4..b42e941 100644
--- a/src/nu/validator/messages/TextMessageEmitter.java
+++ b/src/nu/validator/messages/TextMessageEmitter.java
@@ -80,6 +80,11 @@ public class TextMessageEmitter extends MessageEmitter {
         this.messageTextHandler = new TextMessageTextHandler(writer, asciiQuotes);
     }

+    public TextMessageEmitter(Writer writer, boolean asciiQuotes) {
+        this.writer = writer;
+        this.messageTextHandler = new TextMessageTextHandler(writer, asciiQuotes);
+    }
+
     private void emitErrorLevel(char[] level) throws IOException {
         writer.write(level, 0, level.length);
     }
```

**Comment by veita** [comment]
Yes, that's fine.

We are currently investigating if we could use the validator from JUnit test that run on Jenkins.

There it would be convenient to collect all errors of certain HTML source trees with a single writer.

**Comment by sideshowbarker** [comment]
OK, I have pushed the code for the new constructor to the sources. If you need a new maven release lemme know and I can try to get one out sometime soon.

**Comment by veita** [comment]
Thank you very much for the new constructor.

A new maven release is not required.
