### ISSUE TITLE
ARIA role="timer" on element <time>

### ISSUE THREAD

**Issue by chris-scheurle** [validator/validator#32]
As stated in both [HTML5](http://www.w3.org/TR/html5/text-level-semantics.html#the-time-element) and [HTML 5.1 Nightly](http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-time-element), the `<time>` element can be asigned *any ARIA role value* and [WAI-ARIA 1.0](http://www.w3.org/TR/wai-aria/roles#timer) defines `timer` as a valid ARIA role. Yet, validating
```html
<!DOCTYPE html><html><head><title>Timer</title></head><body><p>

<time role="timer" aria-label="Countdown" datetime="10s"><samp>10</samp> seconds</time>

</p></body></html>
```
leads to
> **Error:** Bad value `timer` for attribute `role` on element `time`.

**Comment by sideshowbarker** [comment]
Nice catch :-) Thanks for finding it. From examining the code, I see we don't actually have support for `timer` at all anywhere. So I'll get it added soon.
