### ISSUE TITLE
Validator truncates output after 8192 bytes

### ISSUE THREAD

**Issue by veita** [validator/validator#320]
Validator output is truncated after 8192 bytes (for a single file). However this behaviour seems not to be documented.

```Java
	private boolean _validateHtml(Path file, OutputStream err) throws Exception
	{
		try (final InputStream in = Files.newInputStream(file))
		{
			final InputSource             inputSource;
			final SourceCode              sourceCode;
			final ImageCollector          imageCollector;
			final boolean                 bShowSource;
			final MessageEmitter          emitter;
			final MessageEmitterAdapter   errorHandler;
			final SimpleDocumentValidator validator;

			inputSource = new InputSource(in);
			inputSource.setSystemId(_getSystemId(file));

			sourceCode     = new SourceCode();
			imageCollector = new ImageCollector(sourceCode);
			bShowSource    = false;

			emitter = new TextMessageEmitter(err, true);

			errorHandler = new MessageEmitterAdapter
				(sourceCode, bShowSource, imageCollector, 0, true, emitter);

			errorHandler.setErrorsOnly(true);

			validator = new SimpleDocumentValidator();
			validator.setUpMainSchema("http://s.validator.nu/html5-rdfalite.rnc", new SystemErrErrorHandler());
			validator.setUpValidatorAndParsers(errorHandler, true, false);
			validator.checkHtmlInputSource(inputSource);

			return errorHandler.getErrors() == 0;
		}
	}

```

`err` may be a `FileOutputStream`, or `System.out`.

**Comment by sideshowbarker** [comment]
I can’t reproduce this with [SimpleCommandLineValidator](https://github.com/validator/validator/blob/master/src/nu/validator/client/SimpleCommandLineValidator.java) (which calls `SimpleDocumentValidator`).

Try this:

    java -cp ./build/dist/vnu.jar nu.validator.client.SimpleCommandLineValidator \
        http://www.eriwongel.com/tig/ > OUT 2>&1

…where `./build/dist/vnu.jar` is of course whatever local path to the classes in your environment.

When I run that in my environment, I get a multi-megabyte `OUT` file. The output doesn’t get truncated at 8192 bytes. (Instead it just stops as expected at the configured limit for the maximum number of errors.)

**Comment by sideshowbarker** [comment]
I have gone in and doublechecked to validator sources to see if I could spot anything that might be causing this problem, but I can’t find anything that would. You’re certain this is not just something you may have overlooked in your client code? e.g., not calling `flush()` or `close()` or something?

**Comment by sideshowbarker** [comment]
I have now triple-checked this and still found nothing that would cause this. If you have client code you can post that will reproduce it or otherwise want to keep this issue active, feel free to re-open.
