### ISSUE TITLE
allow aria-readonly on input type=text with role=combobox

### ISSUE THREAD

**Issue by jasonkiss** [validator/validator#324]
Error: Attribute aria-readonly not allowed on element input at this point.
-edit">↩		<input type="text" readonly="readonly" aria-readonly="true" role="combobox" aria-expanded="false" aria-autocomplete="none" aria-owns="listbox" value="" id="combobox">↩		<bu

aria-readonly is used with combobox role [[wai-aria 1.1](https://www.w3.org/TR/wai-aria-1.1/#aria-readonly)]

input type=text with role=combobox allows any aria-* attributes applicable to the combobox role [[ARIA in HTML](https://w3c.github.io/html-aria/#input-text-list)]

**Comment by sideshowbarker** [comment]
paging @stevefaulkner for feedback

**Comment by stevefaulkner** [comment]
@jasonkiss currently input type=text with no list attribute is not allowed any overide https://w3c.github.io/html-aria/#input-text

do you have a use for it?

**Comment by stevefaulkner** [comment]
@jasonkiss note the updated definition of combobox as a composite role in 1.1 https://www.w3.org/TR/wai-aria-1.1/#combobox

**Comment by jasonkiss** [comment]
Ah :) I read the text "input type = text, search, tel, url, or email with a list attribute" as a list of scenarios with input type=email being the only one needing the list attribute. Of course, given that there's already an explicit entry for input type=text with no list attribute, I should probably have inferred differently. Maybe a slight editorial tweak to something like "input type = text, search, tel, url, or email, and with a list attribute" would help? Or maybe it was just me... :)

Thanks for the pointer to the revised combobox definition. I've been working on a combobox with non-editable input using the old 1.0 approach where the input has role=combobox.

In my 1.0 approach, I had 
```html
<input type="text" role="combobox" readonly aria-readonly="true" aria-owns="listbox" ...>
<ul id="listbox" role="listbox" ...>
```

You can see that I had aria-readonly on the input, but this raised the validation error as I wasn't using a list attribute. The aria-owns was establishing the relationship. 

As I read it, the new 1.1 definition requires that role=combobox be on the container with the input nested within that container. So then, as per the 1.1 spec, I'd have something like this, right, with aria-readonly that now has to go on the container div with role=combobox, and not the input?

```html
<div role="combobox" aria-owns="listbox" aria-readonly="true" ...>
    <input type="text" aria-autocomplete="none" aria-controls="listbox" ...>
</div>
<ul role="listbox" id="listbox">
```

And if I wanted to stick with the 1.0 approach, in order to specify aria-readonly on the input, I'd have to add the list attribute to the input. But then, as per the HTML5 spec, I'd also have to use `<datalist>` instead of `<ul>`. Have I got that right?

```html
<input type="text" role="combobox" list="listbox" readonly aria-readonly="true" aria-owns="listbox" ...>
<datalist id="listbox" ...>
```

If I've got that right, then I understand and rescind the issue :)

**Comment by jasonkiss** [comment]
Follow up: Actually took the time to validate some of these examples.

Here is the original 1.0 approach that failed aria-readonly on the input, presumably because it didn't have a list attribute:

```html
<input type="text" role="combobox" readonly aria-readonly="true" aria-owns="listbox" ...>
<ul id="listbox" role="listbox" ...>
```
And here's the same with aria-readonly on the input with a list attribute pointing to a datalist element, and this validates as expected:

```html
<input aria-readonly="true" type="text" aria-autocomplete="none" aria-controls="listbox" list="listbox">
<datalist id="listbox">
```

Here is the new 1.1 version of the combobox approach, with aria-readonly on the div, but this fails validation, as aria-readonly not allowed on div at this point:

```html
<div role="combobox" aria-owns="listbox" aria-readonly="true" ...>
    <input type="text" aria-autocomplete="none" aria-controls="listbox" ...>
</div>
<ul role="listbox" id="listbox">
```

Here is the same markup but with aria-readonly on the input, and this passes validation, but I reckon it shouldn't because the input has no list attribute, right?

```html
<div role="combobox" aria-owns="listbox" ...>
    <input type="text" aria-readonly="true" aria-autocomplete="none" aria-controls="listbox" ...>
</div>
<ul role="listbox" id="listbox">
```

Is this last instance an oversight, and it should fail?

**Comment by sideshowbarker** [comment]
> @sideshowbarker That's a bug as aria-readonly is allowed on role=combobox https://www.w3.org/TR/wai-aria-1.1/#combobox and role=combobox is allowed on div http://w3c.github.io/html-aria/#div

OK, thanks—will fix those

**Comment by jasonkiss** [comment]
Thanks for clarifying, Steve.

What about that last scenario where aria-readonly on input type="text" without a list attribute nested within a role="combobox" still passes? Also a bug?

**Comment by stevefaulkner** [comment]
@jasonkiss why would you not just put readonly on the text box? 
http://w3c.github.io/html-aria/#attr-readonly

**Comment by jasonkiss** [comment]
I would/should probably just do that :) Just pointing out what seemed to be a discrepancy in the validator: aria-readonly only allowed on input type="text" with list attribute, but in that last scenario, no list attribute and aria-readonly validated.

Anyway, thanks for bearing with me and your help on this. Happy to leave it there and for this issue to be closed at @sideshowbarker's leisure.

**Comment by sideshowbarker** [comment]
>> Here is the new 1.1 version of the combobox approach, with aria-readonly on the div, but this fails validation, as aria-readonly not allowed on div at this point:
>> `<div role="combobox" aria-owns="listbox" aria-readonly="true" ...>`

> @sideshowbarker  That's a bug as aria-readonly is allowed on role=combobox https://www.w3.org/TR/wai-aria-1.1/#combobox and role=combobox is allowed on div http://w3c.github.io/html-aria/#div

Fixed and pushed to https://validator.w3.org/nu/

Lemme know if there’s anything I still need to fix here or if instead we can close this issue.

**Comment by jasonkiss** [comment]
Thanks, @sideshowbarker .

I think the following remains an issue, as according to http://w3c.github.io/html-aria/#input-text, aria-readonly on this input with no list attribute should be an error:
```
<div role="combobox" aria-owns="listbox" aria-expanded="false">
    <input type="text" aria-readonly="true" aria-autocomplete="none" aria-controls="listbox">
</div>
<ul role="listbox" id="listbox">
   <li role="option">blah</li>
</ul>
```
Deferring to @stevefaulkner .

**Comment by sideshowbarker** [comment]
> I think the following remains an issue, as according to http://w3c.github.io/html-aria/#input-text, aria-readonly on this input with no list attribute should be an error:

Can you explain in more detail why? I may be confused but based on what I understand:

1. The implicit semantics of `input type=text` are `role=textbox`.
2. So, even if an `input type=text` element has no explicit `role` attribute, it’s permitted to have any ARIA properties or states that are allowed with the `textbox` role.
3.  [The spec says`aria-readonly` is allowed with the `textbox` role](http://w3c.github.io/html-aria/#index-aria-textbox).

**Comment by jasonkiss** [comment]
Good point. You're right. I'm confused :)

I think I'm identifying an issue with the ARIA in HTML spec. The entry for `input type=text` with no `list` attribute says no role override and only global aria-* attributes allowed. It doesn't expressly say that any aria-* attributes applicable to the textbox role are also permitted, as it does for other elements where it typically specifies "global aria-* attributes and any aria-* attributes applicable to the [whatever] role." 

I'll file this as an issue against ARIA in HTML, which means, I think, you can close this one.

**Comment by sideshowbarker** [comment]
Closing here per https://github.com/validator/validator/issues/324#issuecomment-241546685
