### ISSUE TITLE
"https://validator.nu/" redirects to "https://hsivonen.fi/"

### ISSUE THREAD

**Issue by ericmacfa** [validator/validator#325]
Title explains it, for some reason the [validator.nu](https://validator.nu/) redirects to "https://hsivonen.fi/"

**Comment by esetnik** [comment]
Same issue just popped up for me

**Comment by lancesnider** [comment]
Everything was working fine yesterday, but now I'm getting the same.

**Comment by sideshowbarker** [comment]
Will need to wait to hear from @hsivonen who maintains validator.nu

In the mean time you can use https://checker.html5.org/ (which these days is always going to be more up to date with the latest changes to the source anyway)

**Comment by hsivonen** [comment]
Sorry. This was an nginx configuration error. I fixed this a week ago, but the manifestation of the error was cacheable, so the fix isn't visible without clearing the cache.

**Comment by esetnik** [comment]
validator.nu is down again

**Comment by sideshowbarker** [comment]
it seems to be back again now
