### ISSUE TITLE
Make heading-level outline ignore <hgroup> and display all headings

### ISSUE THREAD

**Issue by sideshowbarker** [validator/validator#326]
Consider the following document:
```html
<!DOCTYPE html>
<title>Test</title>
<hgroup>
<h1>Title</h1>
<h2>Subtitle</h2>
</hgroup>
```

[In the **Heading-level outline** output from the checker for that doc](https://validator.w3.org/nu/?showoutline=yes&doc=data%3Atext%2Fhtml%3Bcharset%3Dutf-8%2C%3C%2521DOCTYPE%2520html%3E%3Ctitle%3ETest%3C%252Ftitle%3E%3Chgroup%3E%3Ch1%3ETitle%3C%252Fh1%3E%3Ch2%3ESubtitle%3C%252Fh2%3E%3C%252Fhgroup%3E), the `h2 Subtitle` doesn’t appear.

**Comment by stevefaulkner** [comment]
@sideshowbarker that's a bug ;-)

**Comment by sideshowbarker** [comment]
> @sideshowbarker that's a bug ;-)

yeah, will try to get it fixed soon
