### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by nkhensi84** [validator/validator#327]
I tried to validate my code it shows this error  : it seems like this code is written in English change , consider changing the language to lang ="EN" or variant  html .what could be the problem and how do i fix this ?

**Comment by sideshowbarker** [comment]
Please post a link with the URL for the actual document.

**Comment by nkhensi84** [comment]
<!DOCTYPE html>
<html>
<head>
<title>Web Page Activity 2</title>
<meta http-equiv="Content-Type" content="text/html;
charset=UTF-8">
</head>
<body>
<h1>Social Media</h1>
<p>Social media refers to the means of interactions among people in which they create, share, and exchange information and ideas in virtual 

communities and networks.</p>
<p>There are many effects that stem from internet usage. According to Nielsen, internet users continue to spend more time with social media 

sites than any other type of site. At the same time, the total time spent on social media in the U.S. across PC and mobile devices increased 

by 37 percent to 121 billion minutes in July 2012 compared to 88 billion minutes in July 2011.</p>
<p>Social media differentiates from traditional/industrial media in many aspects such as:</p>
<ul>
<li>Quality</li>
<li>Reach</li>
<li>Frequency</li>
<li>Usability</li>
<li>Immediacy</li>
</ul>

</body>
</html>

**Comment by nkhensi84** [comment]
https://validator.w3.org this the link i used to validate my code .

**Comment by sideshowbarker** [comment]
So, in line 2 of your source, where you currently have this:

```html
<html>
```

…change it to this:

```html
<html lang="en">
```

**Comment by nkhensi84** [comment]
So when it says your code is validated according to specified schem(a).does that means it is validSent from my Huawei Mobile-------- Original Message --------Subject: Re: [validator/validator] Language (#327)From: "Michael[tm] Smith" To: validator/validator CC: nkhensi84 ,Author So, in line 2 of your source, where you currently have this:

<html>

…change it to this:

<html lang="en">

**Comment by sideshowbarker** [comment]
> So when it says your code is validated according to specified schem(a).does that means it is valid

yeah

**Comment by sideshowbarker** [comment]
Closing. Feel free to re-open if you have further questions.
