### ISSUE TITLE
Validator not picking up missing closing tags

### ISSUE THREAD

**Issue by gransalamandra** [validator/validator#329]
I have noticed that the validator is not picking missing closing tags (e.g., /p tag).

**Comment by sideshowbarker** [comment]
See [“A p element's end tag can be omitted…“ in the spec](https://html.spec.whatwg.org/multipage/semantics.html#the-p-element), [“The end tag may be omitted” in MDN](https://developer.mozilla.org/en/docs/Web/HTML/Element/p) etc.
