### ISSUE TITLE
Abusing IP Address with Validator

### ISSUE THREAD

**Issue by karirichardson** [validator/validator#330]
Today my 30 students in class validated the same html document and were not able to recheck because it stated we were "abusing our IP address". I have never had an error like this in class and have used this tool for the last 3+ years.  Curious what anyone suggests a school teacher to use to validate html/css in the classroom of 30+ students.  Thanks!

**Comment by sideshowbarker** [comment]
You and your students can instead use https://checker.html5.org/ and you won’t get blocked.

**Comment by sideshowbarker** [comment]
Closing. Feel free to reopen if needed.

**Comment by jaimeiniesta** [comment]
Does this IP blocking come with the validator itself, or is something to be configured on the web server on front of it?

In case it comes with the validator, can it be configured, is there a whitelist?

**Comment by sideshowbarker** [comment]
> Does this IP blocking come with the validator itself, or is something to be configured on the web server on front of it?

Neither. It’s not controlled by anything in the HTML checker code itself, nor in the (Jetty) servlet engine the HTML checker runs under in the W3C deployment. It’s instead something completely separate configured commonly in the environment the (Java-based) https://validator.w3.org/nu/ HTML checker and (Perl-based) https://validator.w3.org/ legacy markup validator both run under.
