### ISSUE TITLE
Is there a way to configure timeouts?

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#332]
Some sites take a long time to respond, and this can clog up the validator, making it reject other validations.

Can the connect and receive timeouts be configured? I'd like to set a much lower limit to avoid this.

**Comment by sideshowbarker** [comment]
For the jar, you can control the timeouts with these Java system properties:

* `-Dnu.validator.servlet.connection-timeout=NNN`
* `-Dnu.validator.servlet.socket-timeout=NNN`

…where _NNN_ is some number of milliseconds.

The defaults if those are not specified is `5000` (5 seconds).

**Comment by jaimeiniesta** [comment]
For the war can the timeouts be configured? If not, the defaults are the same as above?

**Comment by sideshowbarker** [comment]
> For the war can the timeouts be configured?

I don’t use the war but for Tomcat I see mention of a JAVA_OPTS environment variable that you can trying adding them to. Otherwise what I can glean it seems that you might have to edit the startup scripts for the servlet engine.

> If not, the defaults are the same as above?

Yes, the defaults in the checker sources are 5000 milliseconds.
