### ISSUE TITLE
Report: Erroneous language warning for "Norwegian" in the Nu Html Checker

### ISSUE THREAD

**Issue by isNaN** [validator/validator#338]
Warning: This document appears to be written in Norwegian but the `html` start tag has `lang="nb-NO"`. Consider using `lang="no"` (or variant) instead.

Tag in question: `<html class="no-js" lang="nb-NO">`

Norwegian has two written languages, "Norwegian Bokmål" and "Norwegian Nynorsk". Their respective tags are "nb-NO" and "nn-NO". The suggestion `lang="no"` would only inform an agent of the macrolanguage of the page, and would not be the recommended standard, neither by BCP 47 (which has a paragraph on Norwegian sublanguages) nor the Norwegian "Law on language usage in the public sector" (ISBN 82-504-1293-1).

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I will try to get a fix pushed to the validator as soon as possible.

**Comment by sideshowbarker** [comment]
I’ve pushed a fix for this to https://validator.w3.org/nu/ and https://checker.html5.org/

Please re-check now at either of those and if you still run into any misidentification problems lemme know.

(And sorry it took me a lot longer to get back to fixing this than I had planned.)

**Comment by steinarer** [comment]
The Norwegian subtags "nb" and "nn" (as per BCP 47) still cause both validators to throw the warning:

> This document appears to be written in Norwegian but the `html` start tag has `lang="nb"`. Consider using `lang="no"` (or variant) instead.

**Comment by sideshowbarker** [comment]
OK, clearly I flubbed something here. Will attempt to fix it right now.

**Comment by sideshowbarker** [comment]
I’ve pushed a fixup to https://validator.w3.org/nu/ and https://checker.html5.org/

Please re-check again now at either of those and if you still run into any misidentification problems lemme know.

Sorry for the churn.
