### ISSUE TITLE
misidentified the language of this document

### ISSUE THREAD

**Issue by bjoey37** [validator/validator#343]
The validator thought my html files were in French but they were in English.

**Comment by cvrebert** [comment]
Going to need a sample of the misidentified HTML to be able to do anything about it.

**Comment by sideshowbarker** [comment]
As @cvrebert there’s no way to troubleshoot this without have a document to test with. So can you please post a link to a document the checker is misidentifying as French?

**Comment by sideshowbarker** [comment]
Closing for lack of response. Please re-open if you have a document I can test against.
