### ISSUE TITLE
javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#345]
Hello, I'm running the latest release of validator in a [dockerized server](https://github.com/sitevalidator/nu-cat/blob/master/Dockerfile), everything works great, but I've found a case where I encounter a SSL exception.

This happens when validating https://tractionboard.com/ - it doesn't happen when validating from https://validator.nu, so I guess the problem lies on the Java setup? It works fine with other HTTPS sites, it's just this one that's failing.

```
INFO VerifierServletTransaction - IOException
 — javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 — at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
 — at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
 — at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
 — at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
 — at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
 — at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
 — at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
 — at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
 — at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
 — at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
 — at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
 — at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
 — at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:395)
 — at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:354)
 — at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
 — at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
 — at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
 — at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
 — at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
 — at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
 — at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
 — at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
 — at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
 — at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
 — at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
 — at nu.validator.xml.PrudentHttpEntityResolver.resolveEntity(PrudentHttpEntityResolver.java:253)
 — at nu.validator.xml.DataUriEntityResolver.resolveEntity(DataUriEntityResolver.java:94)
 — at nu.validator.localentities.LocalCacheEntityResolver.resolveEntity(LocalCacheEntityResolver.java:94)
 — at nu.validator.servlet.VerifierServletTransaction.loadDocumentInput(VerifierServletTransaction.java:1957)
 — at nu.validator.servlet.VerifierServletTransaction.loadDocAndSetupParser(VerifierServletTransaction.java:1315)
 — at nu.validator.servlet.VerifierServletTransaction.validate(VerifierServletTransaction.java:916)
 — at nu.validator.servlet.VerifierServletTransaction.service(VerifierServletTransaction.java:801)
 — at nu.validator.servlet.VerifierServlet.doPost(VerifierServlet.java:270)
 — at nu.validator.servlet.VerifierServlet.doGet(VerifierServlet.java:195)
 — at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
 — at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
 — at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
 — at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
 — at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 — at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
 — at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
 — at nu.validator.servlet.MultipartFormDataFilter.doFilter(MultipartFormDataFilter.java:194)
 — at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
 — at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
 — at nu.validator.servlet.InboundGzipFilter.doFilter(InboundGzipFilter.java:60)
 — at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
 — at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
 — at nu.validator.servlet.InboundSizeLimitFilter.doFilter(InboundSizeLimitFilter.java:63)
 — at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
 — at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
 — at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
 — at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
 — at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
 — at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
 — at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
 — at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
 — at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
 — at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
 — at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
 — at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
 — at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
 — at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
 — at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
 — at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
 — at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2445)
 — at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 — at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 — at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 — at java.lang.Thread.run(Thread.java:745)
 — Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Thanks!

**Comment by mprins** [comment]
You need to make sure the tls certificate on the webserver is signed / authorized by a global certificate provider; the message says it isn't

**Comment by jaimeiniesta** [comment]
Thanks @mprins - do you mean the TLS certificate on the web server that serves https://tractionboard.com/  or on the web server that hosts my instance of the validator?

**Comment by cvrebert** [comment]
The former, but it's already valid, at least according to Chrome.
Presumably the relevant root CA (AddTrust) isn't in Java's bundle of root certificates?

**Comment by jaimeiniesta** [comment]
The thing is that if you validate this URL on validator.w3.org/nu there's no trouble with the SSL:

https://validator.w3.org/nu/?doc=https%3A%2F%2Ftractionboard.com%2F

But, when I do it from my hosted validator (using the latest release, from 29 June 2016), I get the above error.

So it looks like something that is outside the validator code, that depends on the server that hosts it I guess.

**Comment by jaimeiniesta** [comment]
This happens both on the production server and on my development machine - that's coherent, as it uses Docker.

If you want to try it, here's the Dockerized validator, also available in DockerHub:

https://github.com/sitevalidator/nu-cat

**Comment by mprins** [comment]
It depends on the java runtime; you can manually install the required root cert (in this case COMODO) in the java certificate store of the JVM in use.
the following might be helpful:
 - https://azure.microsoft.com/en-us/documentation/articles/java-add-certificate-ca-store/

**Comment by jaimeiniesta** [comment]
Thanks for your help @mprins - I tried this, in the case of this Dockerized server, based on the [official Tomcat Dockerfile](https://github.com/docker-library/tomcat/blob/989f50ed5db788921a4954109b90362e2209295e/8.0/jre8/Dockerfile), the cacerts is located at:

    /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts

I checked the certs list and it looks like the root certificate for Comodo is already installed as it comes from Debian's ca-certificates package. The certificate is quite fresh, from June 2016.

Anyway I downloaded the Root certificate from Comodo, tried to install it, but keytool told me this cert was already installed.

I'm still investigating this issue - it might help to know where the root certificates used in other instances of the validator come from, are they based on this Debian package @sideshowbarker ?

**Comment by jaimeiniesta** [comment]
Another option would be disabling SSL trust checking, with the [nuvalidatorxmlpromiscuous-ssl](https://github.com/validator/validator/wiki/Service:-Java-system-properties#nuvalidatorxmlpromiscuous-ssl) property.

I'm checking to see how can this be set up on a Tomcat environment.

**Comment by sideshowbarker** [comment]
> Another option would be disabling SSL trust checking, with the [nuvalidatorxmlpromiscuous-ssl](https://github.com/validator/validator/wiki/Service:-Java-system-properties#nuvalidatorxmlpromiscuous-ssl) property.

Yeah, I suggest doing that. Everywhere I run any instance of the HTML checker anywhere, I start it with that `-D nu.validator.xml.promiscuous-ssl` Java system property. And the times when I have forgotten to start it with that option, I have run into problems like the one description in this issue.

**Comment by jaimeiniesta** [comment]
Thanks @sideshowbarker I ended doing that too, I feel more relaxed now that I see is what you do on your instances too. Thanks!

**Comment by sideshowbarker** [comment]
https://github.com/validator/validator/commit/ca1ce46b897ee51840e186b79ab48ec10a380450 and https://github.com/validator/validator/commit/d332ba14b2ccb0fbdd2d1656334ab4608e33b5a9 fix this such that you should no longer ever need to specify the `nu.validator.xml.promiscuous-ssl` Java system property. I made it the default behavior.

**Comment by jaimeiniesta** [comment]
Hi @sideshowbarker it looks like this issue is back, both on 19.7.5 and 20.2.13 I'm getting a `handshake_failure` when checking  https://www.audreyjournal.com.au/

**Comment by sideshowbarker** [comment]
I’ve (re)fixed this.

The underlying cause of the `handshake_failure` this time turned out to be quite different from the cause when this was first reported.

This time that cause was that I had switched the Docker images to not use the vnu.jar distribution but to instead use the Java runtime image.

And the specific problem was that some Java library crypto library code containing ciphers necessary for TLS negotiation was not getting bundled into the Java runtime images. That caused the `handshake_failure` to happen when checking many or most HTTPS web documents.

Anyway, I believe it should be working as expected again now. But if you run into further problems with it, lemme know
