### ISSUE TITLE
HTML lang processing

### ISSUE THREAD

**Issue by classroom24-7** [validator/validator#346]
The validator is not properly identifying the HTML lang content when this code is being used:

`<!DOCTYPE html>`
`<!--[if lt IE 7 ]> <html class="ie6 lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->`
`<!--[if IE 7 ]> <html class="ie7 lt-ie9 lt-ie8" lang="en"> <![endif]-->`
`<!--[if IE 8 ]> <html class="ie8 lt-ie9" lang="en"> <![endif]-->`
`<!--[if IE 9 ]> <html class="ie9 no-js" lang="en"> <![endif]-->`
`<!--[if (gt IE 9)|!(IE)]> <html lang="en"> <![endif]-->`
`    <head>`

It's telling me that I don't have `<html lang="en">` in my HTML.

If you have any questions, I can be reached at kgrammer@classroom24-7.com.

**Comment by nschonni** [comment]
The last one should be wrapped like 
```
<!--[if gt IE 9]><!-->
<html class="no-js" lang="{{language}}" dir="{{{i18n "lang-dir"}}}">
<!--<![endif]-->
```
Note the comment escaping `<!-->`, because modern browsers won't read the IE conditionals at all

**Comment by classroom24-7** [comment]
Yeah, we were talking about that this afternoon before leaving ahead of the Hurricane (we are in Gainesville, FL).  We are actually considering removing all of that because we don't support anything older than IE 9 and won't support it much longer.

Thanks for the tip!

**Comment by sideshowbarker** [comment]
Yeah all the lines between `<!DOCTYPE html>` and `<head>` in https://github.com/validator/validator/issues/346#issue-174616901 are just treated as comments by browsers (other than IE I guess, any maybe Edge?).

Anyway the solution is to instead either use the syntax @nschonni describes in https://github.com/validator/validator/issues/346#issuecomment-244272855 or to just drop all of it an only have the `html` start tag with no conditional comment.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/346#issuecomment-244663146
