### ISSUE TITLE
Pages that contain java code are identified as english, no matter what the actual language is.

### ISSUE THREAD

**Issue by cguckes** [validator/validator#347]
I tested the validator on this page: 
https://blog.torq-dev.de/generische-junit-tests-fuer-interface-vererbung/

It's a german page and it identifies it as english. The majority of the text is german, only the code is commented in english.

**Comment by sideshowbarker** [comment]
Thanks for catching this and taking time to report it. I’ve pushed a fix to https://validator.w3.org/nu/

If you catch other cases of misidentification please do report them.

**Comment by cguckes** [comment]
Not a problem. I use your service fairly regularly, it's the least I can do.
