### ISSUE TITLE
File an issue report

### ISSUE THREAD

**Issue by u6nu83** [validator/validator#348]
http://luciya.web.hdv.tw/sandolly_web/productsearch/productsearch_list
This page's languages is  "zh-hans" not "en"

**Comment by jaimeiniesta** [comment]
Duplicate of #349 ?

**Comment by sideshowbarker** [comment]
I made a change to the language detector today that appears to have eliminated the language-misidentification problem reported here.

So I am going to close this issue for now. But if the problem re-occurs or you find other documents that get misidentified as the wrong language, please file a new issue here.
