### ISSUE TITLE
[Bug] Consider using lang="ce" (or variant) instead

### ISSUE THREAD

**Issue by Arttse** [validator/validator#353]
A bug in the definition in https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.options-review.com

> Warning: This document appears to be written in Chechen but the html start tag has lang="ru-ru". Consider using lang="ce" (or variant) instead.

But this site only in Russian language. So `lang="ru-ru"` is correct. I have not found a single Chechen character, or maybe I'm not very well tested. How is it determined language?

Another thing I noticed, from time to time if you check this site in the `validator.w3.org/nu`, it says `Document checking completed. No errors or warnings to show.`

**Comment by sideshowbarker** [comment]
> A bug in the definition in https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.options-review.com

>> Warning: This document appears to be written in Chechen but the html start tag has lang="ru-ru". Consider using lang="ce" (or variant) instead.

> But this site only in Russian language. So `lang="ru-ru"` is correct.

I made a change to the language detector recently that appears to have eliminated the language-misidentification problem the document reported here.

So I am going to close this issue for now. But if the problem re-occurs or you find other documents that get misidentified as the wrong language, please file a new issue here.

> Another thing I noticed, from time to time if you check this site in the `validator.w3.org/nu`, it says `Document checking completed. No errors or warnings to show.`

Yeah the language detector works on a random sample of text from each document it checks; so the results can non-deterministic depending on what part of the document it samples.

Anyway, I think misidentifications should happen much less frequently now, after the change I made.

**Comment by Arttse** [comment]
Thanks!
