### ISSUE TITLE
build.py:1109 "urlopen() got an unexpected keyword argument 'cafile'"

### ISSUE THREAD

**Issue by jmullee** [validator/validator#354]
```
diff --git a/build/build.py b/build/build.py
index ac7f09f..8f7a45c 100755
--- a/build/build.py
+++ b/build/build.py
@@ -1106,7 +1106,7 @@ def fetchUrlTo(url, path, md5sum=None):
   while not completed:
    try:
     socket.setdefaulttimeout(httpTimeoutSeconds)
-    f = urlopen(url, cafile=CAFILE)
+    f = urlopen(url)
     data = f.read()
     f.close()
     completed = True
```

**Comment by jmullee** [comment]
looking into why only htps for whatwg.org fails -
possibly python urlopen using ipv6 ? ip6:whatwg.org times out
 - https://www.ssllabs.com/ssltest/analyze.html?d=wiki.whatwg.org
hmm
 - http://stackoverflow.com/questions/18007174/python-urllib2-force-ipv4

**Comment by sideshowbarker** [comment]
@takenspc It would be good to know your thoughts on how to resolve this.

**Comment by dm-wyncode** [comment]
I was running into this exact error 

> "urlopen() got an unexpected keyword argument 'cafile'"

when I used `python ./build/build.py all`

The error was not thrown when I used

`python3 ./build/build.py all`

**Comment by sideshowbarker** [comment]
@takenspc I am still hoping to get your thoughts on how to resolve this

**Comment by sideshowbarker** [comment]
@jmullee please give the build a try now and see if runs to completion for you

@ dm-wyncode if you’re able to give a try again too that would be great (in Python 2)
