### ISSUE TITLE
Warning appears during the validation

### ISSUE THREAD

**Issue by neymanroman** [validator/validator#356]
I tried to validate the page but I have got this warning:
This document appears to be written in Estonian but the html start tag has lang="ru". Consider using lang="et" (or variant) instead.
From line 1, column 16; to line 2, column 16
TYPE html> ↩<html lang="ru">↩

But this page contains russian text (http://elitcomplekt.ru/)
What should I do in this situatin?

**Comment by sideshowbarker** [comment]
I made a change to the language detector recently and that appears to have eliminated the language-misidentification problem for http://elitcomplekt.ru/

So I am going to close this issue for now. But if the problem re-occurs or you find other documents that get misidentified as the wrong language, please file a new issue here.
