### ISSUE TITLE
Warn about <keygen>

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#359]
HTML says

> This feature is in the process of being removed from the Web platform. (This is a long process that takes many years.) Using the keygen element at this time is highly discouraged.

https://html.spec.whatwg.org/multipage/forms.html#the-keygen-element

There should be a warning for `<keygen>`

**Comment by sideshowbarker** [comment]
Fixed by 5c2eb05.

**Comment by zcorpan** [comment]
I assume https://github.com/validator/validator/commit/8abce40c5d39adf7eb438ced62224321a110f43d

**Comment by sideshowbarker** [comment]
> I assume 8abce40

oofs yeah, updated
