### ISSUE TITLE
Support <script type=module>

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#364]
https://github.com/whatwg/html/pull/443

(Not supported in browsers yet I think but filing this here to track it.)

**Comment by sideshowbarker** [comment]
HTML spec uses it so I’m going ahead and adding support for it.

We can add a warning later if needed.

**Comment by zcorpan** [comment]
Sweet, but it's missing this:

* `defer` and `charset` are not allowed on module scripts

I think it'd be good to include the warning. Having people accidentally (or deliberately) use `type=module` before it's supported and relying on it *not* executing (maybe with some "smart" polyfill) could lead to needing to mint a new name instead of "module"...
