### ISSUE TITLE
Internal Error for <input autocomplete="section-foo">

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#365]
```
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<input autocomplete="section-foo">
</html>
```

Internal Error: Oops. That was not supposed to happen. A bug manifested itself in the application internals. Unable to continue. Sorry. The admin was notified.

**Comment by sideshowbarker** [comment]
Not sure what the cause was but I can’t reproduce this now. If you can still, please re-open

**Comment by zcorpan** [comment]
Also can't reproduce.
