### ISSUE TITLE
Confirm whether slf4j, antlr, junit, jsontools dependencies are actually needed

### ISSUE THREAD

**Issue by sideshowbarker** [validator/validator#37]
As part of a set of changes made to the `build.py` script in https://github.com/validator/validator/commit/130dcd8850533fd0948f6e94add180c549e0789d and in the interest of trimming some clutter out of the build, I recently removed the following dependencies:

* antlr
* junit
* jsontools
* slf4j

In my testing, the code builds and starts up and runs as expected without those, and the service seems to work as expected without them.

As far as I can glean, antlr, junit, and jsontools are only referenced in the htmlparser test-harness code, which don't actually use for the validator. So I think dropping those from the set of the dependencies the build downloads and puts into the classpath isn't going to have any unexpected effects.

But I'm less sure about slf4j. It seems like it may be used under some circumstances by the jetty code or maybe in the case where you're installing the vnu.war as an app within another servlet engine.

So @jacobq, can you please confirm whether or not the sl4j code needs to be included in the war file for some reason? If it turns out it's actually need in there, then I can restore it. But as far as I can see, even cases where sl4fj is actually needed, the need can be met by just separately downloading the sl4fj jar(s) and adding the jar(s) to your classpath.

But as far as the default behavior of the validator service goes, it doesn't seem to be relying on having sl4fj around at all—and if so, then I'd rather we not have it among the set of dependencies that we download and package up into vnu.jar and vnu.war.

**Comment by jacobq** [comment]
I'm pretty sure they're not used in the WAR building code, but I'll plan to scan through the servlet code to see if slf4j is used. Personally, I'd like to leave that dependency there, but I also understand the desire to keep things lean and uncluttered. Unfortunately this week is super busy for me at work, but I've penciled some time on my calendar Saturday. I have a bad habit of letting requests rot though, so if a week goes by feel free to nag me and accept my apologies in advance :)

**Comment by sideshowbarker** [comment]
Hi @jacobq, OK and thanks for the reply—I'll plan to follow up with you next week. I'm not at all opposed to restoring the slf4j jar to the war package (and jar package too) but so far it's just not been clear to me in what other code and what other context that bundled sl4j code is actually ending up being used.

**Comment by cvrebert** [comment]
Upgrading slf4j to a more recent version would also be nice, if you're going to keep it around.

**Comment by sideshowbarker** [comment]
> Upgrading slf4j to a more recent version would also be nice, if you're going to keep it around.

Agreed we should upgrade it if we keep it. But in two weeks of running without the slf4j dependency—both running a lot of tests locally and running without slf4j in the environment of the W3C validator (which processes on the order of at least 6 requests every second…), no errors due to the slf4j dependency have occurred. So as far as I can see, it's never getting exercised, so there's no point in restoring it.

**Comment by cvrebert** [comment]
Great! It was giving me grief when trying to use slf4j for application-level logging anyway :smile:

**Comment by sideshowbarker** [comment]
Closing this, as it’s been a few weeks and no problems were reported.
