### ISSUE TITLE
vector-effect="non-scaling-stroke"

### ISSUE THREAD

**Issue by catalinred** [validator/validator#373]
I'm constantly getting the following validation error: "**Attribute “vector-effect” not allowed on element “path/circle/etc” at this point.**" whenever I want to add `vector-effect="non-scaling-stroke"` on an [SVG inner element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element).

	<svg width="200" height="200" viewBox="0 0 50 50">
	  <title>Plus icon</title>
	  <circle cx="25" cy="25" r="20" fill="none" stroke="#000" stroke-width="2" vector-effect="non-scaling-stroke"/>
	  <path d="M25 15 L 25 35" fill="none" stroke="#000" stroke-width="2" vector-effect="non-scaling-stroke"/>
	  <path d="M15 25 L 35 25" fill="none" stroke="#000" stroke-width="2"  vector-effect="non-scaling-stroke"/>
	</svg>

What am I missing? [https://www.w3.org/TR/SVGTiny12/painting.html#VectorEffectProperty](https://www.w3.org/TR/SVGTiny12/painting.html#VectorEffectProperty)

**Comment by sideshowbarker** [comment]
Do any web browsers actually support `vector-effect="non-scaling-stroke"`? The policy we have generally followed for the checker is to not recognize markup until it’s actually supported in browsers. There are many features in SVG Tiny 1.2 and SVG 2 that are not supported in browsers yet at all. So if we were to add anything specific for those cases to the checker, it would be to have it emit a warning saying, “This feature is not supported in browsers yet.”

**Comment by catalinred** [comment]
As far as I tested, `vector-effect="non-scaling-stroke"` is supported in latest Chrome, Firefox, Opera and Safari. No Edge support for now. 

I do agree with the policy you follow regarding the checker and I think it is correct to not recognize markup until it’s actually supported in browsers. Still, this has a pretty decent browser support and, as you also suggest, a warning message would be more fair, maybe. 

But I guess the tricky thing would be to compute and maintain this list of specific stuff to show warnings for.

**Comment by sideshowbarker** [comment]
> As far as I tested, `vector-effect="non-scaling-stroke"` is supported in latest Chrome, Firefox, Opera and Safari. No Edge support for now.

Yup, looking at http://codepen.io/thebabydino/pen/oXpWjd and other places now I see that. Sorry, I should have taken time first to test it.

So thanks for report this—I will add checker support for it soon (and post a comment here after I’ve pushed it to the checker).

**Comment by sideshowbarker** [comment]
I’ve pushed `vector-effect` support to https://checker.html5.org/  and https://validator.w3.org/nu/

If you test and find that I missed anything, please post a comment here and feel free to re-open.

Thanks again for taking time to report this

**Comment by catalinred** [comment]
Thanks for your help!
