### ISSUE TITLE
Nu Html Checker - file upload issue

### ISSUE THREAD

**Issue by blaminack** [validator/validator#374]
First, select "file upload", browse and select file, click "Check" - **It works fine!**
The "file upload", "Browse" and "Check" remain.
Browse and select file again and click "Check".
**The screen refreshes and displays an error. The selection is changed to "address".**

**Comment by sideshowbarker** [comment]
I’ve not been able to reproduce this. Does it happen for you in all browsers? Or just in one browser?

**Comment by sideshowbarker** [comment]
Closing for lack of response
