### ISSUE TITLE
Wrong warning language is correct lang="de"

### ISSUE THREAD

**Issue by GrischaK** [validator/validator#381]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.lern-online.net%2Fmathematik%2Farithmetik%2Fzahlen%2Ffigurierte-zahlen%2Fpentatopzahlen

lang="nl" isn't correct, so the suggestion is wrong.

**Comment by sideshowbarker** [comment]
I made a change to the language detector today and that appears to have eliminated the language-misidentification problem for the document reported in this issue.

So I am going to close this issue for now. But if the problem re-occurs or you find other documents that get misidentified as the wrong language, please file a new issue here.
