### ISSUE TITLE
his document appears to be written in Portuguese but the html start tag has lang="es". Consider using lang="pt" (or variant) instead.

### ISSUE THREAD

**Issue by Mijsoot** [validator/validator#384]
Hello,
http://www.mannequins-online.com/sp/bustos-maniquies/bustos-de-senora/busto-de-senora-maniqui-do1040-1479.html

I confirm you that the language is Spanish :

Warning: This document appears to be written in Portuguese but the html start tag has lang="es". Consider using lang="pt" (or variant) instead.
From line 1, column 16; to line 2, column 16
TYPE HTML>↩<html lang="es">↩<head
For further guidance, consult Declaring the overall language of a page and Choosing language tags.
If the HTML checker has misidentified the language of this document, please file an issue report or send e-mail to report the problem.

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I have pushed a change to https://validator.w3.org/nu/ that fixes the problem with the document reported in the description for this issue. If you find other documents for which the language is getting misidentified, please raise other issues.
