### ISSUE TITLE
Error detection russian lang, see warning that it's bulgarian web site

### ISSUE THREAD

**Issue by sergo44** [validator/validator#388]
I validated http://www.na-dom-mame.ru and seen warning
"Warning: This document appears to be written in Bulgarian but the html start tag has lang="ru". Consider using lang="bg" (or variant) instead."
But it's in russian only.

Thank's

**Comment by sideshowbarker** [comment]
I’ve pushed a workaround for this to https://validator.w3.org/nu/ and the results for https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.na-dom-mame.ru%2F no longer show a “This document appears to be written in Bulgarian” warning.

**Comment by ichepurnoy** [comment]
@sideshowbarker Hi! I'm still getting that same problem occasionally on my forum. For example on this category view, but NOT in any of its topics.   Lang attributes in both are the same. https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.vet.zp.ua%2Fforum-i-obshenie%2Fforum%2F13-zadaite-vopros-veterinarnomu-vrachu%2F   
So is it a problem with my site or the validator ?

**Comment by sideshowbarker** [comment]
HI @ichepurnoy 
> So is it a problem with my site or the validator ?

It was a problem with the validator, not with your site.

But I’ve now fixed it, so if you try again you will find the validator no longer misidentifies the language of your site as being Bulgarian.
