### ISSUE TITLE
use of ARIA implicit semantics = warning

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#39]
The use of default implicit role semantics is now a 'should not'
https://specs.webplatform.org/html-aria/webspecs/master/#document-conformance-requirements-for-use-of-aria-attributes-in-html
Suggest flagging a warning with reference to note

>Setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and is NOT RECOMMENDED as these properties are already set by the browser.
https://specs.webplatform.org/html-aria/webspecs/master/#h-note1

**Comment by sideshowbarker** [comment]
Excellent 🐲
I’ll try to get this added this week

**Comment by sideshowbarker** [comment]
Pushed to https://validator.w3.org/nu/

**Comment by thibaudcolas** [comment]
The webplatform links above are now broken. In case anyone else is looking for the reasoning behind this warning like me, I believe this is the correct resource: https://w3c.github.io/html-aria/#docconformance.

It would be nice if the warning had a reference to the correct part of the spec like suggested above – but for now hunting the source works too 🙂.
