### ISSUE TITLE
Filtering validation error messages for CI process

### ISSUE THREAD

**Issue by violinner** [validator/validator#391]
For a continuous integration build process, I am using validator as a library called by an automated test framework.  The validation is intended to screen for high-risk errors, and needs to ignore many others.

Is there a built-in or maintainable way to filter a list of specific errors to ignore?

**Comment by sideshowbarker** [comment]
There is is not yet a built-in or maintainable way to filter a list of specific errors to ignore. We would welcome a patch for one.

Other projects have dealt with the deficiency bad adding their own filtering mechanisms. See for example [the code that the (Java) `lmvtfy` tool uses to ignore certain errors](https://github.com/cvrebert/lmvtfy/blob/860b0447f6a0ab8508b6d081a87d81273b1dbf4e/src/main/scala/com/chrisrebert/lmvtfy/validation/Html5Validator.scala#L51) or see the backend for [the `ignore` option in (JavaScript) `grunt-html`](https://github.com/jzaefferer/grunt-html#ignore).

If your implementation is in Java, @cvrebert (`lmvtfy` author) especially might be able to give you some guidance on how best to add filtering.

**Comment by violinner** [comment]
I have a working filter based on a copy of MessageEmitterAdapter (cannot extend a final class), with a call to a filtering discriminator "isAllowed()" in methods warning() and error().  A JSON persisted configuration class is used to load ignored error and warning messages, which has a "debug" flag that ignores everything and prints a uniquely sorted list of all the errors encountered-- potentially to add some of them to the "ignored" list.  Everything is chained through a Selenium and ChromeDriver browser test framework.

There are two problems so far:  1) Testing is difficult (changed a number of private methods to public to unit test), and 2) method MessageEmitterAdapter.elaboration(Exception e) has some dead code due to two cases testing for "if (e instanceof StringNotAllowedException)"

I will try to post the suggested changes soon.

**Comment by sideshowbarker** [comment]
Thanks for the update—sounds like good progress

**Comment by sideshowbarker** [comment]
Given that the checker does now have a message-filtering feature and it’s documented at https://github.com/validator/validator/wiki/Message-filtering, I’m gonna go ahead and close this out. But feel free to comment here if any clarification is needed
