### ISSUE TITLE
Report error when integrity="" is used on non-stylesheet <link> or non-classic <script>

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#395]
See https://github.com/whatwg/html/pull/1984#issuecomment-258115046

Examples:

```html
<!doctype html>
<title>x</title>
<link rel="icon" href="x" integrity="sha256-1337">
<div itemscope><link itemprop="x" href="x" integrity="sha256-1337"></div>
<script type="text/plain" integrity="sha256-1337"></script>
<script type="module" src="x" integrity="sha256-1337"></script>
<script integrity="sha256-1337"></script>
```
The last one I think is conforming per spec but that is a spec bug (https://github.com/whatwg/html/pull/2011).

**Comment by jhabdas** [comment]
I believe there's an issue in this implementation. Left a note here: https://github.com/whatwg/html/pull/1984#issuecomment-464961671

Bottom line, `integrity` on inline scripts should be allowed. Forbidding it will lead to reduced security through the use of `inline-unsafe` or externalized scripts which could hurt performance.
