### ISSUE TITLE
 HTML checker has misidentified the language

### ISSUE THREAD

**Issue by pedroborregoinmediatamente** [validator/validator#406]
the validator responds with an error 

>  This document appears to be written in English but the html start tag has lang="it". Consider using lang="en" (or variant) instead.

even when page is actually in italian language, this is not happening with all pages but just one for now (still validating a few more before finishing the entire site).

**Comment by cvrebert** [comment]
We need either a link to or the HTML of the misidentified webpage in order to investigate the problem.

**Comment by pedroborregoinmediatamente** [comment]
[missidentified it language.txt](https://github.com/validator/validator/files/589899/missidentified.it.language.txt)

there you go I hope that helps.

**Comment by zcorpan** [comment]
I think it's because there is HTML in the `textarea`s (with URLs containing English-looking strings, and `width='1' height='1'`).

**Comment by sideshowbarker** [comment]
> I think it's because there is HTML in the `textarea`s (with URLs containing English-looking strings, and `width='1' height='1'`).

The language detector should already be ignoring all the `textarea`s in that doc, because they’re inside a `form` in that doc, and the language detector already ignores everything inside `form`s.

**Comment by sideshowbarker** [comment]
@pedroborregoinmediatamente I can’t reproduce this currently with https://validator.w3.org/nu/. ( I made some changes recently that may have fixed it.) Please let me know if you can still reproduce it, and I’ll investigate further.

**Comment by pedroborregoinmediatamente** [comment]
Thank you Sr. Effectively It does not reproduces the language tag warning any more.

**Comment by sideshowbarker** [comment]
@pedroborregoinmediatamente OK thanks I’ll go ahead and close this, then. But if you run problems with other documents please do raise issues here

**Comment by pedroborregoinmediatamente** [comment]
Good enough for me, thanks!
