### ISSUE TITLE
Local / teriminal behavior differs for DOCTYPE validation

### ISSUE THREAD

**Issue by still-dreaming-1** [validator/validator#408]
When I install this locally (version 16.6.29) and use it from the terminal, it behaves differently than the online service at https://validator.w3.org/nu/. Locally it considers `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">` to be an error: `error: Almost standards mode doctype. Expected “<!DOCTYPE html>”`. The public online validator recognizes this as a valid document type, which it should. https://www.w3.org/QA/2002/04/valid-dtd-list.html

**Comment by sideshowbarker** [comment]
Thanks for catching this. The bug is actually in the online validator. The online version should report the same error the jar reports. I don’t understand why it doesn’t but I’ll look into it and fix it.

> The public online validator recognizes this as a valid document type, which it should. https://www.w3.org/QA/2002/04/valid-dtd-list.html

https://www.w3.org/QA/2002/04/valid-dtd-list.html is just an informative reference. It’s not up to date with the current normative HTML requirements, which are here:

https://html.spec.whatwg.org/multipage/syntax.html#obsolete-permitted-doctype-string

Those requirements currently only allow the doctype to contain the system identifier for HTML4 Strict or XHTML 1 Strict or XHTML 1.1 Strict. Specifically, the requirements don’t allow the HTML4 Transitional doctype.

**Comment by sideshowbarker** [comment]
I’ve fixed this in the checker sources and pushed the fix to https://validator.w3.org/nu/

So the https://validator.w3.org/nu/ behavior on this should now be consistent with the jar behavior.

**Comment by still-dreaming-1** [comment]
Thanks for the help. That is interesting that HTML 4 transitional is no longer a valid doctype according to the standard. So basically between HTML 4 and 5, we are supposed to choose one or the other?

I want to understand what these options mean not just in terms of which one we are supposed to use, but how they might affect browser behavior. Of course each browser might behave a little differently, but I mean in terms what the standard does and does not guarantee if they succeeded in following the standard.

I'm guessing if I set the doctype to one of the HTML 4 values, this means the browser should work correctly with HTML 4, but it might not work at all with HTML 5 stuff. Is that right?

If I select HTML 5, the browser should work correctly with HTML 5, but will not necessarily work at all with HTML 4 code, and using HTML 4 code in that document is considered invalid from the standpoint of the specification. Is that right?

If those are both correct, this seems to mean that it is no longer valid to mix HTML 4 and HTML 5 in the same document whereas it used to be considered valid for HTML 4 transitional. Is that correct?

**Comment by sideshowbarker** [comment]
> So basically between HTML 4 and 5, we are supposed to choose one or the other?

No, you’re just supposed to use HTML, period. The HTML language is now versionless.

> I want to understand what these options mean not just in terms of which one we are supposed to use, but how they might affect browser behavior

Browsers process HTML without regard to any version. For browsers, HTML is versionless, just as with the language itself.

> I'm guessing if I set the doctype to one of the HTML 4 values, this means the browser should work correctly with HTML 4, but it might not work at all with HTML 5 stuff. Is that right?

No, browsers don’t care if you use an HTML4 doctype or the “HTML5” one. Browsers will process the document in exactly the same way regardless.

**Comment by still-dreaming-1** [comment]
That is super interesting and clarifies a lot, thanks! I guess I will just use `<!DOCTYPE html>` which is what the spec now says to use even though a lot of the HTML I am working with is still a mix of proper and outdated the artist formerly known as "HTML 4" stuff...

For element attributes that the validator says is an error because they should not longer be used, but they used to be valid at one point in time, what is the browser supposed to do when it encounters those? That might be hard to answer without a specific example so here is one. What is a browser supposed to do when it encounters a width attribute on a table element?

**Comment by cvrebert** [comment]
Outdated features are spec'd as "Browsers MUST implement them. Authors MUST NOT use them."
Web compatibility means that browsers will probably never be able to remove those features, or at least not for a *very* long time.
