### ISSUE TITLE
Validator trips over ♿️ value for class.

### ISSUE THREAD

**Issue by MichielBijl** [validator/validator#410]
I noted that the [validator trips over ♿️ as a value of `class`](https://twitter.com/MichielBijl/status/799782973767819264) on an `svg`.

Sample code:

```
<svg viewBox="0 0 120 120" class="♿️" aria-label="role=drinks logo">
  <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#role-drinks"></use>
</svg>
```

If you apply it to a `div` it doesn’t trip:

```
<div class="♿️">Okey doke</div>
```

**Comment by AmeliaBR** [comment]
For reference, here's the [`class` definition in the SVG 2 spec](https://www.w3.org/TR/SVG2/styling.html#ClassAttribute), which defers to the HTML spec for what makes a valid space-separated token.  The [SVG 1.1 definition](https://www.w3.org/TR/SVG11/styling.html#ClassAttribute) likewise put no restrictions on valid characters.

**Comment by sideshowbarker** [comment]
Thanks for catching this. Fix pushed to https://validator.w3.org/nu/ and https://checker.html5.org/

**Comment by MichielBijl** [comment]
Fantastic, thank you.
