### ISSUE TITLE
“The ‘abbr’ attribute on the ‘th’ element is [_not_] obsolete”

### ISSUE THREAD

**Issue by PointedEars** [validator/validator#412]
For `<th scope="col" id="hdr-feature" abbr="Feature">…</th>` in the [ECMAScript Support Matrix](http://PointedEars.de/es-matrix) (declared HTML 5.x), Nu Html Checker issues an error message that claims:

> The `abbr` attribute on the `th` element is obsolete. […]

*That is **not** so.* **The `th` element has a *standards-compliant* `abbr` attribute** in HTML 5.x:

- [HTML5, 28 October 2014, § 4.9.10 “The `th` element”](https://www.w3.org/TR/2014/REC-html5-20141028/tabular-data.html#the-th-element)
- [HTML 5.1, 1 November 2016, § 4.9.10 “The `th` element”](https://www.w3.org/TR/2016/REC-html51-20161101/tabular-data.html#the-th-element)
- [HTML 5.2 Working Draft, 25 October 2016, § 4.9.10 “The `th` element”](https://www.w3.org/TR/html52/tabular-data.html#the-th-element)
- [HTML 5.2 Editor’s Draft, 18 November 2016, § 4.9.10 “The `th` element”](https://w3c.github.io/html/tabular-data.html#the-th-element)

Instead, **the `abbr` attribute *on the `td` element* is obsolete *since HTML 5.1***:

- [HTML 5.1, 1 November 2016, § 11.2. “Non-conforming features”](https://www.w3.org/TR/2016/REC-html51-20161101/obsolete.html#non-conforming-features) (cf. [the same section in HTML5](https://www.w3.org/TR/2014/REC-html5-20141028/obsolete.html#non-conforming-features))
- [HTML 5.2 Working Draft, 25 October 2016, § 11.2. “Non-conforming features”](https://www.w3.org/TR/html52/obsolete.html#non-conforming-features)
- [HTML 5.2 Editor’s Draft, 18 November 2016, § 11.2. “Non-conforming features”](https://w3c.github.io/html/obsolete.html#non-conforming-features)

**Comment by sideshowbarker** [comment]
Thanks for catching this and taking time to report it. I’ve fixed it in the sources and pushed the fix to https://checker.html5.org/ and https://validator.w3.org/nu/
