### ISSUE TITLE
IO Error: Connect to [site] failed: connect timed out

### ISSUE THREAD

**Issue by Arttse** [validator/validator#416]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fxn--b1agaljvudi.xn--p1ai

![validator-io-error](https://cloud.githubusercontent.com/assets/7123950/20558144/bac6124e-b17f-11e6-9370-3b1ad83fd553.jpg)

**Comment by sideshowbarker** [comment]
The problem here does not appear to be specific to https://validator.w3.org/nu/ but instead to the network (at MIT) the server it runs on is in.

From the MIT network I can’t get a route to xn--b1agaljvudi.xn--p1ai from any tool.

To see what I mean try http://csvoss.scripts.mit.edu/traceroute/

**Comment by Arttse** [comment]
Thank you for the clarification. I guessed something similar, but thought it might be a problem with `validator.w3.org/nu` and you have the opportunity to fix. It seems that this problem can be solved only from the site where is hosted.
