### ISSUE TITLE
localhost only?

### ISSUE THREAD

**Issue by boistordu** [validator/validator#419]
Hi,

I wanted to know if you hardcoded any answer of your tool to send to localhost? I'm trying to integrate your tool in a docker container to use internally on a LAN network so I would need to use something else than localhost. So is it localhost hardcoded or is it something wrong with my container?

**Comment by sideshowbarker** [comment]
Please elaborate on what the question is here

**Comment by boistordu** [comment]
yes sorry I was mistyping enter:)

**Comment by boistordu** [comment]
is it enough understandable? I don't know if I'm presenting my poblem correctly enough

**Comment by sideshowbarker** [comment]
> yes sorry I was mistyping enter:)

No worries 😄 

> is it enough understandable? I don't know if I'm presenting my poblem correctly enough

I think it’s clear and I hope the answer is clear…

> I wanted to know if you hardcoded any answer of your tool to send to localhost?

See https://github.com/validator/validator/blob/master/src/nu/validator/servlet/Main.java#L94
With [`java.net.InetAddress.getByName(127.0.0.1)`](https://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html#getByName-java.lang.String-) as the `InetAddress ` arg, the code calls:

* [`java.net.Socket(InetAddress address, int port)`](https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#Socket-java.net.InetAddress-int- )
* [`java.net.ServerSocket(int port, int backlog, InetAddress bindAddr)`](https://docs.oracle.com/javase/8/docs/api/java/net/ServerSocket.html#ServerSocket-int-int-java.net.InetAddress-)

So it’s not hardcoded anywhere to use the name `localhost`; instead it uses the address `127.0.0.1`.

**Comment by boistordu** [comment]
Yeah okey it's the combination between markup validation service  and vnu who screwed things up . vnu works perfectly on standalone
