### ISSUE TITLE
CURL via PHP silently failed on missing Header

### ISSUE THREAD

**Issue by redaxmedia** [validator/validator#421]
Hello,

I used this great service via PHP and CURL using the endpoint for GET. From one day to another it stopped working, I figured out that the User-Agent was needed to get a result.

Please send a 404 or something similar with an error code like User-Agent is missing. At the moment there is a 200 status code including an empty result.

Best regards

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I remember now, the reason I had it reporting a 200 in this case was that if I have it report a 404 it causes a backend failure in our load-balancing setup that I don’t understand.

So I just now changed the source to respond with a 202 “Request accepted but lacks User-Agent header, so not processed.” message, and pushed the change to https://validator.w3.org/nu/ 

A 202 is maybe not the ideal semantic but I hope it achieves the right effect of informing users what happened with the request.

If not lemme know and I will look into it further when I can.

**Comment by redaxmedia** [comment]
Ok, fine...

**Comment by sideshowbarker** [comment]
We got the backend problem with 4xx errors fixed, so the checker now returns a 400 for this, which seems like the right thing.

Sorry for the churn and thanks again for taking time to report this.

**Comment by redaxmedia** [comment]
Giving back is an essential thing of open source, no need to thank people for that :-)
