### ISSUE TITLE
request: add dpub role values as conforming

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#427]
these roles have mappings to acc APIs
http://rawgit.com/w3c/aria/master/aria/dpub.html

mapping for implementation:
https://rawgit.com/w3c/aria/master/dpub-aam/dpub-aam.html

**Comment by richschwer** [comment]
thanks.

**Comment by sideshowbarker** [comment]
Added https://github.com/validator/validator/commit/63fd012d3dd15ed93206d847e12d7992b226d8da
