### ISSUE TITLE
Allow autonomous custom elements

### ISSUE THREAD

**Issue by domenic** [validator/validator#429]
E.g. https://checker.html5.org/?showoutline=yes&doc=https%3A%2F%2Ftc39.github.io%2Fecma262%2F gives a bunch of warnings saying

> If the element is not a child of a dl element: Flow content.

But flow content links to https://html.spec.whatwg.org/multipage/dom.html#flow-content-2 which includes autonomous custom elements

**Comment by cvrebert** [comment]
The validator doesn't allow custom elements at all currently. See #94

**Comment by domenic** [comment]
Yes, it seems like things have changed since that issue, however, as the spec is now updated.
