### ISSUE TITLE
Inappropriate error shows in W3C Validator

### ISSUE THREAD

**Issue by Aakash30Sethiya** [validator/validator#430]
> Warning: This document appears to be Lorem ipsum text but the html start tag has lang="en". Consider using lang="zxx" (or variant) instead.
> From line 5, column 23; to line 5, column 54
`E 8]><!--> <html  lang="en" class="no-js"> <!--<`

**Comment by sideshowbarker** [comment]
Thanks for reporting this. Are you able to post the rest of the content of the document which triggered that checker message? I need that in order to fix the language misidentification.

**Comment by Aakash30Sethiya** [comment]
I checked on my website other pages it seems normal but only one page gives
this kind of error, I think the validator find some lorem ipsum text that's
why it want to change the language from "en" to "zxx". But I want to know
that why this has happened to the single page only???

**Comment by cvrebert** [comment]
We'd need either a link to your page or a post of your page's HTML in order to determine why. We're not psychic.

**Comment by sideshowbarker** [comment]
Closing for lack of response. But feel free to reopen if there’s any new information.
