### ISSUE TITLE
Small fix for html5check.py

### ISSUE THREAD

**Issue by gilleslamiral** [validator/validator#434]
Hi,

    html5check.py -h file.html
    400 Bad request. Valid requests must include a User-Agent header.

The fix is just one line:

     connection.putrequest("POST", "%s?%s" % (parsed[2], parsed[3]), skip_accept_encoding=1)
    + connection.putheader("User-Agent", 'html5check.py/2008-02-12')
    connection.putheader("Accept-Encoding", 'gzip')

Adapt the "release number" /2008-02-12 or simply suppress it.

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this! Now fixed~
