### ISSUE TITLE
npm install faling for release 17

### ISSUE THREAD

**Issue by bstoney** [validator/validator#441]
Installing the current release 17.0.1 with the npm command `npm install vnu-jar` is failing with the error `npm ERR! cb() never called!`. Installing the previous release `npm install vnu-jar@^16` completes successfully.

I have tried running `npm cache clean` and the result is the same. I am running this on Windows with npm version 4.0.5 and nodejs version 5.9.0

**Comment by Arttse** [comment]
A similar problem is already on npm/npm#15395 with Node.js `5.9.x`. 

Just update Node.js to the `5.12.0` (latest `5.x`branch) and it will work. 

It's better to go to the Node.js stable version `6` LTS. Or you can try latest `7` version.

**Comment by bboysathish** [comment]
@Arttse Have you faced the similar problem and It solved by upgrading to 5.12.0 ? I am working on common build machine system, which have been used by many teams around the world, i don't have access and can't upgrade as it. Is there way i can overcome this issue. If there is a npm release and node.js release changelog says that it has been fixed then i can vouch for that version to upgrade.

**Comment by Arttse** [comment]
@bboysathish 
> Have you faced the similar problem and It solved by upgrading to 5.12.0 ?

Yes. It crashed with error `npm ERR! cb() never called!` if I install `vnu-jar` using Node.js `5.9.0` or `5.9.1`, NPM `3.7.3` (included) and NPM `4.0.5`.

Tested on Linux Ubuntu 16.04 and on Windows 10. With Node.js `5.12.0`, NPM `3.8.6` (included) and NPM `4.0.5` package `vnu-jar` was installed correctly.

Tested again on Linux Ubuntu 16.04 with Node.js `5.12.0` and NPM `3.8.6` (included):
![t](https://cloud.githubusercontent.com/assets/7123950/21798360/ffd80bf6-d724-11e6-98b1-509494d83793.gif)

Tested again on Windows 10 with Node.js `5.12.0` and NPM `3.8.6` (included):
![w2](https://cloud.githubusercontent.com/assets/7123950/21799844/ffdd1e5a-d72b-11e6-861d-7a3ec964c7b8.gif)

So just update Node.js to `5.12.0`. Or update to closest `5.10.0` which also works.

**Comment by sideshowbarker** [comment]
So is there anything I need to do for this? Or can it be closed?

**Comment by Arttse** [comment]
I think you can close. The decision is written. If someone has another solution let write here.

**Comment by sideshowbarker** [comment]
OK, closing for now. But feel free to continue to comment here as needed, or reopen if needed.
