### ISSUE TITLE
aria-required=true allowed on input types that allow required attribute

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#447]
this for example, throws an error it shouldn't
`<input type="password" aria-required="true">`

refer to https://www.w3.org/TR/html-aria/#attr-required

> Use the aria-required attribute on any element that is allowed the required attribute in HTML5. MUST NOT be set to false if the required attribute is set.

**Comment by sideshowbarker** [comment]
OK I can align the checker with the spec on this, though I am confused about why an `aria-required` attribute should ever be necessary for elements that already have a native `required` attribute.

**Comment by stevefaulkner** [comment]
@sideshowbarker legacy support in this case http://caniuse.com/#feat=form-validation, also the UI error messages etc associated with required are flaky across browsers, and many devs still roll thier own error UI and we still want them to programmatically expose the required state even though they don't use the required attribute.

**Comment by sideshowbarker** [comment]
OK well that all sounds like a pretty broken and depressing state of affairs but at least it helps make clear why I should add this for the checker

**Comment by HugoGiraudel** [comment]
> OK well that all sounds like a pretty broken and depressing state of affairs but at least it helps make clear why I should add this for the checker

Welcome to the web. :D

**Comment by sideshowbarker** [comment]
Fixed and pushed to https://validator.w3.org/nu/
