### ISSUE TITLE
Element 'track' not allowed as child of element 'video' in this context.

### ISSUE THREAD

**Issue by BaelfireNightshd** [validator/validator#449]
Contexts in which element `track` may be used:
As a child of a `media element`, before any `flow content`.

Element `video` is a `media element` according to the html 5.2 specification.

**Comment by sideshowbarker** [comment]
Please post a document or URL which demonstrates the problem.

Do you have child content in the `video` element before the `track` element?

**Comment by BaelfireNightshd** [comment]
After some sleep I reread the description of `flow content` and realized that `text` counts as a flow content. I changed my HTML and the validated no longer complains. Thus this issue is closed.

**Comment by sideshowbarker** [comment]
OK—thanks for having taken time to report it & please don’t hesitate to report other issues if/when you find them
