### ISSUE TITLE
<link rel="SHORTCUT ICON"> handled incorrectly (case-sensitive)

### ISSUE THREAD

**Issue by Socob** [validator/validator#453]
The standards ([W3C](https://www.w3.org/TR/html5/links.html#linkTypes), [WHATWG](https://html.spec.whatwg.org/multipage/semantics.html#linkTypes)) specify that
> Link types are always [ASCII case-insensitive](https://www.w3.org/TR/html5/infrastructure.html#ascii-case-insensitive), and must be compared as such.
> > Thus, `rel="next"` is the same as `rel="NEXT"`.

Specifically, for the `icon` link type  ([W3C](https://www.w3.org/TR/html5/links.html#rel-icon), [WHATWG](https://html.spec.whatwg.org/multipage/semantics.html#rel-icon)):
> For historical reasons, the `icon` keyword may be preceded by the keyword "`shortcut`". If the "`shortcut`" keyword is present, it must be come immediately before the `icon` keyword and the two keywords must be separated by only a single `U+0020 SPACE` character.

However, recently the validator at validator.w3.org/nu has begun flagging any spelling of `rel="shortcut icon"`, where “shortcut” is not all lower-case, as an error. Consider the following to outputs from the validator instance at W3C (note: may trigger XSS warnings in NoScript or similar browser addons/features):
- [lower case (`rel="shortcut icon"`)](https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fhtml%3Bcharset%3DUTF-8%2C%3C%21DOCTYPE+html%3E%3Chtml%3E%3Chead%3E%3Ctitle%3E-%3C%2Ftitle%3E%3Clink+rel%3D%22shortcut+icon%22+href%3D%22%2F%2Fwww.w3.org%2F2008%2Fsite%2Fimages%2Ffavicon.ico%22%3E%3C%2Fhead%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E)
- [upper case (`rel="SHORTCUT ICON"`)](https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fhtml%3Bcharset%3DUTF-8%2C%3C%21DOCTYPE+html%3E%3Chtml%3E%3Chead%3E%3Ctitle%3E-%3C%2Ftitle%3E%3Clink+rel%3D%22SHORTCUT+ICON%22+href%3D%22%2F%2Fwww.w3.org%2F2008%2Fsite%2Fimages%2Ffavicon.ico%22%3E%3C%2Fhead%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E)

The first case does not report any errors, as expected, but the second case says

> **Error:** Bad value` SHORTCUT ICON` for attribute `rel` on element `link`: The string `SHORTCUT` is not a registered keyword.

Considering the statements from the standards above, I believe that this is a mistake (and it doesn’t make sense to demand lower case here, anyway). A quick search indicates that the issue seems to stem from [the `isRegistered()` method in `LinkRel.java`](https://github.com/validator/validator/blob/71517ecd11fe2c6067d2d135e886a567b1aea07b/src/nu/validator/datatype/LinkRel.java#L75-L89). Line 77 says `if ("shortcut".equals(token)) {`, which should instead probably be something like `if ("shortcut".equals(token.toLowerCase())) {`. After a cursory look, it seems to me like this issue was triggered by [this recent change in `AbstractRel.java`](https://github.com/validator/validator/commit/fcdaa2fac98f6ec342ead4961a325350227d9aed#diff-bd10a97cb94e2fa67dae08ec4ac2e49b) in fcdaa2fac9.

**Comment by sideshowbarker** [comment]
Thanks much for catching this and taking time to report it. I’ve pushed the fix to https://checker.html5.org/ and https://validator.w3.org/nu/
