### ISSUE TITLE
Exit status from the command line

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#457]
It looks like the jar is returning a non-zero exit status when completing a check, which is interpreted as an error. For example, this will return a zero status so the execution can continue:

```
$ java -jar ./node_modules/vnu-jar/build/dist/vnu.jar --version http://example.com && echo SUCCESS
17.2.0
SUCCESS
```

But this will not get to the `echo SUCCESS` point:

```
$ java -jar ./node_modules/vnu-jar/build/dist/vnu.jar --format json http://example.com && echo SUCCESS
{"messages":[{"type":"error","url":"http://example.com","lastLine":7,"lastColumn":73,"firstColumn":5,"message":"A document must not include both a “meta” element with an “http-equiv” attribute whose value is “content-type”, and a “meta” element with a “charset” attribute.","extract":"8\" />\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n    <","hiliteStart":10,"hiliteLength":69}]}
```

So, the example for the [vnu-jar npm package](https://www.npmjs.com/package/vnu-jar) works fine, but if we make it perform a real check, it will log an error:

```js
'use strict';

const exec = require ( 'child_process' ).exec;
const vnu = require ( 'vnu-jar' );

// Print path to vnu.jar
console.log ( vnu );

// Work with vnu.jar
// for example get vnu.jar version
exec ( `java -jar ${vnu} --format json http://example.com`, ( error, stdout ) => {

    if ( error ) {
        console.error ( `exec error: ${error}` );
        return;
    }

    console.log ( stdout );

} );
```

Output:

```
$ node example.js
/Users/jaime/code/nu-js/node_modules/vnu-jar/build/dist/vnu.jar
exec error: Error: Command failed: java -jar /Users/jaime/code/nu-js/node_modules/vnu-jar/build/dist/vnu.jar --format json http://example.com
{"messages":[{"type":"error","url":"http://example.com","lastLine":7,"lastColumn":73,"firstColumn":5,"message":"A document must not include both a “meta” element with an “http-equiv” attribute whose value is “content-type”, and a “meta” element with a “charset” attribute.","extract":"8\" />\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n    <","hiliteStart":10,"hiliteLength":69}]}
```

**Comment by sideshowbarker** [comment]
The command-line checker intentionally returns a non-zero status if a document has errors.

Is that what you’re referring to?

If so, it’s not something new—it’s been doing that more than 2 years now.

The rationale for that behavior is, it enables the checker to be used in CI systems such as Travis. And the initial reason I changed it to do that was from a feature request: https://github.com/validator/validator.github.io/issues/2

So are you proposing we have the checker instead always exit 0 even for documents with errors?

**Comment by jaimeiniesta** [comment]
Thanks for the explanation, it makes sense.

Yes, I was referring to this. I expected the command-line checker to return 0 even for documents with errors, meaning "the checks were performed, here are the results... 0 errors found".

With the actual behaviour, on the npmjs script above, how can we differentiate between a check that found errors (non-zero exit status), and a java exception or other situation that results in a crash?

To put this in context, I'm conducting an experiment to run the command line checker as an AWS Lambda function, which basically does the same as the above script, and returns the results as JSON. This is why I was expecting a zero exit status for a succesful completion of the check (successful in the sense that it completed without exception, with or without findind an HTML issue).

I guess the best solution will be not relying on the exit status code, and instead check if the checker returned a JSON response with the expected format?

**Comment by sideshowbarker** [comment]
> With the actual behaviour, on the npmjs script above, how can we differentiate between a check that found errors (non-zero exit status), and a java exception or other situation that results in a crash?

I don’t know. But that context is not one I considered when implementing the current behavior (we didn’t have an npm package til very recently, so I didn’t really anticipate this).

> I guess the best solution will be not relying on the exit status code, and instead check if the checker returned a JSON response with the expected format?

For now yeah I guess that’s the best way to work around it. But it seems like the right way to address it would be to add a new option to the checker to opt in to making it exit zero even for documents that have errors.

That would work for you, right?

**Comment by jaimeiniesta** [comment]
> But it seems like the right way to address it would be to add a new option to the checker to opt in to making it exit zero even for documents that have errors.

:+1: This would be great, yes!

**Comment by sideshowbarker** [comment]
OK, will make time to get the option added very soon

**Comment by sideshowbarker** [comment]
Added `--exit-zero-always` option & pushed a nightly to https://sideshowbarker.net/nightlies/jar/ and a new npm to the `dev` branch—which you can get with `npm install --save vnu-jar@dev`

**Comment by jaimeiniesta** [comment]
This worked fine - I still had to look for the output on `stderror` instead of `stdout`, not sure if that's intended? Wouldn't it be more coherent to use `stdout` when using this new option?

**Comment by sideshowbarker** [comment]
> This worked fine - I still had to look for the output on `stderr` instead of `stdout`, not sure if that's intended? Wouldn't it be more coherent to use `stdout` when using this new option?

I think changing that could break existing scripts/tools that others have set up which expect the results to go to `stderr`. I wouldn’t think that people would expect that when they change the exit status, the file descriptor the messages go to should also change.

I guess a reasonable argument can be made that the checker should be sending results to `stdout` in all cases always anyway. But I’m kind of loathe to change it now. I recall there was some logic to the `stderr` choice when I made it originally but I don’t remember the specific rationale now.

**Comment by jaimeiniesta** [comment]
Sounds good. As long as all the output always goes to the same place then it's OK. I was afraid that when HTML issues were found, `stderr` would be used but when no issues were found, then the output would be on `stdout`, but I've checked and it always goes to `stderr`.
