### ISSUE TITLE
paragraph: validator does not dedect missing </p> or wrong end tag <p> in Chrome

### ISSUE THREAD

**Issue by AnnLow** [validator/validator#461]
```html
<!DOCTYPE html>
<html lang="nl">
<head>
  <Title>p end tag </Title>
  <meta charset="UTF-8">
</head>
<body>
<h2 id="r">Me</h2>
	<div>
		<p>a.</p>
		<p><em>Li</em><p>
		<p><em>M</em> </p>
		<p><em>E</em> </p>
		<p>Hns<a href="#z">K</a>.
	</div>
</body>
```
=>results in a validated html, even though the end `</p>` paragraph tag is missing or wrong `<p>`

**Comment by sideshowbarker** [comment]
The `p` element’s end tag is optional in most cases, per the HTML spec:

https://html.spec.whatwg.org/#the-p-element:syntax-end-tag

So the document in the description for this is in fact valid per the HTML spec.
