### ISSUE TITLE
Documentation on Output

### ISSUE THREAD

**Issue by jarodium** [validator/validator#466]
Hello,

I have been trying to use the webservice with output JSON.
I would like to know where I should start highlighting the code.
I mean, I use the firstColumn/lastColumn pair or should I use the hiliteStart and hiliteLength pair?
The docs do not mention these so the only ones I can use for these are the first and last column.

**Comment by sideshowbarker** [comment]
You need to use both the `lastLine`/`lastColumn` pair *and* the `hiliteStart` and `hiliteLength` pair.

Here’s an example:
```json
{
	"type"   : "info",
	"subtype": "warning",
	"lastLine"   : 20,
	"lastColumn" : 15,
	"url"    : "http://example.com/",
	"message": "Trailing slash for void element",
	"extract": "<br/>",
	"hiliteStart" : 3,
	"hiliteLength" : 1
},
```

So for that case, you:

1. Go line 20, column 15
    You will find the string "`<br/>`" there.

2. At that line 20, column 15 point, in the string you find at that point, count over by the  value of `hiliteStart` and start highlighting there.
    So if you start counting at the beginning of `<br/>` and count over by 3 characters, that takes you to the position after the `r` and before the `\`. Start highlighting there.

3. Continue highlighting for the number of characters specified by `hiliteLength`, then stop there.
    You started at the position before the `\` character, so you go 1 character and stop.

So following the steps above, you end up with just one single character highlighted: the `\` character in `<br/>`.

**Comment by jarodium** [comment]
@sideshowbarker Thank you.
That helped. I was using both firstColumn but now I know how to work :)
