### ISSUE TITLE
'asciiQuotes' is hard-coded to 'false'

### ISSUE THREAD

**Issue by Artum** [validator/validator#469]
The `asciiQuotes` option is hard-coded to `false` without an option to override it from command line:
`-Dnu.validator.client.asciiquotes=no`

**Comment by sideshowbarker** [comment]
Thanks for raising this. The command-line checker now has an `--asciiquotes` option:

```bash
java -jar ~/vnu.jar --asciiquotes FILE.html
```
That will be included in the next stable release (probably some time next month).

In the mean time I’ve pushed out a nightly to https://sideshowbarker.net/nightlies/jar/

**Comment by theRealBaccata** [comment]
Merci
