### ISSUE TITLE
role="none" incorrectly flagged as error on img

### ISSUE THREAD

**Issue by dstorey** [validator/validator#472]
See **https://html5.validator.nu/?doc=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Fmicrosoft-edge%2F**

We use role="none" as it replaces role="presentation". (and Edge needs one or the other to remove from a11y tree)

ARIA 1.1 is cand rec now and role="none" is fairly well supported, so would be great to allow it in the validator for use on anchors. This would require http://w3c.github.io/html/semantics-embedded-content.html#elementdef-img to be updated. Filing an issue there if it doesn't already exist.

**Comment by sideshowbarker** [comment]
The checker implements the requirements in the ARIA in HTML spec https://w3c.github.io/html-aria/ which currently explicitly only allows `role=presentation` for `img[alt=""]`

So you’d want to file an issue at https://github.com/w3c/html-aria/issues

All that said, I notice the ARIA 1.1 spec contains this admonition:

> Until implementations include sufficient support for`role="none"`, web authors are advised to use the `presentation` role alone `role="presentation"` or redundantly as a fallback to the `none` role `role="none presentation"`.

So, seems I need to add a checker warning saying, Don’t use `role=none` yet by itself til browsers support it, and instead use `role=presentation` for now or else `role="none presentation"`.

And so the `img[alt=""]` instances in https://developer.microsoft.com/en-us/microsoft-edge/ will trigger that checker warning (once it’s added) unless they’re changed to `role="none presentation"`.

**Comment by dstorey** [comment]
It's an aside for this but the reason we use none is that it is an edge only issue (well really edge and Firefox I think, but SR in firefox can fix up the DOM), so the support is good enough not to need presentation as well.

**Comment by stevefaulkner** [comment]
Have updated ARIA in HTML to also allow role=none as its a 'replacement' for role=presentation and does the same thing as presentation. https://w3c.github.io/html-aria/#img-alt

**Comment by xfq** [comment]
@stevefaulkner What about other elements – apart from `img` with `alt=""`?

**Comment by sideshowbarker** [comment]
Now live at https://checker.html5.org/ and https://validator.w3.org/nu/
