### ISSUE TITLE
The "Microsyntax descriptions" page does not render correctly

### ISSUE THREAD

**Issue by xfq** [validator/validator#480]
https://github.com/validator/validator/wiki/Microsyntax-descriptions

This page does not render correctly on my browsers[1]. It might be caused by the `mode: text;` file local variable at line 1.

* * *

[1] Tested with the latest versions of Firefox/Chrome/Safari on macOS:

<img width="826" alt="screen shot 2017-03-21 at 9 03 37 am" src="https://cloud.githubusercontent.com/assets/2863444/24128316/11cbf4f8-0e16-11e7-94dc-ef92ec933554.png">

**Comment by sideshowbarker** [comment]
Thanks for catching. Just pushed a fix for that drops the `mode: text`. I have no idea why that should break the rendering but have also reported it directly to GitHub (just using the **Contact GitHub** form-based thing; if you know of some other issue tracker where I should report it, please lemme know).

**Comment by xfq** [comment]
AFAIK there GitHub doesn't have a public issue tracker, although there's an unofficial one: https://github.com/isaacs/github

* * *

P.S. Both Bitbucket and GitLab have issue trackers:

* https://bitbucket.org/site/master/issues
* https://gitlab.com/gitlab-org/gitlab-ce/issues/

**Comment by sideshowbarker** [comment]
Thanks I just now filed https://github.com/isaacs/github/issues/904
