### ISSUE TITLE
Add datatype/microsyntax checking of color values for link[rel=mask-icon] and meta[theme-color]

### ISSUE THREAD

**Issue by sideshowbarker** [validator/validator#483]
Now that we allow `link[rel=mask-icon]` and `meta[theme-color]`, which both enable CSS color values to be specified, we should do actual datatype/microsyntax checking on the values of the accompanying attributes for those which the HTML spec says must be CSS color values.

https://github.com/validator/validator/blob/master/src/nu/validator/datatype/Color.java is stub where the actual datatype checking would need to go.

Implementing the datatype checking could be a lot of work, given the ridiculously wide range of ways to specify colors in CSS https://drafts.csswg.org/css-color/#typedef-color and also given baroqueness syntax allowed with that.

https://github.com/w3c/css-validator/tree/master/org/w3c/css/values has some code we might be able to steal from; see in particular:

* https://github.com/w3c/css-validator/blob/master/org/w3c/css/values/CssColor.java
* https://github.com/w3c/css-validator/blob/master/org/w3c/css/values/CssColorCSS4.java

**Comment by xfq** [comment]
[servo/rust-cssparser](https://github.com/servo/rust-cssparser/blob/master/src/color.rs) also has some helper functions to parse CSS colors. Although they are not written in Java, some functions can be used for reference.

**Comment by sideshowbarker** [comment]
Closing this for now as I think the level of effort required for it is quite a bit higher than we’re going to be able to put into it any time soon, and quite a bit higher than it probably merits anyway
