### ISSUE TITLE
The source code doesn't retain after checking (in text input mode)

### ISSUE THREAD

**Issue by xfq** [validator/validator#484]
It may be my fault (cause by #479), and I'll look into it later, after fixing #254.

**Comment by sideshowbarker** [comment]
Yeah it doesn’t seem to always happen but I noticed I seem to have run into some case where #479 regressed the behavior

And I’m now reminded of why I hadn’t touch that issue for a long time—because I think I couldn’t see how to fix it without regressing other behavior. But not sure…

**Comment by sideshowbarker** [comment]
If we get bugs submitted against it we might have to revert to the old behavior

**Comment by Phuizour** [comment]
Having the same issue, when checking my code ANY way it breaks please see the page im seeing attached to this issue.
![capture](https://cloud.githubusercontent.com/assets/4639747/24343282/4176f89c-12f8-11e7-90bf-2fab967aff29.PNG)

**Comment by xfq** [comment]
Hmm, this issue sometimes disappears when I attempt to study it...

@sideshowbarker I think you can revert 43e8f992d5adc62c6e2a4bbf65734f14e344da1a (and reopen #154) for now.
