### ISSUE TITLE
Angular attributes found as errors

### ISSUE THREAD

**Issue by svanschu** [validator/validator#488]
Can I check Angular WebApps with this validator? I get always error such as 

 Attribute ng-app not allowed on element html at this point.
From line 1, column 16; to line 2, column 22
TYPE html>↩<html ng-app="WebApp">↩<head
Attributes for element html:

But w3schools says that it's ok: https://www.w3schools.com/angular/ng_ng-app.asp

**Comment by Arttse** [comment]
For Angular in client side use prefix `data` for valid template code. Example `data-ng-app`, `data-ng-controller`, `data-ng-model` and etc.

**Comment by cvrebert** [comment]
Such attributes do not conform to the current standard (although there is a proposal to change that part of the spec: https://github.com/whatwg/html/issues/2271).
Protip: Don't take w3schools as gospel.

**Comment by sideshowbarker** [comment]
As noted in https://github.com/validator/validator/issues/488#issuecomment-289859994 discussion is going on about if/how to change the HTML spec to treat custom attributes like `ng-app` as conforming. But unless/until the HTML spec does actually change to make them conforming, the checker is required to continue reporting them as conformance errors.

So I’m going to go ahead and close this issue out for now.
