### ISSUE TITLE
style element conforming in body in w3c HTML

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#489]
https://github.com/w3c/html/pull/843 makes it conforming to use style in body
can we make this conforming but with a warning/info? 
Example note from spec 
> A style element should preferably be used in the head of the document. The use of style in the body of the document may cause restyling, trigger layout and/or cause repainting, and hence, should be used with care. 
http://w3c.github.io/html/document-metadata.html#the-style-element
/cc @adanilo

**Comment by nmg196** [comment]
Why was this closed?  It still seems to be an issue.

**Comment by sideshowbarker** [comment]
> Why was this closed? It still seems to be an issue.

`style` in `body` isn’t conforming per the current canonical HTML spec:

https://html.spec.whatwg.org/multipage/semantics.html#the-style-element

**Comment by nextend** [comment]
Style element is valid in the body, if it is used where metadata content expected. For example:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<template>
<style></style>
</template>
</body>
</html>
```
