### ISSUE TITLE
type-specific <input> attribute error message somewhat unclear

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#49]
(I will fully understand if this ends up being closed due to infeasibility.)
If you try to validate
```html
<input type="datetime" placeholder="Enter datetime">
```
you'll get an error because `placeholder` isn't permitted on `input`s of `type="datetime"`. The validator's HTML UI makes this clear by showing a helpful table of attributes with a highlighted row. However, this table isn't available when accessing the validator via its other interfaces. In such cases, one has to go by the error message alone:
> Attribute `placeholder` not allowed on element `input` at this point.

which isn't so indicative/helpful in this case, since `placeholder` isn't a misspelled or completely absurd attribute for an `input`.
It would be nice if the error message made some reference to the `type` attribute in such cases.

Refs https://github.com/twbs/bootstrap/issues/15971#issuecomment-77105688

**Comment by sideshowbarker** [comment]
100% agreed that for the CLI output too we should try to provide some kind of elaboration here. I'll try to make some time to come up with some ideas but in the mean it would also be helpful to have a concrete proposal to consider, about what the messages would say for this in the CLI output—what the messages would look like.

**Comment by sideshowbarker** [comment]
Actually after thinking about this more, I now realize (remember) it'd be quite feasible, code-wise, to have a more detailed message for this. (It'd take some work but I've just been lazy about taking the time to implement it. However the fact it's enough of a problem that somebody took time to raise an issue for it gives me some motivation to move it up higher in the enhancement-priorities stack.)

Anyway, here at two proposals for what the message should say. Please chime in on which looks better, or with some other proposal for the wording.

1. Attribute placeholder not allowed on element input at this point. (Not allowed when attribute `type` is `datetime`).

2. Attribute placeholder not allowed on element input at this point. (Only allowed when attribute `type` is one of: `text` `search` `url` `tel` `e-mail` `password` `number`).

Note that we can't drop or re-word the `Attribute placeholder not allowed on element input at this point` part (well it wouldn't be impossible but we are just passing that message on from 3rd-party library code we use, so it would not be highly feasible to change that part). But we could append some "elaboration" to it, like the above proposals.

**Comment by cvrebert** [comment]
Cool!
(2) sounds great to me.

**Comment by sideshowbarker** [comment]
Please test with latest nightly at https://sideshowbarker.net/nightlies/jar/ and https://sideshowbarker.net/nightlies/war/

**Comment by sideshowbarker** [comment]
…and with that I reckon it’ll be time to do a new stable release
