### ISSUE TITLE
allow multiple main elements, with restrictions

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#492]
> There must not be more than one visible main element in a document. If greater than one main element is present in a document, all other instances must be hidden using §5.1 The hidden attribute.
https://w3c.github.io/html/grouping-content.html#the-main-element

**Comment by xfq** [comment]
Currently [checker.html5.org](https://checker.html5.org/) allows multiple main elements (without restrictions), but [validator.w3.org/nu/](https://validator.w3.org/nu/) doesn't allow multiple main elements (with/without restrictions). This is controlled by `nu.validator.servlet.follow-w3c-spec`. I'll write a patch when I have time.

(Ref: w3c/html#761 & whatwg/html#100)
