### ISSUE TITLE
Language of the site is french not english

### ISSUE THREAD

**Issue by walidou23** [validator/validator#493]
Language of the French page sites but the validator detects the English language when scanning my html code

**Comment by sideshowbarker** [comment]
Please post a link to a site/document that the checker wrongly detects as English

**Comment by sideshowbarker** [comment]
Closing this as I’ve not been able to reproduce it when using the checker directly (rather than the html5validator frontend). See https://github.com/svenkreiss/html5validator/issues/32#issuecomment-295019473
