### ISSUE TITLE
Question on use of focusable and tabindex on SVGs

### ISSUE THREAD

**Issue by iandevlin** [validator/validator#500]
Currently the validator reports the presence of the `focusable` and `tabindex` attributes on SVGs as being errors - which they are - but they are required for accessibility reasons to prevent Internet Explorer (and some versions of Edge) from adding SVGs to the list of tabbable elements.

Could the error message perhaps be improved to acknowledge this requirement? It is quite startling to see such errors on a site when one is trying to do some good.

Just a thought.

**Comment by AmeliaBR** [comment]
`tabindex` should not be an error.  It is added in SVG 2, and is valid on any renderable SVG element.

`focusable` should probably be a warning.  It's basically non-standard, but as @iandevlin notes, it is still required for cross-browser compatibility (it's from the dead-end SVG 1.2 spec). 

Ideally, there would be a check that `focusable="true"` is only used in combination with a positive `tabindex` value, and that `focusable="false` is not used on elements that are normally focusable, unless `tabindex="-1"` is also used.   [There's some guidance in SVG 2 on coordinating the two attributes](https://www.w3.org/TR/SVG2/interact.html#Focus), but that was written for authors, not validators.
