### ISSUE TITLE
servlet fails with FileNotFoundException: resources/message-filters.txt

### ISSUE THREAD

**Issue by arbruijn** [validator/validator#502]
I've build vnu.war from the current sources (commit 36b883e3e658f42551bdfc49262d9a1be1127a7f) and installed it on a Tomcat 7 container.

The initial form shows but when validating a page the servlet crashes with the message:
java.io.FileNotFoundException: resources/message-filters.txt (No such file or directory)
...
at nu.validator.servlet.VerifierServletTransaction.<clinit>(VerifierServletTransaction.java:577)
...

I saw that SimpleCommandLineValidator.java doesn't use message-filtes.txt at all and so I've removed loading this file from VerifierServletTransaction.java. This seems to work fine.

**Comment by Arttse** [comment]
@sideshowbarker said that this will be fixed. If you don’t run it from directory that has a `resources/message-filters.txt` it will just fail like that.
