### ISSUE TITLE
Message filtering

### ISSUE THREAD

**Issue by emedws** [validator/validator#503]
I was attempting to filter this message:
`Attribute “wmode"” not allowed on element “param” at this point.`

So I wrote this regex:
`Attribute (.*?) not allowed on element (.*?) at this point.`

Which should work, but it doesn't because the matching happens before the output formatting, so `message.getMessage()` contains a slightly different message:
`Attribute “wmode"” not allowed on element “param” in this context.`

Testing with 36b883e3e658f42551bdfc49262d9a1be1127a7f

**Comment by sideshowbarker** [comment]
Thanks for catching this and taking time to report it.

I’ve fixed this particular case but not the general issue. So if you come across other cases like this, please do report them and I’ll fix them case by case.
