### ISSUE TITLE
Excessive memory usage?

### ISSUE THREAD

**Issue by malexdev** [validator/validator#504]
Hello! Just wanted to say, excellent work on this program! I do have a question and possible issue, although I'm totally open to the idea that I'm misconfiguring something.

I'm running a local copy of the `vnu.jar` server in order to validate a large website. If it matters, this is on CentOS 7.

I run the server with the command `/usr/bin/java -Xss2048k -cp ~/html-validator/dist/vnu.jar nu.validator.servlet.Main 8888`.

After this server starts, I then have a crawler that crawls my website and submits all its found HTML files to the checker. This particular site has ~21k HTML files.

When I start the crawler, the memory usage of the validator jumps up to ~400 MB almost immediately, then continues to grow. By the time the scan is done, I'm using a little over 500 MB. This usage doesn't ever seem to go down until I restart the validator server.

Is there something that I need to do in order to limit this memory usage, or correct for it? I'd rather not have to periodically restart the validator service if I can avoid it.

Thanks for your time!

**Comment by sideshowbarker** [comment]
The service consumes a lot of memory. How much of the memory is made recoverable to the OS when the service is idle is something that I think is just up to the Java runtime. I don’t know anything we could be doing differently the code that would make the service use less memory or to free up more memory when it’s idle. But I will leave this open in case anybody else comes by with ideas.

**Comment by sideshowbarker** [comment]
Rather than leaving this hanging open I’m gonna go ahead and close it as it’s not clear we can otherwise really resolve it. But feel free to comment further here if there’s anything more to add or ask
