### ISSUE TITLE
Feature request: Check if line length < 80 characters

### ISSUE THREAD

**Issue by jyn514** [validator/validator#507]
According to https://www.w3schools.com/htmL/html5_syntax.asp, best practice to for line length to be no more than 80 characters. I checked an html document with lengths of over 200 (!) but no errors appeared.

**Comment by ezequiel-garzon** [comment]
That recommendation isn't part of the standard. It doesn't make much sense to request an error from the validator when it is valid markup.

**Comment by nschonni** [comment]
@jyn514 you might be better looking at linters for style checking EX: https://github.com/htmllint/htmllint/wiki/Options#line-max-len

**Comment by sideshowbarker** [comment]
This is out of scope for the checker.

**Comment by jyn514** [comment]
Understood, thanks for the help @nschonni
