### ISSUE TITLE
Input "range" step

### ISSUE THREAD

**Issue by seanmisra** [validator/validator#508]
The validator does not accept a decimal point for the step attribute (of input type "range"). For example, if the step attribute is ".3", the following error is thrown:  

"Bad value .3 for attribute step on element input: Expected a digit but saw . instead".

**Comment by cvrebert** [comment]
I agree. Per the spec:

> **The `step` attribute**, if specified, must either have a value that is a **valid floating-point number** that parses to a number that is greater than zero [...]
> -- https://html.spec.whatwg.org/multipage/forms.html#attr-input-step

> A string is a **valid floating-point number** if it consists of:
> * (1) Optionally, [...]
> * (2) One or both of the following, in the given order:
>   * (1) [...]
>   * (2) Both of the following, in the given order:
>     * (1) A single U+002E FULL STOP character (.).
>     * (2) A series of one or more ASCII digits.
> * (3) Optionally: [...]
> 
> -- https://html.spec.whatwg.org/multipage/infrastructure.html#valid-floating-point-number

**Comment by xfq** [comment]
Related code:

* https://github.com/validator/validator/blob/bed5d1f72a5110a460d50885545c56c883f029a0/schema/html5/web-forms2.rnc#L111-L114
* https://github.com/validator/validator/blob/8b333171c4f8d81524d205934bdf77c1935d2b77/schema/html5/common.rnc#L282-L283
* https://github.com/validator/validator/blob/8b333171c4f8d81524d205934bdf77c1935d2b77/src/nu/validator/datatype/Html5DatatypeLibrary.java#L121-L122
* https://github.com/validator/validator/blob/fe88da45fd505a4add9a61d1e15c3a57cd8b30fe/src/nu/validator/datatype/FloatingPointExponentPositive.java#L47
