### ISSUE TITLE
Bad value for attribute src on element img: Expected a token character or / but saw ; instead.

### ISSUE THREAD

**Issue by tale07** [validator/validator#516]
I'm getting error for this part of code. Validator expect a token character or / instead ;
![validatorissue](https://cloud.githubusercontent.com/assets/17012193/26347793/eff1adfc-3faa-11e7-8041-1de88f878dcd.PNG)

`<img alt="Digital Signature" src="data:image;base64,iVBORw0KGgoAAAANSUhEUgAAAJkAAABCCAYAAABEpXRWAAAA…emKdjTQP8lc6gxToLIPzNdu8G99Fk6p4B5y+g4z18o9R8MjwvqB+hTDQAAAABJRU5ErkJggg==" width="180" height="60">`

I think that this is issue, or can someone explain why is this error.

**Comment by Arttse** [comment]
Data URIs syntax: `data:[<mediatype>][;base64],<data>`. The mediatype is a MIME type string, such as `image/jpeg` for a JPEG image file. So you need to specify the MIME type string of your image.

**Comment by sideshowbarker** [comment]
Closing as explained in https://github.com/validator/validator/issues/516#issuecomment-303350061
