### ISSUE TITLE
Error related with random language detection

### ISSUE THREAD

**Issue by iconamer** [validator/validator#519]
Hello,
I want to raise an issue related with below warning. I got this error randomly. Sometimes its showing but not all the time. In my page i've used dummy content like "lorem ipsum". Language set for the html document is "en-US"

**Warning: This document appears to be written in Catalan but the html start tag has lang="en-US". Consider using lang="ca" (or variant) instead.**

Please advise how to avoid this issue permanently. 

Thanks,
Amernath

**Comment by xfq** [comment]
Looks like #328.

**Comment by sideshowbarker** [comment]
In order for me to have something to troubleshoot this with, please a document that reproduces the problem, even intermittently.

**Comment by sideshowbarker** [comment]
Closing for lack of response
