### ISSUE TITLE
validator.nu API with fsockopen of PHP?

### ISSUE THREAD

**Issue by miniBB** [validator/validator#522]
I'm trying to build a validation for my pages coding PHP script and I'm stuck at the API validation either by POST or GET method. If the HTTP request is issued via the regular PHP 'fsockopen' function, none of these methods appear to work. In both cases, in response, I'm getting something like this (tried both validator.nu and validator.w3.org/nu/ and results are mostly the same):

HTTP/1.1 200 OK
Date: Thu, 01 Jun 2017 20:31:15 GMT
Accept-Encoding: gzip
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: content-type
Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/html; charset=UTF-8
Vary: Accept-Encoding, User-Agent
Connection: close
Server: Jetty(9.2.9.v20150224)
Strict-Transport-Security: max-age=15552015; preload
Public-Key-Pins: pin-sha256="cN0QSpPIkuwpT6iP2YjEo1bEwGpH/yiUn6yhdy+HNto="; pin-sha256="WGJkyYjx1QMdMe0UqlyOKXtydPDVrk7sl2fV+nNm1r4="; pin-sha256="LrKdTxZLRTvyHM4/atX2nquX9BeHRZMCxg3cf4rhc2I="; max-age=864000
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block

**or**

HTTP/1.1 200 OK
Server: nginx/1.13.1
Date: Thu, 01 Jun 2017 20:36:49 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Accept-Encoding: gzip
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: content-type
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

and then these headers followed by HTML body of the input validation form. None results are given if the page was validated or not and what errors are/not found.

For example, when connected to validator.nu via post method and sending HTML contents as the message body after 'Connection: Close' header this is written below the form:

_The document validates according to the specified schema(s).
Used the schema for HTML + SVG 1.1 + MathML 3.0 + RDFa Lite 1.1.
Used the HTML parser._

Nothing else besides of that...

I'm pretty sure I'm applying the correct code, because the same function is used in PayPal API and some other scripts I have.

The question is, did you test the API with PHP and maybe there are some examples for the 'fsockopen' function? Those demos of curl and java provided on the Service -> Input pages will not work for PHP... thanks.

**Comment by miniBB** [comment]
I didn't find the way how to implement it via PHP/fsockopen... poor docs :(

So I ended up with implementing it with cURL. For someone who may need it, here's the piece of code for cURL W3C validation:

```
$instanceURL='https://validator.w3.org/nu/?out=text';
$clientSide='Mozilla/5.0 (Windows NT 5.1; rv:38.0) Gecko/20100101 Firefox/38.0'; //for example

$tmpFileContent=trim(file_get_contents($url)); // $url stands for the URI of your page or file to validate

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $instanceURL);
curl_setopt($ch, CURLOPT_USERAGENT, $clientSide);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: text/html; charset=utf-8'));
    
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
curl_setopt($ch, CURLOPT_FRESH_CONNECT, 1);   
curl_setopt($ch, CURLOPT_FORBID_REUSE, 1);  
curl_setopt($ch, CURLOPT_TIMEOUT, 100);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
    
curl_setopt($ch, CURLOPT_POSTFIELDS, $tmpFileContent);
    
$result = curl_exec ($ch);
curl_close ($ch);
```

I've spent hours while discovered file contents should be supplied as the whole contents for CURLOPT_POSTFIELDS. This is the most important thing in the code...

$result will keep the report from the Validator, which could be easily parsed/analyzed regarding its contents. I've chosen TXT output as the most easier to parse for my needs.

**NOTE**: you must be careful submitting data to _validator.w3.org/nu/_ and NOT debug your script live with this tool regarding multiple same URLs, only provide real validation when you are completely sure on everything. Else you may get "[Forbidden due to abuse](https://www.w3.org/Help/abuse-info/re-reqs.html)" error. This error also will be produced if you validate more than 500 URLs in one bulk request. So after each 500 URLs, make a pause of few minutes and then continue. It's very annoying, but it could work if you don't hurry too much :)

**Comment by sideshowbarker** [comment]
Closing per solution in https://github.com/validator/validator/issues/522#issuecomment-307639991

Thanks for taking time to write that up so we have a record here
