### ISSUE TITLE
language detection prob html5

### ISSUE THREAD

**Issue by dioskey** [validator/validator#524]
The validator shows a warning during validation of this site: http://notanumber.it/en/
But the language tag is correct.

**Comment by sideshowbarker** [comment]
Put `lang="it"` on the `<div id="cck_pup_txt">` element and you won’t get any warning.

The thing is, the `.textContent`  of that `<div id="cck_pup_txt">` element is 4057 characters of words of Italian. The total `.textContent` of the entire body of the document is just 5638 characters. So from the perspective of the language detector that the checker uses, 72% of the text on the page appears to be in Italian.

I see the CSS for that `<div id="cck_pup_txt">` element is set to `display: none`, but the language detector can only examine the source of the document without regard to CSS visibility properties.

So in general if you have any element in a document whose content is in a different language than the document itself, per Internationalization guidelines from the W3C and elsewhere, you should put a `lang` attribute on that element, with a value that indicates what language it’s in.

If you follow that best practice, a side effect is that you also won’t get these kinds of warnings from the language detector.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/524#issuecomment-310876030 But feel free to comment further here if there’s anything more to add or ask
