### ISSUE TITLE
Ampersand followed by a semicolon gives error

### ISSUE THREAD

**Issue by ezequiel-garzon** [validator/validator#529]
The HTML standard considers [an ambiguous ampersand](https://www.w3.org/TR/html5/syntax.html#syntax-ambiguous-ampersand) to be (my emphasis) 'a U+0026 AMPERSAND character (&) that is followed by **one or more** alphanumeric ASCII characters, followed by a ";" (U+003B) character, where these characters do not match any of the names given in the named character references section.'

Based on this standard "&a;" should yield an error, but "&;" should not. However it does: "& did not start a character reference. (`&` probably should have been escaped as `&amp;`)

**Comment by sideshowbarker** [comment]
@inikulin @RReverser @zcorpan is `&;` not a parse error?

**Comment by inikulin** [comment]
@sideshowbarker No, it's not a parse error. There should be at least one alphanumeric to trigger an error.

**Comment by sideshowbarker** [comment]
@inikulin thanks for confirming

**Comment by sideshowbarker** [comment]
Fixed in the sources and pushed to https://checker.html5.org/ and https://validator.w3.org/nu/ and https://sideshowbarker.net/nightlies/jar/ and new `vnu-jar` npm in the `dev` tag (17.7.6)
