### ISSUE TITLE
Allow | in link href

### ISSUE THREAD

**Issue by larsmagnusherland** [validator/validator#534]
I've checked with the most up to date validator, and it does not support  | in the `<link href> `like in the following example:
`<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:400,100,100itali…00,900italic|Source+Sans+Pro:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic">`

This is a valid and suggested way by Google to fetching one CSS files having additional fonts inside and that way only use 1 connection.
By doing this as two separate lines, it will make the fetching of the needed CSS files become 2 files and 2 separate connection, making the overall page speed slower.

This should be added as a valid character in `<link href>` as it helps making the web faster and more optimized.
 
Ref:
https://developers.google.com/fonts/docs/getting_started

**Comment by nschonni** [comment]
Looks like that character is marked as "unsafe" by the IETF https://perishablepress.com/stop-using-unsafe-characters-in-urls/

**Comment by sideshowbarker** [comment]
The `|` character (U+007C) isn’t a [valid URL code point][1] per the current URL Standard.

You can fix URLs with invalid characters by running them through a tool that will [percent encode][2] any characters in them that aren’t [valid URL code points][1].

One good online tool for percent-encoding URLs is Eric Meyer’s [URL Decoder/Encoder][3].

  [1]: https://url.spec.whatwg.org/#url-code-points
  [2]: https://url.spec.whatwg.org/#percent-encode
  [3]: http://meyerweb.com/eric/tools/dencoder/

**Comment by sublimeshrub** [comment]
I'm having the same issue with code copied and pasted from Google. It is what it is, and let's just be honest, if Google is going to use it than eventually it's going to be accepted as valid.

**Comment by sideshowbarker** [comment]
Closing per explanation at https://github.com/validator/validator/issues/534#issuecomment-313808641. The checker’s in conformance with the spec requirements here and I’ve described how the URL can fixed to also conform to the spec requirements. Anybody’s free to make no fixes to their documents and ignore the error messages but we won’t be changing the checker behavior unless the relevant spec requirements change.
