### ISSUE TITLE
Allow "Interaction Media Features" for media attribute

### ISSUE THREAD

**Issue by 1jj** [validator/validator#536]
Validating  http://elektronotdienst-nuernberg.de/bugs/prefix.html  reports this error:

> Bad value (hover:none) for attribute media on element style: Expected a CSS media feature but saw hover instead.

because of  `<style media="(hover:none)">`

Spec https://www.w3.org/TR/mediaqueries-4/#mf-interaction  is implemented in Chrome and Safari/iOS and should be allowed to use.

**Comment by nschonni** [comment]
> Note: the hover, any-hover, pointer, and any-pointer media features are at risk.

**Comment by 1jj** [comment]
Hmm,  it can't be at risk in practice because it's implemented in Safari 9, Chrome 41, Edge 12 since 2015.
Spec issues and compatibility with Safari were considered when implemented in Chrome:

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/ZSp8aCPnwPM

**Comment by nschonni** [comment]
Looks like the designation was recent https://github.com/w3c/csswg-drafts/commit/7bb4be3d9a36be0f65681e3ee5dd0ddac4b9b015
Some stuff does get pulled from time-to-time if the spec doesn't work out as indended

**Comment by sideshowbarker** [comment]
I had been planning to add support for the `hover` etc. media features over the weekend but didn’t manage to get to it yet. Will try to get them added asap

**Comment by sideshowbarker** [comment]
Thanks for having taken time to report this, and sorry I ended making you wait longer than I had expected for the fix to land
