### ISSUE TITLE
How come the validator doesn't show "bolded" in title as error and it appears in browsers tab as title not as comment? When written on Visual Studio or Intel XDK it marks it as a HTML comment.

### ISSUE THREAD

**Issue by RivalIsling** [validator/validator#537]
<!DOCTYPE html>
<html lang="en"> 
    
    <head> 
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
            
            <title>  ****
                GoldenEYE 
            </title>
                <script rel="javascript" src="myscript.js"></script> 
                <link rel="stylesheet" type="text/css" href="stylesheet.css"> 
    </head>
            <body> 
                <div>
                    <a href="pagelayout.html"><img  src="pictures_folder.jpg" alt="developer@developer.com"></a>
                    </div>
                </body>

</html>

**Comment by sideshowbarker** [comment]
<title>  ****

That’s not a comment. Any characters in the contents of a `title` element are treated a text, including the characters `<!--`. So if Visual Studio or Intel XDK or any other tools show that as a comment, that is a bug in those tools that you should report to them.

Closing but feel free to comment here further if you need any more clarification on this.
