### ISSUE TITLE
Allow decimals with no leading 0 as the time in refresh <meta>

### ISSUE THREAD

**Issue by sideshowbarker** [validator/validator#540]
See https://github.com/whatwg/html/commit/b8a34e302cdf0289f5403a02905629bb358519a6 and https://github.com/whatwg/html/pull/2852 and https://github.com/whatwg/html/issues/2844

**Comment by domenic** [comment]
I don't think this is necessary; we did not change the definition of a valid string for authors. For authors the rules remain:

> - just a valid non-negative integer, or
>
> - a valid non-negative integer, followed by a U+003B SEMICOLON character (;), followed by one or more ASCII whitespace, followed by a substring that is an ASCII case-insensitive match for the string "URL", followed by a U+003D EQUALS SIGN character (=), followed by a valid URL string that does not start with a literal U+0027 APOSTROPHE (') or U+0022 QUOTATION MARK (") character.

**Comment by sideshowbarker** [comment]
ah OK thanks—closing
