### ISSUE TITLE
html include considered as a bug (w3)

### ISSUE THREAD

**Issue by Mrgts411** [validator/validator#541]
i tried validating but this shows as an error when it's actually not.

https://www.w3schools.com/howto/howto_html_include.asp

validation results: https://validator.w3.org/nu/?acceptlanguage=&doc=https%3A%2F%2Fgasplund.github.io%2F

**Comment by LeeKowalkowski** [comment]
Custom HTML attributes are supposed to start with "data-" as far as I know: https://www.w3schools.com/tags/att_global_data.asp (whoops, I meant: https://www.w3.org/TR/html5/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes)

I used the 'REPORT ERROR' link on that w3schools page to let them know, so hopefully they'll fix their library.  (W3 Schools is not affiliated with the W3C)

**Comment by sideshowbarker** [comment]
Closing per resolution in https://github.com/validator/validator/issues/541#issuecomment-318354750
