### ISSUE TITLE
Attribute intputmode not allowed on element input at this point.

### ISSUE THREAD

**Issue by Louis-MarieMatthews** [validator/validator#547]
Hi,

Is HTML 5.1 supported at this point? I am getting the following error: 

> Attribute intputmode not allowed on element input at this point.

The code it refers to: `<input type="text" intputmode="numeric">`.

If I'm correct `inputmode` is a new feature as of HTML 5.1.

**Comment by sideshowbarker** [comment]
I think you just mistyped the attribute name as `intputmode` instead of `inputmode`?

**Comment by Louis-MarieMatthews** [comment]
My bad indeed, don't know how I didn't notice it, I read my code several times…
Sorry for that!
