### ISSUE TITLE
Meta without `name` and `content` but with `resource` reported as error

### ISSUE THREAD

**Issue by ArmorDarks** [validator/validator#550]
Here is an example of RDFa markup with Schema.org vocabulary:

```html
<!doctype html>
<html vocab='https://schema.org/'>

  <head>
    <meta typeof='WebSite' resource='#this-website'>
    <meta about='#this-website' property='name' content='Example'>
    <link about='#this-website' property='url' href='https://example.com'>
  </head>

  <body>Example</body>

</html>
```

This will yield:

![chrome_2017-08-21_23-07-10](https://user-images.githubusercontent.com/4460311/29536188-7fb8e2a0-86c5-11e7-9afb-8202ca30cc20.png)

To be honest, I'm not sure is that error legit or not. I looked through specs, but didn't find anything specifically about such usage of `<meta>` tag in RDFa examples. Google and other major users of structured data recognizing content correctly.

The tricky thing here that `WebSite` according to Schema.org can not have any content or name directly on the node, which has that `typeof`.

If you wonder, why not place it on `<body>` or other element, which can nest and be _not_ `<meta>` (and thus contain `WebSite` properties and not require `content` attribute) — we wanted it to be detached from page itself, to avoid properties collisions and give a place for other structured data elements, which in our case are more suitable for page root than `WebSite`.

**Comment by sideshowbarker** [comment]
See https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element, which says:

> Exactly one of the `name`, `http-equiv`, `charset`, and `itemprop` attributes must be specified.

I think https://www.w3.org/TR/html-rdfa/ extends that so the requirement is effectively “Exactly one of the `name`, `http-equiv`, `charset`, `itemprop`, and `property` attributes must be specified”.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/550#issuecomment-324540055 but feel free to comment here further if you have any new information or further questions
