### ISSUE TITLE
IO Error

### ISSUE THREAD

**Issue by msklenicka** [validator/validator#551]
Hi, is possible get more information, like where exactly is error ?
I have one record in logs:
128.30.52.64 - - [22/Aug/2017:12:25:53 +0200] "GET / HTTP/1.1" 200 9269 "-" "Validator.nu/LV http://validator.w3.org/services"

But I get IO Error. I tried this url :
https://validator.w3.org/nu/?doc=http%3A%2F%2Fblog.itify.eu%2F

**Comment by sideshowbarker** [comment]
> But I get IO Error. I tried this url :
> https://validator.w3.org/nu/?doc=http%3A%2F%2Fblog.itify.eu%2F

I don’t get any IO Error there

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/551#issuecomment-324536661 but feel free to comment here further and we can reopen this if the problem reoccurs
