### ISSUE TITLE
Sanitise input URI; specifically, discard e-mail addresses

### ISSUE THREAD

**Issue by tripu** [validator/validator#553]
Some scammers are tricking non-tech-savvy users into &ldquo;validating&rdquo; their e-mail addresses on [`validator.w3.org/`](https://validator.w3.org/). Apparently, the validator takes the domain portion of the address and tries to validate that. If the corresponding page isn't valid (which is the most likely outcome), scammers use that to convince victims that it is their e-mail *address* that is wrong, somehow.

I suggest being more strict about valid URIs.

Thanks to [`@john_holley`](https://twitter.com/john_holley) for reporting:

https://twitter.com/john_holley/status/900217901705310208
https://twitter.com/john_holley/status/900220845909565440
https://twitter.com/john_holley/status/900271480323190784
https://twitter.com/john_holley/status/900271661479378944
https://twitter.com/john_holley/status/900271858355912704

**Comment by xfq** [comment]
If you input an email address on https://validator.w3.org/nu/, the checker will only allow http, https or data URLs. So this might be an issue of https://github.com/w3c/markup-validator

**Comment by LeeKowalkowski** [comment]
The email address is converted to a URL here: https://github.com/w3c/markup-validator/blob/master/httpd/cgi-bin/check#L1780-L1789

**Comment by tripu** [comment]
Thank you, @xfq &amp; @LeeKowalkowski.
I'm moving this issue to w3c/markup-validator, then.
