### ISSUE TITLE
Nightlies: Test them

### ISSUE THREAD

**Issue by sideshowbarker** [validator/validator#56]
So I've added a step to my development workflow such that, going forward from now on, Nightly builds of the `vnu.jar` and `vnu.war` executables will be available here:

https://sideshowbarker.net/nightlies/

The workflow is such that I'll only upload a new nightly there if I've made a bug fix or enhancement to the actual application code (as opposed to the build files or the docs).

So the biggest benefit of this is that other packagers won't have to wait for me to get around to updating the change log, etc., and doing a formal release. Otherwise the intent is that the nightlies are intended to be just as stable (in terms of the application behavior) as the normal releases; e.g., I do exactly the same level of testing for each.

So @cvrebert @jzaefferer @jaimeiniesta especially, please give the current nightly jar there a try and let me know if you find any problems. And @jacobq and @Pacoup especially, please try out the war file.

**Comment by jaimeiniesta** [comment]
That's a great idea @sideshowbarker 

I've tried it and it works fine for me (#53 keeps happening, though).

**Comment by Pacoup** [comment]
Ok, the 11-Mar-2015 02:41 nightly works. What do you think would be the best way to report on this going forward? Just silently test and report bugs if they happen?

**Comment by sideshowbarker** [comment]
@jaimeiniesta Thanks for testing—I’ll try to make time to look into #53 today.

@Pacoup Yeah, basically just “silently test and report bugs if they happen”. I’m still trying to figure out some non-kludgy way to do automated testing of the war builds.

**Comment by sideshowbarker** [comment]
> @Pacoup Yeah, basically just “silently test and report bugs if they happen”. I’m still trying to figure out some non-kludgy way to do automated testing of the war builds.

It seems I may be able to set up something on Heroku for free, up to some monthly usage limit. But it should be sufficient for testing. I’ve opened issue #66 for this.

**Comment by sideshowbarker** [comment]
@Pacoup So FYI, I’ve now added Travis testing to help ensure the vnu.war build doesn’t break—steps that install Tomcat 7, copy the vnu.war file to the Tomcat webapps dir, and then send a document to that vnu instance for checking—https://github.com/validator/validator/blob/master/.travis.yml#L22
```
- sudo apt-get install tomcat7
- sudo cp ./build/dist/vnu.war /var/lib/tomcat7/webapps
- sleep 15
- curl -sS 'http://localhost:8080/vnu/?out=gnu&doc=data:text/html;charset=utf-8,%3C%21doctype%20html%3E%3Cmeta%20charset%3Dutf-8%3E%3Ctitle%3ETest%3C%2Ftitle%3E' > RESULTS
- test -z "$(cat RESULTS)"
- if [ $? != 0 ]; then cat RESULTS; fi
```
I’ve also add a build target that I can to push updates of the war release to https://vnu.herokuapp.com/

So I think the project finally now has some good ways to prevent build breakage of the war build.

**Comment by Pacoup** [comment]
@sideshowbarker That's great :+1:

**Comment by sideshowbarker** [comment]
Note that I moved the jar and war distributions into separate subdirs:
https://sideshowbarker.net/nightlies/jar/
https://sideshowbarker.net/nightlies/war/
