### ISSUE TITLE
<style> and <script> conformance updates

### ISSUE THREAD

**Issue by domenic** [validator/validator#560]
https://github.com/whatwg/html/pull/3024 will land soon and make a number of changes that are relevant to the checker:

- More clearly require checkers to emit warnings for `<script>` when its `type` is the empty string or a JavaScript MIME type, since doing so is reundant.
- Require checkers to emit warnings for `<style>` when its `type` attribute is specified at all.
- Remove the requirement on `<style>` text content prohibiting unmatched comment syntax (previously specified with an ABNF)
- Add the requirement that `<style>` text content be valid parseable CSS (this will be a fun one to implement for you, I am sure :) )

**Comment by sideshowbarker** [comment]
> - More clearly require checkers to emit warnings for `<script>` when its `type` is the empty string or a JavaScript MIME type, since doing so is reundant.

Fixed in 782c84b

> - Require checkers to emit warnings for `<style>` when its `type` attribute is specified at all.

Fixed in 983a05a

Pushed both fixes to https://checker.html5.org/

**Comment by sideshowbarker** [comment]
> - Add the requirement that `<style>` text content be valid parseable CSS (this will be a fun one to implement for you, I am sure :) )

Fixed in d954e3c and pushed to https://checker.html5.org/

**Comment by sideshowbarker** [comment]
I think all changes for this have been merged but if I missed anything, lemme know
