### ISSUE TITLE
--filterfile not work on win10 

### ISSUE THREAD

**Issue by AlexDaSoul** [validator/validator#561]
Works only with windows charset file

**Comment by XhmikosR** [comment]
I have a Windows environment, so @LTN please share a complete test case.

**Comment by LTN** [comment]
Hi! Now i cant make test case for you, we are already using another solution. Sorry.
All warnings in messages remained when we added them to patterns file. But working when we change charset patterns file to windows-1251.

**Comment by XhmikosR** [comment]
Unless you are using the API, any other solution can't be on par with the **official** validator, which is what vnu.jar is :)

Anyway, I'd be happy to try if we have a complete test case.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/561#issuecomment-334140965 but if/when you have a test case, feel free to comment here further or open a new issue.

**Comment by nschonni** [comment]
Just hit this as well through Win 10  with VSCode/bash shell calling to vnu-jar through an NPM script. Without `asciiquotes` option it was printing messages like `The ÔÇ£contentinfoÔÇØ role is unnecessary for element ÔÇ£footerÔÇØ.` without it. Even with the `asciiquotes` it wouldn't read the filter from a file `.vnurc`. I'll try and do a simplified test case.
