### ISSUE TITLE
Error when video width or height is set in %. But it is valid value for these attributes

### ISSUE THREAD

**Issue by victoriaslin** [validator/validator#562]
I have video heigt and width set in %:
          <video height="100%" width="100%" controls muted id="new-fifth-video">↩     

Validator gives me this error:
"Error: Bad value 100% for attribute width on element video: Expected a digit but saw % instead."

But it is allowed to set height and width both in pixels and percent, isn't it?

**Comment by cvrebert** [comment]
No, it's not allowed. Per https://html.spec.whatwg.org/multipage/embedded-content-other.html#attr-dim-width (emphasis mine):

> The `width` and `height` attributes on [...] `<video>` [...] may be specified to give the dimensions of the visual content of the element (the width and height respectively, relative to the nominal direction of the output medium), **in CSS pixels**.
> The attributes, if specified, **must have values that are valid non-negative integers**.

And integers aren't percentages.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/562#issuecomment-331303125
