### ISSUE TITLE
Support for svg2?

### ISSUE THREAD

**Issue by mikkopori** [validator/validator#564]
Hello,

when will support for svg2 be available? Currently the validator supports 1.1.

Thank you!

Mikko

**Comment by sideshowbarker** [comment]
If there are specific features from SVG2 that you believe the checker should support, please raise separate issues for each of them. There are otherwise no plans to add blanket support for SVG2 as a whole.

**Comment by mikkopori** [comment]
Thank you for your response.

I ran into this while validating a google maps -application. I've now tried to reproduce the svg-related errors, but unfortunately I am unable to. (solved the issue by removing the map from the html to be validated).

So, next time I run into those I'll be more specific.

**Comment by sideshowbarker** [comment]
OK, closing per https://github.com/validator/validator/issues/564#issuecomment-334413838. But please do open a new issue if/when you have a specific case.
