### ISSUE TITLE
Slot attribute

### ISSUE THREAD

**Issue by js-choi** [validator/validator#567]
The HTML and DOM standards allow the [slot attribute](https://html.spec.whatwg.org/multipage/dom.html#attr-slot) on any HTML element.

The validator returns this document as invalid:

    <!DOCTYPE html>
    <title>Slot Test</title>
    <test-root>
    <p slot=test>Slot Test</p>
    </test-root>

…giving this error:

<samp>
Error: Attribute slot not allowed on element p at this point.
From line 4, column 1; to line 4, column 13
</samp>

**Comment by sideshowbarker** [comment]
Fixed and pushed to https://validator.w3.org/nu/

Thanks!
