### ISSUE TITLE
validator.w3.org does not pass the validator

### ISSUE THREAD

**Issue by fancyfarfalle** [validator/validator#568]
The [W3 Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fvalidator.w3.org) website does not pass the W3 Validator test, but instead returns ten different errors.

**Comment by unor** [comment]
The document https://validator.w3.org/ is written in XHTML 1.0. The tool https://validator.w3.org/nu/ doesn’t support checking against the XHTML 1.0 spec.

If you check it with https://validator.w3.org/ itself, [it reports no errors](https://validator.w3.org/check?uri=https%3A%2F%2Fvalidator.w3.org%2F).

**Comment by fancyfarfalle** [comment]
Don't know how I missed that! Stupid mistake on my part, should have looked closer at the URL. Thanks!

**Comment by sideshowbarker** [comment]
While as noted in https://github.com/validator/validator/issues/568#issuecomment-341980856 it’s true that the legacy https://validator.w3.org/ validator was valid per the rules of the obsolete XHTML1 doctype it was labeled with, it’s now 2017 and all current W3C services should rightly be conforming to the current HTML standard and not using obsolete markup.

So I have fixed the markup of the legacy validator to conform to the current HTML standard.
