### ISSUE TITLE
Update commons-logging version

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#57]
`nu.validator:validator:15.3.10` [currently depends on](https://github.com/validator/validator/blob/6ba964ae59f05c8bfce03cbe18a510f2a67db5b1/build/build.xml#L252) `commons-logging:commons-logging-adapters:1.1`, whose artifact in Maven Central is kinda broken (see https://issues.apache.org/jira/browse/LOGGING-161). The guy in that issue suggests fixing the coordinates & updating the version of that dependency.

This issue currently prevents me from using the Maven release, as sbt/Ivy fails to resolve that indirect dependency (see https://github.com/cvrebert/lmvtfy/issues/77#issuecomment-78074085).

**Comment by sideshowbarker** [comment]
I updated the dependency info and bumped the package version:

http://repo1.maven.org/maven2/nu/validator/validator/15.3.11/

Please test it and if it's not working as expected, re-open this bug with a comment.

**Comment by cvrebert** [comment]
Nice, it's able to compile now. Thanks!

**Comment by sideshowbarker** [comment]
cheers

**Comment by joehni** [comment]
The artifacts in build.py are declared correctly, but not those in build.xml. However, If you declare the main artifact of commons-logging, you don't need -adapters or -api at all.

**Comment by sideshowbarker** [comment]
> The artifacts in build.py are declared correctly, but not those in build.xml. However, If you declare the main artifact of commons-logging, you don't need -adapters or -api at all.

ah ok, I'll just remove the -adapters and -api dependencies then
