### ISSUE TITLE
"Used the HTML parser" when it should have used the XHTML parser

### ISSUE THREAD

**Issue by Rob-S** [validator/validator#572]
I've validated the same pages in the past, but right now it's saying "Used the HTML parser" when trying to validate pages. There's an error that says "Saw <?. Probable cause: Attempt to use an XML processing instruction in HTML. (XML processing instructions are not supported in HTML.)" It should be using the XHTML parser.

Request for a new feature: Please add an option to override the default so that it uses the XHTML parser. Thanks!

**Comment by sideshowbarker** [comment]
> Request for a new feature: Please add an option to override the default so that it uses the XHTML parser.

No. Sorry.

If you want the checker to parse a document using the XML parser, then I recommend serving it with an XML media type instead of serving it as text/html.

Either that or use interface at https://validator.nu/, which allows you to force use of the XML parser.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/572#issuecomment-344795273
