### ISSUE TITLE
validator misidentifies html page as german

### ISSUE THREAD

**Issue by stuart-e-anderson** [validator/validator#577]
I validated a html page I am designing.  The page is here [link](http://www.squaring.net/nav.html).  The validator identifies the page as German, when it is English.

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. I believe it should be fixed now, if you try at https://validator.w3.org/nu/?doc=http://www.squaring.net/nav.html

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/577#issuecomment-349328781
