### ISSUE TITLE
Does the validator understand responsive css hiding?

### ISSUE THREAD

**Issue by vetbactstaff** [validator/validator#578]
I have a question regarding an error message from https://validator.w3.org/nu/ and the use of "autofocus" in HTML 5. I wonder whether I have made an error or if the problem is perhaps in the validator's handling of "responsive css".

The page I have tested using https://validator.w3.org/nu/ tests clean except for an error message regarding "autofocus": "A document must not include more than one autofocus attribute".

My source file (http://www.vetbact.org/html5index.php) does indeed contain two instances of autofocus (on `<input>)` but they should not be exposed at the same time to any given browser because they are in different "divs" `(<div></div>)` and one of those should always be hidden using css to make the page "responsive" and adapt to different screen sizes (using "@media screen...").

Now, my question is, does the validator take "responsive css hiding" into account?  If so, I guess I might have some error in my css file which looks like this:

----------------------------------------------------
`@media screen and (min-width: 500px) {
  #smallscreensearchbox {
        position: relative;
        display: none;
  }
}`
`@media screen and (max-width: 499px) {
  #searchbox {
        position: relative;
        display: none;
  }
}`
----------------------------------------------------

Do you think that the problem is in my use of css or has this feature not been implemented in the validator yet?

Thanks
Staffan

**Comment by sideshowbarker** [comment]
See https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofocusing-a-form-control:-the-autofocus-attribute:attr-fe-autofocus-3:

> There must not be two elements with the same nearest ancestor autofocus scoping root element that both have the autofocus attribute specified.

See also issue #95.

**Comment by vetbactstaff** [comment]
Is there some way to deal with this in css without having to resort to using scripts? I'd prefer to keep the autofocus feature for both small and large screens, if at all possible.

**Comment by LeeKowalkowski** [comment]
I'm not sure you should ever validate a HTML document in the context of what will be visible once it has been styled.  

To me, one benefit of validating HTML is to encourage consistent rendering.  So if we needed to match a HTML document with a style sheet before validating the HTML, that would be putting the cart before the horse.

I'm not sure why you have two versions of your form for the different screen widths.  That didn't look necessary at all, sorry.  My personal preference is to use the exact same HTML for all display modes, mainly because then there is only one set of functional tests to create.

**Comment by vetbactstaff** [comment]
OK, thanks for clarifying. It does make sense to validate the style sheet and the HTML independently. Of course, it would have been convenient to be able to test a whole page 'as seen by a browser', but I do see the point.

Having two different search forms with different widths, placement and associated texts and hints, seemed like a good way of solving the problem given that only one of them would be exposed to a browser at any given time since they live in 'mutually exclusive' divs. However, I do think that you are right and that there must be some way around that (although it seems more complicated at the moment because I do want things surrounding the search box to differ between the two cases).

I will of course try to find a way to make the same search form work for both cases, but in the meantime I guess I'll have to live with that single validation error since it doesn't seem terribly serious and it works better in actual practice than simply removing the autofocus attribute from one of the screen widths (which would clear the error flag from the validator).

Thanks again.
