### ISSUE TITLE
Invalid rowgroup error

### ISSUE THREAD

**Issue by jnurthen** [validator/validator#579]
Getting the following error 
An element with “role=rowgroup” must be contained in, or owned by, an element with “role=grid”.

On http://w3c.github.io/aria-practices/examples/table/table.html

In ARIA 1.1 role=rowgroup can be contained in an element with role=table too.
See https://www.w3.org/TR/wai-aria-1.1/#table

**Comment by sideshowbarker** [comment]
@stevefaulkner checker bug?

**Comment by jnurthen** [comment]
any updates? We are trying to publish aria-practices and are trying to squash any invalid HTML errors. We believe this is a bug in the validator.

**Comment by sideshowbarker** [comment]
> any updates? We are trying to publish aria-practices and are trying to squash any invalid HTML errors. We believe this is a bug in the validator.

Will check and try to get this updated today

**Comment by sideshowbarker** [comment]
Fix pushed to https://validator.w3.org/nu/
