### ISSUE TITLE
pointer-events false error

### ISSUE THREAD

**Issue by YoKoGFX** [validator/validator#582]
The Property `pointer-events` is giving false error messages.
https://developer.mozilla.org/de/docs/Web/CSS/pointer-events

Example: https://validator.w3.org/nu/?doc=https%3A%2F%2Ftanzschule-hartung.de%2F

**Comment by sideshowbarker** [comment]
I made a change today and as a result, stylesheets with the `pointer-events` property should no longer cause errors to be reported.

But if that hasn’t resolved the problem you were seeing, please post a follow-up comment here

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/582#issuecomment-349898794
