### ISSUE TITLE
when validators disagree...

### ISSUE THREAD

**Issue by lucy24** [validator/validator#584]
The HTML validator at
https://validator.w3.org/
says:
Warning: The type attribute for the style element is not needed and should be omitted.

The CSS validator next door at
http://jigsaw.w3.org/css-validator/
says:
Warning: You should add a 'type' attribute with a value of 'text/css' to the 'style’ element

Is it too much to ask that the two of you get your stories straight?

**Comment by sideshowbarker** [comment]
Thanks much for catching this and taking time to report it.

The CSS Validator needs updating to align with the current requirements for this in the HTML spec.

I’ve raised w3c/css-validator#97 for that.

**Comment by sideshowbarker** [comment]
https://github.com/w3c/css-validator/pull/97 has been merged and deployed, so closing thise
