### ISSUE TITLE
Show a larger chunk of the code causing the error.

### ISSUE THREAD

**Issue by SusanSS** [validator/validator#587]
We absolutely love the validator.
When finding errors... please consider displaying a large bit of the code.

> > Error found at:
> > `<td></td></tr> ....`

Doesn't tell us much.   That line could appear anywhere in our code.
Please display the line before... and error line... and the line after... and be MUCH more informative.

**Comment by sideshowbarker** [comment]
> Doesn't tell us much. That line could appear anywhere in our code.

The error message also shows the line number, right? (And the column number as well…)

**Comment by sideshowbarker** [comment]
Closing for lack of response.
