### ISSUE TITLE
Validate SVG files in command line

### ISSUE THREAD

**Issue by speedyhoon** [validator/validator#589]
Is it possible to validate standalone SVG files using vnu.jar?
I tried executing `java -Xss512k -jar vnu.jar icon.svg` which returned:
`"file:/D:/icon.svg":1.1-2.79: error: Start tag seen without seeing a doctype first. Expected ÔÇ£<!DOCTYPE html>ÔÇØ.`

Tried versions 17.3.0 and 17.11.1

**Comment by sideshowbarker** [comment]
> Is it possible to validate standalone SVG files using vnu.jar?

It’s not possible yet, but I can add support for it

**Comment by sideshowbarker** [comment]
https://sideshowbarker.net/nightlies/jar/vnu.jar now has SVG-checking support.

To use it, you must specify either the `--svg`, `--skip-non-svg`, or `--also-check-svg` option

For example, to check all documents in a particular directory as SVG, but skip any documents whose names don’t end with the extension `.svg`:

```
java -jar ~/vnu.jar --skip-non-svg some-directory-name/
```
