### ISSUE TITLE
Problem with validating table

### ISSUE THREAD

**Issue by cakotay** [validator/validator#591]
Missing closing tags for **tr** and **td** are not reported as errors.
In the following example there are no errors reported:
`<!DOCTYPE html>
    <html>
    <head>
    <title>Test</title>
    </head>
    <body>
    <table>
        <tr>
        <td>     
          some text
        <tr>
        <td>
           some more text
        <tr>
        <td>
           and more ...
    </table>
    </body>
    </html>`

**Comment by cvrebert** [comment]
Those end tags are technically optional, per the HTML spec. See #372.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/591#issuecomment-354761940
