### ISSUE TITLE
Start tag body seen but an element of the same type was already open.

### ISSUE THREAD

**Issue by zitengine** [validator/validator#594]
ISSUE:--------- How to solve
site:  [https://www.zitengine.com](https://www.zitengine.com)

Error: Bad value https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Lato:400,700 for attribute href on element link: Illegal character in query: | is not allowed.
From line 24, column 191; to line 24, column 312
ns     --><link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Lato:400,700"><link 
Error: Bad start tag in img in head.
From line 24, column 2161; to line 24, column 2285
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=355293128267412&ev=PageView&noscript=1"></noscri
Error: An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.
From line 24, column 2161; to line 24, column 2285
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=355293128267412&ev=PageView&noscript=1"></noscri
Error: Stray end tag noscript.
From line 24, column 2286; to line 24, column 2296
ript=1"></noscript>
	<link rel = "canonical" href = "<?php echo "https://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; ?>" />
	<?php
		//	CSS ZITNEIGNE
		include_once('../zitengine_include/common-css.html');
		//	 Global site tag (FB GA.js) - Google Analytics
		include_once('../zitengine_include/common-script-100.html');
	?>
</head>
<body>
<?php
	//NAV ZITENGINE
	include_once('../');
	//body ZITENGINE
	include_once('../');
	// Footer ZITENGINE
	include_once('../');
	//Common Modal ZITENGINE
	include_once('../');
	//ZITENGINE's   Java Script START
	include_once('../');
?>

<div class = "wrapper">
	<div class = "header">
	</div>
	
	<div class = "main">
		<div class = "container">
			
		</div>
	</div>
</div>
<script>
	// Aditional
</script>

</body>
</html>`

#at common script I have -------
common-script-100.html
`
<script async src = "https://www.googletagmanager.com/gtag/js?id=UA-33333333-1"></script>

<script>
	//###########Global site tag - Google Analytics START###########
	window.dataLayer = window.dataLayer || [];
	
	function gtag() {
		dataLayer.push(arguments);
	}
	
	gtag('js', new Date());
	
	gtag('config', 'UA-3333333333-1');
	// #########   Global site tag - Google Analytics END#########
	//###########  Facebook SDK for JavaScript START ###########
	window.fbAsyncInit = function () {
		FB.init({
			appId: '33333333333333',
			autoLogAppEvents: true,
			xfbml: true,
			version: 'v2.11'
		});
	};
	(function (d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {
			return;
		}
		js = d.createElement(s);
		js.id = id;
		js.src = "https://connect.facebook.net/en_US/sdk.js";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
	//#####    Facebook SDK for JavaScript END  #######
	//######   Facebook Pixel Code  START   ###########
	!function (f, b, e, v, n, t, s) {
		if (f.fbq) return;
		n = f.fbq = function () {
			n.callMethod ?
				n.callMethod.apply(n, arguments) : n.queue.push(arguments)
		};
		if (!f._fbq) f._fbq = n;
		n.push = n;
		n.loaded = !0;
		n.version = '2.0';
		n.queue = [];
		t = b.createElement(e);
		t.async = !0;
		t.src = v;
		s = b.getElementsByTagName(e)[0];
		s.parentNode.insertBefore(t, s)
	}(window, document, 'script',
		'https://connect.facebook.net/en_US/fbevents.js');
	fbq('init', '33333333333333');
	fbq('track', 'PageView');
	//#######  Facebook Pixel Code  END   ############
</script>

<noscript><img height = "1" width = "1" style = "display:none" src =
		"https://www.facebook.com/tr?id=355293128267412&ev=PageView&noscript=1" />
</noscript>

`

**Comment by cvrebert** [comment]
You can't put an `<img>` within a `<noscript>` within `<head>`.
Per the spec (emphasis added):

https://html.spec.whatwg.org/#the-noscript-element
> the allowed content model is as follows:
>
> * In a `head` element, if scripting is disabled for the `noscript` element:
>   * The `noscript` element **must contain only `link`, `style`, and `meta` elements.**
> * In a `head` element, if scripting is enabled for the `noscript` element:
>   * The `noscript` element **must contain only text**, except that invoking the HTML fragment parsing algorithm with the `noscript` element as the context element and the text contents as the input must result in a list of nodes that consists only of `link`, `style`, and `meta` elements that would be conforming if they were children of the `noscript` element, and no parse errors.

**Comment by zitengine** [comment]
This is Facebook Pixex Code. I have to put that into Head

**Comment by Malvoz** [comment]
> This is Facebook Pixel Code. I have to put that into Head

It is perfectly fine to put the code anywhere inside the `<body>` element.

**Comment by LeeKowalkowski** [comment]
The [guidance from Facebook](https://www.facebook.com/business/help/952192354843755) is: 

> Paste the code at the bottom of the header section, just above the closing head tag.

Disappointingly, Facebook aren't very hot on valid HTML.

**Comment by Malvoz** [comment]
@LeeKowalkowski 
Yes that is usually the recommendation for any third party analytics code, it is because you don't want to miss out on tracking hits if the visitor exits the page before the code is run. If a site is loading decently fast, this'll never be an issue.

**Comment by LeeKowalkowski** [comment]
Indeed. Yet as a site owner I doubt such a scenario ought to be considered a hit. If a visitor leaves before any content is displayed, counting a hit would unfairly spoil a conversion ratio.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/594#issuecomment-357054296
