### ISSUE TITLE
Allow multiple `main` elements when only one is visible

### ISSUE THREAD

**Issue by Arttse** [validator/validator#598]
In HTML 5.2 https://www.w3.org/TR/html52/grouping-content.html#elementdef-main

> There must not be more than one visible `<main>` element in a document. If more than one `<main>` element is present in a document, all other instances must be hidden using [§5.1 The hidden attribute](https://www.w3.org/TR/html52/editing.html#the-hidden-attribute).

Ref w3c/html@d53f789557ebc446fa87ea5e788677910af5cc79

---

There are #492 and #496, but maybe not fully implemented. For now, it's looks like this:

This code with no errors:
```html
<main>Text 1</main>
<main hidden>Text 2</main>
<main hidden>Text 3</main>
```

But this code:
```html
<main hidden>Text 1</main>
<main>Text 2</main>
<main hidden>Text 3</main>
```
and this
```html
<main hidden>Text 1</main>
<main hidden>Text 2</main>
<main>Text 3</main>
```
throw error ([validator.w3.org/nu](https://validator.w3.org/nu/)):
```
Error: A document must not include more than one visible main element.
```

cc @xfq @stevefaulkner

If I have something misunderstood, please explain. Thank you.

**Comment by xfq** [comment]
Looks like a bug in my (untested) code, sorry for that.

Given that https://github.com/whatwg/html/issues/100 will hopefully be fixed in the near future, I think we should just remove the `followW3Cspec` part and fix this issue (and adding the corresponding tests to WPT).
