### ISSUE TITLE
Error messages isn't displayed for time-zone string with a minus sign and a time-zone offset of zero

### ISSUE THREAD

**Issue by rh-KIMATA** [validator/validator#601]
[2.4.5.6. Time zones in HTML5.2](https://www.w3.org/TR/html52/infrastructure.html#time-zones)

> Either a U+002B PLUS SIGN character (+) or, if the time-zone offset is not zero, a U+002D HYPHEN-MINUS character (-), representing the sign of the time-zone offset

(And [2.3.5.6 Time zones in HTML Living Standard](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#time-zones) is the same.)

But, error messages isn't displayed for "&lt;time&gt;2018-01-18T00:00:00-00:00&lt;/time&gt;".

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve pushed the fix to https://validator.w3.org/nu/

**Comment by rh-KIMATA** [comment]
Thank you very much.
