### ISSUE TITLE
Error menu/listbox/tree/dialog/grid nor allowed as values for aria-haspopup

### ISSUE THREAD

**Issue by jnurthen** [validator/validator#602]
the following
```html
<button aria-haspopup="listbox" aria-labelledby="exp_elem exp_button" id="exp_button">Neptunium</button>
```
Triggers 
Error: Bad value listbox for attribute aria-haspopup on element button.

Aria 1.1 allows the following values for aria-haspopup

false - Indicates the element does not have a popup.
true - Indicates the popup is a menu.
menu - Indicates the popup is a menu.
listbox - Indicates the popup is a listbox.
tree - Indicates the popup is a tree.
grid - Indicates the popup is a grid.
dialog - Indicates the popup is a dialog.

See https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve pushed the fix to https://validator.w3.org/nu/
