### ISSUE TITLE
https://validator.nu/ is not accessible anymore

### ISSUE THREAD

**Issue by catalinbuletin** [validator/validator#603]
Hello,

I noticed that `https://validator.nu/` is not accessible anymore and by using `https://validator.w3.org/nu/` in the exact same way - with JSON output - i get an invalid JSON.

Is `https://validator.nu/` going to be permanently down?

Thanks

**Comment by jaimeiniesta** [comment]
https://validator.nu/ is also unreachable here, but I get a valid JSON output on https://validator.w3.org/nu/ :

https://validator.w3.org/nu/?doc=http%3A%2F%2Felpais.com&out=json

**Comment by sideshowbarker** [comment]
https://validator.nu/  appears to be available again

If you have a case where https://validator.w3.org/nu/ produces invalid JSON, please post a separate issue for that, and include a URL and document that can be used to reproduce the problem

**Comment by catalinbuletin** [comment]
@sideshowbarker  thanks a lot! as the https://validator.nu/ is online again, i'll close this issue!
