### ISSUE TITLE
Check By > Text Input issue no longer working in IE11?

### ISSUE THREAD

**Issue by graemecoleman** [validator/validator#604]
I'm having an issue trying to use Check By > Text Input in IE11. Selecting this option and then pressing Check used to display an editable skeleton HTML text area. However, this no longer appears to work on IE11 (but does on Google Chrome).

Tested on IE version 11.192.16299.0 (Windows 10, x64-based PC).

I can provide a screenshot if required.

**Comment by sideshowbarker** [comment]
Are any errors logged in the IE devtools console?

**Comment by stevefaulkner** [comment]
Object doesn't support property or method 'append'
`cssLabel.append("CSS")`
script.js (439,22)

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve pushed the fix to https://validator.w3.org/nu/
