### ISSUE TITLE
Is it possible to set User-Agent command-line checking?

### ISSUE THREAD

**Issue by karukade** [validator/validator#605]
Hi!

I'm new to Java.
I need check some pages that respond with different contents depending on the User-Agent string.
So I builded with --user-agent option. like below.

`./build/build.py --user-agent="mobile user agent" all`

then build jar.

`./build/build.py jar`

Standalone web server shows mobile's source results.
But command-line checking shows results of PC's source.

Is it possible to set user agent with command-line checking.
or something wrong with build?

**Comment by sideshowbarker** [comment]
The user-agent string was previously hardcoded in the command-line checker, but 9834af6 adds a new option for specifying it. See https://sideshowbarker.net/nightlies/jar/vnu.jar for jar with that option included — or else you can build a new one on your own from the latest sources in the master branch.

**Comment by karukade** [comment]
Thank you so much!! It really helped!
