### ISSUE TITLE
Validator says to add an english tag?

### ISSUE THREAD

**Issue by livi2201** [validator/validator#608]
<img width="990" alt="screen shot 2018-02-08 at 1 41 50 am" src="https://user-images.githubusercontent.com/26696942/35958943-57445f98-0c71-11e8-8865-94a38e0f58ff.png">

I don't think I need an english tag but I might be missing something, never seen anything like that before.

**Comment by sideshowbarker** [comment]
Change your `<html>` tag to `<html lang="en">`

**Comment by sideshowbarker** [comment]
Closing this per https://github.com/validator/validator/issues/608#issuecomment-364071839. But feel free to comment further if you need more clarification.
