### ISSUE TITLE
Validator tells me to change my US-ASCII page into both Windows-1252 and UTF-8

### ISSUE THREAD

**Issue by ssb22** [validator/validator#611]
When pointing validator.w3.org to my homepage http://people.ds.cam.ac.uk/ssb22 it gave the following 2 messages:

Error: Bad value text/html; charset=us-ascii for attribute content on element meta: us-ascii is not a preferred encoding name. The preferred label for this encoding is windows-1252.

Warning: Legacy encoding us-ascii used. Documents should use UTF-8.

As a webmaster, I see two conflicting pieces of advice.  One message is telling me to use windows-1252, and the other message is telling me to use UTF-8.  And the message that says windows-1252 looks stronger, because it is an error, whereas the other is only a warning.  So first of all I would suggest that, if we really want people to move to UTF-8, we should not also be telling them about Windows-1252.

Also, the message about Windows-1252 is unclear because it uses the phrase "preferred encoding name" but there are no results for this phrase on the front page of Google.  I believe some confusion has arisen from our reading of https://www.w3.org/International/questions/qa-choosing-encodings which says:

"Until recently the [IANA registry](http://www.iana.org/assignments/character-sets) was the place to find names for encodings. The IANA registry commonly includes multiple names for the same encoding. In this case you should use the name designated as 'preferred'. The new [Encoding](http://encoding.spec.whatwg.org/) specification now provides a list that has been tested against actual browser implementations. You can find the list in the table in the section called [Encodings](http://encoding.spec.whatwg.org/#encodings). It is best to use the names in the left column of that table."

Note that the term "preferred" was used only in the IANA table, not in the newer "Encoding" specification. The latter does not use the term "preferred", but the above W3C page has added the sentence "It is best to use the names in the left column of that table". However even that W3C page does not use the actual word "preferred" when referring to the newer "Encoding" specification, so no wonder this is hard to find if you are given as a starting point the phrase "preferred encoding name".  I think this message would be better if it contained a link to https://www.w3.org/International/questions/qa-choosing-encodings for a start.

Also, in the case of us-ascii, note that the older IANA registry recognises this as different from ISO-8859-1 and Windows-1252; I don't fully understand why the newer standard treats them as the same, especially given the ridiculously large number of other encodings (including UTF-8) that are also supersets of us-ascii, so if you are using only us-ascii bytes in your HTML file then why on earth should you have to call it Windows-1252?  There might be an ancient device out there that doesn't know what Windows-1252 is but is perfectly happy with us-ascii.  Not to mention that not all webmasters would like the idea of a gratuitous little promotion of a Microsoft product (my first thought was "have Microsoft taken over the W3C now").  I would be inclined to interpret the W3C's sentence "It is best to use the names in the left column of that table" as being mild enough not to insist that this means the fact that us-ascii entry is listed under Windows-1252 means we should use the term Windows-1252 instead of ASCII, especially in the case where it's possible to verify that only ASCII bytes are in use (I could cut this message much more slack if I were using non-ASCII bytes and incorrectly labelled the file "ascii", but if the code can see all my bytes are in fact ASCII, why tell me off for saying ascii?)

So I really think there is a strong case for removing that error altogether and just keep the warning that UTF-8 is now preferred, which nicely sidesteps the Windows-1252 issue.  Although in the case of ASCII-only pages, I don't even see why we should say utf-8 instead of us-ascii, as I certainly remember browsers that did not support utf-8 and it seems needless to declare our pages incompatible with such browsers even though there is not a single non-ASCII byte in the HTML file.

**Comment by sideshowbarker** [comment]
Agreed.

So in 261121e and validator/htmlparser@8563d77 I’ve changed the backend code to eliminate the unnecessary *“preferred encoding name”* message and to make the *“Legacy encoding foo used. Documents must use UTF-8.”* message an error rather than a warning.

I’ve pushed the updated code to https://validator.w3.org/nu/ so you can see the result at:

https://validator.w3.org/nu/?doc=http%3A%2F%2Fpeople.ds.cam.ac.uk%2Fssb22%2F

Note that the fact it reports two error messages rather than just one is intentional — because it’s actually reporting on two different error conditions that are caused by the (now) non-conforming character-encoding value specified.

But if you’re interested in a longer explanation of why that’s the case, lemme know; I’d be happy to elaborate in follow-up comment.

Regardless, thanks very much for taking time to report this. The behavior had been in need of an update for a while now, so your report was very helpful in giving me a push to look back at it and prioritize fixing it to align with the current spec requirements.

**Comment by sideshowbarker** [comment]
> Although in the case of ASCII-only pages, I don't even see why we should say utf-8 instead of us-ascii, as I certainly remember browsers that did not support utf-8 and it seems needless to declare our pages incompatible with such browsers even though there is not a single non-ASCII byte in the HTML file.

https://html.spec.whatwg.org/multipage/semantics.html#charset:utf-8 is the part of the HTML spec where the requirement for UTF-8 is stated; it says this:

> The Encoding standard requires use of the UTF-8 character encoding and requires use of the "utf-8" encoding label to identify it. Those requirements necessitate that the document's character encoding declaration, if it exists, specifies an encoding label using an ASCII case-insensitive match for "utf-8". Regardless of whether a character encoding declaration is present or not, the actual character encoding used to encode the document must be UTF-8.

**Comment by ssb22** [comment]
Thanks, that's great.  And my worry about declaring an ASCII page to be UTF-8 was triggered by my misremembering the behaviour of old versions of Lynx.  I remembered them as holding up the user with an extra alert if they encountered a character set they couldn't display, so I extrapolated they would complain about being asked to display a UTF-8 document on an ASCII-only terminal.  But now I've checked the source code from the 1998 version 2.8.1 (the oldest Lynx version I could still find), and I see the alert was actually issued if Lynx didn't know how to convert the character set to Unicode; it was not a complaint about a poor match between the character set and the likely terminal fonts as I had assumed.  So it should be fine to say UTF-8 for your ASCII-only site and still expect it to work without complaint on an old Unix box in a Computing History Museum.  That's a relief.

**Comment by sideshowbarker** [comment]
> So it should be fine to say UTF-8 for your ASCII-only site and still expect it to work without complaint on an old Unix box in a Computing History Museum.  That's a relief.

Yeah, good to know. And thanks again for having taken time to raise this issue. I’m glad to have the checker behavior aligned with the current spec requirement.
