### ISSUE TITLE
bcp 47 t extension should not cause an error

### ISSUE THREAD

**Issue by r12a** [validator/validator#613]
If you try to validate (or publish) https://www.w3.org/TR/2018/WD-alreq-201802022/ you get 626 error messages complaining about the -t extension.  That shouldn't happen. See https://tools.ietf.org/html/rfc6497

**Comment by xfq** [comment]
The /TR link is 404 for the moment. Providing the ED link here for your convenience: https://w3c.github.io/alreq/

**Comment by sideshowbarker** [comment]
Will fix this soon. Is `t` the only standard extension that there’s a spec for so far? If not, where are the others documented?

**Comment by sideshowbarker** [comment]
Fix pushed to https://validator.w3.org/nu/ —

https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Falreq%2F

**Comment by xfq** [comment]
Also verified in the /TR version:

* https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FWD-alreq-20180222%2F
* https://checker.html5.org/?doc=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FWD-alreq-20180222%2F

Thank you :)

-----

By the way, there's also [BCP 47 Extension U](https://tools.ietf.org/html/rfc6067), which is also a part of [LDML](https://www.unicode.org/reports/tr35/#Locale_Extension_Key_and_Type_Data). And there's "x-", which is for private use extensions.

Should I file a new issue?

See the following links for more info:

* https://www.w3.org/International/articles/language-tags/#extension
* https://www.iana.org/assignments/language-tag-extensions-registry/language-tag-extensions-registry
* https://en.wikipedia.org/wiki/IETF_language_tag#Extensions

**Comment by sideshowbarker** [comment]
> By the way, there's also [BCP 47 Extension U](https://tools.ietf.org/html/rfc6067), which is also a part of [LDML](https://www.unicode.org/reports/tr35/#Locale_Extension_Key_and_Type_Data).

Ah, OK. I think the checker code may not support that yet

> And there's "x-", which is for private use extensions.

OK yeah, that one we already support.

> Should I file a new issue?

nah, it’s OK — I’ll investigate

**Comment by r12a** [comment]
On 24/02/2018 22:44, Michael[tm] Smith wrote:
>     By the way, there's also BCP 47 Extension U
>     <https://tools.ietf.org/html/rfc6067>, which is also a part of LDML
>     <https://www.unicode.org/reports/tr35/#Locale_Extension_Key_and_Type_Data>.
> 
> Ah, OK. I think the checker code may not support that yet
> 
>     And there's "x-", which is for private use extensions.
> 
> OK yeah, that one we already support.
> 
>     Should I file a new issue?
> 
> nah, it’s OK — I’ll investigate

thanks Mike. The u- extension is described at 
http://www.rfc-editor.org/rfc/rfc6067.txt

I have to admit, i'm currently not entirely up to date on other 
extensions beyond u- and t- (and of course x-).  Addison would know.

ri
