### ISSUE TITLE
Inconsistency between command line and online version in error

### ISSUE THREAD

**Issue by gemal** [validator/validator#614]
I have the following piece of HTML code:

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>x</title>
	</head>
	<body>
		<div class="b-question-expand" role="button" data-toggle="collapse" data-target="#b-question-3" aria-expanded="false" aria-controls="b-question-3">
			<a><i class="fa fa-plus" aria-hidden="true"></i></a>
			<div class="collapse" id="b-question-3">test</div>
		</div>
	</body>
</html>
```

On https://validator.w3.org/nu/#textarea I get:
`The element a must not appear as a descendant of an element with the attribute role=button`

Using command line version 17.11.1 I get valid HTML

Not sure if I'm doing anything wrong or?

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/614#issuecomment-371353745 but feel free to comment further here if needed
