### ISSUE TITLE
Validator reports Carriage Return numeric entity as an error

### ISSUE THREAD

**Issue by JAT86** [validator/validator#617]
The validator reports that the HTML entity `&#013;` (Carriage Return/new line) is an error:

```
Error: A numeric character reference expanded to carriage return.

At line 17, column 6282

sample&#013;text
```
Why would this be an error?

**Comment by sideshowbarker** [comment]
> The validator reports that the HTML entity `&#013;` (Carriage Return/new line) is an error…
> Why would this be an error?

Because the HTML spec requires it to be treated as a parse error:

https://html.spec.whatwg.org/multipage/parsing.html#numeric-character-reference-end-state:parse-error-control-character-reference

> **If the number is 0x0D**, or a control that's not ASCII whitespace, **then this is a control-character-reference parse error**.

＊(…[`0x0D` is the same code point represented by `&#13`](https://www.fileformat.info/info/unicode/char/d/index.htm))

**Comment by JAT86** [comment]
Ok, thank you for clarifying. So what would be the alternative for adding a new line within the HTML and have the document validated? I explicitly used `&#013;` so that I could add a line break within the `title` attribute.

**Comment by sideshowbarker** [comment]
> So what would be the alternative for adding a new line within the HTML and have the document validated?

Use an actual line break instead of a character reference

> I explicitly used `&#013;` so that I could add a line break within the `title` attribute.

Line breaks are allowed in the `title` attribute. If you put a line break in the `title` attribute, the document will validate.

**Comment by JAT86** [comment]
Thanks. I did not know that was possible. Maybe the validator should suggest this solution?

**Comment by sideshowbarker** [comment]
Going ahead and closing per https://github.com/validator/validator/issues/617#issuecomment-370146965

> Maybe the validator should suggest this solution?

Yeah, I’ll investigate adding a bit more detail/context to the error message.

In the mean time, we have the discussion preserved in the comments here — so at least others who find themselves asking the same question and doing a Google search will be able to find the answer here. So thanks much for taking time to raise the issue
