### ISSUE TITLE
How to activate the optional CSS check?

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#621]
In the latest release this feature is mentioned:

> optional feature in the command-line checker, Web-based checker, and network API to check CSS documents (in addition to the checking of HTML documents we already do)

How can I activate it on the web-based checker? I can only find the `--also-check-css` flag for the command-line checker.

**Comment by sideshowbarker** [comment]
@jaimeiniesta Any more clarification need on this? Is there anything that’s not’s working the way you’d expect?

**Comment by jaimeiniesta** [comment]
Yes, the tag `--also-check-css` mislead me into thinking that I could validate an HTML page and tell it to `also` check the linked stylesheets. But this is not how it works, right? We need to validate CSS stylesheets apart. As inline styles will always be validated, I don't get why this option is named `also`.

>  or use the text-input option with CSS checkbox checked

I can't find that checkbox in https://validator.w3.org/nu/

**Comment by sideshowbarker** [comment]
> Yes, the tag `--also-check-css` mislead me into thinking that I could validate an HTML page and tell it to `also` check the linked stylesheets. But this is not how it works, right?

When checking an *HTML*, right, it only checks the internal CSS that’s embedded in the document itself — not any external CSS. But the `--also-check-css` option has nothing to do with that — instead what it causes to happen is that if you’re running the command-line checker in the default way (to check `.html` and `.xhtml` documents) it also causes the command-line checker to check any `.css` files it finds (e.g., if you have it recursively checking a directory).

> We need to validate CSS stylesheets apart.

Well, the checker will never follow any `link rel=stylesheet` elements in HTML document to check those external CSS contents. But if you’re running the checker on a directory in the local filesystem, and you have `.css` files in the same directory — or in a subdirectory (e.g., a `style` or `css` or whatever directory), it will check those `.css` files along with the `.html` files.

> As inline styles will always be validated, I don't get why this option is named `also`.

I hope the above explanation helps to clarify that

> >  or use the text-input option with CSS checkbox checked

> I can't find that checkbox in https://validator.w3.org/nu/

I mean the checkbox on the https://validator.w3.org/nu/#textarea view — right next to the **text input** select control.

**Comment by jaimeiniesta** [comment]
Thanks for the explanation! All is clear now.
