### ISSUE TITLE
[Suggestion] Remove gzip decompression configuration from web.xml

### ISSUE THREAD

**Issue by Umoxfo** [validator/validator#622]
The `vnu.war` file is bundled with some jetty libraries as gzip decompression dependencies. 
I think if this feature is necessary, you use what a servlet container provides. As a result, it is possible to reduce the file size of `vnu.war`.

**Comment by sideshowbarker** [comment]
> The `vnu.war` file is bundled with some jetty libraries as gzip decompression dependencies. 
I think if this feature is necessary, you use what a servlet container provides. As a result, it is possible to reduce the file size of `vnu.war`.

No objection from me. But ideally before we make that change, it’d be good to hear from some of the known uses of the war distribution to see if they agree — especially @jacobq (who wrote the war build) and @Pacoup and @jaimeiniesta.

As far as why the gzip filter was in the war to begin with, my guess is, when @jacobq designed it to replicate https://github.com/validator/validator/blob/master/src/nu/validator/servlet/Main.java; esp. this:

https://github.com/validator/validator/blob/dc2deecad6c60705776b6fca2704d6064d9179e7/src/nu/validator/servlet/Main.java#L67-L68

But if server containers already provide their own means for gzipping responses, then it’s not necessary for the war distribution to provide its own.

**Comment by jaimeiniesta** [comment]
I'm not sure how this might affect the installation from Docker Hub / npm packages. If it doesn't affect and we can keep gzip decompression on those after this change, then it's OK for me to remove them.

**Comment by jacobq** [comment]
To be honest, it's been so long since I've used this (made the WAR package for a special situation for a former employer) that I can't remember why we needed it. However, I like the idea of leaving the HTTP-ish details to the container rather than the validator package (separation of concerns) and have no objection to removing the gzip-related stuff from here.

**Comment by sideshowbarker** [comment]
Responding to @jaimeiniesta:

> I'm not sure how this might affect the installation from Docker Hub / npm packages

The npm just uses the jar distro, which will continue to include the gzip filter, so the proposed change here wouldn’t affect that at all.

The https://github.com/validator/validator/blob/master/Dockerfile (upstream) Dockerfile uses the jar distro too, so it also isn’t affected.

However, it would affect sitevalidator/nu-cat (as currently configured). But I believe the solution there is to make the Docker build do an edit of the `/usr/local/tomcat/conf/server.xml` such that to the relevant `Connector` element there, it adds `compression="on"`; for example:

```xml
<Connector port="8080" protocol="HTTP/1.1"
           compression="on"
           connectionTimeout="20000"
           redirectPort="8443" />
```

**Comment by Pacoup** [comment]
> However, it would affect sitevalidator/nu-cat (as currently configured). But I believe the solution there is to make the Docker build do an edit of the /usr/local/tomcat/conf/server.xml such that to the relevant Connector element there, it adds compression="on"; for example:

I believe this is correct, but could sitevalidator/nu-cat work without gzip if you don't enable compression in your servlet container?

**Comment by sideshowbarker** [comment]
> I believe this is correct, but could sitevalidator/nu-cat work without gzip if you don't enable compression in your servlet container?

Yeah, it’ll still work fine — the responses will just be sent as-is and never gzipped. But in the rest of the validator code there’s nothing that depends on the responses being gzipped — not in the frontend JavaScript code nor any part of the backend code.

**Comment by jaimeiniesta** [comment]
Then it's OK for me, I'll update `nu-cat` to add that `compression="on"` option.
