### ISSUE TITLE
Please emit warning "Consider adding a lang attribute to the html start tag to declare the language of this document." regardless of number of chars

### ISSUE THREAD

**Issue by takenspc** [validator/validator#626]
Nu Html Checker emits following warning if the html element has no lang attribute and the checker collects more than 1024 chars.

> Warning: Consider adding a lang attribute to the html start tag to declare the language of this document

However, it doesn't emit the warning when the page isn’t lengthy. This could cause flakiness of continuous testing. The number of warning varies with time when the number of characters varies with time.

As far as I know, the warning corresponds to following paragraph of the HTML Standard.

https://html.spec.whatwg.org/multipage/semantics.html#the-html-element
> Authors are encouraged to specify a lang attribute on the root html element, giving the document's language.

The paragraph doesn’t mention about length of the document. [If the author can’t identify the language, she or he can use lang=""](https://html.spec.whatwg.org/multipage/dom.html#attr-lang) though it rarely happens.

I believe that Nu Html Checker should always encourage authors to specify lang attribute. This will make Nu Html Checker more useful for continuous testing.

**Comment by sideshowbarker** [comment]
Agreed and thanks — fix pushed to https://validator.w3.org/nu/ and https://checker.html5.org/

**Comment by Guil44** [comment]
"Warning: Consider adding a lang attribute to the html start tag to declare the language of this document."

I have got the same problem. I have tested :  <meta charset="UTF-8">    and    
<html lang="en">. they do not pass the validator.
