### ISSUE TITLE
Report "Use CSS instead" error for body[topmargin]

### ISSUE THREAD

**Issue by takenspc** [validator/validator#631]
Please refer to https://github.com/whatwg/html/pull/3603

Currently https://checker.html5.org/ reports "Use CSS instead" error for margintop of body element while the obsoleted attribute is topmargin.

https://checker.html5.org/?doc=data%3Atext%2Fhtml%2C%3C%21DOCTYPE+html%3E%3Chtml+lang%3Den%3E%3Chead%3E%3Cmeta+charset%3Dutf-8%3E%3Ctitle%3ETest%3C%2Ftitle%3E%3C%2Fhead%3E%3Cbody+margintop%3D10+topmargin%3D50%3E

It should report the error for topmargin.

**Comment by sideshowbarker** [comment]
Pushed to https://checker.html5.org/ and https://validator.w3.org/nu/
