### ISSUE TITLE
Set up some systematic way to more consistently push new nightlies and Docker images

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#633]
I'd like to install the same version that http://validator.w3.org/nu/ has - currently 18.4.6, but installing validator/validator:latest will give me 18.3.24.

Is there any way to do that from Dockerhub? Maybe an `edge` tag?

**Comment by jaimeiniesta** [comment]
The reason for that is that for the same document I'm getting different reports, on 18.3.24 I get 7 `Element “p” not allowed as child of element “figure” in this context` errors, while on 18.4.6 we get no errors.

**Comment by sideshowbarker** [comment]
> I'd like to install the same version that http://validator.w3.org/nu/ has - currently 18.4.6, but installing validator/validator:latest will give me 18.3.24.
> 
> Is there any way to do that from Dockerhub? Maybe an edge tag?

There is no way. The available Dockerhub version just depends on whether I’ve pushed a new nightly to https://sideshowbarker.net/nightlies/ or not. The http://validator.w3.org/nu/ version is independent of whether or not I’ve pushed a new nightly; so the http://validator.w3.org/nu/ version is usually ahead of the nightly version.

I guess the answer is that any time you find that http://validator.w3.org/nu/ is ahead of the Dockerhub version, and you need a Dockerhub version of whatever http://validator.w3.org/nu/ has, then either ping me on Gitter or raise an issue here, and I’m push a new nightly build.

> The reason for that is that for [the same document](https://bobbi.ivytech.edu/~emead/project/secondDraft/FeaturedListings.html) I'm getting different reports, on 18.3.24 I get 7 `Element “p” not allowed as child of element “figure” in this context` errors, while on 18.4.6 we get no errors.

That surprises me. I can’t see any commit that was made in between which would account for that

**Comment by sideshowbarker** [comment]
I pushed a new nightly just now, so the Dockerhub version should now pick that up

**Comment by jaimeiniesta** [comment]
It looks like Docker Hub is not picking the latest version:

https://hub.docker.com/r/validator/validator/builds/

**Comment by sideshowbarker** [comment]
> I've kept a server on 18.3.24 so you can see the difference in the report:
> 
> [18.3.24 returns 7 errors](http://167.99.43.122:8888/?doc=https%3A%2F%2Fbobbi.ivytech.edu%2F~emead%2Fproject%2FsecondDraft%2FFeaturedListings.html)
> 
> [validator.w3.org/nu returns 0 errors](http://validator.w3.org/nu/?doc=https%3A%2F%2Fbobbi.ivytech.edu%2F~emead%2Fproject%2FsecondDraft%2FFeaturedListings.html)

Thanks much

So I still don’t understand what caused that. I’ll make some time to investigate and figure out it so that I can make sure it doesn’t happen again, but off the top of my head, the only thing I can imagine is that when I build the 18.3.24 nightly I must have somehow had my git clone set to an older revision.

**Comment by sideshowbarker** [comment]
> It would be great if this could be automated so a new nightly would be pushed periodically, this way we don't need to bother you to do it manually every time :)

Agreed. I’ll work on getting some automation set up for that

**Comment by sideshowbarker** [comment]
* https://github.com/validator/validator/releases now has auto-published nightlies
* https://hub.docker.com/repository/docker/validator/validator/ now has auto-published images

…so I’m gonna go ahead and close this out. But feel free to comment here further to let me know if we need more work to get done here.
