### ISSUE TITLE
Code in the master branch needs Java 9

### ISSUE THREAD

**Issue by prantlf** [validator/validator#634]
When you release the next version after 18.3.0, do you want people, who use this validator, upgrade to Java 9 or will you [build the JAR files for compatibility with Java 8](http://openjdk.java.net/jeps/247)? For example:

```sh
javac --release 8
```

I found this by using the Node.js integration via `vnu-jar@dev`, which includes a newer JAR, than the latest release 18.3.0. I run it with Java 8:

```text
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at nu.validator.htmlparser.io.HtmlInputStreamReader.<init>(HtmlInputStreamReader.java:175)
	at nu.validator.htmlparser.io.Driver.tokenize(Driver.java:197)
	at nu.validator.htmlparser.sax.HtmlParser.tokenize(HtmlParser.java:488)
	at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:408)
	at nu.validator.spec.html5.Html5AttributeDatatypeBuilder.parseSyntaxDescriptions(Html5AttributeDatatypeBuilder.java:76)
	at nu.validator.messages.MessageEmitterAdapter.<clinit>(MessageEmitterAdapter.java:291)
	at nu.validator.client.SimpleCommandLineValidator.setErrorHandler(SimpleCommandLineValidator.java:545)
	at nu.validator.client.SimpleCommandLineValidator.setup(SimpleCommandLineValidator.java:302)
	at nu.validator.client.SimpleCommandLineValidator.main(SimpleCommandLineValidator.java:291)
```

The JAR worked well after upgrading Java to the version 9.

**Comment by Arttse** [comment]
I can't to reproduce. Tested in Ubuntu 16.04. Worked with Java 8:
```sh
$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
I installed `vnu-jar@dev` and then ran this script:
```js
const exec = require("child_process").exec;
const vnu = require("vnu-jar");

exec(`java -jar ${vnu} --version`, (error, stdout) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }

  console.log(stdout);
});
```
Output:
```sh
nightly.2018-04-09
```

---
Could you provide more information?

**Comment by sideshowbarker** [comment]
I can reproduce this and I understand the cause. Unfortunately in our case, using the `--release` option isn’t a solution — because the checker sources are currently using some internal Nashorn APIs that aren’t exposed when using the `--release` option or `-bootclasspath` or `-system` options.

However, I can instead make a change to the sources that will allow the code to run under Java8 even when while compiled under Java9. I have a patch ready to land but I need to test it further before landing it.

**Comment by prantlf** [comment]
@Arttse , are you sure, that you installed `vnu-jar` from the `dev` branch?

```sh
npm i vnu-jar@dev
```
The latest released version of `vnu-jar` includes an earlier JAR file from `validator`, which works with Java 8 well.

For example, testing this grunt task with Java 8 fails: https://github.com/prantlf/grunt-html/tree/vnu-jar-dev.

**Comment by prantlf** [comment]
@sideshowbarker, yes, it would work too. I created this issue as a question, at first, what Java would you like to request. I don't know, what your other customers would say. I don't know, what benefits has compiling and running on Java 9.

I use `validator` via `vnu-jar` and `grunt-html` to validate HTML snapshots for a couple of products during the CI/CD build. Installing Java 9 will be no problem, if you decide for it and document it. (Your README says, that Java 8 is the minimum now.) If you change the code to be compilable for Java 8, it will be no problem either, of course :-)

**Comment by Arttse** [comment]
@prantlf, I installed `vnu-jar@dev` via NPM: `npm i vnu-jar@dev`. The recent version of dev tag is `18.4.9`. Output version is `nightly.2018-04-09`.

I cloned https://github.com/prantlf/grunt-html/tree/vnu-jar-dev then ran `npm i && npm test` and it passes with Java 8 (`1.8.0_171`). Tested with Node.js `v8.11.1` and NPM `5.6.0`. Maybe I'm doing something wrong?

I tried to build validator jar from commit 814927f015200cb510582237c3266e4eead9218d:
```sh
$ ./build/build.py update dldeps build test jar
```
and it again works:
```sh
$ java -jar ./build/dist/vnu.jar --version
18.4.27
```
and for https://github.com/prantlf/grunt-html/tree/vnu-jar-dev too...

The fact that @sideshowbarker knows why the error is happening is good. But I'm wondering why then it works for me with Java 8, but not works for @prantlf with Java 8?

**Comment by sideshowbarker** [comment]
I fixed this by making a change to the HTML parser sources:

https://github.com/validator/htmlparser/commit/cad75746991d4a18c11d50a1df44d34a7aeba95c

I believe that’s the only change needed to ensure the classes will be runnable under Java8 even when compiled under Java9.

**Comment by MPParsley** [comment]
I know that the README states you need java 8 but java 9 and up should be supported no?

I have java 9 and I'm using this package via grunt-html which results in the following error:
```
Running "htmllint:all" (htmllint) task
Fatal error: 
Unsupported Java version used: 9.0.4. v1.8 is required!
```

**Comment by Arttse** [comment]
@MPParsley maybe a problem in the package grunt-html? https://github.com/jzaefferer/grunt-html/blob/v9.0.0/lib/htmllint.js#L75

Please create an issue in https://github.com/jzaefferer/grunt-html

**Comment by MPParsley** [comment]
Indeed @Arttse, thanks!

I created a PR to reflect the java support: #680 and a PR over at https://github.com/jzaefferer/grunt-html/pull/120.
