### ISSUE TITLE
Validator showing error for <svg><use href="xxx"...>

### ISSUE THREAD

**Issue by KringleClaus** [validator/validator#641]
In validating my WordPress blog, I am getting the following:

> Attribute href not allowed on element use at this point.
> <use↩href="#icon-youtube" xlink:href="#icon-youtube"></use>
{see [https://validator.w3.org/nu/?doc=https%3A%2F%2Fsanta-claus-blog.emailsanta.com](https://validator.w3.org/nu/?doc=https%3A%2F%2Fsanta-claus-blog.emailsanta.com)}

While the xlink:href attribute is deprecated, I thought href was a valid attribute of `<svg><use>` 
{see [https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use)}

**Comment by sideshowbarker** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use#Browser_compatibility indicates that all major browser engines support `use@href` so yeah I’ll land a change soon that makes it a non-error.

**Comment by KringleClaus** [comment]
Many thx SSB!  All your work is greatly appreciated.  I'll see if the elves can make something extra special for you this Christmas 0<;-}}}

**Comment by sideshowbarker** [comment]
OK, in looking at the checker sources I see they actually already allow the `href` attribute for `use`.

But what the sources intentionally do not allow is: They don’t allow the `href` attribute if the `use` element has an `xlink:href` attribute.

So to avoid the error message from the checker, drop the `xlink:href` attributes from your document.

On the face of it, using both the `href` and `xlink:href` on the same element seems like bad practice. So unless there’s some compelling use case for having an element with both, I don’t intend to make any change to the checker for this issue.

**Comment by sideshowbarker** [comment]
I’m gonna go ahead and close this per https://github.com/validator/validator/issues/641#issuecomment-386788964 but please feel free to comment here further and if you have new info, we could reopen this

**Comment by anasbouzid** [comment]
Safari doesn't support `use@href`. Unfortunately, I have to keep both attributes.

**Comment by sideshowbarker** [comment]
> Safari doesn't support `use@href`. Unfortunately, I have to keep both attributes.

If that works without causing any unexpected side effects, then I guess you can safely ignore the error.

And from the spec I can’t actually tell whether the spec allows `use` with both `href` and `xlink:href` at the same time. So if you’d like for the checker behavior on this to change, I suggest raising an issue at https://github.com/w3c/svgwg/issues asking for the spec to be updated to make it clear.

**Comment by sideshowbarker** [comment]
On further reflection, since I can’t find any explicit prohibition in the SVG spec that disallows use of `href` and `xlink:href` together on the same element, I’ve gone ahead and pushed a change that allows it in the checker.

https://validator.w3.org/nu/ and https://checker.html5.org/ now both have that change.
