### ISSUE TITLE
html5check.py on web site out of date

### ISSUE THREAD

**Issue by tbm** [validator/validator#651]
(I hope it's okay to open an issue here, I'm not sure if there's  better place)

https://about.validator.nu/ offers a command line option and links to https://about.validator.nu/html5check.py but unfortunately this script is out of date - it doesn't work as it doesn't include the fix for issue #434.

**Comment by sideshowbarker** [comment]
The current source of that script is now here:

https://github.com/validator/validator/blob/master/resources/examples/html5check.py
https://raw.githubusercontent.com/validator/validator/master/resources/examples/html5check.py

**Comment by sideshowbarker** [comment]
I’ve changed to the link to point to the current location, in the upstream source for https://about.validator.nu/. However, @hsivonen will need to pull that change in order for https://about.validator.nu/ itself to actually get updated.

Note however that at this point, https://validator.github.io/validator/ has more-current docs — including information about how to check documents from the command-line using the `vnu.jar` distribution — and for Python, the (third-party) `html5validator` script, which available as a `pip` package and from https://github.com/svenkreiss/html5validator

**Comment by tbm** [comment]
Thank you @sideshowbarker

**Comment by hsivonen** [comment]
Sorry about failing at GitHub notifications. I've updated the link.
