### ISSUE TITLE
some roles incorrectly valid for <datalist>

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#653]
[test case](https://hanshillen.github.io/aria-test-builder/dist/testcases/datalist-test.html)

- role='menuitem' incorrectly flagged as valid for datalist element.
- role='none' incorrectly flagged as valid for datalist element.
- role='presentation' incorrectly flagged as valid for datalist element.

**Comment by sideshowbarker** [comment]
Thanks — pushed to https://validator.w3.org/nu/
