### ISSUE TITLE
potentially bad advice on "copyright" link relation

### ISSUE THREAD

**Issue by reschke** [validator/validator#654]
From <https://validator.w3.org/nu/?doc=https%3A%2F%2Fgreenbytes.de%2Ftech%2Fwebdav%2Frfc7230.html>:

> Potentially bad value Copyright for attribute rel on element link: The keyword copyright for the rel attribute should not be used. Consider using license instead.

However:

- "copyright" appears both in <https://www.w3.org/TR/html4/types.html#h-6.12> and <http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions>

...so it would be good if there was a place that explained why "license" is preferable over "copyright" (and why).

**Comment by sideshowbarker** [comment]
I think the checker is in conformance with the spec on this (and the Microformats wiki is not…)

See https://html.spec.whatwg.org/multipage/links.html#linkTypes:attr-hyperlink-rel
> Some of the sections that follow the table below list synonyms for certain keywords. The indicated synonyms are to be handled as specified by user agents, but **must not be used in documents (for example, the keyword "copyright").**

And https://html.spec.whatwg.org/multipage/links.html#link-type-license:link-type-license-4 has the “indicated synonyms” for the `license` keyword:
> Synonyms: For historical reasons, user agents must also treat the keyword "copyright" like the license keyword.

So I think if I can change the checker behavior on this, the checker won’t conform to the HTML spec.
Therefore if we want to the checker behavior to change, then I think the HTML spec needs to change (and so an issue should be filed there).

But let me know if you disagree that the spec is making such a requirement.

> ...so it would be good if there was a place that explained why "license" is preferable over "copyright" (and why).

Agreed, but I personally don’t know why either

**Comment by reschke** [comment]
Ah.

I was looking at the list of defined link relations, did not see "copyright", and thus ended up at <https://www.w3.org/TR/html52/links.html#sec-other-link-types> which refers to the Microformats Wiki.

FWIW, if UAs need to treat "copyright" and "license" as equivalent anyway then there's no good reason to make one of these non-compliant; in particular if it was compliant in earlier versions of HTML (4).

**Comment by sideshowbarker** [comment]
> FWIW, if UAs need to treat "copyright" and "license" as equivalent anyway then there's no good reason to make one of these non-compliant; in particular if it was compliant in earlier versions of HTML (4).

Personally I agree — however as far as the checker behavior I’m limited to what the current spec actually says. But if you raised it as an issue at https://github.com/whatwg/html/issues I’d at least be happy to weigh in to agree.

More broadly though, I’m not convinced there’s much benefit to having any document-conformance requirements for `rel` values at all. I mean, at this point I’d personally rather the spec didn’t state any restrictions at all on what `rel` values can be used in documents.

**Comment by reschke** [comment]
See https://github.com/whatwg/html/issues/3724
