### ISSUE TITLE
validation for pronunciation link keyword

### ISSUE THREAD

**Issue by Nick-Levinson** [validator/validator#656]
The HTML 5.2 link element may use the rel attribute, which may have as its value a keyword. While some keywords are predefined, extensions may be registered under HTML 5.2 section 4.8.6.14 at <http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions>. That page, more broadly, lists proposals for HTML as existing rel values at <http://microformats.org/wiki/existing-rel-values#proposals>. The proposals section begins with this: "A few rel values have been developed as drafts as a result of going through most of the microformats process, and are thus listed here for your serious consideration. You may use these values". (It then discusses an issues page, but that page does not exist.)

One of the proposed keywords that thus may be used is "pronunciation".

However, the validator rejects it as "not a registered keyword".

But it may be used as an extension. Therefore, the validator either should accept it or, if rejection is a more accurate response for the validator, it should explain that it is a proposal for HTML and that it may be used.

**Comment by sideshowbarker** [comment]
Fixed and pushed to https://validator.w3.org/nu
