### ISSUE TITLE
Removed </html>, but no error is found

### ISSUE THREAD

**Issue by mohnoj** [validator/validator#658]
![screenshot from 2018-06-01 11-48-22](https://user-images.githubusercontent.com/39024902/40824417-bc063dc4-6591-11e8-947f-ce475d6a710c.png)
(:

**Comment by sideshowbarker** [comment]
The `</html>` end tag is optional:

https://html.spec.whatwg.org/multipage/semantics.html#the-html-element

> Tag omission in text/html:
> * An `html` element's start tag can be omitted if the first thing inside the `html` element is not a comment.
> * An `html` element's end tag can be omitted if the `html` element is not immediately followed by a comment.

**Comment by cvrebert** [comment]
See also https://github.com/validator/validator/issues/372#issuecomment-248201300 for tools to detect "missing" close tags.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/658#issuecomment-393779556
