### ISSUE TITLE
Investigate setting up automated testing of war builds on Heroku

### ISSUE THREAD

**Issue by sideshowbarker** [validator/validator#66]
https://devcenter.heroku.com/articles/deploying-war-files-to-heroku-from-travis-ci

**Comment by sideshowbarker** [comment]
So I ended up deciding not to use Travis to automate the upload to Heroku but instead to just add a `heroku` build target that can be called to push https://vnu.herokuapp.com/ when needed.

For Travis testing of the war file, I added steps that install Tomcat 7, copy the vnu.war file to the Tomcat webapps dir, and then send a document to that vnu instance for checking:
https://github.com/validator/validator/blob/master/.travis.yml#L22
```
- sudo apt-get install tomcat7
- sudo cp ./build/dist/vnu.war /var/lib/tomcat7/webapps
- sleep 15
- curl -sS 'http://localhost:8080/vnu/?out=gnu&doc=data:text/html;charset=utf-8,%3C%21doctype%20html%3E%3Cmeta%20charset%3Dutf-8%3E%3Ctitle%3ETest%3C%2Ftitle%3E' > RESULTS
- test -z "$(cat RESULTS)"
- if [ $? != 0 ]; then cat RESULTS; fi

**Comment by jaimeiniesta** [comment]
I'd be interested in knowing how to set up vnu in Heroku, can you share the recipe?
