### ISSUE TITLE
Multiple meta descriptions now allowed (only in W3C fork)

### ISSUE THREAD

**Issue by nschonni** [validator/validator#663]
Originally made an error in #370
Looks like they have been "allowed" now in https://github.com/w3c/html/issues/553 via https://github.com/w3c/html/pull/1161

**Comment by matkoniecz** [comment]
It it a proposal to revert https://github.com/w3c/html/pull/1161 or is it proposal to apply https://github.com/w3c/html/pull/1161 also in this repository?

**Comment by sideshowbarker** [comment]
All document-conformance requirements now must be in the canonical (WHATWG) HTML spec in order to be normative.
