### ISSUE TITLE
vnu-jar@dev cannot be found by npm

### ISSUE THREAD

**Issue by prantlf** [validator/validator#668]
Installing `vnu-jar@dev` reports, that this module does not exist:

```txt
npm ERR! code ETARGET
npm ERR! notarget No matching version found for vnu-jar@dev
```
See [the full npm log](https://gist.github.com/prantlf/cab7695eb85d3235ffa945027cfa6574) for more information.

Was this package & version removed by accident, or are you planning to be releasing versioned releases `vnu-jar` more often? We use it to validate HTML using `vnu-jar` as close to https://validator.w3.org/nu/ as possible.

Thank you!

**Comment by sideshowbarker** [comment]
I changed the tag to `next`. Sorry for the hassle that created. But I made a `18.6.16` of `next` just the other day. So you can grab that.

**Comment by prantlf** [comment]
The `next` works well. Thank you!
