### ISSUE TITLE
Validator says no doctype

### ISSUE THREAD

**Issue by extasy2247** [validator/validator#677]
Validator says no doctype, while dotctype is here in source code

**Comment by cvrebert** [comment]
We'd need a link to your webpage, or for you to post its HTML source here, in order to debug this. We can't do anything sight-unseen.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/677#issuecomment-402528591 and lack of response so far. But if you have new information to add, then please post it here and I can respond and re-open if needed
