### ISSUE TITLE
"Consider adding a lang attribute to the html start tag to declare the language of this document." not reported by .jar file, reported by https://checker.html5.org/

### ISSUE THREAD

**Issue by matkoniecz** [validator/validator#682]
https://checker.html5.org/?doc=http%3A%2F%2Fmapsaregreat.com%2F shows

> Warning: Consider adding a lang attribute to the html start tag to declare the language of this document.

I tested the same file locally with jar file obtained as recommended in the readme, by using `npm install vnu-jar` and it reported some issues but not this error.

I used

`java -jar /install_path/vnu.jar --also-check-css --also-check-svg *.html

**Comment by sideshowbarker** [comment]
Thanks very much for catching this and taking time to report it. I’ve made a fix in the sources and pushed a new npm package, numbered 18.7.18, which you should be able to install with:

    npm install --save vnu-jar@next

**Comment by matkoniecz** [comment]
Thanks for a quick fix!
