### ISSUE TITLE
link failure at https://github.com/validator/validator/wiki/Service-%C2%BB-Common-params

### ISSUE THREAD

**Issue by matkoniecz** [validator/validator#683]
for some reason this wiki appears to be not accepting mediawiki syntax - so `[[XML|Output » XML]]` generates `[[XML` rather than a link and no info is displayed within the editor.

at least https://github.com/validator/validator/wiki/Service-%C2%BB-Common-params is affected

**Comment by cvrebert** [comment]
GitHub wikis use Markdown by default, not MediaWiki syntax.

**Comment by sideshowbarker** [comment]
> for some reason this wiki appears to be not accepting mediawiki syntax - so `[[XML|Output » XML]]` generates `[[XML` rather than a link and no info is displayed within the editor

It works as expected for me.

Per https://help.github.com/articles/adding-links-to-wikis/#using-a-wiki-markup-syntax-to-make-links:

> ### Using a wiki markup syntax to make links
> You can also create links with the wiki format of `[[Link Text|WikiLink]]`. In this case, `WikiLink` is the name of your wiki page, not the full URL.

> at least https://github.com/validator/validator/wiki/Service-%C2%BB-Common-params is affected

If you look at https://github.com/validator/validator/wiki/Service-%C2%BB-Common-params/_edit, you should find it already has this at the very end of the source:

```
See also: [[Web Service Interface|Service » HTTP interface]]
```

…and that’s producing a link to the right place as expected.

So I understand why it’s not working for you when you try it.

**Comment by matkoniecz** [comment]
> It works as expected for me.

What you see at https://github.com/validator/validator/wiki/Service-%C2%BB-Common-params ?

For me it is.
![selection_001](https://user-images.githubusercontent.com/899988/43361014-9335e20e-92c4-11e8-82f0-5581b29ead87.png)

**Comment by sideshowbarker** [comment]
> What you see at https://github.com/validator/validator/wiki/Service-%C2%BB-Common-params ?
>
> For me it is:
> ![selection_001](https://user-images.githubusercontent.com/899988/43361014-9335e20e-92c4-11e8-82f0-5581b29ead87.png)

Ah yeah, same here. I guess maybe that link markup doesn’t work within table markup

**Comment by sideshowbarker** [comment]
> Ah yeah, same here. I guess maybe that link markup doesn’t work within table markup

So it’s the `|` character that’s the problem in that case. I guess the markdown parser interprets it as a table-column separator

**Comment by sideshowbarker** [comment]
> ![selection_001](https://user-images.githubusercontent.com/899988/43361014-9335e20e-92c4-11e8-82f0-5581b29ead87.png)

I fixed that problem by changing it to just use a bulleted list instead of a table
