### ISSUE TITLE
Latest release from Docker Hub reports 18.7.18 instead of 18.7.23

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#687]
The version installed via `docker run -p 8888:8888 --restart=always validator/validator:latest` shows version 18.7.18, but it should be 18.7.23 as the latest release, shouldn't it?

**Comment by jaimeiniesta** [comment]
Thanks! But it still says `18.7.18` - and I've already pruned my Docker environment, tried both in my mac and in Digital Ocean and it keeps getting the old release.

Also, I'm unable to shut down the server with Ctrl+C - any idea?

**Comment by jaimeiniesta** [comment]
Thanks! Now I see `18.7.23`.

I'm still unable to kill it with Ctrl+C though.

**Comment by jaimeiniesta** [comment]
It looks like to be able to stop the container with Ctrl+C some flags need to be included:

https://github.com/moby/moby/issues/2838#issuecomment-52135557

Running it with `docker run -it -p 8888:8888 --restart=always validator/validator:latest` lets me stop the container.

**Comment by sideshowbarker** [comment]
> I'm still unable to kill it with Ctrl+C though.

Try giving `docker run` the `-t` argument:

```
docker run -t -p 8888:8888 --restart=always validator/validator:latest
```

You might also want to add the `-i` option

**Comment by sideshowbarker** [comment]
> Hey there, I just installed the latest release, I hoped to see version `18.8.29` but in the footer I see `18.7.28` instead.

Should be fixed now. Sorry about that. There seems to be a chronic problem with Docker Hub not being able to reach particular gpg key servers when it’s running the build from the Dockerfile. So I guess I need to update it to make it try multiple key servers or something.

**Comment by jaimeiniesta** [comment]
Thanks! It works fine now.

**Comment by sideshowbarker** [comment]
> There seems to be a chronic problem with Docker Hub not being able to reach particular gpg key servers when it’s running the build from the Dockerfile. So I guess I need to update it to make it try multiple key servers or something.

I added that today in 6ddba7b and it seems to have helped. So hopefully going forward that’ll make things work better.
