### ISSUE TITLE
HTML5 VALIDATOR -- UNSUPPORTED_MIMETYPE -- ERROR 

### ISSUE THREAD

**Issue by laqniti** [validator/validator#689]
* I got this error when i try to upload my playable ad make it by GameMakerStudio 2 

**Zip file contents check**
expand_more
To see if your .ZIP contains an unsupported file type, try the following:

Open the .ZIP by double-clicking on it.
In the resulting folder, make sure that each file is one of the supported file types: .CSS, .JS, .HTML, .GIF, .PNG, .JPEG and .SVG. If you find one that is not supported, remove it.
To save your updated version, select all of the files in the folder, and click File > Compress items.
If your folder doesn't zip correctly, it might be because you compressed the folder. Make sure to select each item, not the entire folder.
More details:

**UNSUPPORTED_MIMETYPE**

Please some Help !!!

**Comment by sideshowbarker** [comment]
The message described in the question isn’t a message from the HTML checker (validator). Instead I guess it’s some message from GameMakerStudio 2 and you need to raise an issue or help/support ticket wherever it is such GameMakerStudio 2 issues/tickets can be raised.

**Comment by laqniti** [comment]
thank you !! i solved
