### ISSUE TITLE
'justify-content: space-evenly' is valid CSS

### ISSUE THREAD

**Issue by oliviertassinari** [validator/validator#690]
- The error :
![capture d ecran 2018-08-20 a 23 28 30](https://user-images.githubusercontent.com/3165635/44367684-c6c8c780-a4d0-11e8-89ec-fb62bc1e3f47.png)

- It's valid : https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. Unfortunately I don’t think I’m gonna be able to make time right now to update the `justify-content`-checking support in the CSS backend, so what I’ve done instead for the time being is, I’ve just hacked in a filter that causes all error messages about `justify-content` values to be filtered out (dropped/ignored/suppressed).

So I’ll keep this issue open until I can get around to actually fixing it properly.

**Comment by ylafon** [comment]
It was fixed in the CSS Validator, see  w3c/css-validator#204
