### ISSUE TITLE
Misidentified language

### ISSUE THREAD

**Issue by diegargon** [validator/validator#694]
Forget it i known why and ins't a validator problem
Page: https://XXX/ (sometimes down, errors, etc "developing/testing" )

why give me this warning?
beware the page detect your brownse language and change en/es

From line 1, column 16; to line 3, column 15
TYPE html>↩<html↩ lang="es"    > ↩    

For further guidance, consult Declaring the overall language of a page and Choosing language tags.

If the HTML checker has misidentified the language of this document, please file an issue report or send e-mail to report the problem.

**Comment by sideshowbarker** [comment]
I when the site has a problem the server sends an HTML error-message document stating the problem? e.g., a 404 page. And if so guess those error pages don’t have any `html lang` value
