### ISSUE TITLE
Validate Golang HTML templates

### ISSUE THREAD

**Issue by kaihendry** [validator/validator#696]
Given a Golang template, for example:
https://github.com/unee-t/inspectionreportgenerator/blob/master/templates/signoff.html

I get errors like:

```
Error: Bad value https://{{ domain }}/report/{{ .ID }} for attribute href on element a: Invalid host: Illegal character in domain: space is not allowed.

From line 285, column 12; to line 285, column 59

eference: <a href="https://{{ domain }}/report/{{ .ID }}">{{ .ID
```

It would be nice if the validator could ignore these space around these {{ }} substitution marks. Maybe this is an existing method of doing this? The use case is that I am trying to prevent colleagues from checking in bad HTML.

**Comment by cvrebert** [comment]
See #93

**Comment by kaihendry** [comment]
Hmm, maybe it's a better approach if I execute the template and then post it then.
