### ISSUE TITLE
Python 3's Expat Validator Finds Markup Errors That Validator.nu Does Not

### ISSUE THREAD

**Issue by CyberneticEntomologist** [validator/validator#697]
A very simple Python script that creates a SAX parser then attempts to pass a file that Validator.nu reports is valid, will throw a xml.parsers.expat.ExpatError.  

These are real markup errors such as missing close tags as well as bad entities that are the result of not replacing "&" with "&amp;" in URL Query Parameters.

I am unable to catch the ExpatError but was able to catch the resulting xml.sax._exceptions.SAXParseException.  This enabled me to write a simple python script that parsed over 700 files, finding about 15 that were invalid.

Attached is a very simple script that demonstrates the parsing of two mostly identical files, one my original invalid file, the other an edited file that Python and Expat are happy with.  Also attached is a tarball of my complete website, along with the script that finds those 15 or so invalid files.

Don't Let This Get You Down: I regard your validators as Heaven-Sent Miracles. -- Mike

[Python_Expat_Catches_Errors_W3C_HTML5_Validator_Does_Not_2018-09-20.tar.gz](https://github.com/validator/validator/files/2407068/Python_Expat_Catches_Errors_W3C_HTML5_Validator_Does_Not_2018-09-20.tar.gz)

[Soggy_Jobs_Plus_Python_Expat_SAX.tar.gz](https://github.com/validator/validator/files/2407098/Soggy_Jobs_Plus_Python_Expat_SAX.tar.gz)

Python 3.6.6 from MacPorts: https://www.macports.org/
macOS 10.12.6
Mid 2015 MacBook Pro
Model Identifier MacBookPro11,5

**Comment by nschonni** [comment]
HTML5 allows unclosed tags and has rules around those in the spec (think automatic semicolon insertion in JavaScript if that helps). Think you might be able set the type to XHTML to see similar results.

**Comment by sideshowbarker** [comment]
Closing per explanation given in https://github.com/validator/validator/issues/697#issuecomment-423787713. Feel free to comment further here if you have any follow-up questions
