### ISSUE TITLE
Allow `loading` attribute for `<img>`

### ISSUE THREAD

**Issue by Malvoz** [validator/validator#699]
Allow `loading` attribute for `<img>` per https://github.com/whatwg/html/pull/3752, when ready.

**Comment by sideshowbarker** [comment]
Actually, stepping back even further: What should happen first for both these cases is that the editors of those specs creates patches that integrate the attribute definitions directly into the HTML spec, and submit PRs at https://github.com/whatwg/html with the patches

**Comment by DamonHD** [comment]
FYI:

    https://twitter.com/addyosmani/status/1114777583302799360

Native <img> lazy-loading is coming to the web! (link: https://bit.ly/loading-attribute) bit.ly/loading-attrib… <img loading=lazy> defers offscreen images until the user scrolls near them. Shipping in Chrome ~75 (link: https://bit.ly/loading-i2s)

    http://bit.ly/loading-i2s

**Comment by DamonHD** [comment]
https://tiny.pictures/guide/native-lazy-loading

"Beginning with version 75 (available as preview version now, beta in May, stable on 04th June 2019), Chromium and Google's Chrome browser will be shipped with a native lazy-loading mechanism enabled by default."

**Comment by nschonni** [comment]
I don't think Chromium Edge will count as a second browser, same as Opera doesn't count as a second implementation when they did the same years ago

**Comment by DamonHD** [comment]
OK!

But I'm itching to get the loading=lazy tags on all my below-the-fold images regardless.  For a number of my longer pages weight will be significantly loaded for some users, I think.

Rgds

Damon

**Comment by DamonHD** [comment]
If I wanted to jump the shark here, I guess that I could hack the relevant lines into:
     validator/schema/html5/embed.rnc 
and learn how to build myself the vnu.jar.  I doubt I have the time for that as soon as I'd like to try 'loading=lazy'.  Is there some "please don't look at the attributes in tag XXX too closely" flag that I can use in the meantime?

Rgds

Damon

**Comment by DamonHD** [comment]
While complaining to various people at Google how it had stopped working, I pulled the very latest mainline Chrome and it does now seem to have a full working implementation as of 76.0.3809.100.

See test page (load over slow-ish network):  http://www.earth.org.uk/img/WW-PV-roof/EVAnalysis201210/

And BTW, it works very nicely on somewhat extreme case.

Rgds

Damon

**Comment by tomayac** [comment]
The `loading` attribute is now fully supported in Chrome, Opera, and the upcoming Chromium-based version of Edge ([up-to-date info](https://caniuse.com/#feat=loading-lazy-attr)). The validator should probably no longer disallow it.

**Comment by sideshowbarker** [comment]
The `loading` attribute is still not actually in the HTML spec, until https://github.com/whatwg/html/pull/3752 lands.

**Comment by Malvoz** [comment]
I read somewhere (can't remember where specifically) that there wasn't much benefit in implementing `importance` atm. And It was dumb of me to create one issue for two separate features. Removed mentions of `importance` in this issue.

**Comment by XhmikosR** [comment]
@sideshowbarker it seems this has landed as you probably already know, waiting for a new version with this implemented :)

**Comment by bazzadp** [comment]
+1

> In general as far as allowing new attributes, it seems better to wait until at least two different browser engines support them. At this point, `importance` is only supported in Blink, right? And `lazyload` is only supported in Edge?

> Also the spec PR now only concludes <img> - loading for <iframe> and other elements will be defined separately, later.

At the moment [`loading=lazy` is supporting in Chromium](https://web.dev/native-lazy-loading/) (Chrome, new Edge, Opera...etc.) for `<img>` and `<iframe>` elements.

It's been [added to Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1542784) and should be in the next release. Not sure if just for `<img>` elements or also `<iframe>` elements. That bug suggests just `<img>`

And [Webkit/Safari are also working on it](https://bugs.webkit.org/show_bug.cgi?id=200764) too. Again not sure if just for `<img>` elements or also `<iframe>` elements.

Can I Use link (not yet updated with Firefox and Safari): https://caniuse.com/#feat=loading-lazy-attr

**Comment by DamonHD** [comment]
Yes, as FF and Chrome are published independent implementations, albeit only one on by default in the mainline product so far, is it now time to validate the new attribute so that some of us can be ready and waiting for FF and Safari (and supporting Chrome immediately)?

Rgds

Damon

**Comment by sideshowbarker** [comment]
Fixed in the sources and pushed to https://validator.w3.org/nu/

**Comment by DamonHD** [comment]
Thanks!

Damon

**Comment by bazzadp** [comment]
Excellent! Thanks for that.

BTW noticed a slight typo in the change log:

```
Allow `loaing` attribute for the `img` element (lazy loading)
```
should be:
```
Allow `loading` attribute for the `img` element (lazy loading)
```

**Comment by sideshowbarker** [comment]
> BTW noticed a slight typo in the change log:

Thanks for catching that — fixed now
