### ISSUE TITLE
Validation Problem

### ISSUE THREAD

**Issue by tawfiqct** [validator/validator#717]
The validator said that this code is correct !
![sans titre](https://user-images.githubusercontent.com/23529983/46659294-f7fe7380-cbb4-11e8-9d61-8c91dd7187c8.png)

No end tag for `<p>`

**Comment by sideshowbarker** [comment]
Closing this since as noted in https://github.com/validator/validator/issues/717#issuecomment-428190021 the HTML spec allows `</p>` end tags to be omitted
