### ISSUE TITLE
validator.w3.org defaults to HTML 4.01 when DOCTYPE missing

### ISSUE THREAD

**Issue by dd8** [validator/validator#719]
Not really a VNU bug, but related

If someone is validating HTML 5 code via http://validator.w3.org/ (without the /nu) and miss out the DOCTYPE it defaults to validating HTML 4.01 Transitional and they get a bunch of HTML 4.01 messages. 

In the worst case, if the code is fully valid HTML 5 apart from the missing DOCTYPE, they get lots of irrelevant and/or misleading messages (e.g. STYLE and SCRIPT elements require TYPE attributes, ARIA-LABEL not allowed here etc)

If instead a page with a missing DOCTYPE was routed to the VNU backend they'd get a single message:
`Start tag seen without seeing a doctype first. Expected <!DOCTYPE html>`

Given all the previous versions of HTML are marked superseded defaulting to HTML 5 is probably more sensible.

**Comment by sideshowbarker** [comment]
OK, I have already pushed a temporary change for this to the production markup validator for testing. Please let me know if it’s not working as expected. https://github.com/w3c/markup-validator/pull/37 has the permanent fix.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/719#issuecomment-435549276
