### ISSUE TITLE
Content-Security-Policy HTTP header: Bad content security policy: Unrecognised directive-name: "script-src-attr". Unrecognised directive-name: "script-src-elem". Unrecognised directive-name: "style-src-attr". Unrecognised directive-name: "style-src-elem".

### ISSUE THREAD

**Issue by BillGoldstein** [validator/validator#721]
New CSP directives to support

**Comment by sideshowbarker** [comment]
For CSP checking the checker relies on third-party library, and that library doesn’t yet support those new directives. See https://github.com/shapesecurity/salvation/issues/207

So when they add support upstream and release it, I’ll pull in that release here

**Comment by Malvoz** [comment]
Friendly ping, these were resolved upstream in https://github.com/shapesecurity/salvation/pull/216.

**Comment by sideshowbarker** [comment]
Thanks for the bump — will try to get our Salvation version updated very soon

**Comment by sideshowbarker** [comment]
@Malvoz So I see now that for the HTML checker we’re already using the latest Salvation release — v2.7.1. And that should support `style-src-elem` as far I know. But if you have a test document that shows we’re not yet supporting something that we should be, please post it here and I can investigate.

**Comment by Malvoz** [comment]
Thanks @sideshowbarker, I can confirm that all the directives are being recognized in the online validator now.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/721#issuecomment-590325048

**Comment by ethzero** [comment]
Look like this issue has crept back in:
> Error: Content-Security-Policy HTTP header: Bad content security policy: Unrecognised directive-name: "style-src-elem"

**Comment by Malvoz** [comment]
@ethzero are you sure it's not a syntax error? What does https://csp-evaluator.withgoogle.com/ return?

**Comment by sideshowbarker** [comment]
> @ethzero are you sure it's not a syntax error? What does [csp-evaluator.withgoogle.com](https://csp-evaluator.withgoogle.com/) return?

I wonder the same thing.

Regardless, to reproduce this, we would need a document to test with that causes the checker to emit that error message. Otherwise, without that, it’s not reproducible and thus there’s no way to troubleshoot it.

**Comment by EverybodyGetsHurt** [comment]
> Regardless, to reproduce this, we would need a document to test with that causes the checker to emit that error message. Otherwise, without that, it’s not reproducible and thus there’s no way to troubleshoot it.

I can arrange that for you guys!

I ran into the need for script-src-elem when trying to achieve a CSP setup with backwards compatability from CSP3->CSP2->CSP1(i removed 'unsafe-inline' 


I've created 2 server configurations for you, that are identical configurations, but 1 with scrpt-src-elem, 1 without.

- Use the home or about pages to test only, other pages are not for this demo.
- It are separate servers, where I split up one of my multi-domain names for this purpose.



INCL SCRIPT-SRC-ELEM: https://benemortasia.com
https://cspvalidator.org/#url=https://benemortasia.com/
https://csp-evaluator.withgoogle.com/?csp=https://benemortasia.com
https://www.hardenize.com/report/benemortasia.com/1684886289#www_csp
https://securityheaders.com/?q=https%3A%2F%2Fbenemortasia.com&followRedirects=on
https://observatory.mozilla.org/analyze/benemortasia.com
https://www.ssllabs.com/ssltest/analyze.html?d=benemortasia.com

![image](https://github.com/validator/validator/assets/59669136/f54cb735-f885-43fb-972b-6a8032b8ee29)



EXCL SCRIPT-SRC-ELEM: https://dontvisit.me
https://cspvalidator.org/#url=https://dontvisit.me/
https://csp-evaluator.withgoogle.com/?csp=https://dontvisit.me
https://www.hardenize.com/report/dontvisit.me/1684886292#www_csp
https://securityheaders.com/?q=https%3A%2F%2Fdontvisit.me&followRedirects=on
https://observatory.mozilla.org/analyze/dontvisit.me
https://www.ssllabs.com/ssltest/analyze.html?d=dontvisit.me

![image](https://github.com/validator/validator/assets/59669136/23282d38-50b6-4f0d-81df-e371b3ddd65d)
