### ISSUE TITLE
Java Documentation for integrating validator into applications?

### ISSUE THREAD

**Issue by sivadatta-igt** [validator/validator#737]
I've looked for Java documentation for integrating the Validator into a standalone Java application but could not find any.
I went through the WIKI page but couldn't understand how to implement it.
Could you please provide documentation to implement the validator in a java project instead of command line.
Thank you.

**Comment by sideshowbarker** [comment]
There’s no documentation on that and I don’t have plans any time soon to write up any. But you can figure it out by looking at the code here:

* https://github.com/validator/validator/blob/master/src/nu/validator/client/EmbeddedValidator.java
* https://github.com/validator/validator/blob/master/src/nu/validator/client/SimpleCommandLineValidator.java

The API is provided by this class:

* https://github.com/validator/validator/blob/master/src/nu/validator/validation/SimpleDocumentValidator.java
