### ISSUE TITLE
Can't validate SVG by File Upload on validator.nu

### ISSUE THREAD

**Issue by kevinoid** [validator/validator#746]
If I visit https://validator.nu, enter https://www.w3.org/Graphics/SVG/svglogo.svg in the Address field and press Validate, I get "The document validates according to the specified schema(s)." as expected.

If I switch "Address" to "File Upload" and select a saved copy of https://www.w3.org/Graphics/SVG/svglogo.svg and either leave Parser as "Automatically from Content-Type" or set to "HTML" then press Validate, I get multiple errors from the HTML parser (such as "Expected <!DOCTYPE html>.").  Alternatively, if I set Parser to "XML; don’t load external entities" or "XML; load external entities" I get the error "IO Error: Non-XML Content-Type: text/html."  (Even though the file is uploaded with `Content-Type: image/svg+xml`.)

This can be reproduced using `curl`, assuming `svglogo.svg` is in the current directory:

```sh
curl -q -LsS --compressed -F out=gnu -F parser=xml -F doc=@svglogo.svg\;type=image/svg+xml\;filename=svglogo.svg https://validator.nu
```

Thanks,
Kevin

**Comment by sideshowbarker** [comment]
https://validator.nu isn’t guaranteed to be up-to-date with the latest changes to the sources.

Can you reproduce the problem using https://validator.w3.org/nu/ or does that work as expected?

**Comment by kevinoid** [comment]
https://validator.w3.org/nu/ (and building from the `master` branch) work as expected.  Thanks!

**Comment by sideshowbarker** [comment]
> https://validator.w3.org/nu/ (and building from the `master` branch) work as expected. Thanks!

Cheers
