### ISSUE TITLE
certificate verify error with comodo ssl

### ISSUE THREAD

**Issue by hunboy** [validator/validator#747]
Follow this link:
https://validator.w3.org/check?uri=www.utasirobert.com

it says: 500 Can't connect to www.utasirobert.com:443 (certificate verify failed)

I use comodo ssl
My cert file is valid everywhere for more 2 years. What should be the reason?
Other virtualhosts work o.k. on my server.

I can't solve this issue in my side, and it worked before with this ssl cert.

**Comment by nschonni** [comment]
Not sure it's related, but long lived cert's aren't allowed anymore https://www.globalsign.com/en/blog/ssl-certificate-validity-capped-at-maximum-two-years/

**Comment by hunboy** [comment]
idk, but my cert is only 1 year old (less) so I'm inside the 2years period as well

**Comment by sideshowbarker** [comment]
Try using https://validator.w3.org/nu/ instead:

https://validator.w3.org/nu/?doc=https://www.utasirobert.com/

This (https://github.com/validator/validator/) repo’s code is for the https://validator.w3.org/nu/ service.


https://validator.w3.org/ is a different service that runs running legacy Perl+SGML+DTD code from a different repo at https://github.com/w3c/markup-validator.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/747#issuecomment-457763655. But if you have further questions, feel free to post comments here

**Comment by gdsotirov** [comment]
I have the same problem. However, is it possible to use the service at https://validator.w3.org/nu/ with Referer header? It was possible with the old service (i.e. with https://validator.w3.org/check?uri=referer), but I'm not able to figure out the way for Nu.

**Comment by sideshowbarker** [comment]
> is it possible to use the service at https://validator.w3.org/nu/ with Referer header?

No, it’s not

**Comment by gdsotirov** [comment]
> No, it’s not

OK. Is there a plan to support it? It would be very nice to have for static pages.

**Comment by sideshowbarker** [comment]
> Is there a plan to support it? It would be very nice to have for static pages.

There’s no plan to support it. I don’t plan on implementing it myself at least. But if you raise a new issue here, I could label it as a “needs help” feature request and another contributor might decide to take in on and write up a patch for it.

**Comment by gdsotirov** [comment]
> But if you raise a new issue here, I could label it as a “needs help” feature request and another contributor might decide to take in on and write up a patch for it.

OK. I opened #762, so we track this properly. I could perhaps help myself with the implementation, but I'm totally unfamiliar with the project, so I'll start with reading [CONTRIBUTING.md](https://github.com/validator/validator/blob/master/CONTRIBUTING.md) :-)
