### ISSUE TITLE
can see documentGetElementByID as error

### ISSUE THREAD

**Issue by EsenExpoTech** [validator/validator#751]
Validator can not recognize documentGetElementByID as error but it is an error.
documentGetElementByID should be fixed to documentGetElementById

**Comment by nschonni** [comment]
That is a JavaScript issue, not an HTML markup issue. You might want to look at something like https://eslint.org/ to flag JavaScript issues

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/751#issuecomment-459128972
