### ISSUE TITLE
Warning about <body> and </head>

### ISSUE THREAD

**Issue by daehworra** [validator/validator#755]
Lol repost cuz it didnt use my html correctly and showed the page. Anyways, the validator says that my `</head>` and `<body>` tag are not functioning correctly.  My `</head>` tag is not paired with my opening tag, and there already is another body tag open, according to the validator. I don't see any issues with my document and neither does my teacher. I'm uploading my code as a file since when I paste it within these `` tags it just implements the code into the page for some reason.

[index.zip](https://github.com/validator/validator/files/2827212/index.zip)

**Comment by sideshowbarker** [comment]
Your `<div class="title_encasing">` start tag at line 10 is where your document body actually begins. So move the `</head>` end tag to the line before that one, and move the `<body class="main_content">` start tag to the line after that `</head>` end tag and before the `<div class="title_encasing">` tag.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/755#issuecomment-460193979. Feel free to comment more if you have further questions
