### ISSUE TITLE
Allow 'size' property for '@page'

### ISSUE THREAD

**Issue by dpordomingo** [validator/validator#756]
As defined by W3C [7.1.Page size: the size property](https://www.w3.org/TR/css-page-3/#page-size-prop):
>_A page size can be specified using one of the following media names. This is the equivalent of specifying size using length values. The definition of the the media names comes from Media Standardized Names..._

Allowed size names: https://www.w3.org/TR/css-page-3/#typedef-page-size-page-size

example, from _**bootstrap**_:
>_`Error`: `size`: Property `size` doesn't exist._
>_From line `9848`, column `11`; to line `9848`, column `12`_
_`void;↩  }↩  @page {↩    size: a3;↩  }↩`

at https://validator.w3.org/nu/?doc=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Ftwitter-bootstrap%2F4.2.1%2Fcss%2Fbootstrap.css

**Comment by sideshowbarker** [comment]
Moved to https://github.com/w3c/css-validator/issues/219. This change needs to be implemented in the CSS validator backend — and after it is, then it will be integrated into the HTML checker backend

**Comment by sideshowbarker** [comment]
Thanks for reporting this. Support for `size` for `@page` is now deployed to https://validator.w3.org/nu/
