### ISSUE TITLE
ES6 module warning is no longer accurate

### ISSUE THREAD

**Issue by PikeUK** [validator/validator#759]
When validating a page that includes an ES6 module (via type="module") the following warning is issued:

    Module scripts are not supported in most browsers yet.

According to the stats at [Can I use](https://caniuse.com/#feat=es6-module), ES6 modules are now supported by 80% (by usage) of browsers, perhaps the warning could be reworded or removed.

**Comment by sideshowbarker** [comment]
Agreed. Thanks for having raised this issue. I’ve fixed in the sources and pushed the fix to https://validator.w3.org/nu/
