### ISSUE TITLE
td[role=rowheader] raises an error when used as a child of a TR element

### ISSUE THREAD

**Issue by poorgeek** [validator/validator#760]
The following bit of code raises the error, 

> An element with role=rowheader must be contained in, or owned by, an element with role=row.

```
<table>
  <tr>
    <td role="rowheader">Name</td>
    <td>Bob</td>
  </tr>
</table>
```

While the merits of using `<td role="rowheader">` instead of a `TH` can be debated, it seems as if this should not be throwing this error as the `TR` has an implied role of row.

**Comment by sideshowbarker** [comment]
> While the merits of using `<td role="rowheader">` instead of a `TH` can be debated, it seems as if this should not be throwing this error as the `TR` has an implied role of row.

The requirement is that the ancestor must have an explicit `role=row`, not an implied role.

**Comment by jnurthen** [comment]
The note in the aria spec states
NOTE
An element with the appropriate implicit WAI-ARIA semantic fulfills this requirement.

This can be found at https://www.w3.org/TR/wai-aria-1.2/#scope

**Comment by sideshowbarker** [comment]
OK, I see

**Comment by sideshowbarker** [comment]
I committed a fix for this in https://github.com/validator/validator/commit/15e8584 and pushed it to https://validator.w3.org/nu/.

So the markup snippet in the issue description no longer triggers an error:

https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fhtml%3Bcharset%3Dutf-8%2C%253C%2521DOCTYPE%2520html%253E%250D%250A%253Chtml%2520lang%253D%2522%2522%253E%250D%250A%253Chead%253E%250D%250A%253Ctitle%253ETest%253C%252Ftitle%253E%250D%250A%253Ctable%253E%250D%250A%2520%2520%253Ctr%253E%250D%250A%2520%2520%2520%2520%253Ctd%2520role%253D%2522rowheader%2522%253EName%253C%252Ftd%253E%250D%250A%2520%2520%2520%2520%253Ctd%253EBob%253C%252Ftd%253E%250D%250A%2520%2520%253C%252Ftr%253E%250D%250A%253C%252Ftable%253E%250D%250A#textarea

Thanks for having taken time to report this issue.
