### ISSUE TITLE
Error: CSS: “word-break”: “break-word” is not a “word-break” value.

### ISSUE THREAD

**Issue by miniBB** [validator/validator#763]
Error: CSS: “word-break”: “break-word” is not a “word-break” value - I've recently started to experience this in my code (appeared only some time ago), the same repeated using online versions. 

But "break-word" is definitely a valid property, it has been validated some time ago perfectly. Check: https://www.w3schools.com/cssref/css3_pr_word-break.asp

Is this a bug in Validator or possibly on my end?

**Comment by nschonni** [comment]
Looks like `break-word` is not a standardized property right now https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

PS: w3schools isn't always a trustworthy reference, they just still have really high SEO. MDN is what the browser developers use to document support

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/763#issuecomment-464911544

**Comment by EndeavourAccuracy** [comment]
> Closing per [#763 (comment)](https://github.com/validator/validator/issues/763#issuecomment-464911544)

When @nschonni commented on February 18th it is "not a standardized property", the MDN web docs page [contained](https://web.archive.org/web/20190215010448/https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) a `/* non-standard */` comment and a warning icon, but the current page [no longer](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) includes this comment and icon. Comparing the browser compatibility tables, it looks like Edge dropped support while Firefox gained it.

**Comment by sideshowbarker** [comment]
> When @nschonni commented on February 18th it is "not a standardized property", the MDN web docs page [contained](https://web.archive.org/web/20190215010448/https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) a `/* non-standard */` comment and a warning icon, but the current page [no longer](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) includes this comment and icon.

I’ve updated that MDN article to indicate the CSS Text Level 3 spec now defines the `break-word` value as being deprecated:

https://drafts.csswg.org/css-text-3/#word-break-property
> For compatibility with legacy content, the word-break property also supports a deprecated break-word keyword. When specified, this has the same effect as word-break: normal and overflow-wrap: anywhere, regardless of the actual value of the overflow-wrap property. However, the break-word keyword is not appropriate for newly-written style sheets. Authors must not use it.
