### ISSUE TITLE
The type attribute is unnecessary for JavaScript resources.

### ISSUE THREAD

**Issue by envy3000** [validator/validator#770]
Well that is wrong if a website needs to be optimized for speed.
The information type='text/javascript' is used as in indicator bij apache if the module mod_deflate is active. And every modern website need that to be enabled.
 
https://httpd.apache.org/docs/2.4/mod/mod_deflate.html

**Comment by sideshowbarker** [comment]
On this the checker is just conforming to a requirement in the HTML spec:

https://html.spec.whatwg.org/multipage/scripting.html#attr-script-type
> Authors should omit the `type` attribute instead of redundantly setting it.

So if you think the spec should say otherwise, open an issue at https://github.com/w3c/html/issues
