### ISSUE TITLE
error html

### ISSUE THREAD

**Issue by HassanKohi** [validator/validator#781]
Error: Bad value images\logo.png for attribute src on element img: Backslash ("\") used as path segment delimiter.

From line 13, column 3; to line 13, column 29

"logo">↩		<img src="images\logo.png">↩</div

**Comment by speedyhoon** [comment]
Forward slashes `/` should be used instead `<img src="images/logo.png" alt="Logo">`

**Comment by sideshowbarker** [comment]
> Forward slashes `/` should be used as as path segment delimiters instead `<img src=images/logo.png alt=Logo>`
> Backslashes need to be encoded as `%5C` within a URL

Yup
