### ISSUE TITLE
Batch checking using https://html5.validator.nu/

### ISSUE THREAD

**Issue by MichaelDalrymple** [validator/validator#785]
Wondering if the possibility exists to have the https://html5.validator.nu/ scan a batch list of URLs/addresses rather than just 1 URL at a time. Is this something anyone is looking into or could look into?

**Comment by sideshowbarker** [comment]
It’s not possible and there are no plans to add a feature for it. But there are third-party site-crawling tools such as https://github.com/spk/validate-website that run on top of the HTML checker and allow you to do batch checking.
