### ISSUE TITLE
Contents of <code> ... </code>

### ISSUE THREAD

**Issue by jonasjacek** [validator/validator#795]
I am unsure if this is a bug or a feature. My personal understanding is, that contents of a code-element (`<code>...</code>`) or a block of code (`<pre><code>...</code></pre>`) should not be considered. 

The following example from one of my talks (https://www.jonas.me/talks/introduction-to-the-web-content-accessibility-guidelines/#/4/46 (~8 MB!!!)) throws errors.

**Excerpt:** 
`<pre>
  <code>
      <p>I like HyperText Markup Language (HTML).</p>
  </code>
</pre>`

Screenshot: https://imgur.com/0ABQ4Zy

Maybe it's a good idea to discuss this topic.

**Comment by XhmikosR** [comment]
You need to escape the brackets.

```html
<pre><code>&lt;p&gt;I like HyperText Markup Language (HTML).&lt;/p&gt;</code></pre>
```

**Comment by jonasjacek** [comment]
> You need to escape the brackets.
> 
> ```
> <pre><code>&lt;p&gt;I like HyperText Markup Language (HTML).&lt;/p&gt;</code></pre>
> ```

I know that this would solve the validation issue. However, I would like to find out, if this is actually required/if it is actually considered wrong. I was not able to find an official statement and most examples in the wild do make use of entities (I know, ...). 

The spec is silent about this (https://www.w3.org/TR/html/textlevel-semantics.html#example-8bacfdd1). 

I know older versions of HTML required this, but modern browsers seem to interpret correctly. That makes me wonder if this is still required.

**Comment by sideshowbarker** [comment]
The spec states that `code` elements must only contain phrasing content:

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element

The `p` element is not phrasing content:

https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2

Phrasing content is limited to:

> a, abbr, area (if it is a descendant of a element), audio, b, bdi, bdo, br, button, canvas, cite, code, data, datalist, del, dfn, em, embed, i, iframe, img, input, ins, kbd, label, lin], (if it is allowed in the body), map, mark, MathML math, meta (if the itemprop attribute is present), meter, noscript, object, output, picture, progress, q, ruby, s, samp, script, select, slot, small, span, strong, sub, sup, SVG svg, template, textarea, time, u, var, video, wbr, autonomous custom elements, text

**Comment by jonasjacek** [comment]
Michael, thanks for the clarification.

**Comment by jonasjacek** [comment]
Michael, thanks for the clarification.
