### ISSUE TITLE
Usage notes reference non working flags --force-svg and --force-css

### ISSUE THREAD

**Issue by speedyhoon** [validator/validator#807]
Should --force-css and --force-svg be updated to --css and --svg in the usage notes referenced on:

- https://github.com/validator/validator/blob/master/index.html on lines 259 and 277,
- https://github.com/validator/validator/blob/master/README.md on lines 104 and 119?

**Comment by sideshowbarker** [comment]
> force-css

Yes. Either that or I guess I should actually implement support for --force-css and --force-svg — if I had intended for them to have some different effect than just what `--css` and `--svg` already do.
