### ISSUE TITLE
Characters in the private use area

### ISSUE THREAD

**Issue by MozartSoftware** [validator/validator#815]
There's a warning against using characters in the Unicode private use area.

This occurs even when the font is explicitly specified as one which is specified in the CSS as embedded in the web site,   It therefore appears impossible to show that a certain font contains certain characters in this area, without getting a warning.

**Comment by sideshowbarker** [comment]
The warning can be suppressed using one of the checker’s filtering options.

The details are at https://github.com/validator/validator/wiki/Message-filtering

The **Message filtering** button in the Web UI can also be used to persistently filter out particular messages.
