### ISSUE TITLE
Custom Constraint Pattern Validator

### ISSUE THREAD

**Issue by deepakThedeveloper** [validator/validator#824]
I have created a @URL  constraint validation and provided regex. Above it I have annotated @Pattern. So, whenever in my bean I am entering value in field url, the url is getting validated

Currently i have a regex which is validating this url. "http://www.google.com".

My new requirement is it should validate only "www.google.com"
I can just change the regex and it will work. but the problem is there are 2 different scenarions
1.In one i need to validate               "http://www.google.com"
2.In second i need to valdiate this   "www.google.com"

So, i cannot change the regex. Can anyone please help how can I resolve this? If i need to use custom validator instead of hibernate validator, then how can i achieve this?

**Comment by sideshowbarker** [comment]
You seem to have filed this issue at the wrong repo…
