### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by ribeaud** [validator/validator#825]
Hi,
if the page I want to validate lies behind an authentication wall, how can I provide the credentials?
I would appreciate something like **curl**:
- `-u, --user USER[:PASSWORD]  Server user and password`

What do you think? I could help and implement this feature if you give me some hints.

Thanks and kind regards,

christian

**Comment by nschonni** [comment]
See #122

**Comment by ribeaud** [comment]
Hi @nschonni. Thanks for this link. As far as I understood this will work if the target URL supports basic authentication ONLY. This will NOT work if we only have form based authentication. To be able to do so the tool probably needs some mechanism to handle/set the cookie(s) behind the scenes. But then, this is maybe just too much asked for it. Have a nice day, christian.

**Comment by ribeaud** [comment]
You might close the issue. Or should I? Cheers, christian.

**Comment by sideshowbarker** [comment]
I don’t see how support could be added to the checker backend for form-based authentication.

The checker makes GET requests for the documents it checks — it doesn’t make POST requests.

So unless you were to provide credentials in the query string in the GET request (not secure of course unless you were doing it locally only or within your LAN), I don’t see how it would work.

I agree that it would be great to have a way to check the source/state of documents that require form-based authentication. So I’d love to have a way to enable it. It’s just that at this point I can’t personally think of how we could make it actually work.

**Comment by pgr1973** [comment]
The option to define a custom-header (that the v.nu then uses in it's GET-Request to the URL to check) would be nice.
That would also solve the BasicAuth problem, that lingers since several years in this project.
Trying at the moment to use v.nu for automated validations (CI/CD), but the persistent impossibility to use it against sites behind basic-auth, will seemingly lead to not using it at all.
