### ISSUE TITLE
Validator found error but there is no error

### ISSUE THREAD

**Issue by LaDanza** [validator/validator#827]
Hello! I checked page https://ostrov-s.ru and found that error:
No p element in scope but a p end tag seen.

I checked syntax manually but I can't find a mistake. Can it be a bug?

**Comment by cvrebert** [comment]
The relevant snippet of your code (re-indented for clarity) is:

```html
<p>
  <h2 class="banner__header banner__header--with-shadow banner__header--left">
    <span style="font-size: 18pt;">Все вопросы уточняйте по телефону:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span>
    <span style="color: #f16522;">8-927-511-70-09&nbsp;</span>
  </h2>
</p>
```

HTML doesn't permit nesting heading tags (such as `<h2>`) inside `<p>` tags.
[`<p>`'s content model](https://html.spec.whatwg.org/#the-p-element) (i.e. which tags you're allowed to use inside it) is [Phrasing content](https://html.spec.whatwg.org/#phrasing-content-2), which doesn't include `<h2>`.

The HTML parser implicitly closes the paragraph when it encounters the opening `<h2>` tag, thus causing the closing `</p>` tag to become extraneous and unpaired.

**Comment by LaDanza** [comment]
Ohm, that it is! Thanks a lot for your answer! But I can suggest to do that error message can be more informative.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/827#issuecomment-502255360
