### ISSUE TITLE
Misdetection of language (English instead of French)

### ISSUE THREAD

**Issue by fxcoudert** [validator/validator#829]
The language for this page https://www.coudert.name/concours_cnrs.html is detected as English when it is French:

<img width="776" alt="Capture d’écran 2019-06-18 à 10 51 02" src="https://user-images.githubusercontent.com/1980544/59667401-fc087980-91b6-11e9-8bf7-7471cc54ed8d.png">

See https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.coudert.name%2Fconcours_cnrs.html

**Comment by sideshowbarker** [comment]
Fixed — thanks for having taken time to report this
