### ISSUE TITLE
Deprecated media features

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#83]
https://drafts.csswg.org/mediaqueries/#mf-deprecated - should have warnings for these. Including min- max- variants.

**Comment by sideshowbarker** [comment]
Where does it mention anything about the min- max- variants?

**Comment by zcorpan** [comment]
https://drafts.csswg.org/mediaqueries/#mq-min-max

min- and max- is just syntax sugar. It's still the same media feature.
