### ISSUE TITLE
Add the enterkeyhint attribute

### ISSUE THREAD

**Issue by mtrootyy** [validator/validator#831]
The enterkeyhint attribute as global attribute is added to the spec of HTML Living Standard.

Ref: https://github.com/whatwg/html/commit/a5422d984d9b7b8a4e0ad7a0ad237b07f190cc93
Ref: https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute

**Comment by sideshowbarker** [comment]
Do you know if any browser engines other than Blink have support for `enterkeyhint` yet?

**Comment by mtrootyy** [comment]
I don't know well situation of browser engines supporting for `enterkeyhint`.

**Comment by sideshowbarker** [comment]
Current implementation status:

* Intent to Ship for Chrome: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/Hfe5xktjSV8/Re-SMF3wAwAJ
* open Mozilla feature bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1490661
* open Safari feature bug: https://bugs.webkit.org/show_bug.cgi?id=189546

**Comment by sideshowbarker** [comment]
* Shipped in Chrome 77 https://bugs.chromium.org/p/chromium/issues/detail?id=634330
* Landed in Safari source https://bugs.webkit.org/show_bug.cgi?id=189546
* Still open in Mozilla https://bugzilla.mozilla.org/show_bug.cgi?id=1490661

So, we now have two implementations, but I think it’s not actually shipped in any stable Safari release yet.
