### ISSUE TITLE
validator not detecting missing </li> tag

### ISSUE THREAD

**Issue by ven-u** [validator/validator#832]
Neither my Firefox plugin, vnu.jar, nor your online validation service detects the error in the code below.

See line containing "`<li><a href="../an/an9.html">The Nines</a>`”, which is missing an `</li>` end tag.

I found the error in Komodo Edit 11 which could not match up start/end tags over that section of the  `<li>..</li>` block (lines 38 through 52).

Komodo Edit 11 does get the start/end tag detection working again in the `<li>..</li>` blocks above and below the `<ul>` block containing the missing `</li>`

========================================================
```html
<div id="navbar">
<ul id="css3menu0" >
  <li class="topfirst" id="home"><a class="pressed" href="../index.html">Home</a></li>
  <li class="topmenu" id="dn"><a href="../dn/dn.html">Digha Nikaya</a></li>
  <li class="topmenu" id="mn"><a href="../mn/mn.html">Majjhima Nikaya</a></li>
  <li class="topmenu" id="sn"><a href="../sn/sn.html">↓ Samyutta Nikaya</a>
    <ul>
      <li><a href="../sn/sn01.html">Part 1 - The Book with Verses</a></li>
      <li><a href="../sn/sn02.html">Part 2 - The Book of Causation</a></li>
      <li><a href="../sn/sn03.html">Part 3 - The Book of the Aggregates</a></li>
      <li><a href="../sn/sn04.html">Part 4 - The Book of the Six Sense Bases</a></li>
      <li><a href="../sn/sn05.html">Part 5 - The Great Book</a></li>
    </ul>
  </li>
  <li class="topmenu" id="an"><a href="../an/an.html">↓ Anguttara Nikaya</a>
    <ul>
      <li><a href="../an/an1.html">The Ones</a></li>
      <li><a href="../an/an2.html">The Twos</a></li>
      <li><a href="../an/an3.html">The Threes</a></li>
      <li><a href="../an/an4.html">The Fours</a></li>
      <li><a href="../an/an5.html">The Fives</a></li>
      <li><a href="../an/an6.html">The Sixes</a></li>
      <li><a href="../an/an7.html">The Sevens</a></li>
      <li><a href="../an/an8.html">The Eights</a></li>
      <li><a href="../an/an9.html">The Nines</a>
      <li><a href="../an/an10.html">The Tens</a></li>
      <li><a href="../an/an11.html">The Elevens</a></li>
    </ul>
  </li>
  <li class="topmenu" id="kn"><a href="../kn/kn.html">↓ Khuddaka Nikaya</a>
    <ul>
      <li><a href="../kp/kp.html">The Khuddakapatha</a></li>
      <li><a href="../dhp/dhp.html">The Dhammapada</a></li>
      <li><a href="../snp/snp.html">Sutta Nipata</a></li>
      <li><a href="../ud/ud.html">Udana</a></li>
      <li><a href="../it/it.html">Itivuttaka</a></li>
      <li><a href="../tha/tha.html">The Theragatha</a></li>
      <li><a href="../thi/thi.html">The Therigatha</a></li>
    </ul>
  </li>
  <li class="toplast" id="vi"><a href="../vi/vi.html">↓ Vinaya Pitaka</a>
      <ul>
      <li><a href="../vi/kd.html">Khandhaka</a></li>
      <li><a href="../vi/bu-vb.html" title="Monk’s Rules">Bhikkhu Vibhanga</a></li>
      <li><a href="../vi/bu-pt.html">Bhikkhu Pātimokkha</a></li>
      <li><a href="../vi/bi-pt.html">Bhikkhunī Pātimokkha</a></li>
      <li><a href="../vi/bi-vb.html" >Bhikkhuni Vibhanga</a></li>
      <li><a href="../bmc/bmc.html">Buddhist Monastic Code I</a></li>
      <li><a href="../bmc/bmc2.html">Buddhist Monastic Code 2</a></li>
      </ul>
  </li>
</ul>
</div> <!--navbar-->
```

**Comment by sideshowbarker** [comment]
> Neither my Firefox plugin, vnu.jar, nor your online validation service detects the error in the code below.

That’s because there’s actually no error there

> See line containing "`<li><a href="../an/an9.html">The Nines</a>`”, which is missing an `</li>` end tag.

The missing `</li>`  isn’t an error in HTML documents. It’s only an error in a document that’s being served with an XML media type and getting parsed by an XML parser.

The HTML spec says the `</li>` end tag can be omitted.

See https://html.spec.whatwg.org/multipage/#the-li-element:concept-element-tag-omission:

> An `li` element's end tag can be omitted if the `li` element is immediately followed by another `li` element or if there is no more content in the parent element.

For complete details about all elements for which end tags or start tags are allowed to be omitted, see the https://html.spec.whatwg.org/multipage/#syntax-tag-omission section of the HTML spec.
