### ISSUE TITLE
Namespace "http://n.validator.nu/messages/" is inaccessible

### ISSUE THREAD

**Issue by rujiel** [validator/validator#836]
The most recent version of nu validator returns xml with this namespace:

http://n.validator.nu/messages/

But this domain doesn't work. Removing the "n" subdomain from that URL results in a 404 on a valid domain. I'm not sure what the proper namespace is for this? This confuses the XSL processor I'm using to parse this XML, please fix. I'm manually stripping out the namespace in code for now.

**Comment by cvrebert** [comment]
Quoting from https://en.wikipedia.org/wiki/XML_namespace#Namespace_names , emphasis added:

> The use of URIs taking the form of URLs in the http scheme [...] is common, despite the absence of any formal relationship with the HTTP protocol. The Namespaces specification does not say what should happen if such a URL is dereferenced (that is, if software attempts to retrieve a document from this location). [...] In general, however, **users should assume that the namespace URI is simply a name, *not* the address of a document on the Web.**

So I'd say your XSL processor is busted. Perhaps it has some setting to disable network fetches that you could set?

**Comment by sideshowbarker** [comment]
> So I'd say your XSL processor is busted.

Yeah, if it’s trying to resolve namespace URIs and fetch something from them and it fails if gets a 404, then that tool is definitely broken.



> The most recent version of nu validator returns xml with this namespace:
> 
> http://n.validator.nu/messages/
> 
> But this domain doesn't work.

Yeah, to be clear, it’s expected that there’s nothing there. There’s no actual `n.validator.nu` host anywhere on the Web — there doesn’t need to be, for the reasons explained in https://en.wikipedia.org/wiki/XML_namespace#Namespace_names and cited in the previous comment.

`http://n.validator.nu/messages/` is simply a name — a string used as an identifier.

**Comment by rujiel** [comment]
OK, my bad. Closing this

**Comment by rujiel** [comment]
One more thought on this. The issue apparently isn't that my parser is attempting to connect to the URL, but rather that the presence of a namespace means that any element matching I do through, say, XSL must include the prefix corresponding to this namespace's prefix if the namespace is present.. so, probably a naive question but is it really necessary that the returned XML uses a namespace at all? Since the namespace doesn't actually point to anything I'm not clear what value it provides? I haven't seen any documentation indicating that a namespace is required. Thanks

**Comment by sideshowbarker** [comment]
> One more thought on this. The issue apparently isn't that my parser is attempting to connect to the URL, but rather that the presence of a namespace means that any element matching I do through, say, XSL must include the prefix corresponding to this namespace if the namespace is present..

Yeah, that’s the namespace tax. That’s how XML works, and that’s how you need to deal with it in XSL.

Dealing with namespaces in XML is a well-known massive PITA. It’s easily the worst misfeature of XML. If you don’t like dealing with it, you probably don’t want to be using XML.

The checker provides JSON-formatted output. I’d recommend using that and ignoring the XML option.

> so, probably a naive question but is it really necessary that the returned XML uses a namespace at all? Since the namespace doesn't actually point to anything I'm not clear what value it provides? I haven't seen any documentation indicating that a namespace is required

Those are all good questions and thoughts but there’s nothing to discuss about it that’s specific to the HTML checker. So, with respect, this isn’t the place to spend time on any of it.
