### ISSUE TITLE
Language declared as lang="en" but validator suggests lang="ms"

### ISSUE THREAD

**Issue by mig281** [validator/validator#838]
> Warning: This document appears to be written in Malay but the html start tag has lang="en,ru,ja". Consider using lang="ms" (or variant) instead.
> 
> From line 1, column 16; to line 2, column 22
> 
> TYPE html>↩<html lang="en,ru,ja">↩<head
I don't even know what Malay looks like!

**Comment by mig281** [comment]
OK, I see now that you can't declare multiple languages (that seems super stupid, BTW), but, even when I change it to `lang="en"`, I still get the same warning:

> Warning: This document appears to be written in Malay but the html start tag has lang="en". Consider using lang="ms" (or variant) instead.
> 
> From line 1, column 16; to line 2, column 16
> 
> TYPE html>↩<html lang="en">↩<head

**Comment by sideshowbarker** [comment]
Thanks for the report. Can provide the actual URL for the document? Either that or the document itself. To fix the problem, I’d first need to be able to reproduce it.

**Comment by mig281** [comment]
@sideshowbarker Oh, of course. Here it is: https://www.mig81.com/index.php?page=news
Please note that I am currently fixing old HTML for the validator, so a number of other things that are wrong are still on the page.

**Comment by mig281** [comment]
Ack. I don't understand what's going on. The warning no longer appears??

**Comment by sideshowbarker** [comment]
> Ack. I don't understand what's going on. The warning no longer appears??

The behavior the language-checker backend is non-deterministic. If you reload a number of times, the warning will most likely reappear.

**Comment by mig281** [comment]
@sideshowbarker Hm. That's a bit strange, but OK. Either way, I can't reproduce this. Sorry. :frowning_face:

**Comment by sideshowbarker** [comment]
> Hm. That's a bit strange, but OK. Either way, I can't reproduce this. Sorry. ☹️

yeah, I’ve been trying myself but can’t reproduce it either. Anyway, I will still investigate it (which I can do without necessarily needing to reproduce it — by looking at logging on the backend to see the raw calculations the language checker is doing)

**Comment by mig281** [comment]
@sideshowbarker Thanks. I now see the issue on this page: https://www.mig81.com/index.php?page=archives_poetry
I just don't understand where it gets Malay.

**Comment by sideshowbarker** [comment]
> I now see the issue on this page: https://www.mig81.com/index.php?page=archives_poetry

OK yeah I can reproduce it there

> I just don't understand where it gets Malay.

The language checker uses sets of N-gram data to match against — where _N_ is two or more, and an N-gram is a sequence of two or more characters. The data indicates how frequently particular letter sequence occur in the language. So for example, “`the`” would be letter sequence that occurs with high frequency in English-language text.  So the checker compares the letter sequences in the source text to all the N-gram frequency data it has, and tries to find the language that is the best match.

So it’s finding that your page there has letter sequences that matches the data it has for Malay more closely than it matches the data it has for any other language.

…which is weird and most likely indicates the N-gram data it’s using for Malay is not good.

But I can’t really change that data easily, so I’ll instead see if I can work around it somehow in the checker code.

**Comment by mig281** [comment]
@sideshowbarker I now understand the problem. This is an interesting one. The use of N-gram data is a clever one, but why not go straight for the (Google translation API)[https://cloud.google.com/translate/docs/?csw=1]? There are a bunch of interesting solutions out there, such as (this one)[https://stackoverflow.com/questions/1192768/how-to-detect-the-language-of-a-string/1192802#1192802].

**Comment by mig281** [comment]
@sideshowbarker Any news on this? :smiley:

**Comment by sideshowbarker** [comment]
> @sideshowbarker Any news on this? 😃

Sorry, I haven’t gotten back to it yet — I’ll make time today

**Comment by sideshowbarker** [comment]
OK, I “fixed” this —

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.mig81.com%2Findex.php%3Fpage%3Dnews

I think that in the document, the specific parts that were tripping up the language detector were all the dates. I don’t know why, but it seems like the Malay N-gram profile must somehow be heavily weighted for character sequences that look like dates. Which is weird, but then it’s not the first time I’ve run across a quirk like this with the language-detector backend.

The way I “fixed” it was to make backend hide any contents of `span` elements from the language detector — which is a bit of a radical step, but I rationalize it by reckoning that any content a document has marked up with `span` are often likely to be different in some way than the predominant text of the document, so it makes some sense to not includes the `span` contents in language detection.

**Comment by sideshowbarker** [comment]
> why not go straight for the [Google translation API ](https://cloud.google.com/translate/docs/?csw=1)? There are a bunch of interesting solutions out there, such as [this one](https://stackoverflow.com/questions/1192768/how-to-detect-the-language-of-a-string/1192802#1192802).

I can’t make the HTML checker backend depend on a third-party network API for any checks.

The Web-based https://validator.w3.org/nu/ service is just one instance of the checker. The same backend is used for providing a command-line client, for users to batch-check documents from the command line. So, one of the core requirements of the checker backend is that it must be possible for somebody to use it even when offline.

**Comment by mig281** [comment]
> The way I “fixed” it was to make backend hide any contents of `span` elements from the language detector — which is a bit of a radical step, but I rationalize it by reckoning that any content a document has marked up with `span` are often likely to be different in some way than the predominant text of the document, so it makes some sense to not includes the `span` contents in language detection.
Well, a fix by any other name would smell as sweet, no? :smile: 
Thank you for this! :+1:

**Comment by mig281** [comment]
> I can’t make the HTML checker backend depend on a third-party network API for any checks.

> So, one of the core requirements of the checker backend is that it must be possible for somebody to use it even when offline.

Makes sense. Thank you again for taking the time to explain, and thanks again for all the hard work you've done on the validator!
