### ISSUE TITLE
The 'name' attribute is obsolete, but replacing it with 'id' (as the validator suggests) causes scripts to fail

### ISSUE THREAD

**Issue by mig281** [validator/validator#839]
Here's an example of the problem:
```
<div class="sidebar-content">
<a href="mailto:poet-AT-mig81-DOT-com"
onmouseover="changeImages('contact_over', '/images/index/contact_over.jpg'); return true;"
onmouseout="changeImages('contact_over', '/images/index/contact.jpg'); return true;"
onmousedown="changeImages('contact_over', '/images/index/contact_over.jpg'); return true;"
onmouseup="changeImages('contact_over', '/images/index/contact_over.jpg'); return true;">
<img name="contact_over" src="/images/index/contact.jpg" alt="poet-AT-mig81-DOT-com" align="top" width="96" height="16"></a> | 
<a class="sidebar-content" href="https://www.mig81.com/index-poetry.xml">RSS 2.0 Feed</a>
</div>
```
The issue is with `name="contact_over"`: if I change it to `id`, the script stops working...

**Comment by sideshowbarker** [comment]
> The issue is with `name="contact_over"`

Yeah, per the HTML spec, `name` is no longer allowed for `img`

https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element

>  if I change it to `id`, the script stops working...

If you’re able to change the script, then the fix would be to make the script look for the `id` attribute value of the `img` (rather then `name`)

**Comment by mig281** [comment]
@sideshowbarker No, I understand this, but (unless I'm missing something here), `onmouseover` and so forth specifically need `name`, no?

**Comment by mig281** [comment]
OK. I'm an idiot. Of course I had a script. It's just I'd written it nearly 20 years ago and forgot how it works. Brilliant.
```
<script>
function newImage(arg) {
if (document.images) {
rslt = new Image();
rslt.src = arg;
return rslt;
}
}
function changeImages() {
if (document.images && (preloadFlag == true)) {
for (var i=0; i<changeImages.arguments.length; i+=2) {
document[changeImages.arguments[i]].src = changeImages.arguments[i+1];
}
}
}
var preloadFlag = false;
function preloadImages() {
if (document.images) {
archives_over = newImage("/images/index/menu/archives_over.jpg");
bio_over = newImage("/images/index/menu/bio_over.jpg");
poetry_over = newImage("/images/index/menu/poetry_over.jpg");
preloadFlag = true;
}
}
</script>
```

**Comment by mig281** [comment]
I asked for some help on StackOverflow and this is how the issue is solved: https://stackoverflow.com/questions/56961811/not-sure-how-to-adapt-ancient-image-switcher-code-from-using-name-foo-to-id-f/56961836#56961836

**Comment by sideshowbarker** [comment]
> I asked for some help on StackOverflow and this is how the issue is solved: https://stackoverflow.com/questions/56961811/not-sure-how-to-adapt-ancient-image-switcher-code-from-using-name-foo-to-id-f/56961836#56961836

Rock and roll — upvoted

**Comment by mig281** [comment]
@sideshowbarker Hey, did you are syntax highlighting to my code on StackExchange? How did you do that?
