### ISSUE TITLE
False positive report in file-upload input state

### ISSUE THREAD

**Issue by AndySky21** [validator/validator#84]
When checking <input type="file"> with accept values in the form of file extension, Validator returns an error as if it expected only MIME types.
It should not expect a '/' when the string begins with a dot.

**Comment by sideshowbarker** [comment]
This is the same problem reported at https://bugzilla.validator.nu/show_bug.cgi?id=1006 right?

**Comment by AndySky21** [comment]
Er, yes. Same problem, different project, I forgot about that report... Sorry. 
Label it as known issue and pretend I never was here, please...

**Comment by sideshowbarker** [comment]
Actually it's better to have it reported here too.

**Comment by AndySky21** [comment]
I'd prefer being able to contribute, rather than just report issue (minor issues, though).

**Comment by sideshowbarker** [comment]
Fix pushed to https://validator.w3.org/nu/
