### ISSUE TITLE
"Attribute href not allowed on element a at this point."

### ISSUE THREAD

**Issue by ToBeFree** [validator/validator#840]
Is "href" ever "not allowed" on "a"?

https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.freiwuppertal.de%2F

**Comment by nschonni** [comment]
I would guess it would be the `role=contentinto"` that might be interferring. You're declaing it as a landmark with that, and I don't think a landmark can have an href, but someone else would need to confirm. The error message is a little confusing, even if i'm right

**Comment by ToBeFree** [comment]
Good point, removing `role="contentinfo"` removes the error message, thanks.

Also, per https://www.w3.org/TR/wai-aria-practices/examples/landmarks/,
> banner, main, complementary and contentinfo landmarks should be top level landmarks. 

However, that alone does not seem to be the problem; moving the anchor outside of `<main>` still causes the error message to appear unchanged, as does changing the order of the attributes.

My solution will be moving the anchor to a separate `<footer>` after the issue has been closed.

**Comment by ToBeFree** [comment]
I have changed the website this report relied upon; the archived version can be found at http://web.archive.org/web/20190711002309/https://www.freiwuppertal.de/

**Comment by sideshowbarker** [comment]
Closing this per discussion in previous comments. But if there’s anything more here that’s in need of resolution, we can reopen this
