### ISSUE TITLE
size attribute should not be allowed on input type "number" or "range"

### ISSUE THREAD

**Issue by scottaohara** [validator/validator#844]
Testing the following in the [HTML Validator](https://validator.w3.org/nu/#textarea):
```html
<input type="range" size="4">
<input type="number" size="4">
```
The validator returns no errors.  But per [Greg Whitworth's note](https://github.com/ThePacielloGroup/AT-browser-tests/pull/67) about the `size` attributes on these elements in the [HTML spec](https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)) they are noted as not allowed.

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it
