### ISSUE TITLE
Useless input element in forms is not recognized

### ISSUE THREAD

**Issue by FinzelStefan** [validator/validator#845]
The select element and some special attributes of input element are tested quite sophisticated. It seems things are changing in the monent, as attribute size is not allowed for type number since yesterday.

But i am missing a much more simple test: without an attribute id or name input element is quite useless.

<!DOCTYPE html>
<html lang=en>
<head><title>input test</title></head><body>
<form action="#" method="post">
input (button)<input type="button" value="Test">
input (checkbox)<label><input type="checkbox" checked>checkbox</label>
input (datalist)<input type="text" list="inputList"><datalist id="inputList"><option value="test"></option><option value="Test"></option><option value="TEST"></option></datalist>
input (disabled)<input type="text" disabled>
input (email)<input type="email">
input (file)<input type="file">
input (hidden)<input type="hidden">
input (image)<input type="image" alt="image">
input (number,0-9)<input type="number" min="0" max="9">
input (password)<input type="password">
input (radio,checked)<input type="radio" name="radio" id="first" value="first" checked> <label for="first">first</label> <input type="radio" name="radio" id="second" value="second"> <label for="second">second</label>
input (range,0-10,step 2)<input type="range" min="0" max="10" value="2" step="2" list="tickmarks"><datalist id="tickmarks"><option value="0"></option><option value="25"></option><option value="50"></option><option value="75"></option><option value="100"></option></datalist>
input (readonly)<input type="text" readonly>
input (required)<input type="text" required>
input (reset)<input type="reset">
input (search)<input type="search">
input (submit)<input type="submit">
input (tel)<input type="tel">
input (text)<input type="text">
input (url)<input type="url">
</form>
</body>

Document checking completed. No errors or warnings to show.

**Comment by FinzelStefan** [comment]
[input.txt](https://github.com/validator/validator/files/3446539/input.txt)

**Comment by sideshowbarker** [comment]
I don’t understand the issue here. Please provide a complete HTML document that demonstrates the problem.
