### ISSUE TITLE
Strange arbitrary rare fails on character entity excl

### ISSUE THREAD

**Issue by FinzelStefan** [validator/validator#847]
Strange arbitrary rare fails on character entity &excl;
[excl.txt](https://github.com/validator/validator/files/3446551/excl.txt)

Several days ago I had arbitrary fails on the character entity &excl; (!). Although i was using lots of other (even quite rare) character entities this happened only for &excl;. It also happened only when included by other character entities   

<!DOCTYPE html>
<html lang=en>
<head><title>excl test</title></head><body>
&nbsp;&excl;&nbsp;  included in between other character entities this failed in about 1 of 5 cases, over several days, but a single
&excl;              did never ever fail
</body>

It's gone now for about a week. The error was something like 'unrecognized entity'.
I wrote this just to remember.

**Comment by sideshowbarker** [comment]
There’s nothing special about `excl;` that would cause any problems. And so I know know of no way for me to resolve this issue, unless you can provide some way to reproduce a specific problem

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/847#issuecomment-521753839
