### ISSUE TITLE
Неправильный перевод

### ISSUE THREAD

**Issue by tde261** [validator/validator#849]
Почему Google Chrome переводит предупреждение "The type attribute is unnecessary for JavaScript resources." как ": атрибут является необходимым для ресурсов JavaScript", и кроме этого еще добавляет к тексту  color: transparent;

**Comment by sideshowbarker** [comment]
I don’t understand what question you’re asking.

If the question is about Google Translate mistranslating a message from the validator, then that’s not a problem in the validator but instead a problem in Google Translate…
