### ISSUE TITLE
false greenlight

### ISSUE THREAD

**Issue by VirtualCharlie** [validator/validator#852]
I have found  that the W3C validator will accept "greenlight" malformed html code which is missing an opening tag, specifically code missing <body> while having a </body> within the <html></html> block. Clearly a <body></body> syntax is indicated. This malformed code will open with IE or Chrome on the desktop, however, this glitch causes a cascade of malfunctions on Android Chrome...

**Comment by sideshowbarker** [comment]
The `<body>` start tag is optional:

https://html.spec.whatwg.org/multipage/sections.html#the-body-element

> A body element's start tag can be omitted if the element is empty, or if the first thing inside the body element is not ASCII whitespace or a comment, except if the first thing inside the body element is a meta, link, script, style, or template element.

So the document shown in the comment above is actually valid per the spec.

> this glitch causes a cascade of malfunctions on Android Chrome...

Exactly what kinds of malfunctions? Whatever the problems are, what makes you conclude they’re caused by the document lacking a `<body>` start tag?

**Comment by VirtualCharlie** [comment]
I have found that malformed code like <html><head></head></body></html> on Android Chrome fails to implement css instructions consistently. These problems simply vanish when I correct the <body></body> code. You tell me why. Of course, there remains the annoying fact that Android Chrome would not seem to clear caches automatically when Chrome is closed and reopened, meaning this must be done manually every time there is a revision.

 

CW
