### ISSUE TITLE
Error on /th label

### ISSUE THREAD

**Issue by jealfonso** [validator/validator#861]
Error: Table column 3 established by element th has no cells beginning in it.

From line 24, column 33; to line 25, column 32

atter</th>↩                <th colspan="2">Descri

This error seems to be a bug

**Comment by cvrebert** [comment]
We'd need you to either post a link to the page, or post the `<table>`'s HTML here, in order to debug this.

**Comment by sideshowbarker** [comment]
closing for lack of response
