### ISSUE TITLE
German site appears to be written in Vietnamese

### ISSUE THREAD

**Issue by 1jj** [validator/validator#866]
https://ebay.de.cool/Schrack-Preisliste.html
> This document appears to be written in Vietnamese but the html start tag has lang="de"

There is no Vietnamese here as far as I can tell.
Those messages are harmful as there is no hint why and what leads to that assumption. I spent some time with investigation of charsets, invalid code points and thing like that.

**Comment by sideshowbarker** [comment]
Thanks very much for reporting this and sorry for the time it cost you. I’ve fixed the problem and pushed the fix to https://validator.w3.org/nu

https://validator.w3.org/nu/?doc=https%3A%2F%2Febay.de.cool%2FSchrack-Preisliste.html

**Comment by 1jj** [comment]
Thanks!
> private static final String[] SKIP_NAMES = { "a", "details", "figcaption",
          "form", "li", "nav", "pre", "script", "select", "span", "style",
            "summary", "td", "textarea", "th", "tr" };

Reading this, I can imagine that other elements are missing with the potential to false detecting English.

`<code>` ? (Isn't the Google translator clever enough not to translate that?)

Or less common: `<samp>` ? (not to mention `<xmp>` and `<plaintext>` )

Should `<foo>` be skipped in  cases like this:
`<foo translate=no>` ?
`<html lang=a> <foo lang=b>` ?

`<template>` ?
