### ISSUE TITLE
Form field value too large

### ISSUE THREAD

**Issue by julmot** [validator/validator#875]
I am having normal HTML documents that I'd like to validate using a POST request. Unfortunately I'm unable to validate them, because `Form field value too large.`:

```
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<title>Error 400 Form field value too large.</title>
</head>

<body>
	<h2>HTTP ERROR 400</h2>
	<p>Problem accessing /. Reason:
		<pre>    Form field value too large.</pre>
	</p>
	<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a>
	<hr />

</body>

</html>
```

What is the maximum length of files? Can it be increased somehow?

**Comment by sideshowbarker** [comment]
There’s no way to increase the maximum length for form-field checking. But if you’re making the request using the HTTP/REST API, then sending it as form field isn’t the recommended way to do it anyway. Instead you should send the document as request body of the POST request.

See the documentation at https://github.com/validator/validator/wiki/Service-%C2%BB-Input-%C2%BB-POST-body

For example, using `curl`, you could send the request like this:

```
curl -H "Content-Type: text/html; charset=utf-8" \
    --data-binary @FILE.html \
    https://validator.w3.org/nu/?out=gnu
```
