### ISSUE TITLE
width=100%

### ISSUE THREAD

**Issue by RHaworth** [validator/validator#876]
Just got this:

Bad value 100% for attribute width on element img: Expected a digit but saw % instead. From:

<img src='http://posp.org.uk/img/ntownam.png' alt='the n-Town (Corpus Christi) plays' width='100%'>

I see nothing wrong with it and browsers seem happy with it.

**Comment by RHaworth** [comment]
Oops! Forgot to change the &lt; the bit of code is

&lt;img src='http://posp.org.uk/img/ntownam.png' alt='the n-Town (Corpus Christi) plays' width='100%'>

**Comment by nschonni** [comment]
width attribute is in pixels. You'd need to use `style` to set percentage

**Comment by cvrebert** [comment]
Spec: https://html.spec.whatwg.org/multipage/embedded-content-other.html#attr-dim-width

> [...] may be specified to give the dimensions of the visual content of the element (the width and height respectively, relative to the nominal direction of the output medium), in CSS pixels. The attributes, if specified, must have values that are valid non-negative integers.

**Comment by RHaworth** [comment]
use style= ! Oops again! Sorry. Silly me.
