### ISSUE TITLE
When the validator would deal with the new Google's REL link attributes ("ugc" and "sponsored")?

### ISSUE THREAD

**Issue by miniBB** [validator/validator#878]
You might know that more than a month ago, evolving "nofollow", Google introduced new "rel" attributes for links, which are "ugc" and "sponsored". Read more here:

https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

However the Nu HTML checker still brings an error if such attributes are present in the HTML source. The error is:

Bad value ugc for attribute rel on element a: The string ugc is not a registered keyword.

Would this issue be fixed soon (if anytime)?

**Comment by nschonni** [comment]
It doesn't look like Google even proposed those to w3c or whatwg, so they are non-standard

**Comment by sideshowbarker** [comment]
See https://twitter.com/html5/status/1183963868382416897
