### ISSUE TITLE
Some SVG features not supported (feDropShadow)

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#880]
I found that https://htmlparser.info doesn't validate because `feDropShadow` isn't an allowed child of `filter`, which I assume means the validator doesn't know about this element.

https://drafts.fxtf.org/filter-effects/#feDropShadowElement
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDropShadow

**Comment by sideshowbarker** [comment]
I’ve added support for `feDropShadow`. If there are other SVG features you’ve found that aren’t supported, please file separate bug(s)
