### ISSUE TITLE
Missing Git tags corresponding to vnu-jar on NPM

### ISSUE THREAD

**Issue by andersk** [validator/validator#883]
Of the 84 versions of the `vnu-jar` package on NPM:

```console
$ npm view vnu-jar versions
 
[
  '16.6.29',  '16.11.19', '16.12.25', '16.12.27', '17.0.0',
  '17.0.1',   '17.1.0',   '17.1.8',   '17.1.31',  '17.1.32',
  '17.1.33',  '17.1.34',  '17.2.0',   '17.2.1',   '17.2.13',
  '17.2.23',  '17.3.0',   '17.4.14',  '17.4.17',  '17.5.7',
  '17.5.20',  '17.7.0',   '17.7.4',   '17.7.6',   '17.7.8',
  '17.8.18',  '17.8.20',  '17.8.28',  '17.9.0',   '17.9.10',
  '17.9.13',  '17.10.1',  '17.10.4',  '17.11.0',  '17.11.1',
  '17.12.5',  '17.12.7',  '17.12.14', '17.12.15', '17.12.26',
  '17.12.28', '18.1.18',  '18.1.30',  '18.2.2',   '18.2.4',
  '18.2.5',   '18.2.13',  '18.2.16',  '18.2.20',  '18.2.21',
  '18.2.24',  '18.3.0',   '18.3.12',  '18.3.13',  '18.3.24',
  '18.4.8',   '18.4.9',   '18.5.5',   '18.6.7',   '18.6.16',
  '18.6.26',  '18.7.16',  '18.7.18',  '18.7.22',  '18.7.23',
  '18.7.28',  '18.8.14',  '18.8.26',  '18.8.29',  '18.9.11',
  '18.10.5',  '18.11.4',  '18.11.5',  '18.11.20', '18.11.21',
  '18.11.28', '18.12.18', '19.2.15',  '19.2.18',  '19.3.3',
  '19.4.24',  '19.5.1',   '19.6.7',   '19.9.4'
]
```

only 15 are tagged in this Git repository, and none more recent than 18.8.29. I would like to be able to see which code corresponds to at least the most recent few `vnu-jar` versions; can you tag them here?

**Comment by sideshowbarker** [comment]
Sorry I’ve not made time yet to go back and do this. Do you still want me to go back and tag a few of the more-recent versions?

For the future, I’ve added a build step that ensures the repo gets tagged from now on before a new npm package is release.

**Comment by andersk** [comment]
The current release still isn’t tagged—did you forget to push the tag maybe?

When the current release is taken care of, I don’t care so much about the historical ones anymore.

**Comment by sideshowbarker** [comment]
> The current release still isn’t tagged—did you forget to push the tag maybe?

oops, yeah… Pushed now (along with a few other older tags that apparently had so far existed only locally in my own clone…)

> When the current release is taken care of, I don’t care so much about the historical ones anymore.

OK
