### ISSUE TITLE
Validator isn't clear it's using WHATWG spec not W3

### ISSUE THREAD

**Issue by jribbens** [validator/validator#890]
I was going to report a bug in that the error message "The only allowed value for the charset attribute for the meta element is utf-8" is untrue, until I realised that this is a difference between the WHATWG HTML spec and the W3C HTML spec.

I think it's probably worth mentioning that "validator.w3.org" doesn't follow the w3.org specification but uses a third-party one instead...

**Comment by nschonni** [comment]
> "validator.w3.org" doesn't follow the w3.org specification but uses a third-party one instead...

that is the legacy validator, this repo is published to validator.w3.org/nu. Those URLs are mention in the README https://github.com/validator/validator#web-based-checking but doesn't call out which use which spec

**Comment by sideshowbarker** [comment]
> until I realised that this is a difference between the WHATWG HTML spec and the W3C HTML spec.

Exactly which W3C HTML spec do you mean? Can you cite the exact URL of that W3C HTML spec?

> I think it's probably worth mentioning that "validator.w3.org" doesn't follow the w3.org specification but uses a third-party one instead...

There’s no longer any difference. There are no longer multiple specs. There’s only one spec: the WHATWG HTML spec — and for all purposes, the W3C now references that WHATWG HTML spec as the authoritative spec.

**Comment by jribbens** [comment]
> that is the legacy validator, this repo is published to validator.w3.org/nu.

... which is where validator.w3.org takes you when you validate something it doesn't recognise as HTML4/XHTML1/etc.

> Exactly which W3C HTML spec do you mean? Can you cite the exact URL of that W3C HTML spec?

Sorry, I don't understand. Is this a trick question? I mean the latest HTML standard at https://www.w3.org/TR/html52/, which is linked from https://www.w3.org/html/.

> There’s no longer any difference. There are no longer multiple specs. There’s only one spec: the WHATWG HTML spec — and for all purposes, the W3C now references that WHATWG HTML spec as the authoritative spec.

They don't though.

**Comment by sideshowbarker** [comment]
> Sorry, I don't understand. Is this a trick question? I mean the latest HTML standard at https://www.w3.org/TR/html52/

Yeah that’s not the latest. It’s obsolete. We’re in the process of marking it as such, but the necessary process wheels don’t turn as quickly as they should.

> which is linked from https://www.w3.org/html/.

I’ve updated that page to make it clear that https://html.spec.whatwg.org/multipage/ is the current spec

**Comment by jribbens** [comment]
Ah ok, that clears things up a lot, thanks! I guess the confusion will lessen as well when the first WHATWG Review Draft gets promoted to W3C REC.
