### ISSUE TITLE
Embedded Microdata: "The itemprop attribute was specified, but the element is not a property of any item."

### ISSUE THREAD

**Issue by Berbe** [validator/validator#891]
```
<p itemprop="address" itemscope="itemscope" itemtype="https://schema.org/PostalAddress" id="id-a">
    <a itemprop="url" href="https://example.org/">https://example.org/</a>
</p>
```
yields:
```
Error: The itemprop attribute was specified, but the element is not a property of any item.
```
on the `<a itemprop="url">` element.

https://search.google.com/structured-data/testing-tool reports no Microdata error.

Note:
The `<p>` element is (correctly) embedded, which is not shown here.

**Comment by sideshowbarker** [comment]
> ```
> <p itemprop="address" itemscope="itemscope" itemtype="https://schema.org/PostalAddress" id="id-a">
>     <a itemprop="url" href="https://example.org/">https://example.org/</a>
> </p>
> ```

As far as I understand it, the HTML spec doesn’t allow you to nest properties that way.

@unor, can you please weigh on this?

I realize the schema.org docs have examples with nested properties — e.g., https://schema.org/address — but that doesn’t mean those examples conform to the requirements in the HTML spec.

**Comment by unor** [comment]
I can’t reproduce the problem using https://validator.w3.org/nu/. The following snippet (I just added a parent item) is, correctly, error-free:

```html
<div itemscope itemtype="http://schema.org/LocalBusiness">

  <p itemprop="address" itemscope="itemscope" itemtype="https://schema.org/PostalAddress" id="id-a">
    <a itemprop="url" href="https://example.org/">https://example.org/</a>
  </p>

</div>
```

(Maybe the document you tested is making use of `itemref` somewhere else, given that the `p` element has an `id` value?)

----

@sideshowbarker: I’m not sure which nesting you are referring to exactly. After a quick look, the examples on https://schema.org/address look fine to me. They are using the common/regular way of adding properties to items, i.e., this kind of nesting should be fine:

```html
<div itemscope itemtype="https://schema.org/Article">
  <span itemprop="name">Article 4</span>

  <div itemprop="about" itemscope itemtype="https://schema.org/Article">
    <span itemprop="name">Article 3</span>

    <div itemprop="about" itemscope itemtype="https://schema.org/Article">
      <span itemprop="name">Article 2</span>

      <div itemprop="about" itemscope itemtype="https://schema.org/Article">
        <span itemprop="name">Article 1</span>
      </div>

    </div>

  </div>

</div>
```

Rarely used, but it should even also be fine to nest two or more properties with non-item values, e.g. a `name` inside a `description`:

```html
<div itemscope itemtype="http://schema.org/Thing">

  <p itemprop="description">This is the <span itemprop="name">description</span>.</p>

</div>
```

Per https://html.spec.whatwg.org/multipage/microdata.html#values, the value of `description` would be "the element's descendant text content", i.e., "This is the description."

**Comment by sideshowbarker** [comment]
@unor OK, I was just lacking a full understanding — thanks for taking time to reply, and clearing things up.

What I didn’t understand is that if there’s an ancestor with an `itemscope` attribute, the snippet shown in the issue description would be conforming — but without such an ancestor, it’s not conforming.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/891#issuecomment-559238015
