### ISSUE TITLE
missing closing tag - still valid HTML

### ISSUE THREAD

**Issue by ulbiopro** [validator/validator#895]
I experienced an issue with the validator at https://validator.w3.org/nu

```
<!DOCTYPE` html>
<html lang="de">
<head>
    <title>Test</title>
</head>
<body>
<p>
This is an example.
<p>
    Example Text
</p>
</body>
</html>
```

Validation of the above code succeeds, though it is clearly not valid because of a missing closing paragraph-tag in line 9.
If this is not an issue, is there an explanation why not?

**Comment by AndySky21** [comment]
https://www.w3.org/TR/html52/syntax.html#optional-tags

> A `p` element’s end tag may be omitted if the `p` element is immediately followed by an `address`, `article`, `aside`, `blockquote`, `details`, `div`, `dl`, `fieldset`, `figcaption`, `figure`, `footer`, `form`, `h1`, `h2`, `h3`, `h4`, `h5`, `h6`, `header`, `hr`, `main`, `nav`, `ol`, `p`, `pre`, `section`, `table`, or `ul` element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, noscript, or video element, or an autonomous custom element.

and as such a missing `p` end tag is not invalid.
