### ISSUE TITLE
Error when bar in URL - which is required in Google webfonts spec

### ISSUE THREAD

**Issue by shochberg** [validator/validator#896]
Hello,
The Google API for downloading fonts specifies a | to separate individual font names when downloading multiple fonts in one request.  See here: https://developers.google.com/fonts/docs/getting_started

For example: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,500,700&display=swap">

HTML checker throws Error: Bad value https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,500,700&display=swap for attribute href on element link: Illegal character in query: | is not allowed.

Thanks

**Comment by nschonni** [comment]
Duplicate of #534, Google documentation gives invalid values

**Comment by shochberg** [comment]
okey doke.  Sorry about that.
