### ISSUE TITLE
sample message endpoints in wiki not valid

### ISSUE THREAD

**Issue by calebcartwright** [validator/validator#898]
The [sample message endpoints enumerated in the wiki](https://github.com/validator/validator/wiki/Service-%C2%BB-HTTP-interface#sample-messages) are no longer valid (getting nginx 502 errors). Would it be possible to get those sample endpoints back up/available? 

https://hsivonen.com/test/moz/messages-types/404.html
![image](https://user-images.githubusercontent.com/13042488/72226190-efcd7a80-3553-11ea-83cd-4ff75fe98c62.png)

**Comment by sideshowbarker** [comment]
Thanks for the report

heads-up @hsivonen 

For the long term, maybe we need to replace those with links to files in the test suite

**Comment by calebcartwright** [comment]
The endpoints are now back online so I'm going to close this. Thanks for the quick response and fix!
