### ISSUE TITLE
Update dockerhub

### ISSUE THREAD

**Issue by RealityShift** [validator/validator#899]
Hello! Can you push the new version to dockerhub? I'm getting handshake_failure alerts that don't seem to appear in the latest version.

**Comment by jaimeiniesta** [comment]
Same here, I'm also getting handshake_failures on some sites:

```
IO Error: Received fatal alert: handshake_failure
```

Is there a way to relax or remove this alert?

**Comment by jaimeiniesta** [comment]
Tried building locally the latest docker image (20.2.13) but I also get the handshake failure.

**Comment by jaimeiniesta** [comment]
Related: https://github.com/validator/validator/issues/345

**Comment by sideshowbarker** [comment]
I just now pushed a new version to dockerhub. Sorry for the delay in getting around to it.

If you try it and find any problems, lemme know.

**Comment by RealityShift** [comment]
Thanks! This fixed our issues.
