### ISSUE TITLE
No error/warning when opening body tag is not present

### ISSUE THREAD

**Issue by cajack2011** [validator/validator#906]
I validated a document that was missing the opening body tag and did not receive any errors.

**Comment by cvrebert** [comment]
Refer to "Tag omission" in https://html.spec.whatwg.org/multipage/sections.html#the-body-element
> A body element's start tag can be omitted if [...]

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/906#issuecomment-582246151
