### ISSUE TITLE
Docker latest image not updating?

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#908]
Hi, the latest image released on https://hub.docker.com/r/validator/validator/ is 7 months old - shouldn't this be updated automatically when there are changes in master?

This image runs validator 19.7.5 but I see that https://validator.w3.org/nu runs on 20.2.13

**Comment by sideshowbarker** [comment]
It seems that the automatic updates for https://hub.docker.com/r/validator/validator/ broke about 7 months ago — I think when versions of gnupg and unzip that I had pinned no longer became available in the debian:stable-slim distro.

Anyway, I think it’s fixed now.

**Comment by jaimeiniesta** [comment]
Thanks, just tried again and it gets the 20.2.18 version 👍
