### ISSUE TITLE
When is next version numbered full release (including a JAR) due?

### ISSUE THREAD

**Issue by DamonHD** [validator/validator#909]
I'm after the loading attribute change in a version JAR, but it does seem to have been over a year since the last formal release (unless as usual I'm missing something).

Rgds

Damon

**Comment by sideshowbarker** [comment]
I’m aiming to do a new release by the end of this week. I have a number of ARIA-related changes I’d like to get in before I do the release.

> it does seem to have been over a year since the last formal release (unless as usual I'm missing something)

You’re not missing anything :) In fact it has been more than a year

**Comment by DamonHD** [comment]
Thanks again!

I'm right now (can't sleep...) preparing my scripts to inject loading=lazy in all the right places!  I shall unleash it when the new JAR has landed...  B^>

Rgds

Damon

**Comment by sideshowbarker** [comment]
I want to get https://github.com/validator/validator/issues/911 resolved before doing the next full release. So the revised ETA for the release is early next week.

**Comment by DamonHD** [comment]
Boo hiss, that's my weekend of site upgrading ruined.  B^>

(Whenever you get to it, thanks: this is an excellent tool which makes my site so much better!)

**Comment by DamonHD** [comment]
Well, I did my upgrade using your pre-release JAR for now, thanks.  Don't tell anyone though!  %-P

**Comment by DamonHD** [comment]
Any better idea when you may be able to drop a versioned release?  I feel twitchy using an unversioned thing as part of my checking process!  B^>

Rgds

Damon

PS. I appreciate that you may be under other pressures at the moment...

**Comment by DamonHD** [comment]
Thanks for the release!

Rgds

Damon
