### ISSUE TITLE
Convert to GitHub Actions for CI

### ISSUE THREAD

**Issue by nschonni** [validator/validator#914]
Pulling out the discussion from #913 to make it easier to track.

- [ ] matrix of Linux/OSX JDK builds to match current travis on push/PR
- [ ] matrix of Windows JDK builds to match current appveyor on push/PR
- [ ] upload artifacts on push to master to replace osx/linux/windows/jar/war tags
- [ ] job upload artifacts on final git tags
- [ ] job to publish Docker hub with version number
- [ ] job to publish npm on final tag

**Comment by nschonni** [comment]
@sideshowbarker is there a reason some of the jobs use Python 3 vs some not?

**Comment by sideshowbarker** [comment]
The reason for some of the jobs using Python 3 vs some not is just to ensure we are testing both with Python 2 and Python 3. So the association of any particular job with Python 2 is just arbitrary. We only need to test one job with Python 2, but it doesn’t matter which job it is.

**Comment by nschonni** [comment]
OK, I don't think it would be hard to set up a python check/lint run separate from the regular build, if you know what it should cover

**Comment by sideshowbarker** [comment]
The Python 2 check should make sure that all the build targets we call in CI work under Python 2. The goal is to ensure that when we’re making changes to the `build/build.py` script, we’re not introducing regressions that prevent the script from continuing to work under Python 2.

**Comment by sideshowbarker** [comment]
This is done now
