### ISSUE TITLE
Spelling error: Two periods after "syntax" when cannot parse input

### ISSUE THREAD

**Issue by Lordology** [validator/validator#916]
![Screenshot 2020-03-01 at 11 07 35](https://user-images.githubusercontent.com/60983054/75624528-ec965880-5bac-11ea-969e-b594113cf080.png)

Syntax Error: Two periods after 'syntax' when validator fails to parse direct input.

<h3>Reproduce By:</h3>
  <p>Enter any HTML markup (on direct input) but check box "CSS" on the page.</p>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. Fixed in the sources and pushed to https://validator.w3.org/nu/
