### ISSUE TITLE
No errors on missing body close tag

### ISSUE THREAD

**Issue by mindhubtest** [validator/validator#919]
The bellow code does not shows an error indicating there's a missing body close tag
`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Northside Youth Soccer League</title>
        <link rel="stylesheet" href="CSS/style.css">
    </head>
    <body>
        <section class="main">
            <img src="Imagenes/nysl_logo.png" id="logo" alt="logo">
                <header><h1>Northside Youth Soccer League</h1>
                    <a href="index.html">Home</a>
                    <a href="about.html">About NYSL</a>
                    <a href="contact.html">Contact</a>
                </header>
        </section>
        <section class="imagenes">
            <img src="Imagenes/soccer_image2.jpg" alt="image">
                <h2>Mission</h2>
                    <p>
                        To support young athletes living in Chicago s northside neighborhoods,
                        who have an interest in<br>learning and playing soccer, with opportunities
                        to learn and practice skills related to the game of<br>soccer, specifically
                        those skills around team cooperation and good sportsmanship
                    </p>
                <h2>Vision</h2>
                    <P>
                        The Northside Youth Soccer League aspires to develop strong, well-rounded,
                        and mindful<br>athletes through the building of character, self-dicipline,
                        and leadership.
                    </P>
                <h2>General Information</h2>
                    <p>
                        The Northside Youth Soccer League was establishied in 1996 to provide athletes
                        residing in<br>Chicago s northside neighborhoods an environment in wich to learn
                        and play soccer. To be a<br>member of NYSL, you must be between the ages of 4 - 12
                        and reside in a Chicago northside<br>neighborhood. NYSL is ran by a small full-time
                        staff, and relies on the generous volunteer time of<br>parents and previous league 
                        members.
                    </p>
        </section>

</html>`

**Comment by DamonHD** [comment]
The head and body tags can be omitted entirely with care, ie are optional, and in some cases that is recommended, eg to fully minify an HTML object.

Eg see my 'lite' site page at http://m.earth.org.uk/

Or maybe I'm misunderstanding you?

Rgds

Damon

**Comment by cvrebert** [comment]
See https://github.com/validator/validator/issues/372#issuecomment-248201300 for tools to detect "missing" close tags.

They may indicate an authoring mistake, but for `<body>` they're not invalid. Per the spec:

> [4.3.1 The body element](https://html.spec.whatwg.org/multipage/sections.html#the-body-element)
> [...]
> Tag omission in text/html:
> [...] A `body` element's end tag can be omitted if the `body` element is not immediately followed by a comment.
