### ISSUE TITLE
osx release not uploaded

### ISSUE THREAD

**Issue by lucafavatellawork** [validator/validator#921]
On [recent master](https://github.com/validator/validator/commit/7296bdbe8143087f4bd7a0c53a839729b14082ca), the [CI fails to upload the osx release](https://travis-ci.org/validator/validator/jobs/658033507) with the following symptoms:
```
Skipping a deployment with the releases provider because this is not on the required runtime
Skipping a deployment with the releases provider because a custom condition was not met
Skipping a deployment with the releases provider because this is not on the required runtime
Skipping a deployment with the releases provider because a custom condition was not met
Skipping a deployment with the releases provider because this is not on the required runtime
```

The problem is that the `jdk: openjdk11` bit is not present in the `osx` job - from 34f20444.

It looks like that the Travis CI config may need to have the `osx` case split out from the [generic case](https://github.com/validator/validator/blob/7296bdbe8143087f4bd7a0c53a839729b14082ca/.travis.yml#L126-L137).

**Comment by sideshowbarker** [comment]
Thanks for reporting this, and for identifying the fix. I’ve deployed the change and it appears to be working as expected.
