### ISSUE TITLE
Incorrect error reporting for background-size

### ISSUE THREAD

**Issue by valodzka** [validator/validator#924]
Css like this trigger incorrect validation error:

    background-size: min(940px,140vw) auto;

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. For CSS checking, the HTML checker uses the same backend as the W3C CSS Validator. So please re-report this in the https://github.com/w3c/css-validator/issues issue tracker

**Comment by sideshowbarker** [comment]
Re-opened at https://github.com/w3c/css-validator/issues/273
