### ISSUE TITLE
Incoherent CHANGELOG / release

### ISSUE THREAD

**Issue by tdelmas** [validator/validator#926]
According to https://github.com/validator/validator/blob/master/CHANGELOG.md the last release is 18.11.5 (05 November 2018)

According to https://github.com/validator/validator/releases it's 20.2.28  (28 February 2020)

https://www.npmjs.com/package/vnu-jar indicate 20.2.28 but the "download latest" link 
![image](https://user-images.githubusercontent.com/1955774/76692789-66bde700-665b-11ea-9e23-2806bf91ca7e.png) https://github.com/validator/validator/releases/latest redirects to https://github.com/validator/validator/releases/tag/18.11.5

The corresponding tags do appears in https://github.com/validator/validator/tags so I think only the release needs to be created on GitHub. 
(But it will not fix the CHANGELOG problem, because it's still incorrect on the tag: https://github.com/validator/validator/blob/v20.2.28/CHANGELOG.md)

May be related: https://github.com/validator/validator/issues/883

**Comment by sideshowbarker** [comment]
> According to https://github.com/validator/validator/blob/master/CHANGELOG.md the last release is 18.11.5 (05 November 2018)

Yeah

> According to https://github.com/validator/validator/releases it's 20.2.28 (28 February 2020)

That’s a pre-release. It’s marked as such

> https://www.npmjs.com/package/vnu-jar indicate 20.2.28

Some of the vnu-jar releases correspond to upstream pre-releases.

> The corresponding tags do appears in https://github.com/validator/validator/tags so I think only the release needs to be created on GitHub.
> (But it will not fix the CHANGELOG problem, because it's still incorrect on the tag: https://github.com/validator/validator/blob/v20.2.28/CHANGELOG.md)

That’s for the v20.2.28 pre-release

**Comment by tdelmas** [comment]
Thank you for the details.

To clarify the current situation, I think:
- pre-release for validator/validator should be pre-release for vnu-jar

or

- vnu-jar should have it's own repository, linked from https://www.npmjs.com/package/vnu-jar with an up-to-date CHANGELOG

Because when looking to release of vnu-jar it's not possible to see a coherent changelog and understand the versioning with the current workflow.

**Comment by sideshowbarker** [comment]
> pre-release for validator/validator should be pre-release for vnu-jar

OK, from now on I will attempt to consistently follow a policy of tagging the npm pre-release versions of vnu-jar with the npm `next` tag, and only using the npm `latest` tag for the full, non-pre-release versions (such as the 20.3.16 version).

**Comment by tdelmas** [comment]
Thank you 🙂 !
