### ISSUE TITLE
checker.py all File Not Found Error

### ISSUE THREAD

**Issue by bsulliva** [validator/validator#927]
I'm getting a file not found error, and I have no idea what file is not found. Please help. Thanks

```
C:\Users\barry.sullivan\Downloads\validator-master>python ./checker.py all
git submodule update --remote --merge --init
Traceback (most recent call last):
  File "./checker.py", line 42, in <module>
    build.main(args)
  File "C:\Users\barry.sullivan\Downloads\validator-master\build\build.py", line 1971, in main
    updateSubmodules()
  File "C:\Users\barry.sullivan\Downloads\validator-master\build\build.py", line 1604, in updateSubmodules
    runCmd([gitCmd, 'submodule', 'update', '--remote', '--merge', '--init'])
  File "C:\Users\barry.sullivan\Downloads\validator-master\build\build.py", line 221, in runCmd
    return subprocess.call(cmd)
  File "C:\Users\barry.sullivan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\barry.sullivan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\barry.sullivan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by sideshowbarker** [comment]
I can’t reproduce this. Running `python ./checker.py all` works as expected in my environment.

I don’t know what might be causing this problem for you. Maybe any older version of git?

**Comment by bsulliva** [comment]
Thanks Michael. Where can I download the latest version?

On Mar 16, 2020, at 6:28 PM, Michael[tm] Smith <notifications@github.com> wrote:

﻿--Sent by External Sender: noreply@github.com
________________________________

I can’t reproduce this. Running python ./checker.py all works as expected in my environment.

I don’t know what might be causing this problem for you. Maybe any older version of git?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_validator_validator_issues_927-23issuecomment-2D599803128&d=DwMFaQ&c=vY6N1du11amUSmqXT2U6Yqw6I-si6nWulSErsUHFzRg&r=bn0n10jf9JP1CYQNGv3k3ng1Mr8CZXLHhEIiQep3iLg&m=OmN4sQOn0geg8EnqdODrBK7jKcYEdCp4l1bpnafHv-k&s=68nAXzyzUz9bZMw-bGnAkPoJNOPy9ldkPJxiQIfMI2U&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABOXINT3BI5OFALWPUPR6S3RH2Y3FANCNFSM4LMVVR4Q&d=DwMFaQ&c=vY6N1du11amUSmqXT2U6Yqw6I-si6nWulSErsUHFzRg&r=bn0n10jf9JP1CYQNGv3k3ng1Mr8CZXLHhEIiQep3iLg&m=OmN4sQOn0geg8EnqdODrBK7jKcYEdCp4l1bpnafHv-k&s=Bf0BlRwmvs1J1mvZMuTx2UDtqcCloBbSHXMRST4-4Sg&e=>.


CONFIDENTIALITY. This electronic mail and any files transmitted with it may contain information proprietary to Mouser Electronics, Inc. or one of its subsidiaries or affiliates, and are intended solely for the use of the individual or entity to whom they are addressed, shall be maintained in confidence and not disclosed to third parties without the written consent of the sender. If you are not the intended recipient or the person responsible for delivering the electronic mail to the intended recipient, be advised that you have received this electronic mail in error and that any use, dissemination, forwarding, printing, or copying of this electronic mail is strictly prohibited. If you have received this electronic mail in error, please immediately notify the sender by return mail. Thank you for your compliance.

**Comment by sideshowbarker** [comment]
https://github.com/validator/validator/releases/tag/20.3.16 has the latest version

**Comment by bsulliva** [comment]
Sorry, did you mean, I don't have git installed? Or just that I'm using the wrong version of the code?

**Comment by bsulliva** [comment]
Sorry for the confusion, it's running now. On Step 3, instead of running the "git clone" command, I just downloaded the code as a zip file and tried to run the checker.py file from that code.
