### ISSUE TITLE
 Consider adding a lang attribute to the html start tag to declare the language of this document.

### ISSUE THREAD

**Issue by bitu123** [validator/validator#929]
```html
TYPE html>↩<html class='v2' dir='ltr' xmlns='http://www.w3.org/1999/xhtml' xmlns:b='http://www.google.com/2005/…' xmlns:data='http://www.google.com/2005/gml/data' xmlns:expr='http://www.google.com/2005/gml/expr'>↩<head
```

**Comment by sideshowbarker** [comment]
change `<html class='v2'` to `<html lang=en class='v2'` (replace `en` with the language tag for whatever language the document is actually written in

**Comment by avivmu** [comment]
@sideshowbarker Dunno know why this issue is showing when searching with the is:open query. A Github bug I think?
https://github.com/validator/validator/issues?q=is%3Aissue+language+is%3Aopen
