### ISSUE TITLE
Attribute width not allowed on element symbol at this point

### ISSUE THREAD

**Issue by jitendravyas** [validator/validator#930]
Is this a real error? I see `width` and `height` being used in MDN Docs https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol

<img width="425" alt="Showing results for Nu Html Checker" src="https://user-images.githubusercontent.com/77309/77145299-1ce75d80-6aae-11ea-86d8-eff60532b9cf.png">

**Comment by sideshowbarker** [comment]
SVG 1.1 https://www.w3.org/TR/SVG11/struct.html#SymbolElement didn’t allow `width` and `height` for the `symbol` element. But apparently the SVG2 spec does https://www.w3.org/TR/SVG2/struct.html#SymbolElement.

So I’ll update the checker to allow those.

**Comment by sideshowbarker** [comment]
Thanks for reporting this. Fixed in the sources and pushed to https://validator.w3.org/nu/
