### ISSUE TITLE
flag --version returns [unknown version]

### ISSUE THREAD

**Issue by martindholmes** [validator/validator#932]
The latest release (20.3.16) doesn't correctly report its version:

~~~~~
java -jar vnu.jar --version
[unknown version]
~~~~~

on Linux, OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1).

**Comment by martindholmes** [comment]
Maybe this commit did it:

https://github.com/validator/validator/commit/032004795195943779bcb3d400e413b4ff7840d0#diff-e22dd07aa09824137ee1809b8a96cbe6

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I’m able to reproduce this in a Linux environment:

```
$ uname -a && curl -sOL \
  https://github.com/validator/validator/releases/download/20.3.16/vnu.jar_20.3.16.zip \
  && unzip -q vnu.jar_20.3.16.zip && java -jar dist/vnu.jar --version
Linux … 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
[unknown version]
```
…but not in a macOS environment:
```
$ curl -sOL \
  https://github.com/validator/validator/releases/download/20.3.16/vnu.jar_20.3.16.zip \
  && unzip -q vnu.jar_20.3.16.zip && java -jar dist/vnu.jar --version
Darwin … 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
20.3.16
```
I have no idea what might be causing that difference. I’ll investigate.

**Comment by sideshowbarker** [comment]
Fixed now in the sources. I will try to do a new release soon, with the fix.

Thanks again very much for taking time to report this

**Comment by martindholmes** [comment]
Thanks for fixing it so quickly! I have some build processes that use vnu.jar to validate site content, and the scripts check to see if they need to update the local version of vnu.jar before running it; with no version number, that process always triggers a fresh download, which is a bit of a waste of bandwidth.
