### ISSUE TITLE
capture should be allowed on input type="file"

### ISSUE THREAD

**Issue by cthart** [validator/validator#933]
I'm getting "Attribute capture not allowed on element input at this point." but it's actually allowed.

**Comment by sideshowbarker** [comment]
The `capture` attribute is not in the HTML standard:

https://html.spec.whatwg.org/multipage/indices.html#attributes-3

For the checker to allow an attribute on a particular HTML element, the attribute needs to be in the HTML standard.

**Comment by cthart** [comment]
It's in this recommendation. https://www.w3.org/TR/html-media-capture/

**Comment by cthart** [comment]
And it was considered a bug on the mailing list. https://lists.w3.org/Archives/Public/www-validator/2018Mar/0016.html

**Comment by sideshowbarker** [comment]
OK yeah, thanks for the pointers — I’ll make some time to add it

**Comment by sideshowbarker** [comment]
incidental FYI https://github.com/whatwg/html/issues/1102#issuecomment-602037615

**Comment by sideshowbarker** [comment]
Fixed in the sources and pushed to https://validator.w3.org/nu/

**Comment by cthart** [comment]
And verified fixed! Thanks!
