### ISSUE TITLE
missing <head> tag as well as existing unbalanced </head> tag went unnoticed.

### ISSUE THREAD

**Issue by KennethRamsey** [validator/validator#934]
Thank you for this service.  Thought you might like to know that I was having some html validated,  and it doesn’t notice that the opening <head> tag is missing, even though the closing </head> tag is in the html.  Idealy i think it should at least warn that there is a closing </head> tag with no matching opening <head> tag.  Here’s a trimmed version of the Html that still has the issue.

```html
<!DOCTYPE html>
<html lang="en">
<title>test</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<style type="text/css">
                /* CLIENT-SPECIFIC STYLES */
                body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
                table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
                img { -ms-interpolation-mode: bicubic; }            
</style>
</head>

<body style="margin: 0 !important; padding: 0 !important;">
  test
</body>
</html>
```

**Comment by KennethRamsey** [comment]
take 2 on adding the html.

`<!DOCTYPE html>
<html lang="en">
<title>test</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<style type="text/css"> 
                /* CLIENT-SPECIFIC STYLES */
                body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
                table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
                img { -ms-interpolation-mode: bicubic; }           
</style>
</head>

<body style="margin: 0 !important; padding: 0 !important;">
  test
</body>
</html>
`

**Comment by sideshowbarker** [comment]
The `<head>` start tag and `</head>` end tag are both optional:

https://html.spec.whatwg.org/multipage/semantics.html#the-head-element

So the document shown in the question conforms to the requirements in the spec.

Note that the spec requirements also allow either the start tag or end tag to be omitted even if the other is present. So a document with a `</head>` end tag but no `<head`> start tag is still conforming. In general in HTML there’s no requirement against “unbalanced” tags. It’s true that XML does have such a requirement — but HTML isn’t XML.

See also https://html.spec.whatwg.org/multipage/syntax.html#optional-tags

**Comment by cvrebert** [comment]
Other tools such as HTML Hint can detect such technically-valid but confusing and error-prone "unpaired" tags: https://github.com/htmlhint/HTMLHint/wiki/Tag-pair

**Comment by KennethRamsey** [comment]
That is surprising that </head> by itself is considered valid.  I appreciates ya'lls time and responses.
