### ISSUE TITLE
report issue per mail is not possible

### ISSUE THREAD

**Issue by Daijobou** [validator/validator#935]
https://validator.w3.org/nu/about.html#issues
>To report bugs, request new features, or ask questions, please raise an issue or send mail to www-validator@w3.org.

Mail delivery failed: returning message to sender:
>   www-validator@listhub.w3.org
>     (generated from www-validator@w3.org)
>     host lyra.w3.org [128.30.52.18]
>     SMTP error from remote mail server after end of data:
>     550 header syntax

**Comment by gosko** [comment]
Hi @Daijobou , I checked our server logs and this delivery failed because it was addressed to `www-validator@w3.org.` including the trailing period. Can you please resend to [`www-validator@w3.org`](mailto:www-validator@w3.org)?

**Comment by Daijobou** [comment]
Embarrassing. Thanks for the advice.
