### ISSUE TITLE
Is CLI version behind from browser version? lazy Loading attribute still showing as error

### ISSUE THREAD

**Issue by jitendravyas** [validator/validator#937]
I just installed via `brew install vnu` and ran a website through it but loading attribute stil showing as error
<img width="352" src="https://user-images.githubusercontent.com/77309/77722772-acdc5880-7014-11ea-830c-20b2024f52e9.png">

While in 16th March release it is showing as allowed.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/77309/77722801-bf569200-7014-11ea-81a2-6b2b187a8408.png">

**Comment by sideshowbarker** [comment]
The homebrew `vnu` package is maintained by a third party and I have no involvement at all with maintaining it or updating it. I guess the maintainer just hasn’t got around yet to building an update of it yet.
