### ISSUE TITLE
Set up automated builds in Docker Hub

### ISSUE THREAD

**Issue by Umoxfo** [validator/validator#942]
Docker Hub supports the automatic construction of images from source code in GitHub and automatically pushes the built image to the Docker repositories.

This allows for the early detection of issues such as #908.

Set up automated builds: 
https://docs.docker.com/docker-hub/builds/

**Comment by sideshowbarker** [comment]
We actually do now have automated builds set up at Docker Hub, and have for some time now. Is there some problem that made you conclude such automated builds aren’t yet set up?

**Comment by Umoxfo** [comment]
It's my false. Sorry.

**Comment by sideshowbarker** [comment]
> It's my false. Sorry.

No worries — I had just thought what we had set up might have broke :) Thanks for taking time to inquire about it.
