### ISSUE TITLE
Stray end tag false positive ?

### ISSUE THREAD

**Issue by ph1823** [validator/validator#944]
Hi !

I have check my html website with w3c validator, and the validator report false positive of div stray end tag.

It's solo error for all website (but i have fix all other error).

Link of tag: https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fdatahosting.fr%2F#l283c6

But this end div tag, close div with class container-dh.
In my IDE (PhPStorm), i remove end tag, error.  And in chrome inspector, the end div tag has been affect to div with class container-dh.

Thank for your help !

**Comment by sideshowbarker** [comment]
No, the `</div>` end tag at line 282 in your source is the one that actually closes that `div class="container-dh"` element.

You can confirm that by doing something like counting how many `<div` start tags you have in the first 283 lines and then counting how many `</div>` end tags you have in the first 283 lines. You’ll find that in those first 283 lines, you have 43 `<div` start tags, but 44 `</div>` end tags.

So if removing the extra `</div>` end tag at line 283 causes an error in your IDE than I guess that’s bug in your IDE.

**Comment by ph1823** [comment]
It's true, I had made a bad twig syntax which created 44 div, so PHPStorm found an error.
 I corrected this syntax, and it works. 
Thank you for your help. Sorry to disturb you.
