### ISSUE TITLE
autofocus attribute's exclusivity isn't checked

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#95]
Currently, a document whose `<body>` consists of:
```html
<input type="text" value="Foo" autofocus>
<input type="text" value="Bar" autofocus>
```
passes validation.

However, [the spec says](https://html.spec.whatwg.org/multipage/forms.html#attr-fe-autofocus):
> There **must not** be two elements with the same *nearest ancestor autofocus scoping root element* that both have the `autofocus` attribute specified.

So I expect that the example document should instead fail validation.

**Comment by cvrebert** [comment]
@sideshowbarker Ping.

**Comment by cvrebert** [comment]
@sideshowbarker Ping?

**Comment by sideshowbarker** [comment]
I haven't forgotten about this but I just haven't been able to make time to work on it. I plan to work on the validator code this weekend, so I should be able to get this then.

**Comment by cvrebert** [comment]
That's fine. Just wanted acknowledgement of this being a legit bug.

**Comment by sideshowbarker** [comment]
Fix pushed to https://validator.w3.org/nu/
Will try to get a jar release with this and other fixes out asap.
