### ISSUE TITLE
No alt atribute on an img with role="presentation" triggers 2 errors

### ISSUE THREAD

**Issue by rianrietveld** [validator/validator#955]
The code
`<img src="image.jpg" role="presentation">`

Gives the errors: 
- 1  Element img is missing required attribute alt.
- 2  Bad value presentation for attribute role on element img.

About 1: As the role of img is removed, the element doesn't need an accessible name and therefore also no alt text. But I can understand adding an alt="" for consistency. Although not having one should maybe not trigger an error.

About 2: role="presentation can be used for an image, it's in the specs and also on 
On https://www.w3.org/WAI/tutorials/images/decorative/ this is actually mentioned as example.
`<img src="topinfo_bg.png" role="presentation">`

Note: The code
`<img src="image.jpg" role="presentation" alt="">`
Doesn't trigger any error, so the second error only occurs when there is no alt atribute.

Codepen:
https://cdpn.io/rianrietveld/debug/GRpxyma/DqADdgzDqgKA

**Comment by rianrietveld** [comment]
After a [discussion on Twitter](https://twitter.com/yatil/status/1258756590901092352) @yatil pointed out that the alt attribute is required as mentioned in the whatwg specs: https://html.spec.whatwg.org/multipage/images.html#alt

That leaves the error  `Bad value presentation for attribute role on element img.`

**Comment by stevefaulkner** [comment]
4.8.4.4.15 Guidance for conformance checkers describes the situations where an alt is and is not required, presence of role="presentation" is not mentioned https://html.spec.whatwg.org/multipage/images.html#guidance-for-conformance-checkers

**Comment by weboverhauls** [comment]
It's best practice to use HTML first. Therefore, empty alt should be used and not role. See first rule of ARIA: https://www.w3.org/TR/aria-in-html/#rule1

**Comment by jashaj** [comment]
What do I see when the image fails to load and there's no alt attribute and only a role="presentation"? The name of the image or nothing?

**Comment by rianrietveld** [comment]
I'm so sorry if I created confusion, that was not my intention.
My issue is not with the question if an alt should be present or if role=presentation should be used for an img. Or what is best practice. I was not discussing the specs, as this is not the right place for that.

What I wanted to say is:
I think there is a bug in the validator.

The first issue (missing alt attribute) is solved. I could not find in the specs that an alt attribute is required if you add role=presentation. Thankfully @yatil and @stevefaulkner pointed out to me that an alt is required on an image, even when role=presentation is added. 

Leaves the second issue I was addressing:
When you leave out the alt attribute, there is a second message:
`Error: Bad value presentation for attribute role on element img.`
I think that is not a correct error message, as you can use a role=presentation on an image.

This second error message only occurs when you leave out the alt while using role=presentation on an img.

Changed the codepen and added a different image that hopefully will appear.
https://cdpn.io/rianrietveld/debug/GRpxyma/DqrDdgzyLoEr

Please note: the error : `Bad value for attribute type on element link: Expected a MIME type but saw the empty string` is generated because of codepen code.

**Comment by sideshowbarker** [comment]
> When you leave out the alt attribute, there is a second message:
> `Error: Bad value presentation for attribute role on element img.`

I think that’s because https://w3c.github.io/html-aria/#el-img-no-alt says that for the *img without alt attribute* case, no `role` attribute is allowed: 

> If not provided an author defined accessible name by other methods: No role, and no aria-* attributes except aria-hidden.

So I think the HTML checker is conforming to the spec on this, but it would be good to get confirmation on that from @stevefaulkner or @scottaohara.

> I think that is not a correct error message, as you can use a role=presentation on an image.

As summarized above, I think role=presentation if there’s an `alt` attribute — but not allowed if there’s no `alt` attribute.

If in fact the checker is conforming to the spec on this, it’s still probably a case where I need to look into improving the error message, to make things more clear.

**Comment by scottaohara** [comment]
@sideshowbarker, testing this morning and yes, presently I think this comes down to just needing a revised error message to indicate that the `role=presentation/none` is allowed if the image has an empty string alt, but otherwise not allowed.

That said, I'm also curious about even needing the `role=presentation` with an empty `alt`, so opened an issue on ARIA in HTML for further discussion.

**Comment by sideshowbarker** [comment]
OK, I’ve attempted to improve the error message for this case, and pushed the fix to https://validator.w3.org/nu/. The following link shows the new message the checker reports:

https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fhtml%3Bcharset%3Dutf-8%2C%253C%2521DOCTYPE%2520html%253E%253Chtml%2520lang%253E%253Ctitle%253ETest%253C%252Ftitle%253E%253Cimg%2520src%253Dfoo%2520role%253Dpresentation%253E

**Comment by rianrietveld** [comment]
@sideshowbarker 
Thank you, I find these error warnings much more informative.

**Comment by sideshowbarker** [comment]
@rianrietveld Thanks — glad you reported this so that we could the improvement made 😀
