### ISSUE TITLE
Missing UI events - focusin and focusout

### ISSUE THREAD

**Issue by piotrtomiak** [validator/validator#957]
I have noticed that those events were removed recently. According to this spec: https://w3c.github.io/uievents/#event-type-focusin events like focusin, focusout are allowed. Additionally those event are recognized by all of the browsers: https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event .

**Comment by sideshowbarker** [comment]
I hadn’t realized those were defined in the UI Events spec. I normally only add checker support for attributes that are defined in the HTML spec.

Anyway, https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event has incorrect support information for `focusin`. Testing and https://web-confluence.appspot.com/ indicate it’s only supported in Safari — but not in Firefox or Chrome. Same for `focusout`.

So it’s not a good idea for the checker to allow them until they’re supported in at least two engines.

(I’ll update the support data for MDN so to correct the wrong info that’s shown there now.)

**Comment by sideshowbarker** [comment]
The UI Events spec doesn’t actually seem to define event handlers named `onfocusin` and `onfocusout`. The HTML checker doesn’t check DOM event names like `focusin` and `focusout`; instead it checks for even-handler attribute names. And in this case there’s no spec which actually defines `onfocusin` and `onfocusout` event-handler attribute names to correspond to the `focusin` and `focusout` event names.

**Comment by sideshowbarker** [comment]
See https://github.com/whatwg/html/issues/4542

**Comment by sideshowbarker** [comment]
Related https://github.com/whatwg/html/issues/4542. I guess I may go ahead and add these, since even though not actually defined anywhere, browsers apparently do support them as content/markup attributes (though not as DOM/IDL attributes).

**Comment by piotrtomiak** [comment]
@sideshowbarker Thanks!
