### ISSUE TITLE
false error for rb element

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#96]
following HTML is valid (as W3C HTML 5.0), but the validator says
"Element rb not allowed as child of element ruby in this context. (Suppressing
further errors from this subtree.)".

> &lt;ruby>&lt;rb>base&lt;rt>annotation&lt;/ruby>

rb element http://www.w3.org/TR/html51/semantics.html#the-rb-element

**Comment by sideshowbarker** [comment]
Fix pushed to https://validator.w3.org/nu/
