### ISSUE TITLE
Bad value fetch for attribute as on element link.

### ISSUE THREAD

**Issue by kapilgorve** [validator/validator#960]
I tried validator on my site. It's built using GatsbyJs,. 
I get this error `Bad value fetch for attribute as on element link.`

According to Mozilla docs `fetch` value is a valid value for json data. 
Link - https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#What_types_of_content_can_be_preloaded

The validator is showing error for `as` on link element. 
Log- 
`Error: Bad value fetch for attribute as on element link.

From line 57, column 588; to line 57, column 682

cc3f.js"/><link as="fetch" rel="preload" href="/page-data/index/page-data.json" crossorigin="anonymous"/><link `
 
Validator link - https://validator.w3.org/nu/?doc=https%3A%2F%2Fjskap.com%2F

**Comment by sideshowbarker** [comment]
Thanks very much for taking time to report this. I’ve fixed it in the checker sources and pushed the fix to https://validator.w3.org/nu/
