### ISSUE TITLE
Possible misuse of aria-label

### ISSUE THREAD

**Issue by angeljenise** [validator/validator#964]
I got this message and literally have tried everything to get rid of this message. I want to file for an error because I think everything is well done on my site.

**Comment by sideshowbarker** [comment]
Please provide the URL for document which demonstrates the problem.

**Comment by angeljenise** [comment]
>ul id=“menu-primary” class=“main-menu” aria-label=“submenu>

**Comment by sideshowbarker** [comment]
See related issue https://github.com/validator/validator/issues/904 and see also https://www.w3.org/TR/using-aria/#practical-support-aria-label-aria-labelledby-and-aria-describedby:

> Don't use <code>aria-label</code>  or <code>aria-labelledby</code>  on any other non-interactive content such as <code> p</code>, <code>legend</code>, <code>li</code>, or <code>ul</code>, because it is ignored.

**Comment by sideshowbarker** [comment]
Closing this per https://github.com/validator/validator/issues/964#issuecomment-630533816 but lemme know if you think it should instead still be kept open
