### ISSUE TITLE
Update style element check to meet updated HTML 5.2 standard

### ISSUE THREAD

**Issue by wnolfm** [validator/validator#965]
The validator is still throwing errors when a <style> element is present in the body, though it is allowed, as per: https://www.w3.org/TR/html52/document-metadata.html#the-style-element

**Comment by sideshowbarker** [comment]
The https://www.w3.org/TR/html52/ spec is obsolete. The current spec is https://html.spec.whatwg.org/multipage/ — which doesn’t allow `style` in the document body.

**Comment by wnolfm** [comment]
Whoops. I wish they didn't reverse that. 

Closing.

**Comment by sideshowbarker** [comment]
Yeah I know a lot of developers would prefer it be allowed. It was discussed at length with the editors of the HTML spec, and in the end the call they made was to continue disallowing it.

Their rationale for disallowing it continues to be that it can cause performance issues for end users, unless you know what you’re doing.

But if you do know what you’re doing and you’re using it intentionally, it’s safe to ignore the error message from the checker — in fact, using any of the message-filtering options the checker provides, you can filter out any messages you don’t want; see the docs here:

https://github.com/validator/validator/wiki/Message-filtering
