### ISSUE TITLE
Targets have moved for the links with text 'Declaring the overall language of a page' and 'Choosing language tags'

### ISSUE THREAD

**Issue by rolandog** [validator/validator#973]
As stated, the specified documentation has moved as follows:

- 'Declaring the overall language of a page'
  + Current: https://www.w3.org/International/techniques/authoring-html#textprocessing
  + Should be: https://www.w3.org/International/techniques/authoring-html.en?open=language&open=textprocessing#textprocessing
- 'Choosing language tags'
  + Current: https://www.w3.org/International/techniques/authoring-html#langvalues
  + Should be: https://www.w3.org/International/techniques/authoring-html.en?open=language&open=langvalues#langvalues

This may affect other links elsewhere.

**Comment by sideshowbarker** [comment]
Thanks for catching this and taking time to raise an issue to get it fixed.

I changed the sources and pushed the changes to https://validator.w3.org/nu/
