### ISSUE TITLE
Daily validation limit

### ISSUE THREAD

**Issue by michael-613** [validator/validator#975]
Hi there,

Does W3C have a limit to how many pages can be validated in one day from the same IP address?

I am referring to this address: https://validator.w3.org/nu/

Please let me know.

Thanks

**Comment by sideshowbarker** [comment]
See https://www.w3.org/Help/abuse-info/re-reqs.html. If the checker receives more than 150 requests from the same IP address within a ten-minute time interval, that IP address will be blocked for 2 hours.

**Comment by michael-613** [comment]
Thank you!
