### ISSUE TITLE
Issue with HTML Structure Suggestion

### ISSUE THREAD

**Issue by shahob44** [validator/validator#976]
Hello,

I used the w3 html validator to check this code:

[HTML_Validator_Code.pdf](https://github.com/validator/validator/files/4736788/HTML_Validator_Code.pdf)

In the above code, the validator suggested (see picture):

[HTML_Validator_Issue.pdf](https://github.com/validator/validator/files/4736744/HTML_Validator_Issue.pdf)

I do not understand this error because the opening <html> tag is already in place.

Thank you very much for your help!

**Comment by sideshowbarker** [comment]
Add a `lang="en"` attribute to the `html` element: `<html lang="en">`
