### ISSUE TITLE
Allow data-* attributes on SVG elements

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#98]
In anticipation of https://www.w3.org/Graphics/SVG/WG/track/actions/3694 (approved in http://www.w3.org/2015/01/15-svg-minutes.html#item03 and previously discussed favorably in https://lists.w3.org/Archives/Public/www-svg/2014Dec/0022.html
& https://lists.w3.org/Archives/Public/www-svg/2011May/0014.html), and since pragmatically speaking, this has already been used by authors in-the-wild for a while without incident, I suggest that the validator be updated to allow `data-*` attributes on SVG elements. Currently it flags them as errors.

**Comment by cvrebert** [comment]
Thank you!

**Comment by cvrebert** [comment]
X-Ref: https://github.com/w3c/svgwg/issues/27

**Comment by sideshowbarker** [comment]
> X-Ref: w3c/svgwg#27

heh—I had already forgotten I’d even made the validator change for this (had to re-read this issue and the related code change to remember). Anyway, glad to see that Cameron has taken care of it now as far as the spec goes.

**Comment by sideshowbarker** [comment]
@cvrebert …and thanks for remembering and taking time to post the x-ref here
