### ISSUE TITLE
SVG element doesn't allow role=presentation

### ISSUE THREAD

**Issue by dd8** [validator/validator#981]
The crown logo at the top of https://www.gov.uk/ is an SVG element marked as role=presentation.  VNU displays an error for this:

> Bad value presentation for attribute role on element svg

That means there's no way to mark inline SVG as decorative. This doesn't seem to match the spec which allows any role on `svg` elements:
https://www.w3.org/TR/svg-aam-1.0/#mapping_role_table

**Comment by sideshowbarker** [comment]
https://w3c.github.io/html-aria/#el-svg says:
> Roles: `application`, `document` or `img`

cc @stevefaulkner @scottaohara

**Comment by dd8** [comment]
Looks like a spec inconsistency

html-aria says `svg` has no corresponding role, and the only allowed roles are `application`, `document` or `img`

svg-aam says `svg` has implicit role `graphics-document` and any role is allowed

Firefox exposes `svg` in html as `role=graphic`
Chrome exposes `svg` in html as `role=SVGRoot`
Safari doesn't expose `svg` in html (treats it role=presentation)

**Comment by sideshowbarker** [comment]
I guess https://github.com/validator/validator/issues/1096 is also about this?
