### ISSUE TITLE
no href in area tag should be allowed

### ISSUE THREAD

**Issue by agn01** [validator/validator#985]
**Description of the bug**
Validator reports error for  `<area target="_self" alt="first_0" title="first_0"  coords="46,4,79,54" shape="rect">`

![validator_error_area_nohref](https://user-images.githubusercontent.com/67182223/85195309-94a56e00-b2d1-11ea-8487-ffbf8ba8b344.png)
https://validator.w3.org/nu/?doc=http://hpaddons.free.fr/validator/test_validator_imagemap_nohref.htm
**file with this problem**
http://hpaddons.free.fr/validator/test_validator_imagemap_nohref.htm
**Expected behavior**
There should be no error according to 
https://www.w3.org/TR/html52/semantics-embedded-content.html#the-area-element

> if the area element has no href attribute, then the area represented by the element cannot be selected, and the alt attribute must be omitted.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area

> href
    The hyperlink target for the area. Its value is a valid URL. In HTML4, either this attribute or the nohref attribute must be present in the element. In HTML5, this attribute may be omitted; if so, the area element does not represent a hyperlink.

**Comment by sideshowbarker** [comment]
The `alt` attribute needs to be removed; so:
```html
<area target="_self" title="first_0" coords="46,4,79,54" shape="rect">
```
The spec section cited in the issue description states that requirement:
> if the area element has no href attribute, then the area represented by the element cannot be selected, and **the alt attribute must be omitted**.

If the `alt` attribute is *not* omitted, then the `href` attribute is also required.
