### ISSUE TITLE
A validator operator would add a validation public key to an [amendment_proxy] config field to mimic the amendment votes of the proxy validator.

### ISSUE THREAD

**Issue by MarcelRaschke** [validator/validator#990]
A validator operator would add a validation public key to an [amendment_proxy] config field to mimic the amendment votes of the proxy validator.

Exported from RIPD-1228

_Originally posted by @carlhua in https://github.com/ripple/rippled/issues/3482_

**Comment by sideshowbarker** [comment]
Unrelated to this repo
