### ISSUE TITLE
Validator wrong

### ISSUE THREAD

**Issue by Ashley100** [validator/validator#993]
Here is your site: https://goldentoy.com.ua/
Validator thinks that it hasn't attribute lang with params, but it has. And there are any two errors that wrong.

Validator: https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fgoldentoy.com.ua%2F

**Comment by Ashley100** [comment]
It whos because the document has an iframe by google tag.

{literal}

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=some_id"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

{/literal}

After deleting this code, the validator works fine, even if returned back the code.

**Comment by sideshowbarker** [comment]
I don’t see anything here that indicates the validator isn’t working as expected. If you still have any cases of error messages that you think the validator is reporting that it should not be, please add a new comment and cite the specific error messages.
