### ISSUE TITLE
Cannot use nuvalidator with Java 8 after an upgrade

### ISSUE THREAD

**Issue by surli** [validator/validator#994]
Hi,

we use in XWiki a custom validator built on top of a `SimpleDocumentValidator` (see: https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-tools/xwiki-platform-tool-standards-validator/src/main/java/org/xwiki/validator/HTML5Validator.java) we recently upgraded the dependency to use Nu Validator 20.6.30 and we now obtain the following error when trying to build our module with Java 8:
> java.lang.UnsupportedClassVersionError: com/thaiopensource/util/PropertyId has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I dig up a little bit and apparently this class is part of `nu.validator:jing:jar:20190429VNU` and from what I see in the build script (https://github.com/validator/validator/blob/20.6.30/build/build.py) there's a javaTarget specified used for building almost all modules but not jing, so I suspect that it has been built with Java 11 without a target to specify to build it to Java 8.

**Comment by sideshowbarker** [comment]
This seems to be the same problem reported in https://github.com/validator/validator/issues/938. I haven’t been able to determine the cause.

> from what I see in the build script (https://github.com/validator/validator/blob/20.6.30/build/build.py) there's a javaTarget specified used for building almost all modules but not jing, so I suspect that it has been built with Java 11 without a target to specify to build it to Java 8.

I don’t think that can be the cause —  because in that script, the `javaTargetVersion` value is only consulted for modules that we build directly using `javac`. For the jing-trang build, as far as I mentioned in https://github.com/validator/validator/issues/938#issuecomment-605629349, the checker (validator) build just runs an ant-based build that’s part of the jing-trang repo, and:

> https://github.com/relaxng/jing-trang/blob/a5ee834d1a9e43f81b9a760e0fc8621b809259f1/build.xsl#L331-L335 invokes `javac` with `source` and `target` options set to `1.8`, and https://github.com/validator/validator/blob/master/build/build.py#L61 sets the `source` and `target` options for the `javac` build for the HTML checker itself to `1.8`.
>
> Also, our existing CI tests successfully with Open JDK 8.

So the problem seems to be that the java-version settings in the build are somehow getting ignored. But I do not know how ore why, and I have thus far not been able to reproduce the problem.

**Comment by surli** [comment]
> I don’t think that can be the cause — because in that script, the javaTargetVersion value is only consulted for modules that we build directly using javac. For the jing-trang build, as far as I mentioned in #938 (comment), the checker (validator) build just runs an ant-based build that’s part of the jing-trang repo, and:

>>    https://github.com/relaxng/jing-trang/blob/a5ee834d1a9e43f81b9a760e0fc8621b809259f1/build.xsl#L331-L335 invokes javac with source and target options set to 1.8, and https://github.com/validator/validator/blob/master/build/build.py#L61 sets the source and target options for the javac build for the HTML checker itself to 1.8.

Not sure here, but note that the `build.py` python script use the `javaTargetVersion` with the javac `--release` flag, while for jing as you mentioned it's source and target options that are used. And according to https://stackoverflow.com/questions/43102787/what-is-the-release-flag-in-the-java-9-compiler `--release` flag does more than source and target to allow cross compilation to older version. I don't have access to the original jeps to check more.

> Also, our existing CI tests successfully with Open JDK 8.

Did you check using Nuvalidator with Java 8 to perform checks, or compiling something on top of it? In our case, it's the latter which is failing.

**Comment by sideshowbarker** [comment]
Can you clarify which jar file you’re actually using? Did you get it from https://github.com/validator/validator/releases/download/20.6.30/vnu.jar_20.6.30.zip or are you instead maybe using Maven and so getting the jar from the Central Repo?

**Comment by sideshowbarker** [comment]
Ah OK I see now that in the issue description you said:

> I dig up a little bit and apparently this class is part of `nu.validator:jing:jar:20190429VNU`

So that in fact indicates that your environment is in the jing distribution from Maven. So I just now tried that:

```
$ curl -s -L -O https://repo1.maven.org/maven2/nu/validator/jing/20190429VNU/jing-20190429VNU.jar \
  && jar xf jing-20190429VNU.jar \
  && javap -v com/thaiopensource/util/PropertyId.class | grep "major version"

  major version: 53
```
So that’s the problem: The jar in the central repo has `major version: 53` — whereas for comparison:

```
curl -s -L -O https://github.com/validator/validator/releases/download/20.6.30/vnu.jar_20.6.30.zip \
  && unzip -q vnu.jar_20.6.30.zip  \
  && jar xf dist/vnu.jar  \
  && javap -v com/thaiopensource/util/PropertyId.class | grep "major version"

  major version: 52
```
But it’s still not yet clear to me why the Maven jar is `major version: 53`. The build I use to upload that Maven jar just copies the jar over the already-built jar from exactly the same place that I get it from for the non-Maven jar.

**Comment by sideshowbarker** [comment]
I guess I’ll try re-building a new Maven jar for jing. I’ll comment here after I’ve got it uploaded

**Comment by surli** [comment]
With same version or you're going to bump the version?

**Comment by sideshowbarker** [comment]
> With same version or you're going to bump the version?

I’ve bumped the version to `20200702VNU`. I’m waiting now for it to actually get deployed.

**Comment by surli** [comment]
> I’ve bumped the version to 20200702VNU

Ok once done, we'll apply back the upgrade with an explicit dependency to that jar to confirm it works.

**Comment by sideshowbarker** [comment]
OK, the 20190429VNU jar is published at the Central Repo https://repo1.maven.org/maven2/nu/validator/jing/20190429VNU/

The following confirms that it’s `major version: 52`:
```
curl -s -L -O https://repo1.maven.org/maven2/nu/validator/jing/20200702VNU/jing-20200702VNU.jar \
  && jar xf jing-20200702VNU.jar \
  && javap -v com/thaiopensource/util/PropertyId.class | grep "major version"

  major version: 52
```

I’ve also published a `validator-20.7.2.jar`:

https://repo1.maven.org/maven2/nu/validator/validator/20.7.2/

…and the POM file for that jar has version `20200702VNU` of jing as a dependency:

https://repo1.maven.org/maven2/nu/validator/validator/20.7.2/validator-20.7.2.pom

So please test with those and let me know if you run into any problems.

**Comment by surli** [comment]
So I confirm I don't get the error anymore when testing with: 
```
<groupId>nu.validator</groupId>
      <artifactId>validator</artifactId>
      <version>20.7.2</version>
```

Thanks!

**Comment by sideshowbarker** [comment]
Thanks much for having taken time to report it, and glad we got it resolved
