### ISSUE TITLE
Possibility to add a token to the header of the request

### ISSUE THREAD

**Issue by klacol** [validator/validator#997]
We want to validate pages behind a login page. The authentication can be done by sending a special token in the header of the request. Is it possible to add such a token to the request of NU HTML checker?

**Comment by sideshowbarker** [comment]
There is no currently way to do this, and enabling something like this for the public https://validator.w3.org/nu/ service would unsafely expose the token to anyone who had access to the https://validator.w3.org/nu/ backend.

So this essentially in the same class as https://github.com/validator/validator/issues/806 — and so the reason we can’t implement this for the public service is that  I don’t want to add a feature that will have the effect in practice of training users to do something unsafe (that is, to voluntarily expose credentials to a MITM that they should not be trusting).

I wish I had a better answer than that. I empathize with the use case but I can’t see a way to satisfy that use case without leading users to compromise security.

**Comment by klacol** [comment]
Ok, thanks for clarification, so we have to implement another type of authentication on our side. I close this.
